Include test for verifying dependencies.
openshift/release pull request #11615
Opened 2020-09-03 18:51 UTC by huffmanca

Includes running `make verify-deps` against the aws-ebs-csi-driver. This is dependent on https://github.com/openshift/aws-ebs-csi-driver/pull/166 .

2020-09-04 09:34 UTC, petr-muller requested changes
Please do not modify files under `openshift-priv` - they are automatically synced from their `openshift` counterparts

2020-09-04 14:43 UTC, huffmanca commented
The `openshift-priv` files should be unmodified, and I've updated the jobs under `ci-operator/config/openshift`.

2020-09-07 10:15 UTC, petr-muller commented
/uncc @petr-muller @bbguimaraes 
/cc @bertinatto @gnufied 

Assingning people from ci-operator/config/openshift/aws-ebs-csi-driver/OWNERS for review

2020-09-07 10:15 UTC, petr-muller commented
/uncc

2020-09-09 00:43 UTC, huffmanca commented
/retest

2020-09-09 14:31 UTC, huffmanca commented
/retest

2020-09-22 14:28 UTC, huffmanca commented
/retest

2020-09-24 16:54 UTC, huffmanca commented
/retest

2020-09-24 17:44 UTC, huffmanca commented
/retest

2020-09-25 13:31 UTC, jsafrane commented
/test pj-rehearse

2020-09-25 15:03 UTC, huffmanca commented
Closing this out, as we're going to backport a patch from upstream instead of taking this approach.

2020-09-25 15:03 UTC, closed without merging