Add openshift/sre-ssh-proxy-container repo
openshift/release pull request #11651
Opened 2020-09-05 18:30 UTC by mbarnes

For https://issues.redhat.com/browse/OSD-5071

2020-09-07 19:09 UTC, cblecker requested changes

2020-09-07 19:09 UTC, cblecker commented on core-services/prow/02_config/_plugins.yaml
> +  review_acts_as_lgtm: true
This isn't needed

2020-09-07 19:09 UTC, cblecker commented on core-services/prow/02_config/_plugins.yaml
> +  require_self_approval: false
This isn't needed

2020-09-07 19:09 UTC, cblecker commented on ci-operator/config/openshift/sre-ssh-proxy-container/openshift-sre-ssh-proxy-container-master.yaml
> +  namespace: ocp
We aren't distributing as a part of OCP, so this isn't needed.
```suggestion
```

2020-09-07 19:09 UTC, cblecker commented on ci-operator/config/openshift/sre-ssh-proxy-container/openshift-sre-ssh-proxy-container-master.yaml
> +  namespace: ocp
We aren't distributing as a part of OCP, so this isn't needed.
```suggestion
```

2020-09-07 19:09 UTC, cblecker commented on ci-operator/config/openshift/sre-ssh-proxy-container/openshift-sre-ssh-proxy-container-master.yaml
> +    tag: golang-1.13
```suggestion
build_root:
  image_stream_tag:
    name: release
    namespace: openshift
    tag: golang-1.13
images:
- dockerfile_path: container/Dockerfile
  from: base
  to: sre-ssh-proxy-container
```

2020-09-07 19:09 UTC, cblecker commented on ci-operator/config/openshift/sre-ssh-proxy-container/openshift-sre-ssh-proxy-container-master.yaml
> +    from: src
We don't have access to the raw daemon socket, so we need to use image stream builds in CI
```suggestion
```

2020-09-09 19:25 UTC, mbarnes commented
Applied all suggestions and squashed.

2020-09-09 20:04 UTC, cblecker commented
@mbarnes Can you run `make jobs` to regenerate the config, and also copy https://raw.githubusercontent.com/openshift/sre-ssh-proxy-container/master/OWNERS into `ci-operator/config/openshift/sre-ssh-proxy-container/` and `ci-operator/jobs/openshift/sre-ssh-proxy-container/` ?

2020-09-11 11:52 UTC, mbarnes commented
> @mbarnes Can you run make jobs to regenerate the config, and also copy https://raw.githubusercontent.com/openshift/sre-ssh-proxy-container/master/OWNERS into ci-operator/config/openshift/sre-ssh-proxy-container/ and ci-operator/jobs/openshift/sre-ssh-proxy-container/ ?

Done; amended the commit.

2020-09-11 17:05 UTC, mbarnes commented
/retest

2020-09-11 17:42 UTC, cblecker commented
/test pj-rehearse

2020-09-11 17:46 UTC, cblecker commented on ci-operator/config/openshift/sre-ssh-proxy-container/openshift-sre-ssh-proxy-container-master.yaml
> +  os:
```suggestion
  base:
```

2020-09-11 19:50 UTC, mbarnes commented
Appears to be using the wrong build context.

`make` runs `"$(CONTAINER_ENGINE) build container"` where `CONTAINER_ENGINE` is `docker` or `podman`.

Works fine locally with Docker, but CI job is failing trying to find `container/pam_sshd`.

2020-09-14 04:50 UTC, cblecker commented
/lgtm
/approve

2020-09-15 14:04 UTC, cblecker commented
/assign @alvaroaleman 

This should be good. We can fix the rehearse in-repo.

2020-09-15 14:07 UTC, alvaroaleman approved these changes

2020-09-15 14:15 UTC, merged