WIP Kubevirt ipi provider e2e template
openshift/release pull request #11738
Opened 2020-09-10 14:44 UTC by bardielle

We are working on a project to achieve true multi-tenancy of Openshift were each tenant has dedicated control plane and have full control on its configuration. 
That achieved by installing Openshift on kubevirt infrastructure that running over openshift baremetal, using the installer - an IPI installation.
And so `kubevirt` becomes a new platform provider for Openshift.
For more information please read the enhancements PR: https://github.com/openshift/enhancements/pull/417

This patch adds kubevirt e2e template.
the template runs lease,setup,test,teardown containers

2020-09-10 15:10 UTC, rgolangh commented on core-services/prow/02_config/_plugins.yaml
> +  openshift-priv/cluster-api-provider-kubevirt:
I think you should rename `openshift-priv` to `openshift` and rerun `make prow-config`

2020-09-14 14:13 UTC, rgolangh commented
we're just missing the OWNERS file now. Copy the one you already added and put it under `ci-operator/jobs/openshift/cluster-api-provider-kubevirt`

2020-09-14 15:21 UTC, rgolangh commented
/test pj-rehearse

2020-09-14 15:40 UTC, bardielle commented
/retest

2020-09-18 12:46 UTC, petr-muller requested changes

2020-09-18 12:46 UTC, petr-muller commented on ci-operator/templates/openshift/installer/cluster-launch-installer-kubevirt-e2e.yaml
> +kind: Template
/hold

Templates are legacy and we should *not* add new ones. This should be brought in as multi-stage steps (https://steps.ci.openshift.org/help.

2020-09-30 09:18 UTC, closed without merging