skip olm test until payloads multiarch
openshift/release pull request #12255
Opened 2020-09-25 19:09 UTC by clnperez

the operator image payloads aren't multiarch yet. we'll add this back
when they are (should be at GA)

Signed-off-by: Christy Norman <christy@linux.vnet.ibm.com>

2020-09-25 19:10 UTC, clnperez commented
fyi @jaypoulz

2020-09-25 20:37 UTC, jaypoulz requested changes
Can you also add it to the s390x skip list please. :) This will save @r4f4 a commit. :)

2020-09-25 21:16 UTC, r4f4 commented
> Can you also add it to the s390x skip list please. :) This will save @r4f4 a commit. :)

Not really needed, it's already here https://github.com/openshift/release/pull/11924/files

2020-09-25 21:20 UTC, jaypoulz approved these changes
In that case I change my answer. 👍

2020-09-25 22:23 UTC, clnperez commented
Thanks @r4f4 

I'm seeing a watch closed message in that failure. Not sure if it's related to https://bugzilla.redhat.com/show_bug.cgi?id=1791739 / https://github.com/openshift/origin/pull/25010

```
level=debug msg="Still waiting for the cluster to initialize: Cluster operator authentication is reporting a failure: WellKnownReadyControllerDegraded: kube-apiserver oauth endpoint https://192.168.126.12:6443/.well-known/oauth-authorization-server is not yet served and authentication operator keeps waiting (check kube-apiserver operator, and check that instances roll out successfully, which can take several minutes per instance)"
W0925 19:56:00.901569      89 reflector.go:326] k8s.io/client-go/tools/watch/informerwatcher.go:146: watch of *v1.ClusterVersion ended with: very short watch: k8s.io/client-go/tools/watch/informerwatcher.go:146: Unexpected watch close - watch lasted less than a second and no items received
```

Trying another run.

/retest

2020-09-28 14:31 UTC, clnperez commented
Hmm. This one timed out. Trying one more time.
/retest

2020-09-29 21:30 UTC, clnperez commented
/retest
and will try to catch this as it's running as the artifacts aren't being uploaded

2020-09-29 23:17 UTC, clnperez commented
All tests passed this time. However, now this test is passing in CI -- which I don't quite understand. @jaypoulz -- confirming but I think we should hold off merging this until we're sure we need to skip it.

2020-09-30 09:40 UTC, petr-muller approved these changes
/approve
/hold

Providing the label, merge at will.

2020-10-06 14:57 UTC, clnperez commented
This test is no longer failing so I'm going to close this PR.

2020-10-06 14:57 UTC, closed without merging