Mandate e2e-metal-ipi on cluster-network-operator and ovn-kubernetes
openshift/release pull request #12374
Opened 2020-10-01 14:54 UTC by stbenjam

Multiple times now, pull requests have merged with e2e-metal-ipi failing
with explicitly clear messages in the CI summary that the failure was
CNO and/or OVN related. We are working on renaming these jobs starting
with 4.7 to indicate they are ovn-ipv6, but it's been proven now that
optional jobs are meaningless.

This sets e2e-metal-ipi to be required to pass on both CNO and OVN
master. These jobs are now as stable as any other platform, so there's
no reason to leave them as optional. It's also the only IPv6 coverage
that exists in OpenShift today.

2020-10-02 08:49 UTC, hardys commented
/retest

2020-10-02 11:51 UTC, stbenjam commented
/test pj-rehearse

2020-10-02 13:39 UTC, trozet requested changes
I wouldn't use build02 for your jobs, we found that a bunch of flakes in CI are due to using that build server:
https://github.com/openshift/release/pull/12386

Also don't put this in a commit message:
"but it's been proven now that
optional jobs are meaningless."

Additionally, I would make sure your job shows must gather logs extracted in the web browser, rather than making the user download the entire must gather. That would be a good way to enable people to easily check your logs. Here's an example:

https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_ovn-kubernetes/297/pull-ci-openshift-ovn-kubernetes-master-e2e-aws-ovn/1311479684466216960/artifacts/e2e-aws-ovn/

2020-10-02 13:44 UTC, trozet commented
Also, before we require this. In case we switch back to ipv4 again, please change:
https://github.com/openshift-metal3/dev-scripts/blob/master/network.sh#L81

to be ovn-kubernetes as well.

2020-10-02 18:07 UTC, stbenjam commented
> I wouldn't use build02 for your jobs, we found that a bunch of flakes in CI are due to using that build server:
> #12386

We haven't seen that.

> Also don't put this in a commit message:
> "but it's been proven now that
> optional jobs are meaningless."
>
> Additionally, I would make sure your job shows must gather logs extracted in the web browser, rather than making the user download the entire must gather. That would be a good way to enable people to easily check your logs. Here's an example:

You can file an issue in our jira project to take care of it, but this was not the reason no one looked. The multiple breakages including the first breakage at the end of 4.6 FF showed the failure reason clearly to be OVN highlighted in yellow in spyglass without having to dig into a must-gather. 


> [gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_ovn-kubernetes/297/pull-ci-openshift-ovn-kubernetes-master-e2e-aws-ovn/1311479684466216960/artifacts/e2e-aws-ovn](https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_ovn-kubernetes/297/pull-ci-openshift-ovn-kubernetes-master-e2e-aws-ovn/1311479684466216960/artifacts/e2e-aws-ovn/)

2020-10-05 08:23 UTC, hardys commented
> Also, before we require this. In case we switch back to ipv4 again, please change:
> https://github.com/openshift-metal3/dev-scripts/blob/master/network.sh#L81
> 
> to be ovn-kubernetes as well.

I already proposed that in https://github.com/openshift-metal3/dev-scripts/pull/1108 and based on discussion there it probably makes sense to set NETWORK_TYPE explicitly for each CI job vs relying on any dev-scripts defaults, that way we can be sure that the configuration used matches the revised naming.

2020-10-05 08:29 UTC, hardys commented
> Additionally, I would make sure your job shows must gather logs extracted in the web browser, rather than making the user download the entire must gather. That would be a good way to enable people to easily check your logs. Here's an example:

There are three parts to this - the error pulling the must-gather which you noticed in the failures is a dev-scripts but, that should be fixed via https://github.com/openshift-metal3/dev-scripts/pull/1125

Then there is the problem (as mentioned in that PR) that when the serviceNetwork doesn't come up, must-gather doesn't actually work (arguably a design fault with must-gather, but we could potentially work around it by using scp instead?)

Finally there is the issue that we don't unpack the tarball, which would be a nice improvement, I'll add it to our Jira backlog.

2020-10-05 13:18 UTC, danwinship commented
/lgtm
(though we're also renaming the jobs to have "ipv6" in the name in openshift/ovn-kubernetes so if you want to do that here too while you're here that would be good)

2020-10-05 13:29 UTC, merged