machine-config-operator: fix tests in 4.6 and 4.7 to be in sync with master
openshift/release pull request #12615
Opened 2020-10-09 12:26 UTC by sinnykumari

After 4.7 branch cut, it seems some of the tests which were
optional has become REQUIRED.
Make e2e-metal-ipi test optional,
make aws-proxy and cluster-bootimages always_run to false

2020-10-09 12:28 UTC, sinnykumari commented
/cc @kikisdeliveryservice @yuqi-zhang

2020-10-09 12:55 UTC, sinnykumari commented
/cc @vrutkovs

2020-10-09 14:14 UTC, vrutkovs commented
I think it would be best to copy `ci-operator/config/openshift/machine-config-operator/openshift-machine-config-operator-master__okd.yaml` to `-release-4.6__okd.yaml` and autogenerate tests (updating always_run and optional)

2020-10-09 14:15 UTC, yuqi-zhang approved these changes
Changes look fine to me compared to master, looking at the history the ci-bot updated these fields 3-4 months ago last. I presume we never used the 4.6 branch tests until the cut so we never hit it?

2020-10-09 15:25 UTC, vrutkovs commented
/hold

needs manifest update

2020-10-09 18:11 UTC, kikisdeliveryservice commented
> Changes look fine to me compared to master, looking at the history the ci-bot updated these fields 3-4 months ago last. I presume we never used the 4.6 branch tests until the cut so we never hit it?

yeah 4.6 tests would have been master tests until 4.6 was cut.

2020-10-09 18:17 UTC, kikisdeliveryservice requested changes
Going by memory when I added a test last:

If you want to add tests (the okd tests) you need to update:

https://github.com/openshift/release/blob/master/ci-operator/config/openshift/machine-config-operator/openshift-machine-config-operator-master.yaml

https://github.com/openshift/release/blob/master/ci-operator/config/openshift/machine-config-operator/openshift-machine-config-operator-release-4.6.yaml

https://github.com/openshift/release/blob/master/ci-operator/config/openshift/machine-config-operator/openshift-machine-config-operator-release-4.7.yaml

then run `make update`, then go in and manually fix the always_run & optional stuff

2020-10-12 09:57 UTC, sinnykumari commented
Removed OKD related changes since it has handled in https://github.com/openshift/release/pull/12683

2020-10-12 10:45 UTC, sinnykumari commented
removing hold as we are not handling okd tests here now and hence manifests update is not required now.
/hold cancel

2020-10-12 13:36 UTC, runcom commented
/approve
/lgtm

2020-10-12 13:48 UTC, merged