Rename lbFloatingIP to apiFloatingIP in OpenStack CI
openshift/release pull request #12762
Opened 2020-10-13 15:29 UTC by Fedosin

lbFloatingIP has been deprecated and we should use apiFloatingIP instead.
https://github.com/openshift/installer/blob/master/data/data/install.openshift.io_installconfigs.yaml#L1068

2020-10-13 19:12 UTC, Fedosin commented
/test pj-rehearse

2020-10-13 21:06 UTC, Fedosin commented
/test pj-rehearse

2020-10-14 07:49 UTC, Fedosin commented
/test pj-rehearse

2020-10-14 18:27 UTC, adduarte commented on ci-operator/templates/openshift/installer/cluster-launch-installer-openstack-e2e.yaml
> +            externalNetwork:  ${OPENSTACK_EXTERNAL_NETWORK}
? not important but it's usually better to make the smallest amount of changes per commit. This  is necessary.

2020-10-14 18:30 UTC, adduarte requested changes
The only change should really be  the test lbFloatingIP -> apiiFloatingIP, to other changes are cosmetic in nature no? 
Best to make the smallest change possible per commit.

2020-10-14 18:33 UTC, adduarte requested changes

2020-10-14 18:33 UTC, adduarte commented on ci-operator/templates/openshift/installer/cluster-launch-installer-openstack-e2e.yaml
> +            externalNetwork:  ${OPENSTACK_EXTERNAL_NETWORK}
cosmetic change, not needed.

2020-10-14 18:33 UTC, adduarte commented on ci-operator/step-registry/openstack/conf/generateconfig/openstack-conf-generateconfig-commands.sh
> +    externalNetwork:  ${OPENSTACK_EXTERNAL_NETWORK}
cosmetic change. Only need to change lbFloatingIP -> apiFloatingIP. This many changes make the commit hard to read when exploring the branch? for example "git show this commit" willl create a very large output, when the only thing that change was lbFloatingIP->apiFloatingIP

2020-10-14 19:33 UTC, Fedosin commented
@adduarte yes, I added a small cosmetic change and alphabetized all the parameters. But why do you think that "+5 −5" is `a very large output`?

2020-10-15 08:21 UTC, Fedosin commented
These templates are used in previous versions where lbFloatingIP was mandatory. Therefore we should close this PR until 4.6 is EOL.

2020-10-15 08:21 UTC, closed without merging