osde2e job configuration for addon-ocs-converged
openshift/release pull request #13303
Opened 2020-11-01 10:25 UTC by brainfunked

2020-11-03 15:40 UTC, jeefy requested changes
Job definition looks pretty good! Only thing that needs updating is the secrets. Let me know if you have any questions about the requested changes.

2020-11-03 15:40 UTC, jeefy commented on ci-operator/jobs/openshift/osde2e/openshift-osde2e-main-periodics.yaml
> +        value: /usr/local/osde2e-common,/usr/local/osde2e-credentials
You should not use the `osde2e-credentials` and instead you should use `/usr/local/ocs-convered-credentials`

2020-11-03 15:40 UTC, jeefy commented on ci-operator/jobs/openshift/osde2e/openshift-osde2e-main-periodics.yaml
> +    - name: osde2e-credentials
This name and the secret name should match the defined secrets below (`ocs-converged-credentials`)

2020-11-05 02:17 UTC, jeefy commented
/test osde2e-stage-aws-addon-ocs-converged

2020-11-05 02:21 UTC, jeefy commented
/test pj-rehearse

2020-11-09 08:44 UTC, brainfunked commented
@jeefy As we discussed on Slack, I'm closing this PR into two separate ones to get the secret mapping merged first.

2020-11-09 08:44 UTC, closed without merging