Use base_image specified in WMCO repo
openshift/release pull request #13320
Opened 2020-11-02 14:27 UTC by sebsoto

This allows us to change the go version used to build artifacts with
changes to the WMCO repo, instead of the release repo as it was
previously done.

2020-11-02 14:38 UTC, aravindhp approved these changes
/approve
/hold

@sebsoto please remove the hold whenever you are ready for this to merg.

2020-11-02 14:42 UTC, aravindhp requested changes
@sebsoto you need to run `make ci-operator-config`
/approve cancel

2020-11-03 15:59 UTC, aravindhp approved these changes
/lgtm

@sebsoto please wait for at least one operator e2e to pass before removing the hold

2020-11-03 16:00 UTC, aravindhp commented
/retest

2020-11-03 17:13 UTC, sebsoto commented
/retest

2020-11-03 18:38 UTC, sebsoto commented
/retest

2020-11-04 17:17 UTC, sebsoto commented
/retest

2020-11-05 14:17 UTC, sebsoto commented
/retest

2020-11-05 14:17 UTC, sebsoto commented
Tests passed for 4.6 e2e, curious if the socket error will be gone now that https://github.com/openshift/windows-machine-config-operator/pull/161 merged

2020-11-05 16:30 UTC, aravindhp commented
@sebsoto we are seeing green on the `build` and `images` job which means the binary / container is getting built correctly. I am comfortable getting this merged now. Worst case we can revert the PR if we find CI issues.

2020-11-05 17:33 UTC, sebsoto commented
/hold cancel

2020-11-05 21:27 UTC, sebsoto commented
/hold

2020-11-05 21:28 UTC, aravindhp commented
/lgtm

2020-11-05 21:30 UTC, sebsoto commented
/hold cancel

2020-11-05 22:00 UTC, merged