wmco: Add testing for release-4.6-community branch
openshift/release pull request #13557
Opened 2020-11-11 16:06 UTC by LorbusChris

Adds presubmit tests for PRs on the new community branch. Tests will run
on an OKD cluster, with the exception of Azure and vSphere e2e tests,
which will run on OCP as they're currently nut runnable on OKD.

/cc @sebsoto @aravindhp @vrutkovs

2020-11-11 17:43 UTC, aravindhp requested changes
@LorbusChris, thanks for doing this. Please add the commands / procedure you followed to add this to the commit message.

2020-11-11 17:43 UTC, aravindhp commented on ci-operator/config/openshift/windows-machine-config-operator/openshift-windows-machine-config-operator-release-4.6-community__okd.yaml
> +- as: aws-e2e-operator-with-custom-vxlan-port
I suggest leaving this out. This will eventually be targeted at vSphere. I don't see folks on the community side using a custom VXLAN port with AWS.

2020-11-17 15:17 UTC, sebsoto commented
/retest

2020-11-17 15:49 UTC, sebsoto commented
/retest

2020-11-17 16:20 UTC, sebsoto commented
/retest

2020-11-17 16:41 UTC, sebsoto commented
/retest

2020-11-17 17:04 UTC, sebsoto commented
/lgtm

2020-11-17 17:40 UTC, aravindhp approved these changes
/lgtm

2020-11-17 18:08 UTC, stevekuznetsov approved these changes

2020-11-17 18:08 UTC, stevekuznetsov commented
/hold

2020-11-17 18:32 UTC, LorbusChris commented
/retest

2020-11-17 19:23 UTC, LorbusChris commented
/retest

2020-11-17 22:23 UTC, sebsoto commented
/lgtm

2020-11-17 23:22 UTC, sebsoto commented
/hold cancel

2020-11-17 23:45 UTC, merged