Add ceph storage gating configuration for openshift/console
openshift/release pull request #13744
Opened 2020-11-19 03:32 UTC by a2batic

Signed-off-by: Kanika Murarka <kmurarka@redhat.com>

2020-11-20 04:09 UTC, a2batic commented
/test pj-rehearse

2020-11-23 05:32 UTC, bipuladh commented
/test pj-rehearse

2020-11-24 05:28 UTC, a2batic commented
/assign @rhrazdil

2020-11-24 06:43 UTC, bipuladh commented
/test pj-rehearse

2020-11-24 07:47 UTC, a2batic commented
/assign @alexnpavel

2020-11-24 09:57 UTC, cloudbehl commented on ci-operator/jobs/openshift/console/openshift-console-master-presubmits.yaml
> +          value: ./test-cypress.sh -p ceph -h true
```suggestion
          value: ./test-prow-e2e.sh ceph
```

2020-11-24 09:57 UTC, cloudbehl commented on ci-operator/jobs/openshift/console/openshift-console-master-presubmits.yaml
> +          value: ./test-cypress.sh -p ceph -h true
https://github.com/openshift/console/pull/7308

2020-11-24 10:03 UTC, bipuladh commented
/hold
until https://github.com/openshift/console/pull/7308 merges

2020-11-24 18:28 UTC, cloudbehl commented
/hold cancel

2020-11-26 09:02 UTC, cloudbehl commented
/retest

2020-11-26 09:02 UTC, cloudbehl commented
/test pj-rehearse

2020-11-27 12:05 UTC, a2batic commented
/test pj-rehearse

2020-12-16 05:57 UTC, cloudbehl commented
@a2batic can you rebase the PR and also add a new parameter of instance_type.

https://github.com/openshift/release/pull/14350

2020-12-17 07:29 UTC, cloudbehl commented on ci-operator/jobs/openshift/console/openshift-console-master-presubmits.yaml
> +        - name: JOB_NAME_SAFE
can you add this?
```
    - name: COMPUTE_NODE_TYPE
      value: m5.2xlarge
```

2020-12-17 07:30 UTC, bipuladh commented on ci-operator/jobs/openshift/console/openshift-console-master-presubmits.yaml
> +        - name: JOB_NAME_SAFE
NIT: m4.2xlarge

2020-12-17 08:11 UTC, umangachapagain requested changes

2020-12-17 08:11 UTC, umangachapagain commented on ci-operator/config/openshift/console/openshift-console-master.yaml
> +    cluster_profile: azure4
```suggestion
    cluster_profile: aws
```

2020-12-17 08:11 UTC, umangachapagain commented on core-services/template-deprecation/_allowlist.yaml
> +          kind: presubmit
```suggestion
```

2020-12-17 12:03 UTC, bipuladh commented
/retest

2020-12-28 15:02 UTC, bipuladh commented
/retest

2020-12-29 04:03 UTC, bipuladh commented
/retest

2020-12-29 07:40 UTC, bipuladh commented
/retest

2020-12-30 05:17 UTC, bipuladh commented
/retest

2021-01-04 05:44 UTC, cloudbehl commented
/retest

2021-01-04 05:45 UTC, cloudbehl commented
test pj-rehearse

2021-01-05 06:25 UTC, bipuladh commented
/retest

2021-01-05 07:39 UTC, bipuladh commented
/retest

2021-01-05 14:19 UTC, bipuladh commented
/retest ci/prow/pj-rehearse

2021-01-05 18:39 UTC, bipuladh commented
/retest

2021-01-06 05:34 UTC, bipuladh commented
/retest

2021-01-07 05:56 UTC, bipuladh commented
/retest

2021-01-07 11:45 UTC, bipuladh commented
/close
Replacement PR: https://github.com/openshift/release/pull/14682

2021-01-07 11:45 UTC, closed without merging