bump ocs-operator ci tests nodes to 4
openshift/release pull request #14296
Opened 2020-12-13 04:40 UTC by raghavendra-talur

This is a requirement for a new feature which requires at least 4 worker
nodes.

Signed-off-by: Raghavendra Talur <raghavendra.talur@gmail.com>

2020-12-13 04:43 UTC, raghavendra-talur commented
cc @jarrpa @obnoxxx @iamniting 

The intention is to get a setup for our ci tests where there are 4 worker nodes. This is necessary to be able to host an arbiter setup.

If we don't want to do this, workaround would be to run the OSDs on the master nodes, which is not a real setup.

2020-12-14 05:43 UTC, iamniting commented
FYI In the 4 worker nodes case also we are going to run arbiter mon on the master node.

2020-12-14 20:58 UTC, jarrpa requested changes
I believe the files under `ci-operator/jobs` are generated, and that we probably want to create a custom environment here: https://github.com/openshift/release/tree/master/ci-operator/templates/openshift/installer

Did you run `make update` from the root of the repo to make sure it doesn't get overwritten? https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_release/14296/pull-ci-openshift-release-master-generated-config/1337980879145799680

2021-02-18 21:18 UTC, raghavendra-talur commented
Closing this PR for now. We will revisit when we decide to run arbiter test cases in the default CI run.

2021-02-18 21:18 UTC, closed without merging