supplemental-images: add centos7 imagestream
openshift/release pull request #14669
Opened 2021-01-06 19:36 UTC by vrutkovs

Import official centos7 image so that it could be reused in builds.

Cincinnati team has been using `quay.io/app-sre/centos:7`, but its apparently not available anymore (see https://github.com/openshift/cincinnati/pull/351)

2021-01-07 08:36 UTC, vrutkovs commented
/cc @LalatenduMohanty

2021-01-11 18:35 UTC, wking commented
[For almost a year][1], we've been using `ci/centos:7` from the CI registry.  Do we need a new CentOS image?  It's not clear to me why we can't use the one we already have (although #14518 has me struggling around the lack of `from` configuration in the `build_root` entry.

[1]: https://github.com/openshift/release/commit/f29b252a6b07e82e3cb6c238baa49385c83622c4#diff-68782ff9568162c433709e5b8b1547dec3c13ca7d6ef74748cc24246558ea60bR2

2021-01-12 10:09 UTC, LalatenduMohanty commented
/lgtm 

Lets move ahead with this one as we have been struggling to fix https://github.com/openshift/release/pull/14518 and we do not have much time.

2021-01-12 10:11 UTC, LalatenduMohanty commented
/lgtm cancel 

As @vrutkovs suggested to use `https://registry.centos.org/centos/centos`

2021-01-12 10:12 UTC, LalatenduMohanty requested changes
As discussed we should use `https://registry.centos.org/centos/centos`

2021-01-12 10:22 UTC, LalatenduMohanty commented
> As discussed we should use `https://registry.centos.org/centos/centos`

we need to send this change to Cincinnati

/lgtm

2021-01-12 10:47 UTC, vrutkovs commented
/hold

There is already a centos image in `ci` namespace

2021-01-15 12:13 UTC, vrutkovs commented
This is not required, there's already `centos` in `ci` namespace

2021-01-15 12:13 UTC, closed without merging