Run single node live CD flow on installer presubmit
openshift/release pull request #14764
Opened 2021-01-11 18:06 UTC by omertuc

2021-01-27 21:48 UTC, jstuever requested changes
I don't think this should be blocking for all PRs.

2021-01-27 21:48 UTC, jstuever commented on ci-operator/jobs/openshift/installer/openshift-installer-master-presubmits.yaml
> +    name: pull-ci-openshift-installer-master-e2e-metal-single-node-live-iso
Add `optional: true`

2021-01-27 21:48 UTC, jstuever commented on ci-operator/jobs/openshift/installer/openshift-installer-master-presubmits.yaml
> +    always_run: true
`always_run: false`

2021-01-27 22:28 UTC, omertuc commented
> I don't think this should be blocking for all PRs.

Right, of-course. Just forgot to `git add`. Fixing.

2021-02-05 00:12 UTC, jstuever commented
/lgtm

2021-02-05 00:15 UTC, jstuever commented
/assign @staebler
I don't know if we need more rehearsals to pass, but we probably wont' get them all in one go.

2021-02-05 00:16 UTC, jstuever commented
/test pj-rehearse

2021-02-05 00:33 UTC, staebler commented
/approve

2021-02-05 01:08 UTC, merged