WIP: openshift/assisted-service: linting and formatting
openshift/release pull request #14816
Opened 2021-01-13 17:14 UTC by lranjbar

Creating separate jobs to run these commands in prow

2021-01-14 20:09 UTC, lranjbar commented
@YuviGold When you have a chance to review

2021-01-14 20:43 UTC, djzager requested changes
Nice work! Two comments.

2021-01-14 20:43 UTC, djzager commented on ci-operator/config/openshift/assisted-service/openshift-assisted-service-master.yaml
> +- as: format
ended up removing the `format` check. If people complain about not knowing why `format-check` fails....then we can add it later.

2021-01-14 20:43 UTC, djzager commented on ci-operator/config/openshift/assisted-service/openshift-assisted-service-master.yaml
>  tests:
I think it would be nice to have `verify-latest-onprem-config` as a check.

2021-01-15 04:36 UTC, lranjbar commented
/retest

2021-01-15 23:02 UTC, lranjbar commented
/retest

2021-01-17 08:36 UTC, YuviGold approved these changes
LGTM

2021-01-18 23:05 UTC, lranjbar commented
@YuviGold The format-check job is finally failing correctly so this can be merged. It fails because there are format issues to fix in assisted-service.

2021-01-19 07:47 UTC, YuviGold commented
/retest

2021-01-19 07:54 UTC, YuviGold commented
> @YuviGold The format-check job is finally failing correctly so this can be merged. It fails because there are format issues to fix in assisted-service.

@lranjbar  We should fix the formatting fix before pushing it, so it won't block anyone.

2021-01-25 18:11 UTC, lranjbar commented
/retest

2021-01-25 18:21 UTC, YuviGold commented
/lgtm

Holding for the tests to still run. You can unhold after they pass.
/hold

2021-01-25 19:48 UTC, YuviGold commented
/retest

2021-01-25 23:04 UTC, lranjbar commented
/unhold

2021-01-25 23:22 UTC, merged