change machine-os-content periodics to use multi-stage steps
openshift/release pull request #14980
Opened 2021-01-18 13:23 UTC by droslean

Signed-off-by: Nikolaos Moraitis <nmoraiti@redhat.com>

2021-01-18 14:06 UTC, droslean commented
/cc @openshift/openshift-team-developer-productivity-test-platform

2021-01-18 14:10 UTC, petr-muller requested changes

2021-01-18 14:10 UTC, petr-muller commented on ci-operator/jobs/openshift/release/openshift-release-release-4.1-periodics.yaml
> +      - name: UNRESOLVED_CONFIG
You will also need to: 
1. remove the `--template` parameter
2. Remove the template volume mount
3. Remove the template volume

2021-01-18 16:03 UTC, stevekuznetsov commented
I would ask @AlexNPavel so that both of you are using the same automation to do this.

2021-01-19 23:31 UTC, stevekuznetsov commented
/assign @AlexNPavel

2021-01-20 07:07 UTC, droslean commented
/test pj-rehearse

2021-01-20 18:57 UTC, petr-muller commented
Eyeballed, looks good. I'm not 100% conviced that removing the config from the alt-arch jobs (that currently do not run ci-op at all) is a must, but it seems that the TODOs to make the jobs actually test somethign will not be fulfilled anytime soon, so /meh. I agree that Alex is the best person to review this.

2021-01-21 17:02 UTC, AlexNPavel approved these changes

2021-01-21 17:54 UTC, merged