Add skip baremetalds e2e tests environment variable
openshift/release pull request #16175
Opened 2021-02-23 14:27 UTC by YuviGold

2021-02-23 15:33 UTC, osherdp requested changes

2021-02-23 15:33 UTC, osherdp commented on ci-operator/step-registry/baremetalds/assisted/baremetalds-assisted-workflow.yaml
> +          documentation: Wheter to skip the e2e tests
typo

2021-02-23 15:33 UTC, osherdp commented on ci-operator/step-registry/baremetalds/assisted/baremetalds-assisted-workflow.yaml
> +          documentation: Wheter to skip the e2e tests
also, this sentence is not complete

2021-02-23 15:39 UTC, osherdp approved these changes
/lgtm

2021-02-24 12:59 UTC, YuviGold commented
Resolved breaking serial conformance tests that were introduced on https://github.com/openshift/release/pull/16075 by splitting the conf step on https://github.com/openshift/release/pull/16207

2021-02-24 12:59 UTC, closed without merging