Add openshift/driver-toolkit to the openshift-ci
openshift/release pull request #16681
Opened 2021-03-10 15:50 UTC by dagrayvid

Add openshift/driver-toolkit to the OpenShift CI. driver-toolkit is a container to be used as a base for creating driver-containers for OpenShift. For more information see [SRO](https://github.com/openshift-psap/special-resource-operator) and this [enhancement](https://github.com/openshift/enhancements/pull/357). We don't want to require any tests/branch-protection (at least for now) but want automated release branching / tide.

Signed-off-by: David Gray dagray@redhat.com

2021-03-10 15:50 UTC, dagrayvid commented
/cc @ArangoGutierrez
/cc @zvonkok

2021-03-10 15:54 UTC, ArangoGutierrez requested changes
If this is just a driver-container I don't see why running the full aws-e2e suite. at least not until SRO becomes CVO. we need to find a better way to run a quick and dirty test over the repo that is not the full e2e-aws suite (which is also slow)

2021-03-10 15:54 UTC, ArangoGutierrez commented on ci-operator/config/openshift/driver-toolkit/openshift-driver-toolkit-master.yaml
> +    workflow: openshift-e2e-aws
not needed

2021-03-10 15:54 UTC, ArangoGutierrez commented on ci-operator/config/openshift/driver-toolkit/openshift-driver-toolkit-release-4.6.yaml
> +- as: e2e-aws
not needed

2021-03-10 15:54 UTC, ArangoGutierrez commented on ci-operator/config/openshift/driver-toolkit/openshift-driver-toolkit-release-4.7.yaml
> +- as: e2e-aws
not needed

2021-03-10 17:26 UTC, zvonkok commented
/lgtm

2021-03-10 20:35 UTC, dagrayvid commented
/retest

2021-03-11 09:38 UTC, zvonkok commented
/retest

2021-03-11 13:03 UTC, dagrayvid commented
/retest

2021-03-11 13:17 UTC, dagrayvid commented
/retest

2021-03-11 13:32 UTC, dagrayvid commented
/retest

2021-03-11 13:46 UTC, zvonkok commented
/lgtm

2021-03-11 13:46 UTC, zvonkok commented
/approve

2021-03-11 13:56 UTC, ArangoGutierrez commented
/assign @petr-muller

2021-03-16 13:20 UTC, ArangoGutierrez commented
PING @petr-muller

2021-03-16 13:32 UTC, ArangoGutierrez approved these changes
/lgtm

2021-03-16 13:32 UTC, dagrayvid commented
/retest

2021-03-16 14:05 UTC, petr-muller approved these changes

2021-03-16 15:25 UTC, merged