Ensure e2e disruptive runs against mao and cma
openshift/release pull request #17000
Opened 2021-03-20 00:16 UTC by marun

Machine approver and machine api operator are critical path for disruptive testing and failure of the disruptive job will need to block merges in the future. For now, the jobs are optional until enough signal indicates that gating is possible.

These jobs remain template pending @smarterclayton's work to migrate to the step registry.

2021-03-20 01:52 UTC, michaelgugino requested changes
I don't think we're going to catch much of anything by enabling these on the MAO repo or the machine approver repo.

2021-03-20 03:53 UTC, marun commented
> I don't think we're going to catch much of anything by enabling these on the MAO repo or the machine approver repo.

I have 2 failure modes (previously: machines not getting removed in a timely manner and currently: new machines not getting approved) that suggest otherwise. DR hasn't been able to be blocking anything for multiple releases now, and that's largely because too many repos are capable of merging breaking changes.

2021-03-29 18:45 UTC, michaelgugino commented
@marun sorry I missed your previous comment.  The most impactful changes to machines not joining the cluster are 1) RHCOS 2) MCO and friends 3) CRIO 4) kubelet

One of these repos breaks machines joining the cluster at least once per release.  By contrast, the CSR approver would be unlikely to pass the standard suite if we were broken.

2021-04-01 16:20 UTC, smarterclayton commented
Please reopen this.  MCO and MAO are expected to be participants in cluster recovery.  Agree approver isn't useful and we can remove from here.

2021-04-01 16:24 UTC, smarterclayton commented
Although if we have evidence approver fails, and approver get so few PRs, it would be good to get disruptive on approver.

2021-04-01 19:38 UTC, smarterclayton commented
will tag once i see green

2021-04-03 17:13 UTC, marun commented
/retest

2021-04-05 21:12 UTC, marun commented
/retest

2021-04-06 12:32 UTC, marun commented
@smarterclayton Green on machine-api-operator...

Note that these are optional for now, so no harm in merging.

2021-04-06 12:32 UTC, marun commented
/retest

2021-04-06 16:54 UTC, marun commented
/retest

2021-04-07 12:03 UTC, petr-muller commented
/approve
(allowlist)

2021-04-12 16:06 UTC, marun commented
/retest

2021-04-12 16:10 UTC, smarterclayton commented
/lgtm
/approve

2021-04-12 16:16 UTC, smarterclayton commented
/retest

2021-04-12 21:20 UTC, smarterclayton commented
/retest

2021-04-12 21:36 UTC, merged