Update e2e-crc tests
openshift/release pull request #17146
Opened 2021-03-25 08:55 UTC by praveenkumar

This patch will use the ci script which present
in the snc repo instead of putting again everything here.

2021-03-25 10:07 UTC, cfergeau commented on ci-operator/step-registry/openshift/e2e/gcp/crc/test/openshift-e2e-gcp-crc-test-commands.sh
>    ./ci.sh
I'm confused by the log, isn't this already using the `ci.sh` script even before this commit?

2021-03-25 10:10 UTC, cfergeau commented on ci-operator/step-registry/openshift/e2e/gcp/crc/test/openshift-e2e-gcp-crc-test-commands.sh
>    ./ci.sh
Ok, this code has been moved to snc as part of https://github.com/code-ready/snc/commit/e6cbd23ad255c862597fffdb021846ba70a58aa4

2021-03-25 10:18 UTC, cfergeau requested changes
/approve if the commit log is slightly reworded.

2021-03-25 12:08 UTC, praveenkumar commented
/retest

2021-03-25 13:38 UTC, praveenkumar commented
/hold

Till CI is green

2021-03-25 14:33 UTC, praveenkumar commented
/retest

2021-03-26 03:45 UTC, praveenkumar commented
/retest

2021-03-26 06:40 UTC, praveenkumar commented
/retest

2021-03-26 11:01 UTC, praveenkumar commented
/retest

2021-03-26 13:24 UTC, praveenkumar commented
/retest

2021-03-26 13:42 UTC, cfergeau approved these changes

2021-03-26 13:42 UTC, cfergeau commented
/lgtm

2021-03-26 17:07 UTC, praveenkumar commented
/hold cancel

2021-03-26 17:17 UTC, merged