Bug 1936874: move e2e-openstack-upgrade to VEXXHOST
openshift/release pull request #17197
Opened 2021-03-26 12:51 UTC by EmilienM

Move the e2e-openstack-upgrade jobs into the VEXXHOST cloud and
hopefully get more stable results.

2021-03-26 13:01 UTC, alvaroaleman commented
/uncc

2021-03-26 13:03 UTC, EmilienM commented
/cc adduarte mandre

2021-03-26 14:21 UTC, EmilienM commented
/test pj-rehearse

2021-03-27 09:48 UTC, mandre commented
/test pj-rehearse

2021-03-28 19:09 UTC, EmilienM commented
/hold i need to add other jobs once we see green CI

2021-04-06 19:35 UTC, EmilienM commented
/retest

2021-04-20 18:03 UTC, EmilienM commented
/retest

2021-04-29 13:05 UTC, vrutkovs approved these changes
/lgtm

2021-04-29 13:07 UTC, EmilienM commented
/retest

2021-04-29 15:42 UTC, vrutkovs commented
/retest

2021-04-29 17:12 UTC, vrutkovs commented
/retest

2021-04-30 08:12 UTC, vrutkovs commented
/retest

2021-04-30 08:57 UTC, vrutkovs commented
/lgtm cancel

Seems 4.6/4.7/4.8 jobs didn't get `cluster_profile` updated

2021-05-18 14:39 UTC, iamemilio commented
/hold cancel

2021-05-18 15:46 UTC, iamemilio commented
/retest

2021-05-18 20:59 UTC, iamemilio commented
/retest

2021-05-19 01:15 UTC, iamemilio commented
/retest

2021-05-19 14:05 UTC, iamemilio commented
These tests are failing, but they are currently failing like this in CI, so the PR is not the issue :)

2021-05-19 16:26 UTC, iamemilio commented
/lgtm

2021-05-19 16:26 UTC, iamemilio commented
/approve

2021-05-19 16:51 UTC, vrutkovs commented
/hold

vexxhost doesn't have Octavia, so upgrade tests would permafail on `timed out waiting for service \"service-test\" to have a load balancer`

2021-06-02 23:14 UTC, EmilienM commented
/retest
we now have octavia in our public cloud!

2021-06-10 09:56 UTC, vrutkovs commented
Still seeing `timed out waiting for service \"service-test\" to have a load balancer` in periodic-ci-openshift-release-master-ci-4.8-upgrade-from-stable-4.7-e2e-openstack-upgrade, lets give it another try

/retest

2021-06-10 13:37 UTC, vrutkovs commented
While we're at that, `openstack-installer` refs need to be fixed in:
* ci-operator/config/openshift/release/openshift-release-master__ci-4.6-upgrade-from-stable-4.5.yaml
* ci-operator/config/openshift/release/openshift-release-master__ci-4.7-upgrade-from-stable-4.7.yaml

Both on these files mistakenly use 4.6 installer, instead of 4.5/4.7

2021-06-16 08:07 UTC, vrutkovs requested changes
Needs rebase and updated `openstack-installer` reference to pass upgrades

/lgtm cancel

2021-07-15 01:23 UTC, EmilienM commented
4.6 fails to deploy because our OpenStack cloud has self signed certificate. I suggest that we backport the necessary fixes to make it work, if possible.

As for the other failure, it seems related to the platform, Neutron API had some issues to address the query...

2021-07-15 01:23 UTC, EmilienM commented
/test pj-rehearse

2021-07-15 09:52 UTC, vrutkovs commented on ci-operator/config/openshift/release/openshift-release-master__ci-4.7-upgrade-from-stable-4.6.yaml
> +    cluster_profile: openstack-vh-mecha
```suggestion
    cluster_profile: openstack-vh-mecha
```

Extra space breaks generated job verification

2021-07-16 03:06 UTC, EmilienM commented on ci-operator/config/openshift/release/openshift-release-master__ci-4.7-upgrade-from-stable-4.6.yaml
> +    cluster_profile: openstack-vh-mecha
Thanks!

2021-07-26 08:43 UTC, vrutkovs commented
/hold cancel
/lgtm

2021-07-26 08:45 UTC, vrutkovs commented
/assign @ravisantoshgudimetla

2021-07-26 15:47 UTC, EmilienM commented
/bugzilla refresh

2021-07-26 15:57 UTC, EmilienM commented
/bugzilla refresh
/hold

@vrutkovs what do you think about the [failures](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_release/17197/rehearse-17197-periodic-ci-openshift-release-master-ci-4.8-upgrade-from-stable-4.7-e2e-openstack-upgrade/1419470014100017152), should we add them to a skip list so we make the job green?

2021-07-26 16:24 UTC, vrutkovs commented
>@vrutkovs what do you think about the failures

These don't seem to be related to the change

> should we add them to a skip list so we make the job green?

Rehearsal works won't block merging this (`ci/prow/pj-rehearse` is not marked as `Required`)

2021-07-26 16:27 UTC, EmilienM commented
/hold cancel

2021-07-26 16:28 UTC, EmilienM commented
> Rehearsal works won't block merging this (`ci/prow/pj-rehearse` is not marked as `Required`)

Right, I guess my question is: "would it be cool to make the job green by excluding some tests that we know fail today, in this PR or maybe in another PR or are we fine with a job that is red all times"

My take: make the job green even if some tests are failing (using TEST_SKIPS)

2021-07-26 17:19 UTC, vrutkovs commented
>would it be cool to make the job green by excluding some tests that we know fail today

I don't think its a great idea. Tests failing during upgrade usually indicate bugs, so these should be filed - instead of adding more skipped tests.

2021-08-23 08:34 UTC, pierreprinetti commented
@EmilienM Would you please change the message of the commit to reflect what this PR is doing? I will be glad to LGTM then

2021-08-23 13:31 UTC, pierreprinetti commented
/approve
/lgtm

2021-08-24 14:04 UTC, vrutkovs commented
/approve

2021-08-25 12:37 UTC, mandre commented
As the bot suggests,
/assign ravisantoshgudimetla

2021-09-10 07:38 UTC, mandre commented
BZ https://bugzilla.redhat.com/show_bug.cgi?id=1936874 is no longer relevant and should probably be closed as we removed the 4.5->4.6 upgrade job. Do you mind updating the commit message?

2021-12-16 16:22 UTC, pierreprinetti commented
This issue seems to be fixed now: https://github.com/openshift/release/blob/1f9cf8282dd46f692b01f8d1222c38872302fb14/ci-operator/config/shiftstack/shiftstack-ci/shiftstack-shiftstack-ci-main__periodic-4.8-upgrade-from-stable-4.7.yaml#L3

/close

@EmilienM please reopen if I am missing something.

2021-12-16 16:26 UTC, closed without merging