ocm:server-foundation add sonarcloud
openshift/release pull request #17342
Opened 2021-03-31 10:48 UTC by zhiweiyin318

2021-03-31 15:12 UTC, qiujian16 commented on ci-operator/jobs/open-cluster-management/multicloud-operators-foundation/open-cluster-management-multicloud-operators-foundation-main-presubmits.yaml
> +
eof?

2021-03-31 15:14 UTC, zhiweiyin318 commented on ci-operator/jobs/open-cluster-management/multicloud-operators-foundation/open-cluster-management-multicloud-operators-foundation-main-presubmits.yaml
> +
fixed

2021-04-01 14:21 UTC, ray-harris requested changes

2021-04-01 14:21 UTC, ray-harris commented on ci-operator/config/open-cluster-management/multicloud-operators-foundation/open-cluster-management-multicloud-operators-foundation-main.yaml
> +  open-cluster-management_builder_go1.15-linux-amd64:
You don't need this part. Base images define external images to use as the "from:" field in the "images:" stanza. For "images:" you only need "base".

2021-04-01 14:21 UTC, ray-harris commented on ci-operator/config/open-cluster-management/multicloud-operators-foundation/open-cluster-management-multicloud-operators-foundation-main.yaml
> +    from: open-cluster-management_builder_go1.15-linux-amd64
This needs to be "from: src". The "open-cluster-management_builder_go1.15-linux-amd64" doesn't have your source code injected into it.

The "src" image is automatically built by Prow by taking the "build_root" image and injecting your source code into it.

2021-04-02 00:04 UTC, zhiweiyin318 commented
/retest

2021-04-14 14:41 UTC, zhiweiyin318 commented
/retest

2021-04-15 03:07 UTC, zhiweiyin318 commented
/retest

2021-04-15 06:26 UTC, zhiweiyin318 commented
/retest

2021-04-15 06:58 UTC, zhiweiyin318 commented
/retest

2021-04-15 08:05 UTC, zhiweiyin318 commented
/retest

2021-04-15 14:01 UTC, qiujian16 commented
/retest

2021-04-19 14:37 UTC, qiujian16 commented
/lgtm

2021-04-19 16:16 UTC, merged