WIP: assisted-installer: Split cluster creation and deployment into two steps
openshift/release pull request #17370
Opened 2021-03-31 22:12 UTC by lranjbar

Major WIP: Trying to split these steps to deploy assisted-installer on dev-scripts provisioned cluster.

2021-03-31 22:13 UTC, lranjbar commented
/test all

2021-04-06 06:02 UTC, lranjbar commented
/test all

2021-04-06 17:21 UTC, lranjbar commented
/retest

2021-04-07 14:53 UTC, lranjbar commented
/retest

2021-04-07 15:32 UTC, lranjbar commented
/retest

2021-04-07 18:48 UTC, lranjbar commented
/retest

2021-04-07 19:10 UTC, lranjbar commented
/retest

2021-04-07 19:18 UTC, lranjbar commented
/retest

2021-04-07 20:18 UTC, lranjbar commented
/retest

2021-04-07 20:36 UTC, lranjbar commented
/retest

2021-04-07 21:05 UTC, lranjbar commented
/test all

2021-04-07 22:12 UTC, lranjbar commented
/retest

2021-04-07 22:44 UTC, lranjbar commented
/retest

2021-04-08 00:27 UTC, lranjbar commented
/retest

2021-04-09 15:29 UTC, lranjbar commented
/retest

2021-04-09 17:13 UTC, lranjbar commented
/retest

2021-04-19 17:32 UTC, lranjbar commented
/retest

2021-04-19 18:49 UTC, lranjbar commented
/retest

2021-04-19 21:17 UTC, lranjbar commented
/retest

2021-04-20 00:50 UTC, lranjbar commented
/retest

2021-04-20 20:05 UTC, lranjbar commented
/test ci-secret-bootstrap-config-validation

2021-05-19 16:48 UTC, osherdp requested changes

2021-05-19 16:48 UTC, osherdp commented on ci-operator/step-registry/baremetalds/assisted/deploy/OWNERS
> +approvers:
can you add me? :)

2021-05-19 16:48 UTC, osherdp commented on ci-operator/step-registry/baremetalds/assisted/deploy/baremetalds-assisted-deploy-commands.sh
> +# Copy assisted source from current directory to the remote server
it's ``assisted-test-infra``, no?

2021-05-19 16:48 UTC, osherdp commented on ci-operator/step-registry/baremetalds/assisted/minikube/setup/baremetalds-assisted-minikube-setup-commands.sh
> +make create_full_environment
hmm, shouldn't it be ``make start_minikube``?

2021-05-19 16:48 UTC, osherdp commented on ci-operator/step-registry/baremetalds/assisted/minikube/OWNERS
> +approvers:
here as well

2021-05-20 06:16 UTC, YuviGold commented
Sorry, but I don't that this solution of duplicating the whole step is a good approach.
For using other Makefile targets there is the `MAKEFILE_TARGET` variable
for example for system-test-olm it is called liked that:
https://github.com/openshift/release/blob/87e8c5ad7b768326271a8ea15cd99f5d74bb7131/ci-operator/config/openshift/assisted-test-infra/openshift-assisted-test-infra-master.yaml#L64-L72

/hold

2021-06-28 16:36 UTC, lranjbar commented
Closed - obsolete

2021-06-28 16:36 UTC, closed without merging