Add boilerplate v0.5.2
openshift/release pull request #17916
Opened 2021-04-21 02:32 UTC by cblecker

ref https://github.com/openshift/boilerplate/pull/158

2021-04-21 14:53 UTC, 2uasimojo requested changes
We'll also need to add the image to our [DPTP-1640 workaround](https://github.com/openshift/release/blob/1a4b43ee6ec0725d9d474d89ecdbe40c6c0f1f10/ci-operator/config/openshift/boilerplate/openshift-boilerplate-master.yaml). Note that that depends on this change, so either we do it in this PR and we'll have to merge despite failed rehearsals; or we do it in a separate PR.

2021-04-21 14:53 UTC, 2uasimojo commented on clusters/app.ci/supplemental-ci-images/boilerplate/boilerplate.yaml
> +    name: image-v0.5.1
```suggestion
    name: image-v0.5.2
```

2021-04-21 15:12 UTC, cblecker commented
@2uasimojo updated

2021-04-22 16:36 UTC, 2uasimojo commented
The [boilerplate side](https://github.com/openshift/boilerplate/pull/158) is merged.

This one is expected to fail rehearsals due to chicken/egg problem: the supplemental-ci-images change is necessary to produce the image referenced by the ci-operator config change. We could split those into two PRs, or we could just rely on visual inspection and merge this all-in-one. I'm going with the latter.

/lgtm
/approve

2021-04-22 16:48 UTC, merged