oVirt: change job without-csi name to release-4.4-4.5 and add release-4.6-4.7 workflow
openshift/release pull request #18439
Opened 2021-05-09 11:30 UTC by Gal-Zaidman

We want to change the names of workflows that are specific to a certain release to the name of the release.
releases 4.4 and 4.5 didn't contain the CSI driver so we should call the workflow release-4.4-4.5 and add a proper description to explain why this is without CSI

2021-05-09 15:28 UTC, Gal-Zaidman commented
/hold

2021-05-10 11:35 UTC, eslutsky requested changes

2021-05-10 11:35 UTC, eslutsky commented on ci-operator/step-registry/openshift/e2e/ovirt/conformance/release-4.6-4.7/openshift-e2e-ovirt-conformance-release-4.6-4.7-workflow.yaml
> +    The Openshift E2E oVirt e2e without csi workflow installs OpenShift cluster on top of oVirt
"e2e without csi" - is that the old name ?

2021-05-10 11:35 UTC, eslutsky commented on ci-operator/step-registry/ipi/conf/ovirt/release-4.4-4.5/ipi-conf-ovirt-release-4.4-4.5-chain.yaml
> +    based on the cluster profile and lease inforamtion for a release-4.4/4.5 OpenShift cluster.
inforamtion = information

2021-05-10 12:07 UTC, Gal-Zaidman commented on ci-operator/step-registry/ipi/conf/ovirt/release-4.4-4.5/ipi-conf-ovirt-release-4.4-4.5-chain.yaml
> +    based on the cluster profile and lease inforamtion for a release-4.4/4.5 OpenShift cluster.
Done

2021-05-10 12:08 UTC, Gal-Zaidman commented on ci-operator/step-registry/ipi/ovirt/pre/upgrade/ipi-ovirt-pre-upgrade-chain.yaml
> +    with persistent Prometheus storage and no Affiniry Groups.
Done

2021-05-10 12:14 UTC, Gal-Zaidman commented on ci-operator/step-registry/openshift/e2e/ovirt/minimal/release-4.6-4.7/openshift-e2e-ovirt-minimal-release-4.6-4.7-workflow.yaml
> +    therfor it uses a different install config and ovirt-config.
Done

2021-05-10 12:14 UTC, Gal-Zaidman commented on ci-operator/step-registry/openshift/e2e/ovirt/csi/release-4.6-4.7/openshift-e2e-ovirt-csi-release-4.6-4.7-workflow.yaml
> +    therfor it uses a different install config and ovirt-config.
Done

2021-05-10 16:50 UTC, Gal-Zaidman commented
/assign @bertinatto @smarterclayton @vladikr @jsafrane @ricardomaraschini

2021-05-12 08:02 UTC, jsafrane commented
/approve
the storage parts

2021-05-18 09:26 UTC, sinnykumari commented
/lgtm
For MCO part

2021-05-18 13:20 UTC, smarterclayton commented
/approve

2021-05-18 13:34 UTC, merged