assisted-installer: Add jobs for ocm-2.3 branch
openshift/release pull request #18606
Opened 2021-05-15 01:12 UTC by lranjbar

Add new jobs for the ocm-2.3 branch since we will be releasing with OCM. 🎉

2021-05-19 16:53 UTC, osherdp commented
/uncc @eranco74 @michaellevy101 
/cc @osherdp @YuviGold

2021-05-19 17:07 UTC, osherdp requested changes
All seems fine, just let's see if we must have the periodic jobs

2021-05-20 21:01 UTC, lranjbar commented
/assign @petr-muller

2021-05-20 23:12 UTC, petr-muller approved these changes

2021-05-20 23:20 UTC, merged