assisted-service: Update from to centos:stream8
openshift/release pull request #19109
Opened 2021-06-08 22:37 UTC by lranjbar

Update the centos image to be `centos:stream8` for assisted-service.

(Under test)

Signed-off-by: Lisa Rashidi-Ranjbar <lranjbar@redhat.com>

2021-06-08 22:38 UTC, lranjbar commented
/unassign @empovit @jordigilh 
/assign @flaper87 @osherdp

2021-06-09 20:25 UTC, lranjbar commented
/assign @YuviGold 

@YuviGold @osherdp @flaper87 

This is ready for review... it is using the stream8:8 mirror in the ci registry properly now. I think will need to rerun the tests in the PR https://github.com/openshift/assisted-service/pull/1788

2021-06-10 05:22 UTC, osherdp requested changes
Same thing for ocm-2.3 branch, no?

2021-06-10 05:23 UTC, osherdp commented
/hold
Until figuring out what to do with other major branch

2021-06-10 18:45 UTC, osherdp commented
I'm not sure it have any value doing it for ocm-2.3 branch, if it will then it will be pretty easy

2021-06-10 21:14 UTC, lranjbar commented
> I'm not sure it has any value doing it for ocm-2.3 branch, if it will then it will be pretty easy

thank you 😃

2021-06-11 05:22 UTC, flaper87 commented
> OK, let's not get blocked on it

Did you keep the `hold` on purpose?

2021-06-11 09:56 UTC, osherdp commented
I never unhold someone else PR
There could always be some other dependencies, checks that needs to be made right after the merge, etc.
@lranjbar, please unhold whenever you want

2021-06-11 11:07 UTC, flaper87 commented
> I never unhold someone else PR

You held it in the first place, hence my question

> @lranjbar, please unhold whenever you want

I was expecting to see this in your previous comment, hence my question :wink: 

All good, thanks for clarifying :+1:

2021-06-11 11:31 UTC, osherdp commented
@flaper87 please see the review approval message, my friend 
Actually, it's a bummer that the hold lock is just one per PR. Maybe having one per user can make those things clearer

2021-06-11 12:02 UTC, flaper87 commented
> @flaper87 please see the review approval message, my friend

OOOOHHHHHH JEEEEEEEEEEZZZZ!!! I'm really sorry, totally missed it :facepalm: 
Forgive my blindness :pray: 

> Actually, it's a bummer that the hold lock is just one per PR. Maybe having one per user can make those things clearer

Funnily enough, I was thinking the same thing after my last comment.

thanks again for clarifying :pray:

2021-06-11 14:30 UTC, lranjbar commented
/unhold

@flaper87 @osherdp Mostly I just like to unhold things in the morning and not before sign off 😅

2021-06-11 14:38 UTC, merged