Add e2e csi job for Cinder CSI operator
openshift/release pull request #19284
Opened 2021-06-15 13:59 UTC by Fedosin

2021-06-15 14:26 UTC, EmilienM commented
> _No description provided._

could you please add a description to your PR? It helps reviewers to understand context. Thanks

2021-06-16 08:47 UTC, jsafrane commented
I can see snapshot tests failing to delete a PV that's used as a source of a snapshot:
```
E0615 15:27:32.659754       1 controller.go:1031] error syncing volume "pvc-617b3a70-fb0d-45d6-b9eb-45efe64262e4": rpc error: code = Internal desc = DeleteVolume failed with error Bad request with: [DELETE https://volume.rdo.mtl2.vexxhost.net/v3/0693e2bb538c42b79a49fe6d2e61b0fc/volumes/7561f5ad-5988-44cb-aeb0-3455e287228c], error message: {"badRequest": {"code": 400, "message": "Invalid volume: Volume status must be available or error or error_restoring or error_extending or error_managing and must not be migrating, attached, belong to a group, have snapshots or be disassociated from snapshots after volume transfer."}}
```

* Please make the job optional until it has a chance to succeed.
* Please fix the driver (or the test?) in a separate PR. Still, it's useful to have the job even if it fails.
* Add some commit message + PR description.
* Add the same (optional) job to the CSI driver itself + CSO repos and to 4.9 yaml files too.

2021-07-05 09:54 UTC, mandre requested changes
From what I can see, this is still missing the 4.9 job that Jan requested in https://github.com/openshift/release/pull/19284#issuecomment-862176005.

Please also add the same job to CSO as a separate PR.

2021-07-13 08:23 UTC, Fedosin commented
CSO job PR: https://github.com/openshift/release/pull/19553

2021-07-13 14:02 UTC, mandre reviewed
/lgtm

2021-07-13 14:20 UTC, merged