mco: always run and gate on gcp-op-single-node test
openshift/release pull request #19322
Opened 2021-06-16 10:15 UTC by sinnykumari

SNO is targeted to go GA in 4.9. Gating on this test
should ensure that incoming changes are not regressing
on SNO.

2021-06-16 19:47 UTC, kikisdeliveryservice requested changes
If this is always_run:false currently, I'd rather switch this to always_run: true first to see the actual state of this test since it is not running on master, capture some runs and see if we need any obvious fixes, then gate.

2021-06-16 19:49 UTC, kikisdeliveryservice commented
adding hold for update
/hold

2021-06-17 08:01 UTC, sinnykumari commented
sure. Updated to keep the test optional until we are sure that it runs successfully on couple of PRs.

2021-06-17 08:04 UTC, sinnykumari commented on ci-operator/jobs/openshift/machine-config-operator/openshift-machine-config-operator-master-presubmits.yaml
> +    run_if_changed: ^([^d]|d(d|o(d|cd))*([^do]|o([^cd]|c[^ds])))*(d(d|o(d|cd))*(oc?)?)?$
This will take care of triggering the test on PRs with non-doc update.

2021-06-17 21:59 UTC, kikisdeliveryservice approved these changes
looks good to me, let's get some runs in next week (once ci clears up) and then make a call on optional! :)

/lgtm

2021-06-18 07:54 UTC, sinnykumari commented
removing hold since cause has been addressed
/hold cancel

2021-06-18 08:03 UTC, merged