Remove LSO steps from assisted-operator workflow
openshift/release pull request #19529
Opened 2021-06-22 06:23 UTC by YuviGold

The entire disconnected logic should be implemented in the same place
as where the connected logic is located.
Currently that's assisted-service repository hence moving the logic
from openshift/release including deleting LSO steps.

assisted-service PR - https://github.com/openshift/assisted-service/pull/2052

@osherdp @lranjbar 
/hold

2021-06-22 06:57 UTC, osherdp requested changes

2021-06-22 06:57 UTC, osherdp commented on ci-operator/step-registry/baremetalds/assisted/operator/setup/baremetalds-assisted-operator-setup-commands.sh
hmm, you meant to call ``deploy/operator/deploy.sh``?

2021-06-22 13:14 UTC, YuviGold commented
/retest

2021-06-22 18:58 UTC, YuviGold commented
/retest

2021-06-24 07:02 UTC, YuviGold commented
/retest

2021-06-24 11:30 UTC, YuviGold commented
https://github.com/openshift/assisted-service/pull/2086 should fix semi-colon issue.

2021-06-24 16:15 UTC, osherdp commented
/retest

2021-06-24 19:49 UTC, YuviGold commented
/retest

2021-06-27 08:57 UTC, YuviGold commented
PR is passing for ocm-2.3 and master branches.
Removing the patch to trigger them.

2021-06-27 08:58 UTC, osherdp approved these changes

2021-06-27 11:18 UTC, YuviGold commented
/unhold

2021-06-27 11:19 UTC, merged