mco: add optional e2e-aws-upgrade test for single-node
openshift/release pull request #19817
Opened 2021-06-29 14:29 UTC by sinnykumari

2021-06-29 17:29 UTC, sinnykumari commented
Since new jobs has been added, these failing tests are expected.

2021-06-29 18:41 UTC, kikisdeliveryservice requested changes
one change.

also, will this be a periodic or something as well? I hope it's not just going to live in the mco repo?

2021-06-29 18:41 UTC, kikisdeliveryservice commented on ci-operator/jobs/openshift/machine-config-operator/openshift-machine-config-operator-release-4.9-presubmits.yaml
> +    rerun_command: /test e2e-aws-upgrade-single-node
```suggestion
    optional: true
    rerun_command: /test e2e-aws-upgrade-single-node
```

2021-06-30 07:53 UTC, sinnykumari commented
> also, will this be a periodic or something as well? I hope it's not just going to live in the mco repo?

Yes, it is already running in the periodic as well https://prow.ci.openshift.org/job-history/gs/origin-ci-test/logs/periodic-ci-openshift-release-master-ci-4.9-e2e-aws-upgrade-single-node .

Reason of adding it in MCO repo as well is to make sure we don't regress due to any MCO changes when we initiate reboot during upgrade.

2021-06-30 07:56 UTC, sinnykumari commented on ci-operator/jobs/openshift/machine-config-operator/openshift-machine-config-operator-release-4.9-presubmits.yaml
> +    rerun_command: /test e2e-aws-upgrade-single-node
good catch! fixed.

2021-06-30 19:12 UTC, kikisdeliveryservice approved these changes
thanks for the change, this now looks good!
/lgtm

2021-06-30 19:21 UTC, merged