Add openshift/cloud-provider-ibm repository
openshift/release pull request #20440
Opened 2021-07-20 17:36 UTC by jonesbr17

CI integration for https://github.com/openshift/cloud-provider-ibm

2021-07-20 21:44 UTC, rtheis requested changes

2021-07-20 21:44 UTC, rtheis commented on ci-operator/config/openshift/cloud-provider-ibm/openshift-cloud-provider-ibm-master.yaml
> +binary_build_commands: make commands
Why aren't we running our full Travis bucket of linting and image building?

2021-07-20 21:44 UTC, rtheis commented on ci-operator/config/openshift/cloud-provider-ibm/openshift-cloud-provider-ibm-master.yaml
> +- as: e2e-aws
I assume all this AWS stuff is required until we have our own E2E?  If so, can we add a TODO comment to fix this?

2021-07-20 21:44 UTC, rtheis commented on ci-operator/jobs/openshift/cloud-provider-ibm/openshift-cloud-provider-ibm-master-presubmits.yaml
> +    context: ci/prow/e2e-aws
Similar comment about AWS in this part.

2021-07-21 08:39 UTC, Fedosin commented
I believe this one is a duplicate of https://github.com/openshift/release/pull/20427

2021-07-21 12:53 UTC, jonesbr17 commented
Closing in favor of https://github.com/openshift/release/pull/20427

2021-07-21 12:53 UTC, closed without merging