Add base images to fast-forward
openshift/release pull request #20485
Opened 2021-07-21 18:01 UTC by mqhackett

Related Issue: open-cluster-management/backlog#10511

Description:
 - Add base image info to fast-forward job in config.

2021-07-21 18:02 UTC, mqhackett commented
/hold

2021-07-21 18:05 UTC, ray-harris commented on ci-operator/config/open-cluster-management/search-collector/open-cluster-management-search-collector-main.yaml
> +  base_images:
The repo-brancher entry needs to be part of the base_images stanza that starts on line 1.

2021-07-21 18:40 UTC, jlpadilla requested changes
@mqhackett We need to update all repos, not just the collector.

2021-07-22 15:21 UTC, jlpadilla commented
@mqhackett search-api is missing.

2021-07-22 18:57 UTC, jlpadilla commented
/lgtm

2021-07-22 19:10 UTC, jlpadilla commented
/retest-required

2021-07-22 19:11 UTC, jlpadilla approved these changes

2021-07-22 19:22 UTC, mqhackett commented
/unhold

2021-07-22 19:28 UTC, merged