Replace run_if_changed with skip_if_only_changed
openshift/release pull request #20663
Opened 2021-07-28 16:58 UTC by zaneb

The addition of the skip_if_only_changed option means we no longer need
to jump through hoops with inverse regexes to do simple stuff like
skipping CI on changes that only update the docs.

2021-07-28 18:45 UTC, zaneb commented
/cc @alvaroaleman

2021-07-28 19:03 UTC, alvaroaleman commented
@zaneb please ping the owners the bot pointed out for you: https://github.com/openshift/release/pull/20663#issuecomment-888469017

/uncc

2021-08-02 15:41 UTC, zaneb commented
/assign @adduarte @danwinship @sinnykumari

2021-08-02 16:56 UTC, sinnykumari commented
Thank you for creating this PR. We were planning to do this changes for MCO configs but didn't get to it yet.

For MCO changes,  can you please also add OWNERS, OWNERS_ALIASES, LICENSE, *.md (for README.md) to the exclude list?

2021-08-02 17:30 UTC, kikisdeliveryservice commented
uhoh for MCO we just merged a run_if_changed: https://github.com/openshift/release/pull/20784

:laughing: 

cc: @mandre

2021-08-02 17:30 UTC, kikisdeliveryservice commented
/assign @kikisdeliveryservice

2021-08-02 18:48 UTC, mandre commented
> uhoh for MCO we just merged a run_if_changed: #20784
> 
> laughing
> 
> cc: @mandre

That's fine, #20784 is really meant to be a run_if_changed.
Zane replaces the negative run_if_changed regex with skip_if_only_changed to make them more maintainable.

2021-08-17 17:04 UTC, zaneb commented
/retest

2021-08-18 19:56 UTC, zaneb commented
> Thank you for creating this PR. We were planning to do this changes for MCO configs but didn't get to it yet.
> 
> For MCO changes, can you please also add OWNERS, OWNERS_ALIASES, LICENSE, *.md (for README.md) to the exclude list?

It's not really my intention to take over maintenance of the CI jobs for other teams; I just happened to have the context about this new feature loaded so I proposed this patch to hopefully simplify maintenance for everyone.

2021-08-18 20:30 UTC, kikisdeliveryservice approved these changes
Thanks for this @zaneb

2021-08-18 20:32 UTC, kikisdeliveryservice commented
/approve

2021-08-18 20:33 UTC, kikisdeliveryservice commented
@danwinship @adduarte can you PTAL and approve?

2021-08-18 20:33 UTC, kikisdeliveryservice commented
/lgtm

2021-09-02 21:31 UTC, danwinship commented
/approve
for the CNO part

2021-09-28 21:50 UTC, kikisdeliveryservice commented
@zaneb if this is ready, please cc the other owners:
https://github.com/openshift/release/pull/20663#issuecomment-929623017

2021-09-29 06:07 UTC, mandre requested changes
I believe you're supposed to leave everything under `ci-operator/config/openshift-priv/` alone and it will get automatically sync'ed by a bot later on. 

https://docs.ci.openshift.org/docs/architecture/private-repositories/#openshift-priv-organization

2021-09-29 20:30 UTC, zaneb commented
> I believe you're supposed to leave everything under `ci-operator/config/openshift-priv/` alone and it will get automatically sync'ed by a bot later on.

Thanks @mandre. I pared back the scope again to try to contain the CI fallout. Could you approve this now? We've been waiting 2 months for someone from shift-on-stack to sign off and in the meantime it seems like more projects keep copying-and-pasting the old anti-pattern.

/assign @mandre, @michaelgugino

2021-09-30 01:37 UTC, zaneb commented
/retest-required

2021-09-30 09:09 UTC, mandre reviewed
> We've been waiting 2 months for someone from shift-on-stack to sign off and in the meantime it seems like more projects keep copying-and-pasting the old anti-pattern.

Apologies for that. In the future, feel free to ping me directly if you need reviews from shiftonstack, or reach out to us in our slack channel. You should always find someone ready to help.

/lgtm

2021-09-30 13:45 UTC, zaneb commented
/assign @michaelgugino

2021-09-30 23:38 UTC, kikisdeliveryservice commented
PTAL
/assign @elmiko

2021-10-01 17:08 UTC, elmiko reviewed
/lgtm

2021-10-01 17:16 UTC, merged