[CVP-2063] Add rehearsal part for v4.6 &v 4.8
openshift/release pull request #20680
Opened 2021-07-29 10:05 UTC by sonam1412

2021-07-29 13:14 UTC, dirgim commented on ci-operator/config/redhat-openshift-ecosystem/cvp/redhat-openshift-ecosystem-cvp-ocp-4.6.yaml
> +- as: cvp-common-powervs
The `powervs`, `probe` and `ibmz` job are out of scope for this ticket and the support for these jobs doesn't exist now - I propose removing this entire section down to line 64

2021-07-29 13:15 UTC, dirgim commented on ci-operator/config/redhat-openshift-ecosystem/cvp/redhat-openshift-ecosystem-cvp-ocp-4.8.yaml
> +- as: cvp-common-powervs
The powervs and probe jobs are out of scope for this ticket and the v4.8 support for these jobs doesn't exist now - I propose removing this entire section down to line 51

2021-07-29 13:16 UTC, dirgim commented on ci-operator/jobs/redhat-openshift-ecosystem/cvp/redhat-openshift-ecosystem-cvp-ocp-4.6-periodics.yaml
> +- agent: kubernetes
The powervs, probe and ibmz jobs are out of scope for this ticket and the support for these jobs doesn't exist now - I propose removing this entire section down to line 296

2021-07-29 13:19 UTC, dirgim requested changes

2021-07-29 13:19 UTC, dirgim commented on ci-operator/jobs/redhat-openshift-ecosystem/cvp/redhat-openshift-ecosystem-cvp-ocp-4.6-periodics.yaml
> +        secretName: result-aggregator
The powervs, probe and ibmz jobs are out of scope for this ticket and the support for these jobs doesn't exist now - I propose removing this entire section down to line 296

2021-07-29 13:19 UTC, dirgim commented on ci-operator/jobs/redhat-openshift-ecosystem/cvp/redhat-openshift-ecosystem-cvp-ocp-4.8-periodics.yaml
> +    ci-operator.openshift.io/prowgen-controlled: "true"
The powervs, probe and ibmz jobs are out of scope for this ticket and the support for these jobs doesn't exist now - I propose removing this entire section down to line 254

2021-07-30 07:11 UTC, sonam1412 commented
/retest

2021-07-30 12:40 UTC, sonam1412 commented
/retest

2021-07-30 20:32 UTC, sonam1412 commented
/retest

2021-08-02 09:19 UTC, dirgim commented
/retest

2021-08-02 14:27 UTC, sonam1412 commented
/retest

2021-08-02 15:49 UTC, sonam1412 commented
/retest

2021-08-02 18:24 UTC, jsztuka commented
/lgtm

2021-08-02 18:25 UTC, jsztuka approved these changes
/LGTM

2021-08-02 21:10 UTC, jsztuka commented
/approve

2021-08-03 08:30 UTC, dirgim commented
/lgtm

2021-08-03 08:30 UTC, dirgim approved these changes

2021-08-03 08:37 UTC, merged