OCM Add cluter-backup-operator to PROW
openshift/release pull request #21097
Opened 2021-08-12 17:35 UTC by jnpacker

Signed-off-by: Joshua Packer <jpacker@redhat.com>

* Add the cluster-backup-operator repository to PROW.
* Creates image cluster-backup-controller.

2021-08-12 17:56 UTC, ray-harris requested changes
You also need to add an OWNERS file in this directory:

```
ci-operator/jobs/open-cluster-management/cluster-backup-operator
```

2021-08-12 17:56 UTC, ray-harris commented on ci-operator/config/open-cluster-management/cluster-backup-operator/open-cluster-management-cluster-backup-operator-main.yaml
> +    tag: latest
Fast forward process has changed. These lines aren't needed. See comment below for more info.

2021-08-12 17:56 UTC, ray-harris commented on ci-operator/config/open-cluster-management/cluster-backup-operator/open-cluster-management-cluster-backup-operator-main.yaml
> +    name: acm-cicd-github
Fast forward process has changed, but docs have not yet been updated. Use this stanza instead:

```
- as: fast-forward
  postsubmit: true
  steps:
    env:
      DESTINATION_BRANCH: release-2.4
    workflow: ocm-ci-fastforward
```

2021-08-12 17:56 UTC, ray-harris commented
/test pj-rehearse

2021-08-12 18:05 UTC, ray-harris commented
The rehearsal jobs to build the images should be passing. Looking at them, it looks like an issue with Prow itself. I'll have to check with the Prow admins about it.

2021-08-12 20:24 UTC, jnpacker commented
I applied the fixes your recommended. I'm still waiting for CICD to create the cluster-backup-controller repo in quay as well.

2021-08-12 21:26 UTC, emilvberglind commented
/retest

2021-08-16 12:58 UTC, ray-harris commented
@jnpacker In the config file for the release-2.4 branch, you're referencing `Dockerfile.prow`, but that doesn't exist in the `cluster-backup-operator` repo.

2021-08-16 14:23 UTC, jnpacker commented
yeah I had a pull to fix that on THU but everyone had headed out. Will be fixing today. 😄

2021-08-16 15:18 UTC, jnpacker commented
/retest

2021-08-16 18:00 UTC, jnpacker commented
/retest

2021-08-16 19:12 UTC, closed without merging