Add golangci-lint job to OCM/submariner-addon
openshift/release pull request #21461
Opened 2021-08-30 15:50 UTC by dfarrell07

Following the example of openshift/cluster-version-operator, add a Prow
job to run Go linting via golangci-lint on the
open-cluster-management/submariner-addon repo.

Signed-off-by: Daniel Farrell <dfarrell@redhat.com>

2021-08-30 15:53 UTC, dfarrell07 commented
/assign @skitt

2021-08-30 16:04 UTC, dfarrell07 commented
> {"component":"unset","error":"error loading prow config: job pull-ci-open-cluster-management-submariner-addon-main-golangci-lint is set to always run but also declares run_if_changed targets, which are mutually exclusive","file":"prow/cmd/checkconfig/main.go:231","func":"main.main","level":"fatal","msg":"Validation failed","severity":"fatal","time":"2021-08-30T15:53:53Z"}

Yay, the CI caught a real error. :partying_face: :pray:

2021-08-30 18:31 UTC, dfarrell07 commented
Does it not run CI for drafts?

2021-08-30 18:39 UTC, dfarrell07 commented
> make: *** No rule to make target 'lint'.  Stop.

This is the failure we "want" for now. Need to add the make target and golangci-lint config file on the submariner-addon side.

2021-08-31 16:12 UTC, dfarrell07 commented
This PR will add the golangci-lint make target expected by this Prow job: https://github.com/open-cluster-management/submariner-addon/pull/120

2021-09-01 15:18 UTC, dfarrell07 commented
Well, the error messages have been quite helpful so far, but this one I don't understand the cause of:

> Init container initupload not ready: (state: waiting, reason: "PodInitializing", message: "") Init container place-entrypoint not ready: (state: waiting, reason: "PodInitializing", message: "")

2021-09-01 15:21 UTC, dfarrell07 commented
/retest

2021-09-01 15:28 UTC, dfarrell07 commented
Ah okay, now I'm getting an error that makes sense (maybe the last one was infra).

> golangci-lint linters
make: golangci-lint: Command not found
make: *** [Makefile:121: golangci-lint] Error 127
{"component":"entrypoint","error":"wrapped process failed: exit status 2","file":"prow/entrypoint/run.go:80","func":"k8s.io/test-infra/prow/entrypoint.Options.Run","level":"error","msg":"Error executing test process","severity":"error","time":"2021-09-01T15:25:31Z"}

2021-09-01 15:42 UTC, dfarrell07 commented
> vendor/github.com/openshift/build-machinery-go/make/targets/golang/../../lib/golang.mk:22: *** `go` is required with minimal version "1.15.2", detected version "go version go1.16 linux/amd64". You can override this check by using `make GO_REQUIRED_MIN_VERSION:=`. Stop.

2021-09-01 15:44 UTC, dfarrell07 commented
This one I find confusing, as it seems to be saying "you need to have at least go 1.15, you have go 1.16, but still error". :sweat_smile: 

> /bin/sh: 1: set: Illegal option -o pipefail
vendor/github.com/openshift/build-machinery-go/make/targets/golang/../../lib/golang.mk:22: *** `go` is required with minimal version "1.15.2", detected version "go version go1.16 linux/amd64". You can override this check by using `make GO_REQUIRED_MIN_VERSION:=`. Stop.
{"component":"entrypoint","error":"wrapped process failed: exit status 2","file":"prow/entrypoint/run.go:80","func":"k8s.io/test-infra/prow/entrypoint.Options.Run","level":"error","msg":"Error executing test process","severity":"error","time":"2021-09-01T15:38:40Z"}

2021-09-01 16:18 UTC, dfarrell07 commented
Still hitting this strange go version error. Any idea @skitt?

> `go` is required with minimal version "1.15.2", detected version "go version go1.16 linux/amd64"

2021-09-01 16:38 UTC, dfarrell07 commented
I added debugging lines to confirm the go version is 1.16, and it did confirm it is. So yes I don't understand why (the submariner-addon/Makefile?) is failing thinking it's less than go 1.15.

2021-09-01 16:56 UTC, dfarrell07 commented
Go and golangci-lint both seem to be installed and able to run basic commands.

> /usr/local/go/bin/go
go version go1.16 linux/amd64
/usr/bin/golangci-lint
golangci-lint has version v1.37.1 built from b39dbcd6 on 2021-02-20T11:59:15Z

2021-09-02 14:45 UTC, skitt commented
The Go version issue is a bug in the build framework: https://github.com/openshift/build-machinery-go/pull/54

2021-09-22 16:23 UTC, dfarrell07 commented
/retest

2021-09-22 16:30 UTC, dfarrell07 commented
The fix to go-build-machinery was just merged, but I'm not sure how long it will take to propagate here. Immediately retesting, I see the same error.

```
vendor/github.com/openshift/build-machinery-go/make/targets/golang/../../lib/golang.mk:22: *** `go` is required with minimal version "1.15.2", detected version "go version go1.16 linux/amd64". You can override this check by using `make GO_REQUIRED_MIN_VERSION:=`.  Stop.
```

I'll keep trying at intervals.

2021-09-24 15:14 UTC, dfarrell07 commented
/retest

2021-09-24 16:02 UTC, dfarrell07 commented
Pervious error fixed, next error is:

```
vendor/github.com/openshift/build-machinery-go/make/targets/golang/../../lib/golang.mk:22: *** `go` is required with minimal version "1.15.2", detected version "1.16". You can override this check by using `make GO_REQUIRED_MIN_VERSION:=`.  Stop.
```

2021-09-27 08:47 UTC, skitt requested changes

2021-09-27 08:47 UTC, skitt commented on ci-operator/config/open-cluster-management/submariner-addon/open-cluster-management-submariner-addon-main.yaml
> +    make golangci-lint
The build machinery assumes that the shell is Bash:

```suggestion
    make golangci-lint SHELL=/bin/bash
```

2021-09-27 15:08 UTC, dfarrell07 commented
Ah, okay I see why this sonarcloud job is failing:

```
13:45:21.321 DEBUG: GET 404 https://sonarcloud.io/api/alm_integration/show_pullrequest?project=open-cluster-management_submariner-addon&pullrequestKey=21461 | time=416ms
```

It's assuming this PR is against the submariner-addon repo, and is looking for a PR with this number there. Obviously that 404s.

So this is a false positive that shouldn't happen in the actual CI. It's not marked as required here, so we can merge over it.

I'll remove my debugging info now.

2021-10-04 13:32 UTC, skitt commented
/lgtm
/approve

2021-10-04 13:43 UTC, merged