add mac e2e test for odo
openshift/release pull request #21518
Opened 2021-09-01 10:11 UTC by anandrkskd

Signed-off-by: anandrkskd <anandrkskd@gmail.com>

This PR adds tests running on  MacOS for odo.

partially fixes  https://github.com/openshift/odo/issues/4408

2021-09-02 11:29 UTC, prietyc123 requested changes

2021-09-02 11:29 UTC, prietyc123 commented on ci-operator/jobs/openshift/odo/openshift-odo-main-presubmits.yaml
> +    optional: true
Could you please make both the jobs as required?

2021-09-14 04:38 UTC, anandrkskd commented
/retest

2021-09-15 07:12 UTC, anandrkskd commented
/retest

2021-09-15 08:15 UTC, anandrkskd commented
/test pj-rehearse

2021-09-21 06:44 UTC, anandrkskd commented
/test pj-rehearse

2021-09-21 16:35 UTC, anandrkskd commented
/test pj-rehearse

2021-09-25 10:56 UTC, anandrkskd commented
/test pj-rehearse

2021-09-27 05:07 UTC, anandrkskd commented
Fixes openshift/odo#4412

2021-09-27 09:07 UTC, anandrkskd commented
/test pj-rehearse

2021-10-03 10:05 UTC, anandrkskd commented
/retests

2021-10-16 16:12 UTC, anandrkskd commented
/test pj-rehearse

2022-01-24 09:16 UTC, closed without merging