Gather subscriptions from clusters
openshift/release pull request #22346
Opened 2021-09-29 15:00 UTC by dmage

2021-09-29 16:26 UTC, dmage commented
/assign @wking 

These resources are useful for jobs that install third-party operators.

2021-09-30 08:22 UTC, dmage commented
/assign @vrutkovs

2021-10-06 08:46 UTC, vrutkovs requested changes

2021-10-06 08:46 UTC, vrutkovs commented on ci-operator/step-registry/gather/extra/gather-extra-commands.sh
> +queue ${ARTIFACT_DIR}/clusterserviceversions.json oc --insecure-skip-tls-verify --request-timeout=5s get clusterserviceversions --all-namespaces -o json
```suggestion
```
ditto

2021-10-06 12:36 UTC, dmage commented on ci-operator/step-registry/gather/extra/gather-extra-commands.sh
> +queue ${ARTIFACT_DIR}/oc_cmds/statefulsets oc --insecure-skip-tls-verify --request-timeout=5s get statefulsets --all-namespaces
The pattern that I see in this file is that everything is collected twice:

`/XXX.json` is output with `-o json`
`/oc_cmds/XXX` is output of the same command, but without `-o` at all or with `-o wide`

`statefulsets` is the only exception, they are collected twice but have different file names.

2021-10-06 13:51 UTC, vrutkovs commented on ci-operator/step-registry/gather/extra/gather-extra-commands.sh
> +queue ${ARTIFACT_DIR}/subscriptions.json oc --insecure-skip-tls-verify --request-timeout=5s get subscriptions --all-namespaces -o json
Hmm, lets follow the same pattern until we're sure human-readable is no longer used

2021-10-06 13:51 UTC, vrutkovs approved these changes
/lgtm

2021-10-06 13:59 UTC, merged