Add CentOS 8 Stream-based OKD 4.10 ironic image builds
openshift/release pull request #22432
Opened 2021-10-01 18:22 UTC by LorbusChris

This commit adds CentOS 8 Stream-based image builds of all ironic
components for Baremetal IPI support in OKD 4.10

Note that for `ironic-static-ip-manager` and `ironic-machine-os-downloader` images the definition from the `Dockerfile.ocp` file in the respective repos can be used, making Prow replace the FROM directive from the file with a CentOS 8 Stream image. All other images have (or will have, see blockers below) their own dedicated `Dockerfile.okd` definitions.

Blocked by: https://github.com/openshift/ironic-agent-image/pull/21 https://github.com/openshift/ironic-hardware-inventory-recorder-image/pull/510
Fixes: https://github.com/openshift/okd/issues/197

/cc @vrutkovs

2021-10-01 18:50 UTC, LorbusChris commented
Seems I gotta investigate why the image build says the base is not a CentOS stream image. 

/hold

2021-10-04 14:55 UTC, zaneb commented
ironic-image Dockerfile has merged.
/retest-required

2021-10-04 17:39 UTC, LorbusChris commented on core-services/release-controller/_releases/release-ocp-4.10-ci.json
> +          "ironic-hardware-inventory-recorder",
Context: we don't want to mirror `ironic-hardware-inventory-recorder` out to the `origin` namespace from `ocp`. It's not being used, and if it were we'd want to promote an OKD-specific version to `origin` anyway.

2021-10-05 08:23 UTC, elfosardo requested changes
with this config in place the jobs will run every time there is a change, even if it's not related to okd or doesn't change the actual build
we should limit the run as it's done for the other jobs for ocp

2021-10-05 08:38 UTC, LorbusChris commented
@elfosardo this is only image builds, not any unit or e2e tests. I think we want to ensure the image gets rebuilt for each change. I don't think image build jobs for OCP are limited in any way either, otherwise I'd appreciate a pointer :)

2021-10-05 08:48 UTC, elfosardo commented
@LorbusChris we'd like to avoid having the OKD image rebuilt if there are changes *only* to OCP related files (dockerfile or package list) or to text files (e.g. README, LICENSE)
please have a look at the OCP jobs for an example, you can find more info at https://docs.ci.openshift.org/docs/how-tos/contributing-openshift-release/#tolerated-changes-to-generated-jobs

2021-10-05 09:39 UTC, LorbusChris commented
@elfosardo ahh yea, I've added appropriate `skip_if_only_changed` to the generated OKD jobs, and also adapted the OCP ones accordingly.

2021-10-05 11:07 UTC, vrutkovs commented
/approve
/lgtm

assuming this looks good to metal folks

2021-10-05 14:45 UTC, LorbusChris commented
/hold cancel
Approval from @smarterclayton is still required.

2021-10-12 16:25 UTC, smarterclayton commented on core-services/image-mirroring/openshift/mapping_origin_4_10
> +registry.ci.openshift.org/origin/4.10:ironic-static-ip-manager quay.io/openshift/origin-ironic-static-ip-manager:4.10 quay.io/openshift/origin-ironic-static-ip-manager:4.10.0 quay.io/openshift/origin
ok

2021-10-12 16:25 UTC, smarterclayton commented
/approve

2021-10-12 16:40 UTC, merged