Serverless: randomize times of periodic runs to prevent spikes
openshift/release pull request #24412
Opened 2021-12-09 09:00 UTC by mgencur

2021-12-16 10:53 UTC, cardil requested changes
The `2/14` expression looks weird.

2021-12-16 10:53 UTC, cardil commented on ci-operator/config/openshift-knative/serverless-operator/openshift-knative-serverless-operator-main__4.8.yaml
> +  cron: 0 2/14 * * *
Did you mean?

```suggestion
  cron: 0 2,14 * * *
```

2021-12-16 10:53 UTC, cardil commented on ci-operator/config/openshift-knative/serverless-operator/openshift-knative-serverless-operator-main__4.9.yaml
> +  cron: 0 2/14 * * *
Did you mean?

```suggestion
  cron: 0 2,14 * * *
```

2021-12-16 10:53 UTC, cardil commented on ci-operator/jobs/openshift-knative/serverless-operator/openshift-knative-serverless-operator-main-periodics.yaml
> +  cron: 0 2/14 * * *
Did you mean?

```suggestion
  cron: 0 2,14 * * *
```

2021-12-16 10:53 UTC, cardil commented on ci-operator/jobs/openshift-knative/serverless-operator/openshift-knative-serverless-operator-main-periodics.yaml
> +  cron: 0 2/14 * * *
Did you mean?

```suggestion
  cron: 0 2,14 * * *
```

2021-12-16 10:57 UTC, cardil commented
Supersedes https://github.com/openshift/release/pull/19843

2021-12-16 11:12 UTC, mgencur commented on ci-operator/config/openshift-knative/serverless-operator/openshift-knative-serverless-operator-main__4.8.yaml
> +  cron: 0 2/14 * * *
Oops. Thanks for the catch.

2022-01-04 07:55 UTC, rhuss reviewed
Looks good to me. Do you know how long a typical run takes ? If its longer than 1 hour maybe a slightly larger spread might be even more helpful ?

2022-01-04 08:37 UTC, mgencur commented
@rhuss On OCP 4.9 the cluster from a cluster-pool is used for so long before releasing:
* e2e - 1h44m
* e2e-mesh - 1h30m
* upgrades - 35m

On OCP 4.8 it takes slightly longer.

I could probably increase the time gap to 2 hours

2022-01-04 08:41 UTC, rhuss commented
I think that would make sense to increase to 2 hours for the long-running tests and maybe 1hour for the upgrade test (you could do the upgrade test first and put one of the longer tests to the end to get results quicker for two tests, but that is probably irrelevant anyway).

2022-01-04 08:50 UTC, rhuss commented
/approve
/lgtm

thanks !

2022-01-04 09:08 UTC, merged