WIP: add techpreview e2e to shared resoruce operator
openshift/release pull request #24612
Opened 2021-12-14 17:10 UTC by gabemontero

2021-12-15 18:01 UTC, gabemontero commented
/assign @coreydaley

2021-12-15 18:32 UTC, gabemontero commented
the 4.11 rehearsal failure is expected ... they have those files present, but the infra is not in place yet to run CI against that branch

2021-12-16 22:50 UTC, gabemontero commented
i believe this is ready for tag for merge @coreydaley (again the 4.11 failure is expected / OK until master branch is forked from 4.10)

2021-12-17 05:34 UTC, prietyc123 requested changes

2021-12-17 05:34 UTC, prietyc123 commented on ci-operator/config/openshift/csi-driver-shared-resource-operator/openshift-csi-driver-shared-resource-operator-release-4.10.yaml
> +  skip_if_only_changed: ^docs/|\.md$|^(?:.*/)?(?:\.gitignore|OWNERS|PROJECT|LICENSE)$
@gabemontero AFAIU adding `skip_if_only_changed` at one place (presubmits file) i.e https://github.com/openshift/release/pull/24612/files#diff-b6158c401a6d08e8c4ae2868c1a04f505b7fcbe86c21b46cb587c8310293fa93R95 should be enough, no? Correct me if I am wrong.

2021-12-17 13:14 UTC, coreydaley commented
/lgtm

2021-12-17 13:26 UTC, merged