MGMT-8601 - Add onprem periodic and presubmit CI jobs
openshift/release pull request #24773
Opened 2021-12-20 10:53 UTC by eliorerz

/cc @osherdp

2021-12-20 10:57 UTC, eliorerz commented
/hold wait for https://github.com/openshift/assisted-test-infra/pull/1313

2021-12-20 11:01 UTC, osherdp requested changes

2021-12-20 11:01 UTC, osherdp commented on ci-operator/jobs/openshift/assisted-test-infra/openshift-assisted-test-infra-master-periodics.yaml
> +  name: periodic-ci-openshift-assisted-test-infra-master-e2e-metal-assisted-onprem-periodic
can you add the slack notification?

2021-12-20 12:44 UTC, osherdp approved these changes

2021-12-20 16:57 UTC, eliorerz commented
/test pj-rehearse

2021-12-21 07:41 UTC, eliorerz commented
/test pj-rehearse

2021-12-21 10:00 UTC, eliorerz commented
@osherdp Any idea why the onprem jobs are failing with this error?
`AttributeError: module 'yaml' has no attribute 'FullLoader'`

2021-12-21 10:13 UTC, osherdp commented
> @osherdp Any idea why the onprem jobs are failing with this error? `AttributeError: module 'yaml' has no attribute 'FullLoader'`

I see nowhere that we deliberately install PyYAML, so that's a gap for sure
Not sure though though what has changed or why we used full-loader and not safe-loader

2021-12-22 10:51 UTC, osherdp approved these changes

2021-12-22 10:54 UTC, eliorerz commented
/unhold

2021-12-22 10:59 UTC, merged