Try running a periodic script to validate build pipeline
openshift/release pull request #25149
Opened 2022-01-11 13:24 UTC by gparvin

Identify any cases where a publish has not completed properly.
This has to be done in a periodic job because there's no notification
mechanism in the pre/post submit jobs which run after delivery tests
pass and publishes are initiated automatically.

Refs:
 - https://github.com/stolostron/backlog/issues/17925

Signed-off-by: Gus Parvin <gparvin@redhat.com>

2022-01-11 15:10 UTC, gparvin commented
Test failure was expected since the script being run hasn't been delivered yet.

2022-01-11 15:33 UTC, gparvin commented
/cc @dhaiducek

2022-01-20 01:45 UTC, dhaiducek requested changes
Looks good, but in the logs it looks like we need to switch the script to use HTTPS instead of SSH when cloning the repos:
```
Could not create directory '/.ssh'.
Host key verification failed.
fatal: Could not read from remote repository.
```
There's a fix for the "Could not create directory" error, but I think HTTPS is more maintainable instead of dealing with SSH keys.

2022-01-20 15:39 UTC, gparvin commented
@dhaiducek Why can't I find the log messages you are referring to?  Can you add a link?

2022-01-20 21:28 UTC, dhaiducek commented
/test ci/rehearse/periodic-ci-stolostron-governance-policy-framework-main-periodic-build

2022-01-20 21:28 UTC, dhaiducek commented
/test pj-rehearse

2022-01-20 22:04 UTC, gparvin commented
The errors that I see in the log now are expected errors that are identifying issues in our pipeline.  @dhaiducek if you merge we can see if a slack notification gets sent to `grc-prow-ci-status`

2022-01-21 14:01 UTC, dhaiducek approved these changes

2022-01-21 21:34 UTC, dhaiducek approved these changes

2022-01-21 21:35 UTC, dhaiducek approved these changes

2022-01-21 21:48 UTC, dhaiducek approved these changes

2022-01-21 21:48 UTC, dhaiducek commented
/unhold

2022-01-21 21:49 UTC, merged