Ocm add volsync addon controller
openshift/release pull request #26590
Opened 2022-02-25 20:10 UTC by tesshuflower

2022-02-28 16:16 UTC, tesshuflower commented
/retest

2022-02-28 18:07 UTC, tesshuflower commented
/retest

2022-02-28 18:25 UTC, tesshuflower commented
/retest

2022-03-01 14:18 UTC, schmidtd requested changes

2022-03-01 14:47 UTC, tesshuflower commented on ci-operator/config/stolostron/volsync-addon-controller/stolostron-volsync-addon-controller-release-2.5.yaml
> +        make -f Makefile.prow osci/publish
Done!

2022-03-01 14:50 UTC, schmidtd approved these changes
/lgtm

2022-03-01 15:05 UTC, merged