Node tuning e2e upgrade
openshift/release pull request #27286
Opened 2022-03-25 11:00 UTC by LakshmiRavichandran1

2022-03-25 12:14 UTC, LakshmiRavichandran1 commented
/test all

2022-03-25 13:27 UTC, LakshmiRavichandran1 commented
/test all

2022-03-25 19:06 UTC, LakshmiRavichandran1 commented on ci-operator/step-registry/ipi/install/libvirt/install/ipi-install-libvirt-install-commands.sh
> +if [[ "${ARCH}" == "s390x" && "${NODE_TUNING}" == "true" ]]; then
addressed in recent commit

2022-04-08 14:32 UTC, deepsm007 approved these changes

2022-04-08 14:34 UTC, deepsm007 requested changes
Can you merge in single commit

2022-04-08 14:51 UTC, LakshmiRavichandran1 commented
@deepsm007 addressed your comment, merged to a single commit.

2022-04-08 14:53 UTC, deepsm007 approved these changes

2022-04-08 15:06 UTC, merged