WIP: add debug info
openshift/release pull request #27334
Opened 2022-03-28 09:17 UTC by yuvalk

trying to understand why job is still failing on PULL_BASE_REF

2022-03-28 11:33 UTC, yuvalk commented
/retest

2022-04-04 11:05 UTC, yuvalk commented
/unhold

2022-04-04 11:05 UTC, yuvalk commented
@sshnaidm please review

2022-04-04 13:09 UTC, sshnaidm requested changes

2022-04-04 13:09 UTC, sshnaidm commented on ci-operator/step-registry/telco5g/gather-pao/telco5g-gather-pao-commands.sh
> +PULL_BASE_REF=${PULL_BASE_REF:-master"}
```suggestion
PULL_BASE_REF=${PULL_BASE_REF:-"master"}
```

2022-04-04 14:14 UTC, yuvalk commented
/retest
missing cli image isnt caused by us

2022-04-04 14:23 UTC, merged

2022-04-04 14:25 UTC, yuvalk commented
/test pj-rehearse