assisted-service: enable periodic for operator-based CAPI job
openshift/release pull request #28237
Opened 2022-04-29 15:59 UTC by mkowalski

/cc @eranco74 
/cc @javipolo 
/cc @osherdp

2022-05-01 08:05 UTC, osherdp requested changes

2022-05-01 08:05 UTC, osherdp commented on ci-operator/jobs/openshift/assisted-service/openshift-assisted-service-master-periodics.yaml
> +  name: periodic-ci-openshift-assisted-service-master-e2e-metal-assisted-operator-capi-periodic
please add the slack notification

2022-05-02 07:21 UTC, mkowalski commented on ci-operator/jobs/openshift/assisted-service/openshift-assisted-service-master-periodics.yaml
> +  name: periodic-ci-openshift-assisted-service-master-e2e-metal-assisted-operator-capi-periodic
Done, thanks!

2022-05-02 07:26 UTC, osherdp approved these changes

2022-05-02 07:28 UTC, merged