MGMT-8938: Add support for bootstrap-in-place day-2 worker flow
openshift/release pull request #28262
Opened 2022-05-02 13:47 UTC by omertuc

Add a daily 4.11 job that runs the SNO BIP + Worker flow

(depends on code added in openshift/assisted-test-infra#1639)

2022-05-02 13:47 UTC, omertuc commented
/hold Waiting for https://github.com/openshift/assisted-test-infra/pull/1639 to merge

2022-05-03 12:10 UTC, eliorerz approved these changes
LGTM

2022-05-03 14:18 UTC, osherdp requested changes
just one small thing (plus waiting to see it rehearses)

2022-05-16 12:28 UTC, omertuc commented
/unhold

2022-05-16 13:12 UTC, eliorerz approved these changes
LGTM
/hold wait for test

2022-05-16 15:12 UTC, omertuc commented
/unhold

2022-05-16 16:13 UTC, wking commented on ci-operator/jobs/openshift/release/openshift-release-master-periodics.yaml
> +      image: gcr.io/k8s-prow/commenter:v20220502-837a10a360
this rollback is probably unintended?

2022-05-17 07:08 UTC, osherdp approved these changes

2022-05-19 10:44 UTC, dgoodwin commented
/approve

2022-05-19 11:00 UTC, merged