MGMT-10717: Set ocp 4.10 as OPENSHIFT_INSTALL_RELEASE_IMAGE in openshift-cluster-api-provider-agent-release-ocm-2.5
openshift/release pull request #29220
Opened 2022-06-07 09:16 UTC by eranco74

This should allow the test to specify the release-image for the hypershift hosted control plane

2022-06-07 11:42 UTC, osherdp commented
/hold
waiting for code in test-infra to land in the relevant branch

2022-06-07 11:43 UTC, osherdp approved these changes

2022-06-07 11:44 UTC, osherdp commented
> /hold waiting for code in test-infra to land in the relevant branch

if this change is non-breaking then we can also do the other way around (merging this and seeing the result in test-infra PR)

2022-06-07 17:35 UTC, osherdp commented
/test pj-rehearse

2022-06-07 17:57 UTC, osherdp requested changes

2022-06-08 06:34 UTC, eranco74 commented
> > /hold waiting for code in test-infra to land in the relevant branch
> 
> if this change is non-breaking then we can also do the other way around (merging this and seeing the result in test-infra PR)

Both are not breaking
+ the test is currently broken as it is

2022-06-09 10:48 UTC, eranco74 commented
/test pj-rehearse

2022-06-13 07:43 UTC, eranco74 commented
Seems that it's not evaluating the release image properly and we end up doing this:
```export OPENSHIFT_INSTALL_RELEASE_IMAGE=release:stable```
Closing

2022-06-13 07:43 UTC, closed without merging