konveyor: add needs-triage label for org
openshift/release pull request #29930
Opened 2022-06-28 19:27 UTC by djzager

2022-06-28 20:40 UTC, djzager commented
I attempted to add the plugin configuration directly to `config/konveyor/crane/_pluginconfig.yaml` but it was rejected by the checks in `make update`.

2022-06-28 21:07 UTC, jmguzik commented on core-services/prow/02_config/_plugins.yaml
> +require_matching_label:
I don't think I can accept it in this place. It should be added to _pluginconfig in repo conf.

2022-06-28 21:08 UTC, jmguzik requested changes
Please see the comment.

2022-06-28 21:08 UTC, jmguzik commented
> I attempted to add the plugin configuration directly to `config/konveyor/crane/_pluginconfig.yaml` but it was rejected by the checks in `make update`.

maybe bad formatting?

2022-06-28 21:15 UTC, jmguzik commented on core-services/prow/02_config/_plugins.yaml
> +require_matching_label:
Ups, this plugin is not supported using shared configuration: https://github.com/kubernetes/test-infra/blob/master/prow/plugins/config.go#L1871~#L1876
In any way I would not like to add to the main prow for every repo, specific info about one org. So, the most likely upstream feature is needed to support this.

2022-06-30 17:38 UTC, bear-redhat commented
/lgtm

2022-06-30 17:58 UTC, merged