Create unit-test specific image with postgresql-server
openshift/release pull request #30308
Opened 2022-07-10 09:32 UTC by michaellevy101

2022-07-10 10:26 UTC, michaellevy101 commented
/hold wait to tests

2022-07-10 12:11 UTC, michaellevy101 commented
/test ?

2022-07-10 12:15 UTC, michaellevy101 commented
/test pj-rehearse-max

2022-07-11 11:37 UTC, michaellevy101 commented
/test pj-rehearse

2022-07-11 12:16 UTC, osherdp commented
/cc

2022-07-11 14:18 UTC, osherdp commented on ci-operator/config/openshift/assisted-service/openshift-assisted-service-master__edge.yaml
> +  coreos_centos_stream9:
be aware it does not use it currently as there was no image substitution in the building of ``project_image``

2022-07-11 17:16 UTC, osherdp commented on ci-operator/config/openshift/assisted-service/openshift-assisted-service-master__edge.yaml
> +      COPY --from=registry.ci.openshift.org/openshift/release:golang-1.17 /usr/local/go /usr/local/go
That's not the scope that I'm referring to. This current PR affecting much than unit-test job. This is the aspect that I think is too much out-of-scope

2022-07-11 17:43 UTC, michaellevy101 commented
/test pj-rehearse

2022-07-11 20:07 UTC, michaellevy101 commented on ci-operator/config/openshift/assisted-service/openshift-assisted-service-master__edge.yaml
> +      COPY --from=registry.ci.openshift.org/openshift/release:golang-1.17 /usr/local/go /usr/local/go
that's ok. It should affect all our images to be centos9. I updated the PR description.

2022-07-12 23:40 UTC, michaellevy101 commented
/retest

2022-07-13 10:41 UTC, michaellevy101 commented
/retest

2022-07-14 07:53 UTC, osherdp requested changes
just one little thing

2022-07-14 07:53 UTC, osherdp commented on ci-operator/config/openshift/assisted-service/openshift-assisted-service-master__edge.yaml
> +  to: assisted-service-test
let's rename to ``assisted-service-subsystem`` to make it 100% clear

2022-07-14 08:06 UTC, osherdp approved these changes

2022-07-14 10:07 UTC, michaellevy101 commented
/unhold

2022-07-14 10:26 UTC, merged