MGMT-11256: assisted-installer: Add Assisted Installer fast forwards for ocm-2.7 release
openshift/release pull request #30686
Opened 2022-07-21 11:40 UTC by eliorerz

Preparation for the ocm 2.6 FF

2022-07-21 11:40 UTC, eliorerz commented
/hold

2022-07-25 07:06 UTC, eliorerz commented
/cc @osherdp

2022-07-25 07:14 UTC, osherdp requested changes
We should do the same for capi, no?

2022-07-25 10:32 UTC, osherdp approved these changes

2022-07-25 10:47 UTC, eliorerz commented on ci-operator/jobs/infra-periodics.yaml
> +  name: periodic-openshift-release-fast-forward-cluster-api-provider-agent
FYI @eranco74

2022-07-26 12:50 UTC, bbguimaraes commented
/approve

2022-07-31 11:22 UTC, eliorerz commented
/unhold
https://github.com/openshift/release/pull/30788 is merged

2022-07-31 11:44 UTC, merged