openshift/os: Promote to `rhel-coreos-8`
openshift/release pull request #31084
Opened 2022-08-04 19:30 UTC by cgwalters

The release payload name will be `rhel-coreos-8`, so let's have the CI config match.

I think this may unblock https://github.com/openshift/machine-config-operator/pull/3258#issuecomment-1205328567

Closes: https://github.com/openshift/os/issues/940

2022-08-04 22:16 UTC, cgwalters commented
OK right, though after this lands we'd need to set up automation which moves the `rhel-coreos-8` image from the `rhcos-devel` namespace into the `ocp/4:12` imagestream or so?

Or alternatively, make that the default, and then have a config which mirrors out back to `rhcos-devel`?

2022-08-05 00:06 UTC, LorbusChris requested changes
Makes sense to me!

Please also add the same changes to the respective `-4.12` and `-4.13` files.

2022-08-05 08:44 UTC, travier commented
Same as Christian. LGTM but needs to be synced.

2022-08-05 11:53 UTC, cgwalters commented
Hmm but wait there's only one `-master` periodic job right?

2022-08-05 12:35 UTC, travier commented
Oh indeed, my bad

2022-08-05 12:35 UTC, travier approved these changes

2022-08-05 12:35 UTC, travier commented
/lgtm

2022-08-05 13:56 UTC, travier commented
/retest

2022-08-05 14:38 UTC, merged