stackrox: only run the operator if operator changes are made
openshift/release pull request #31091
Opened 2022-08-04 23:51 UTC by gavin-stackrox

2022-08-04 23:51 UTC, gavin-stackrox commented
/hold
/uncc

2022-08-05 00:04 UTC, gavin-stackrox commented
/uncc @JoukoVirtanen @msugakov

2022-08-05 00:40 UTC, gavin-stackrox commented
/cc @porridge

2022-08-05 00:40 UTC, gavin-stackrox commented
/retest-required
/unhold

2022-08-05 06:34 UTC, porridge requested changes
The problem here is that `/operator` is not self-contained.
At the bare minimum we'd also need to trigger on the following:

Go deps:
```
$ go list -deps ./operator/|grep github.com/stackrox/rox|cut -d/ -f -4|sort -u
github.com/stackrox/rox/generated
github.com/stackrox/rox/image
github.com/stackrox/rox/operator
github.com/stackrox/rox/pkg
```

make includes:
`^Makefile`, `^make/`

Furthermore, just looking at occurrences of `..` in the `operator/Makefile`, there is `^deploy/`, `^scripts`, `^status\.sh`, `^EXPECTED_GO_VERSION`

I fear to look further.

And even if we listed all these here, the list would soon rot, and there is no simple way to validate it for correctness in an automated way.

2022-08-05 14:05 UTC, gavin-stackrox commented
> The problem here is that `/operator` is not self-contained. At the bare minimum we'd also need to trigger on the following:
> 
> Go deps:
> 
> ```
> $ go list -deps ./operator/|grep github.com/stackrox/rox|cut -d/ -f -4|sort -u
> github.com/stackrox/rox/generated
> github.com/stackrox/rox/image
> github.com/stackrox/rox/operator
> github.com/stackrox/rox/pkg
> ```
> 
> make includes: `^Makefile`, `^make/`
> 
> Furthermore, just looking at occurrences of `..` in the `operator/Makefile`, there is `^deploy/`, `^scripts`, `^status\.sh`, `^EXPECTED_GO_VERSION`
> 
> I fear to look further.
> 
> And even if we listed all these here, the list would soon rot, and there is no simple way to validate it for correctness in an automated way.

Ok. But in Circle CI we _only_ automatically ran operator e2e tests if a change occurred in `operator/`. That is what I am trying to reproduce here. Having the operator e2e tests run for every commit on every PR is probably not supportable by the shared cluster pool and will (probably) lead to flakes that cause the test to get ignored.

2022-08-08 06:01 UTC, porridge reviewed
How about this?

2022-08-08 06:01 UTC, porridge commented on ci-operator/config/stackrox/stackrox/stackrox-stackrox-master.yaml
> +  run_if_changed: ^operator/.*
```suggestion
  run_if_changed: ^((generated|image|operator|pkg|make|deploy|scripts)/.*|Makefile|status\.sh|EXPECTED_GO_VERSION)
```

2022-08-08 06:01 UTC, porridge commented
> Having the operator e2e tests run for every commit on every PR is probably not supportable by the shared cluster

Do we have *any* data on how much we can get?

2022-08-10 07:28 UTC, gavin-stackrox commented
> > Having the operator e2e tests run for every commit on every PR is probably not supportable by the shared cluster
> 
> Do we have _any_ data on how much we can get?

Its a good question but I don't have an answer other than the doc: https://docs.ci.openshift.org/docs/how-tos/cluster-claim/#existing-cluster-pools.

So far using a `version: "4.8"` claim works well for the qa e2e tests but they *only* run on merge by default.

2022-08-10 08:29 UTC, porridge approved these changes

2022-08-10 09:10 UTC, merged