add role-grantor access to cluster-bot service account
openshift/release pull request #31154
Opened 2022-08-08 15:59 UTC by hoxhaeris

Grant Cluster-bot roles to allow giving access to cluster initiators.

2 new roles for the cluster-bot service account:

1. Grant permission that allows creating RoleBinding objects
```yaml
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - rolebindings
  verbs: :
  - create
```

2.  Grant permission (explicitly) by giving permission to bind that particular ClusterRole
```yaml
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterroles
  verbs:
  - bind
  resourceNames:
  - admin
```

2022-08-08 15:59 UTC, hoxhaeris commented
/cc @bradmwilliams

2022-08-08 17:53 UTC, bradmwilliams requested changes

2022-08-08 17:53 UTC, bradmwilliams commented on clusters/build-clusters/common/ci-chat-bot/ci-chat-bot.yaml
> +  - create
These can be collapsed down into a single group with multiple `resources`

2022-08-08 18:19 UTC, bradmwilliams approved these changes

2022-08-09 19:30 UTC, hongkailiu commented
/hold

Could you explain why the permissions are needed, especially of app.ci?

2022-08-09 19:39 UTC, hongkailiu commented
Could the whole file be moved to https://github.com/openshift/release/tree/master/clusters/build-clusters/common_except_app.ci?

Which cluster roles will be created by the bot?
Can they be created as a static yaml in release repo?

2022-08-09 21:32 UTC, hoxhaeris commented
@hongkailiu 

>Could you explain why the permissions are needed, especially of app.ci?

Cluster-Bot will grant access to the cluster initiators (on the respective temporary namespace).
The bot will create a role+rolebinding on runtime (on the temporary namespace), to grant access to the cluster initiator. 

>Which cluster roles will be created by the bot?

The cluster roles will be bound to the temporary namespace only. 

>Can they be created as a static yaml in release repo?

No, we can't do that, since the roles will be created on the temporary namespaces.

2022-08-10 12:37 UTC, hoxhaeris commented
@hongkailiu 

> Could the whole file be moved to https://github.com/openshift/release/tree/master/clusters/build-clusters/common_except_app.ci?

We can't move the whole file, but we can move the new ClusterRole to `common_except_app.ci`

2022-08-10 18:05 UTC, hongkailiu commented
> The cluster roles will be bound to the temporary namespace only.

It explains the `rolebindings`. I cannot see why it needs the permission on creating clusterroles.

2022-08-11 12:30 UTC, hoxhaeris commented
> > The cluster roles will be bound to the temporary namespace only.
> 
> It explains the `rolebindings`. I cannot see why it needs the permission on creating clusterroles. Maybe an example of the clusterrole that might be created?

We will create a ClusterRole specifically for this purpose: to allow access to the cluster initiators on the temporary namespace. 
The ClusterRole will contain something like: 
```golang
	role := &rbacapi.ClusterRole{
		ObjectMeta: m,
		Rules: []rbacapi.PolicyRule{
			{
				APIGroups: []string{""},
				Resources: []string{"pods/attach", "pods/exec", "pods/portforward", "pods/proxy", "services/proxy"},
				Verbs:     []string{"get", "list", "watch"},
			},
		},
	}
```

2022-08-11 15:58 UTC, hoxhaeris commented
@hongkailiu 
We made a few changes to the PR, by removing the need to create the ClusterRoles.

The current change creates 2 new ClusterRoles:
1. Grants permission that allows creating RoleBinding objects (this part has not changed)
2. Explicitly grant permission to the service account to bind the `admin` resourceName in a given namespace. 

During runtime, we will bind the admin ClusterRole to the cluster-initiator user on the temporary namespace.

2022-08-11 18:59 UTC, hongkailiu commented
/lgtm

2022-08-11 19:02 UTC, hongkailiu commented
@hoxhaeris 

Feel free to cancel the hold whenever ready.

2022-08-11 19:27 UTC, hoxhaeris commented
/unhold

2022-08-11 19:53 UTC, merged