Add Serial tests for CNCC on OpenStack
openshift/release pull request #31468
Opened 2022-08-18 18:44 UTC by andreaskaris

Signed-off-by: Andreas Karis <ak.karis@gmail.com>

2022-08-23 15:49 UTC, jluhrsen commented on ci-operator/config/openshift/cloud-network-config-controller/openshift-cloud-network-config-controller-master.yaml
> +      NETWORK_TYPE: OVNKubernetes
don't think you need this for 4.12+ OVNK should be there by default

2022-08-23 15:57 UTC, andreaskaris commented
There's a problem with those rehearsal jobs:

a) when I run the full serial test suite against OSP, about 80 or more tests fail.

b) I can run the following manually:
~~~
./openshift-tests run openshift/conformance/serial --run "\[sig-network\]\[Feature:EgressIP\]" --provider '{"type":"openstack"}'
~~~

But when I add `TEST_ARGS: --run "\[sig-network\]\[Feature:EgressIP\]"` to the arguments of the job then the suite quotes the parameter and that breaks things:
~~~
 + openshift-tests run openshift/conformance/serial --run '"\[sig-network\]\[Feature:EgressIP\]"' --provider '{"type":"openstack"}' -o /logs/artifacts/e2e.log --junit-dir /logs/artifacts/junit
warning: KUBE_TEST_REPO_LIST may not be set when using openshift-tests and will be ignored
openshift-tests version: v4.1.0-5662-g0e21e34
Suite run returned error: suite "openshift/conformance/serial" does not contain any tests
error: suite "openshift/conformance/serial" does not contain any tests 
~~~

2022-08-24 09:51 UTC, jcaamano commented
/test pj-rehearse

2022-08-24 13:31 UTC, andreaskaris commented
/test pj-rehearse

2022-08-24 16:42 UTC, andreaskaris commented
/retest

2022-08-24 17:09 UTC, andreaskaris commented
/test pj-rehearse

2022-08-24 17:46 UTC, andreaskaris commented
The tests now fail with:
~~~
 INFO[2022-08-24T17:29:56Z] Failed to discover available identity versions when contacting https://identity.rdo.mtl2.vexxhost.net/v3. Attempting to parse version from URL.
Gateway Timeout (HTTP 504) 
~~~

I think that's a problem with access to vexxhost itself ...

2022-08-24 17:51 UTC, andreaskaris commented
Well all the OSP tests seem to be affected by that, not jus the rehearse jobs:
https://search.ci.openshift.org/?search=failed+to+discover+available+identity+versions+when+contacting&maxAge=48h&context=1&type=bug%2Bissue%2Bjunit&name=&excludeName=&maxMatches=5&maxBytes=20971520&groupBy=job

2022-08-24 21:26 UTC, andreaskaris commented
/test pj-rehearse

2022-08-24 21:28 UTC, andreaskaris commented
/retest

2022-08-25 11:08 UTC, jcaamano commented
/test pj-rehearse

2022-08-25 17:49 UTC, jcaamano commented
I have seen this test flaking: `pods should have the assigned EgressIPs and EgressIPs can be deleted and recreated`
This flake sometimes but seldom make the jobs fail.

The 4.12 and 4.13 jobs have not passed once, but mostly due to invariants or infra issues that have little to do with egress ip tests 
afaik.

The master sdn and ovn jobs have passed at least once, and again when they have not it has been mostly due to same reasons as above.

Overall the jobs same defined well to me.

/lgtm

2022-08-25 17:49 UTC, jcaamano commented
@jluhrsen 

PTAL

2022-08-26 09:31 UTC, jcaamano commented
/test pj-rehearse

2022-08-26 11:37 UTC, pierreprinetti commented on ci-operator/step-registry/openshift/e2e/openstack/ipi-e2e-only/OWNERS
> +../OWNERS
You should replace this symlink with an actual OWNERS file with your approvers and your reviewers

2022-08-26 11:40 UTC, pierreprinetti requested changes
Creating and maintaining your own workflow is one valid option.

Have you considered these alternatives?

### Alternative 1: override the `test` stanza in config
Use the existing `openshift-e2e-openstack-ipi` workflow, [override](https://docs.ci.openshift.org/docs/architecture/step-registry/#ci-operator-test-configuration) the `test` part of it:
```yaml
- as: e2e-openstack-sdn-serial
  optional: true
  steps:
    cluster_profile: openstack-vexxhost
    env:
      BASE_DOMAIN: shiftstack.devcluster.openshift.com
      CONFIG_TYPE: minimal
      NETWORK_TYPE: OpenShiftSDN
      TEST_ARGS: --run \[sig-network\]\[Feature:EgressIP\]
      TEST_SUITE: openshift/conformance/serial
    workflow: openshift-e2e-openstack-ipi
    test:
    - ref: openshift-e2e-test # This overrides the test chain defined in openshift-e2e-openstack-ipi
```

### Alternative 2: skip all openstack tests
Turn `openstack-test-openstack` into a no-operation by setting `OPENSTACK_TEST_SKIPS` to `.*` in config (a slight modification of `openstack-test-openstack` is needed not to make it error).
```yaml
- as: e2e-openstack-sdn-serial
  optional: true
  steps:
    cluster_profile: openstack-vexxhost
    env:
      BASE_DOMAIN: shiftstack.devcluster.openshift.com
      CONFIG_TYPE: minimal
      NETWORK_TYPE: OpenShiftSDN
      TEST_ARGS: --run \[sig-network\]\[Feature:EgressIP\]
      TEST_SUITE: openshift/conformance/serial
      OPENSTACK_TEST_SKIPS: .*
    workflow: openshift-e2e-openstack-ipi
```

---

The only change request is for the OWNERS file, that you will likely want to be able to maintain without asking reviews to our team.
Once that is fixed (and you optionally have considered the alternatives above), this LGTM as-is.

2022-08-26 11:40 UTC, pierreprinetti commented on ci-operator/step-registry/openshift/e2e/openstack/ipi-e2e-only/OWNERS
> +../OWNERS
Replace this symlink with an actual OWNERS file containing your approvers and your reviewers

2022-08-26 13:40 UTC, jcaamano commented
Following through with the rework on behalf of @andreaskaris here: https://github.com/openshift/release/pull/31724

2022-08-26 17:47 UTC, jcaamano commented
/close

2022-08-26 17:48 UTC, closed without merging