ROX-11900: Test operator E2E on more OpenShift versions.
openshift/release pull request #31489
Opened 2022-08-19 05:49 UTC by porridge

This replaces `openshift-4-operator-e2e-tests` with a few `openshift-<word>-operator-e2e-tests` flavors where where `<word>` is:
- `oldest` for oldest supported OpenShift version (currently `4.6-EUS` but that `EUS` bit [is not reflected in the 4.6 cluster pool name](https://coreos.slack.com/archives/CBN38N3MW/p1660823623840969?thread_ts=1660802750.241459&cid=CBN38N3MW))
- `newest` for the newest GA version, currently `4.11`
- `penultimate` for the newest-but-one version, currently `4.10`
- (potentially) `beta` for the not-yet-GA successor to `newest`, if there will be an appropriate cluster pool

The reason to not use literal version strings is to keep name continuity as new OpenShift versions are released. This way we will not need to keep updating:
- [ ] testgrid config
- [ ] any potential future test statistics-gathering tools

Suggestions for better names welcome, though.

Depending on the context we will run:
- `oldest` and `newest`: on PR checks and on merges
- all flavors: nightly

I also bumped the concurrency according to the number of new jobs introduced.

TODO:
- [ ] update testgrid config with new names
- [x] job name in `dispatch.sh` 👈🏻 no need to do this, the expression there is already generic enough
- [ ] any other place I missed @gavin-stackrox ?

/cc @gavin-stackrox @SimonBaeumer

2022-08-19 05:49 UTC, porridge commented
/test pj-rehearse-max

2022-08-19 06:52 UTC, gavin-stackrox requested changes
I like the naming and maybe we should follow this for non-operator tests also.
`ref: stackrox-e2e` maps the name to an expected script in `scripts/ci/jobs/` in the target repo. Maybe a set of symlinks there to handle it before merge?

2022-08-19 07:10 UTC, porridge commented
> I like the naming and maybe we should follow this for non-operator tests also. `ref: stackrox-e2e` maps the name to an expected script in `scripts/ci/jobs/` in the target repo. Maybe a set of symlinks there to handle it before merge?

@gavin-stackrox do you mean something else than what I mentioned here?

> job name in `dispatch.sh` 👈🏻 no need to do this, the expression there is already generic enough

2022-08-19 07:24 UTC, gavin-stackrox commented
yeah, see `job_script` in dispatch.sh

On Fri, Aug 19, 2022 at 8:10 AM Marcin Owsiany ***@***.***>
wrote:

> I like the naming and maybe we should follow this for non-operator tests
> also. ref: stackrox-e2e maps the name to an expected script in
> scripts/ci/jobs/ in the target repo. Maybe a set of symlinks there to
> handle it before merge?
>
> @gavin-stackrox <https://github.com/gavin-stackrox> do you mean something
> else than what I mentioned here?
>
> job name in dispatch.sh 👈🏻 no need to do this, the expression there is
> already generic enough
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/openshift/release/pull/31489#issuecomment-1220330074>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/APMRL7MOG7ELXQQMOQNXPT3VZ4XNXANCNFSM567P64MA>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-08-19 11:19 UTC, porridge commented
> yeah, see `job_script` in dispatch.sh

🤦🏻 [of course](https://github.com/stackrox/stackrox/pull/2746)!

2022-08-22 04:34 UTC, porridge commented
/test pj-rehearse-max

2022-08-22 07:30 UTC, porridge commented
Looks like this passes now, PTAL @gavin-stackrox

2022-08-22 11:17 UTC, gavin-stackrox approved these changes
LGTM

2022-08-22 11:57 UTC, merged