stackrox: test golang upgrade to 1.17.12
openshift/release pull request #31561
Opened 2022-08-22 16:02 UTC by rukletsov

As per guidelines [here](https://github.com/stackrox/stackrox/blob/917c69412556b2d647c21be1bb2f2b33cf200ed8/.openshift-ci/Dockerfile.build_root#L7), this is WIP PR to test if the https://github.com/stackrox/stackrox/pull/2762 which updates our CI image.

Look at individual commits to better understand what has changed (clone and modify operations are in separate commits).

/hold
/uncc

2022-08-22 16:25 UTC, gavin-stackrox requested changes
those two changes + `make update` + commit + push :sigh: should get the rehearse jobs going.

2022-08-22 16:25 UTC, gavin-stackrox commented on ci-operator/config/stackrox/stackrox/stackrox-stackrox-alexr-golang-bump.yaml
> +  tag: latest
```suggestion
  tag: alexr-hacks
```

2022-08-22 16:25 UTC, gavin-stackrox commented on ci-operator/config/stackrox/stackrox/stackrox-stackrox-alexr-golang-bump__stackrox_branding.yaml
> +  tag: latest-stackrox-branding
```suggestion
  tag: alexr-hacks-stackrox-branding
```

2022-08-23 12:40 UTC, rukletsov commented
/test pj-rehearse-max

2022-08-23 15:19 UTC, rukletsov commented
/test pj-rehearse-max

2022-08-24 10:55 UTC, rukletsov commented
/test pj-rehearse-max

2022-08-24 16:21 UTC, rukletsov commented
/test pj-rehearse-max

2022-08-25 08:52 UTC, rukletsov commented
2 failed jobs are due to failed tests, the CI builder image clearly works. Closing this PR and proceeding with https://github.com/stackrox/stackrox/pull/2762.

2022-08-25 08:52 UTC, closed without merging