WIP: Use candidate releases
openshift/release pull request #31811
Opened 2022-08-30 14:36 UTC by jrvaldes

2022-08-30 14:36 UTC, jrvaldes commented
/test ?

2022-08-30 14:37 UTC, jrvaldes commented
/test pj-rehearse

2022-08-31 02:45 UTC, jrvaldes commented
/test pj-rehearse-more

2022-08-31 15:05 UTC, sebsoto requested changes

2022-08-31 15:05 UTC, sebsoto commented on ci-operator/config/openshift/windows-machine-config-operator/openshift-windows-machine-config-operator-master.yaml
> +      product: ocp
please do the same for community

2022-08-31 15:19 UTC, aravindhp commented
/hold

I am not sure we want to be using released OCP versions in our tests. If we want to pick up a OVN or Machine API change that is yet to be published in our e2e tests, we will have to wait for a release to happen. Unless I am misunderstanding what is meant `Existing OpenShift Releases`.

2022-08-31 21:13 UTC, jrvaldes commented
/close

See https://github.com/openshift/windows-machine-config-operator/pull/1216#issuecomment-1233425511

2022-08-31 21:14 UTC, closed without merging