[loki] add loki-operator package to CLO's e2e jobs
openshift/release pull request #32068
Opened 2022-09-07 09:19 UTC by btaani

2022-09-07 09:20 UTC, btaani commented
/assign @periklis

2022-09-12 11:31 UTC, periklis requested changes

2022-09-12 11:31 UTC, periklis commented on ci-operator/config/openshift/cluster-logging-operator/openshift-cluster-logging-operator-master.yaml
> +      OO_INDEX: ci-index-loki-operator-bundle
```suggestion
      OO_INDEX: ci-index-cluster-logging-operator-bundle
```

2022-09-12 12:31 UTC, btaani commented
/restest-required

2022-09-12 12:44 UTC, btaani commented
/retest-required

2022-09-12 13:55 UTC, Red-GV commented on ci-operator/config/openshift/cluster-logging-operator/openshift-cluster-logging-operator-master.yaml
> +  substitutions:
I think this is missing the `vector` and `logging-view-plugin` substitutions.

2022-09-12 17:11 UTC, periklis commented on ci-operator/config/openshift/cluster-logging-operator/openshift-cluster-logging-operator-master.yaml
> +    with: pipeline:logging-view-plugin
This one is missing in the base_images

2022-09-21 13:22 UTC, periklis commented
/test pj-rehearse

2022-09-21 15:50 UTC, periklis commented on ci-operator/config/openshift/cluster-logging-operator/openshift-cluster-logging-operator-master.yaml
> +    tag: v4.11
```suggestion
    tag: v4.10
```

2022-09-22 06:25 UTC, periklis commented
/test pj-rehearse

2022-09-22 09:04 UTC, btaani commented
/retest pj-rehearse

2022-09-22 09:05 UTC, btaani commented
/test pj-rehearse

2022-09-22 09:23 UTC, periklis commented
/hold Depends on DPTP-2969

2023-03-09 10:26 UTC, btaani commented
/reopen

2023-03-27 11:38 UTC, periklis commented
/pj-rehearse

2023-03-27 12:12 UTC, periklis commented
/pj-rehearse

2023-03-29 10:37 UTC, periklis commented
/pj-rehearse pull-ci-openshift-cluster-logging-operator-master-e2e-target

2023-03-31 10:10 UTC, btaani commented
/pj-rehearse pull-ci-openshift-cluster-logging-operator-master-e2e-target

2023-03-31 10:26 UTC, btaani commented
/test pj-rehearse

2023-03-31 10:28 UTC, btaani commented
/test ci-operator-config

2023-03-31 11:01 UTC, btaani commented
/test pj-rehearse

2023-04-03 14:20 UTC, hongkailiu commented
/pj-rehearse pull-ci-openshift-cluster-logging-operator-master-e2e-target

2023-04-03 15:12 UTC, hongkailiu commented
/pj-rehearse pull-ci-openshift-cluster-logging-operator-master-e2e-target

2023-04-04 08:29 UTC, periklis commented
/approve
/lgtm

2023-04-04 08:29 UTC, periklis commented
/pj-rehearse ack

2023-04-04 08:30 UTC, periklis commented
/hold cancel

2023-04-04 08:31 UTC, periklis commented
/remove-lifecycle rotten

2023-04-04 09:17 UTC, merged