Adding `no-capabilities` to the cluster bot variants
openshift/release pull request #32894
Opened 2022-10-06 10:38 UTC by cardil

This PR adds the `no-capabilities` variant to cluster bot, which will launch a cluster with configured:

```
capabilities: 
  baselineCapabilitySet: None
```

2022-10-06 13:10 UTC, bradmwilliams requested changes

2022-10-06 13:50 UTC, cardil commented on ci-operator/jobs/openshift/release/openshift-release-infra-periodics.yaml
> +              workflow: openshift-e2e-$(CLOUD_TYPE)
:face_exhaling: Ah, white spaces! :heart: 

Thank you so much for debugging!

2022-10-07 10:08 UTC, cardil commented
/test pj-rehearse

2022-10-07 14:57 UTC, bradmwilliams approved these changes

2022-10-07 15:00 UTC, bradmwilliams commented
The final piece here would be adding `no-capabilities` to the supported parameters, here:
https://github.com/openshift/ci-chat-bot/blob/254c3953167c565e69b84455992728f1917b280c/prow.go#L65

2022-10-07 15:29 UTC, merged

2022-10-10 18:05 UTC, cardil commented
PR open https://github.com/openshift/ci-chat-bot/pull/310