MGMT-12039: Add e2e-metal-assisted-lvm jobs
openshift/release pull request #32896
Opened 2022-10-06 12:45 UTC by adriengentil

2022-10-06 12:46 UTC, adriengentil commented
/hold
/cc @osherdp @eliorerz

2022-10-06 12:55 UTC, osherdp requested changes

2022-10-06 12:58 UTC, adriengentil commented on ci-operator/jobs/openshift/assisted-service/openshift-assisted-service-cloud_hotfix_releases-presubmits.yaml
> +    always_run: true
:man_facepalming: ...but I thought about the `reporter_config`!

2022-10-06 13:13 UTC, osherdp approved these changes

2022-10-07 14:09 UTC, adriengentil commented
```ERROR    root:waiting.py:255 Hosts statuses are: [(1, '93e81e55-b9ac-4750-b223-5b6f6318ca4e', 'test-infra-cluster-c8d90384-worker-1', 'worker', 'insufficient', 'Host cannot be installed due to following failing validation(s): ODF LVM requires at least one non-installation HDD/SSD disk on the host (minimum size: 0 GB) ; Require at least 3 CPU cores for worker role, found only 2'), (2, 'a50aca45-2370-43d2-9cd8-c7845991be42', 'test-infra-cluster-c8d90384-master-0', 'master', 'insufficient', 'Host cannot be installed due to following failing validation(s): Require at least 5 CPU cores for master role, found only 4'), (3, '39debd96-cbf4-43e8-b45e-f0c024cf1e7f', 'test-infra-cluster-c8d90384-master-1', 'master', 'insufficient', 'Host cannot be installed due to following failing validation(s): Require at least 5 CPU cores for master role, found only 4'), (4, '059db73c-4c08-46ba-acfb-d70d068472ae', 'test-infra-cluster-c8d90384-worker-0', 'worker', 'insufficient', 'Host cannot be installed due to following failing validation(s): ODF LVM requires at least one non-installation HDD/SSD disk on the host (minimum size: 0 GB) ; Require at least 3 CPU cores for worker role, found only 2'), (5, '6a007a2d-b76d-468f-bad4-8563b54819cf', 'test-infra-cluster-c8d90384-master-2', 'master', 'insufficient', 'Host cannot be installed due to following failing validation(s): Require at least 5 CPU cores for master role, found only 4')]
```
Looks like lvm as specific requirements

2022-10-11 10:13 UTC, osherdp requested changes

2022-10-11 10:13 UTC, osherdp commented on ci-operator/jobs/openshift/assisted-service/openshift-assisted-service-master-presubmits.yaml
> +    always_run: true
Remember to change this

2022-10-13 09:59 UTC, adriengentil commented on ci-operator/config/openshift/assisted-service/openshift-assisted-service-master__edge.yaml
> +        MASTER_CPU=9
the configuration for lvm in test-infra is righty defined here: https://github.com/openshift/assisted-test-infra/blob/master/src/consts/olm_operators.py#L83-L87
but is actually broken by the logic that tries to merge(?) user defined values, trigger defined values and olm defined values: https://github.com/openshift/assisted-test-infra/blob/master/src/assisted_test_infra/test_infra/utils/operators_utils.py#L100-L101

I propose to set the values here in the jobs (if it works), and to follow up with a fix for test-infra later.

2022-10-13 13:20 UTC, adriengentil commented
/test pj-rehearse

2022-10-13 17:10 UTC, osherdp approved these changes

2022-10-14 07:50 UTC, adriengentil commented
/unhold

2022-10-14 07:53 UTC, osherdp approved these changes

2022-10-14 08:09 UTC, merged