[wip]Use non-expiring token for sync-rover-groups-updater
openshift/release pull request #33141
Opened 2022-10-14 21:10 UTC by hongkailiu

Use this one as acceptance test for config-updater.

https://issues.redhat.com/browse/DPTP-3123

/cc @openshift/test-platform

2022-10-18 19:34 UTC, smg247 requested changes

2022-10-18 19:34 UTC, smg247 commented on clusters/psi/Makefile
> +ifeq ($(TOTATE), true)
Is this supposed to be:
```suggestion
ifeq ($(ROTATE), true)
```

2022-10-19 19:39 UTC, hongkailiu commented on core-services/ci-secret-generator/_config.yaml
> -- fields:
I will start to refresh the tokens (from `secret/config-updater-token-version-1`) in vault manually after merge.

2022-10-20 12:40 UTC, smg247 commented on Makefile
> +expire-token-version:
Is this forthcoming?

2022-10-20 12:40 UTC, smg247 commented on Makefile
> +secret-config-updater:
This is something that will have to be called out when adding a new cluster to the build farm. I am not sure that `cluster-init` can handle making the change automatically.

2022-10-20 12:40 UTC, smg247 commented on docs/dptp-triage-sop/token-rotation.md
> +The tokens in [dptp/config-updater](https://vault.ci.openshift.org/ui/vault/secrets/kv/show/dptp/config-updater) has to be refreshed manually.
```suggestion
The tokens in [dptp/config-updater](https://vault.ci.openshift.org/ui/vault/secrets/kv/show/dptp/config-updater) have to be refreshed manually.
```

2022-10-20 12:48 UTC, hongkailiu commented
/label tide/merge-method-squash

2022-10-20 12:53 UTC, hongkailiu commented
/hold cancel

2022-10-20 12:58 UTC, smg247 commented
/lgtm

2022-10-20 13:36 UTC, merged

2022-10-20 14:28 UTC, hongkailiu commented
Updated the tokens in Vault.