Update openshift-cluster-api-provider-agent-master to reference assisted-service-index container images in quay instead of the internal registry of Prow
openshift/release pull request #33240
Opened 2022-10-19 10:24 UTC by eranco74

cc: @osherdp @adriengentil

2022-10-19 10:55 UTC, osherdp requested changes

2022-10-19 10:55 UTC, osherdp commented on ci-operator/config/openshift/cluster-api-provider-agent/openshift-cluster-api-provider-agent-master.yaml
> +    name: assisted-service-index
I think you need to change below:
```
- as: e2e-ai-operator-ztp-capi
  optional: true
  steps:
    cluster_profile: packet-assisted
    dependencies:
      ...
      INDEX_IMAGE: assisted-service-index
      ...
```

2022-10-19 10:55 UTC, osherdp commented
/hold
until seeing it all passing

2022-10-19 13:23 UTC, adriengentil commented
Just in case it fails because the bundle is not available, I'm fixing it here: https://github.com/openshift/release/pull/33246

2022-10-19 15:30 UTC, osherdp commented
failed on dev-scripts setup I think
/test pj-rehearse

2022-10-20 10:18 UTC, eranco74 commented
failed on dev-scripts setup again
/test pj-rehearse

2022-10-20 12:16 UTC, eranco74 commented
/unhold

2022-10-20 12:24 UTC, eranco74 commented
Same change is required in ocm-2.6
https://github.com/openshift/release/pull/33293

2022-10-20 18:13 UTC, merged