Adding a periodic job for OKD/SCOS and set it as an acceptance job
openshift/release pull request #33320
Opened 2022-10-21 08:47 UTC by aleskandro

This PR adds a periodic job to test OKD/SCOS, as a blocker for its releases.
/cc @LorbusChris @vrutkovs @bradmwilliams 

Refers [OKD-6](https://issues.redhat.com//browse/OKD-6)

2022-10-21 13:44 UTC, aleskandro commented
Blocked by https://github.com/openshift/ci-tools/pull/3105 and https://github.com/openshift/machine-config-operator/pull/3382

2022-10-21 15:50 UTC, aleskandro commented
/hold

2022-10-21 16:21 UTC, aleskandro commented
/cc @vrutkovs @bradmwilliams

2022-10-22 06:44 UTC, aleskandro commented
/unhold


/test pj-rehearse

2022-10-24 09:10 UTC, vrutkovs requested changes

2022-10-24 09:10 UTC, vrutkovs commented on ci-operator/config/openshift/release/openshift-release-master__okd-scos-4.12.yaml
> +  interval: 48h
not required - release-controller would start the job whenever necessary (on a new nightly)

2022-10-24 09:22 UTC, vrutkovs commented on ci-operator/config/openshift/release/openshift-release-master__okd-scos-4.12.yaml
> +  interval: 48h
Nevermind, its okay to have it

2022-10-24 09:23 UTC, vrutkovs approved these changes
/lgtm
/hold cancel

2022-10-24 10:28 UTC, LorbusChris commented
/lgtm

2022-10-24 12:42 UTC, bradmwilliams approved these changes

2022-10-24 13:00 UTC, merged