AGENT-290: Add base agent required job to Assisted repositories
openshift/release pull request #33398
Opened 2022-10-24 16:35 UTC by lranjbar

As the Agent team has discussed, we need to have one required job in the Assisted repositories to reduce regressions. We identified the "e2e-agent-compact" as our base passing job to add to the repositories.

This also updates things from 4.11 to 4.12 on master. The PR openshift/assisted-installer#535 will need to merge first.

2022-10-25 18:38 UTC, lranjbar commented
/retest

2022-10-26 13:04 UTC, carbonin commented
Yeah, I'm not sure I'm the best to review this.

Maybe @osherdp ?

2022-10-26 14:04 UTC, osherdp commented
/cc @osherdp 
I'll take a look in a few hours I believe

2022-10-26 17:25 UTC, osherdp requested changes

2022-10-26 17:25 UTC, osherdp commented on ci-operator/jobs/openshift/assisted-service/openshift-assisted-service-master-presubmits.yaml
>      run_if_changed: ^(Dockerfile\.assisted-service\.ocp)|(cmd/agentbasedinstaller)
this one didn't mirror configurations from the config file

2022-10-26 17:25 UTC, osherdp commented on ci-operator/jobs/openshift/assisted-service/openshift-assisted-service-release-4.12-presubmits.yaml
>      run_if_changed: ^(Dockerfile\.assisted-service\.ocp)|(cmd/agentbasedinstaller)
same here

2022-10-27 18:40 UTC, lranjbar commented
@osherdp Thanks for catching that!

2022-10-27 21:47 UTC, osherdp approved these changes

2022-10-27 22:05 UTC, merged