ironic-static-ip-manager OCP image can be used for OKD as well
openshift/release pull request #34252
Opened 2022-11-23 08:49 UTC by sherine-k

This PR is a partial replacement for https://github.com/openshift/release/pull/34166 for ironic-static-ip-manager

2022-11-23 08:53 UTC, LorbusChris approved these changes
/lgtm

2022-11-23 08:53 UTC, LorbusChris commented on core-services/release-controller/_releases/release-ocp-4.13-ci.json
> +}
Not sure whether Prow will bark at this

2022-11-23 09:18 UTC, sherine-k commented
/pj-rehearse

2022-11-23 10:12 UTC, LorbusChris commented
/assign @derekhiggins @jupierce

2022-11-23 16:17 UTC, elfosardo requested changes
I strongly suggest to use stream9, all the packages used come from cs9/rhel9 and this could break without notice
ironic upstream has removed support for python3.6 and CS8 since the beginning of the year, we removed support in the ironic openshift containers right after

2022-11-23 16:20 UTC, elfosardo approved these changes

2022-11-23 16:20 UTC, elfosardo commented
/lgtm
sorry removed the label by mistake, this is good to go

2022-11-23 17:43 UTC, derekhiggins commented
@sherine-k would you mind posting a little context on whats going on here, I'm not familiar with what your doing.

2022-11-23 18:01 UTC, sherine-k commented
> @sherine-k would you mind posting a little context on whats going on here, I'm not familiar with what your doing.

Hello @derekhiggins , yes sorry, of course!
Right now, https://origin-release.ci.openshift.org/#4.13.0-0.okd-scos shows that all builds of OKD on SCOS are failing: cluster-bare-metal-operator is not finding the tags for most of the necessary ironic-* images.

Previously we replaced ironic-* images in 4.6+ as we didn't have baremetal installer. We started working on Fedora-based `*.okd` images, but then in 4.10 we rebased on upstream installer and could reuse existing images. This is the case for all ironic* images, if I'm not mistaken, except for `ironic-image` and `ironic-agent-image`.

In this PR, we are removing `__okd ` for ironic* images if we use the same Dockerfile as for OCP.

2022-11-24 08:50 UTC, derekhiggins commented
/approve
thanks @sherine-k

2022-11-28 12:20 UTC, sherine-k commented
Hi @derekhiggins 
Do you think we can merge this PR?

2022-12-01 08:52 UTC, elfosardo commented
/approve

2022-12-01 16:20 UTC, jupierce commented
/approve

2022-12-01 16:43 UTC, merged