ironic-rhcos-downloader ocp image can be used for okd
openshift/release pull request #34263
Opened 2022-11-23 11:40 UTC by sherine-k

2022-11-23 11:40 UTC, sherine-k commented
/pj-rehearse
/assign @LorbusChris

2022-11-24 16:38 UTC, LorbusChris commented
/hold

@sherine-k the excludeTag for mirroring `ironic-machine-os-downloader` has to be removed here as well

2022-11-28 09:44 UTC, sherine-k commented
/unhold

2022-11-28 09:45 UTC, sherine-k commented
> /hold
> 
> @sherine-k the excludeTag for mirroring `ironic-machine-os-downloader` has to be removed here as well

Done

2022-12-01 04:57 UTC, zaneb commented
/approve

2022-12-01 09:05 UTC, elfosardo commented
/lgtm

2022-12-02 09:10 UTC, sherine-k commented
/assign @jupierce

2022-12-02 09:52 UTC, sherine-k commented
/pj-rehearse

2022-12-02 09:55 UTC, sherine-k commented
/unassign  @jupierce

2022-12-06 14:08 UTC, sherine-k commented
/pj-rehearse

2022-12-06 14:25 UTC, sherine-k commented
/assign @jupierce

2022-12-06 16:37 UTC, LorbusChris requested changes

2022-12-06 16:37 UTC, LorbusChris commented on core-services/release-controller/_releases/release-ocp-4.12-ci.json
> +          "ironic-static-ip-manager",
I think the addition of this line is not right here

2022-12-06 16:37 UTC, LorbusChris commented on core-services/release-controller/_releases/release-ocp-4.13-ci.json
> +          "ironic-static-ip-manager",
same here

2022-12-06 16:41 UTC, LorbusChris commented on core-services/release-controller/_releases/release-ocp-4.12-ci.json
> +          "ironic-static-ip-manager",
Instead, the line above should be removed here. There are two configs in this file, which should both be changed in the same way. (remove `ironic-machine-os-downloader` from the excludeTags)

2022-12-07 14:58 UTC, LorbusChris commented
/lgtm

2022-12-07 15:19 UTC, LorbusChris commented
/assign @jupierce

2022-12-13 19:18 UTC, sdodson commented
/approve

2022-12-14 10:50 UTC, LorbusChris commented on ci-operator/step-registry/rosa/credentials/hypershift/mgmt/rosa-credentials-hypershift-mgmt-ref.yaml
> +    Using ocm cli to get the kubeconfig of the management cluster.
@sherine-k looks like this change snuck in during rebase

2022-12-14 10:50 UTC, LorbusChris commented on ci-operator/step-registry/rosa/sts/cluster/provision/rosa-sts-cluster-provision-commands.sh
> +# fi
so does this

2022-12-14 18:27 UTC, sdodson commented
/approve

2022-12-14 21:13 UTC, LorbusChris commented
/lgtm

2022-12-16 14:06 UTC, jupierce commented
/approve

2022-12-16 14:24 UTC, merged