Initial configuration files for the nova-operator.
openshift/release pull request #34435
Opened 2022-11-30 19:22 UTC by rlandy

2022-12-02 17:16 UTC, rlandy commented
/retest-required

2022-12-02 17:33 UTC, rlandy commented
/retest-required

2022-12-02 17:36 UTC, viroel commented
/pj-rehearse

2022-12-05 11:33 UTC, Sandeepyadav93 commented
/verify-owners

2022-12-05 12:51 UTC, Sandeepyadav93 commented
/pj-rehearse

2022-12-05 13:37 UTC, Sandeepyadav93 commented
/pj-rehearse ack 

We have marked failed jobs as `optional: true`

2022-12-05 13:37 UTC, Sandeepyadav93 commented
/lgtm

2022-12-05 14:08 UTC, bogdando commented on ci-operator/jobs/openstack-k8s-operators/nova-operator/openstack-k8s-operators-nova-operator-master-presubmits.yaml
> +    name: pull-ci-openstack-k8s-operators-nova-operator-master-unit
ditto

2022-12-05 14:09 UTC, bogdando commented on ci-operator/jobs/openstack-k8s-operators/nova-operator/openstack-k8s-operators-nova-operator-master-presubmits.yaml
> +    rerun_command: /test unit
the same

2022-12-05 14:09 UTC, bogdando requested changes

2022-12-05 14:09 UTC, bogdando commented on ci-operator/jobs/openstack-k8s-operators/nova-operator/openstack-k8s-operators-nova-operator-master-presubmits.yaml
> +        - --target=unit
functional

2022-12-05 16:09 UTC, rlandy commented
/retest

2022-12-05 16:10 UTC, Sandeepyadav93 commented
/lgtm

2022-12-05 16:16 UTC, merged