infra-deployments: skip CI for stage-only components
openshift/release pull request #34466
Opened 2022-12-01 14:36 UTC by Michkov

Skip components which are not deployed on development/testing clusters.

2022-12-01 14:44 UTC, flacatus commented
/ok-to-test

2022-12-01 14:45 UTC, flacatus commented
/lgtm

2022-12-01 16:37 UTC, flacatus commented
/lgtm

2022-12-02 11:50 UTC, amfred commented
/lgtm

2022-12-02 11:53 UTC, amfred commented
A little more background if we come back to this later:
https://github.com/redhat-appstudio/infra-deployments/blob/main/argo-cd-apps/overlays/development/delete-applications.yaml 
Preview mode is used by e2e-tests, and that is using the development overlay. Therefore changes to these components are not currently in the CI flow. We could revisit that later but it's the current state of things.

2022-12-06 11:10 UTC, amfred commented
/assign @bamachrn

2022-12-06 11:11 UTC, rhopp approved these changes

2022-12-06 11:12 UTC, rhopp commented
/approve

2022-12-06 11:16 UTC, bamachrn commented on ci-operator/jobs/redhat-appstudio/infra-deployments/redhat-appstudio-infra-deployments-main-presubmits.yaml
> +    skip_if_only_changed: ^docs/|^\.github/|^\.tekton/|^components/(authentication|quality-dashboard|hac-pact-broker|monitoring-workload-in-cluster|tekton-ci)/|\.md$|^(?:.*/)?(?:\.gitignore|OWNERS|PR
these are folders? or argcd applications?

2022-12-06 11:19 UTC, bamachrn requested changes
monitoring directory needs to be changed to `components/monitoring`

2022-12-06 11:20 UTC, rhopp commented
/approve cancel

2022-12-07 09:07 UTC, bamachrn approved these changes
looks good to me

2022-12-07 09:23 UTC, amfred approved these changes

2022-12-07 09:48 UTC, merged