Add e2e tests to the odh-notebook-controller
openshift/release pull request #34934
Opened 2022-12-20 11:13 UTC by maroroman

This PR adds e2e tests to odh-notebook-controller. No changes should be necessary on the nbc side.

Resolves: https://github.com/opendatahub-io/kubeflow/issues/30

I wasn't able to test the e2e tests themselves, but the individual commands in this PR should be working.

/cc @LaVLaS @VaishnaviHire

2023-02-08 02:37 UTC, LaVLaS commented on ci-operator/config/opendatahub-io/kubeflow/opendatahub-io-kubeflow-e2e-commands.sh
> +        export IMG=${arrIN[1]}
@maroroman afaik, bash arrays are zero based so this would assign the imagetag name to `IMG` and `TAG` would be the empty string

2023-02-08 02:39 UTC, LaVLaS commented on ci-operator/config/opendatahub-io/kubeflow/opendatahub-io-kubeflow-e2e-commands.sh
> +        #Gather tag and image for deployment
Does the script need to be indented 8 spaces?

2023-02-08 02:42 UTC, LaVLaS commented on ci-operator/config/opendatahub-io/kubeflow/opendatahub-io-kubeflow-e2e-commands.sh
> +        export KUBECONFIG=~/.kube/config
We can simplify this block to use `/tmp/kubeconfig` as the KUBECONFIG file and copy `/var/run/secrets/ci.openshift.io/multi-stage/kubeconfig` to that location as the default

2023-02-08 19:03 UTC, LaVLaS requested changes

2023-02-08 19:30 UTC, VaishnaviHire commented
@maroroman We would also need to update `v1.6-branch` [config](https://github.com/openshift/release/blob/master/ci-operator/config/opendatahub-io/kubeflow/opendatahub-io-kubeflow-v1.6-branch.yaml) to include e2e tests.

2023-02-09 16:25 UTC, VaishnaviHire commented
@maroroman Can you squash the commits for this PR ?

2023-02-09 19:40 UTC, LaVLaS commented
/lgtm

2023-02-09 19:54 UTC, merged