[telco5g] Ci use prepared cluster
openshift/release pull request #35687
Opened 2023-01-25 13:48 UTC by gpuckett-redhat

cuts down on wasted time during testing

2023-01-25 16:13 UTC, sshnaidm requested changes
Please rebase on latest branch

2023-01-25 16:13 UTC, sshnaidm commented on ci-operator/step-registry/telco5g/cluster-setup/telco5g-cluster-setup-commands.sh
> +    when: cnftests == "false"
```suggestion
    when: not cnftests|bool
```

2023-01-25 16:13 UTC, sshnaidm commented on ci-operator/step-registry/telco5g/cluster-setup/telco5g-cluster-setup-commands.sh
> +    when: cnftests == "true"
```suggestion
    when: cnftests|bool
```

2023-01-25 16:13 UTC, sshnaidm commented on ci-operator/step-registry/telco5g/cluster-setup/telco5g-cluster-setup-commands.sh
>  ANSIBLE_STDOUT_CALLBACK=debug ansible-playbook -i $SHARED_DIR/inventory ~/ocp-install.yml -vv
please add indentation

2023-01-25 16:13 UTC, sshnaidm commented on ci-operator/step-registry/telco5g/cluster-setup/telco5g-cluster-setup-commands.sh
> +CNF_ARG=""
That's good for the first iteration. Please also check an option to manipulate actual parameters for upstream_cluster_all.py - for example:
```bash
ADDITIONAL_ARG=""
if [[ "$T5CI_JOB_TYPE" == "cnftests" ]]; then
  ADDITIONAL_ARG="--cluster-name cnfdc2 --force"
fi
```
And then just using the same task:

```yaml
- name: Discover cluster to run job
  command: python3 ~/telco5g-lab-deployment/scripts/upstream_cluster_all.py --get-cluster -e $CL_SEARCH $ADDITIONAL_ARG
  register: cluster
  environment:
    JOB_NAME: ${JOB_NAME:-'unknown'}
```
Then we leave ansible execution as is and changing just the params inside.

2023-01-25 17:57 UTC, sshnaidm commented
/uncc @jmguzik 
/uncc @danilo-gemoli

2023-01-26 14:06 UTC, closed without merging

2023-01-26 14:11 UTC, gpuckett-redhat commented
bad rebase, closing this one