Added pre-commit job for ovs-operator
openshift/release pull request #36013
Opened 2023-02-03 09:46 UTC by amolkahat

This patch adds pre-commit job for
ovs-operator

Signed-off-by: Amol Kahat <amolkahat@gmail.com>

2023-02-06 03:40 UTC, amolkahat commented
/ok-to-test

2023-02-10 08:29 UTC, amolkahat commented
/pj-rehearse

2023-02-21 06:49 UTC, amolkahat commented
/pj-rehearse

2023-02-21 07:44 UTC, amolkahat commented
/pj-rehearse pull-ci-openstack-k8s-operators-ovs-operator-main-precommit-check

2023-02-27 13:59 UTC, amolkahat commented
/pj-rehearse

2023-03-06 12:12 UTC, amolkahat commented
/pj-rehearse

2023-03-13 11:26 UTC, amolkahat commented
/pj-rehearse pull-ci-openstack-k8s-operators-ovs-operator-main-precommit-check

2023-04-03 20:39 UTC, viroel commented
/pj-rehearse pull-ci-openstack-k8s-operators-ovs-operator-main-precommit-check

2023-04-05 11:19 UTC, Sandeepyadav93 commented
/pj-rehearse pull-ci-openstack-k8s-operators-ovn-operator-main-precommit-check

2023-04-05 11:23 UTC, Sandeepyadav93 commented
/pj-rehearse pull-ci-openstack-k8s-operators-ovs-operator-main-precommit-check

2023-04-05 15:31 UTC, viroel requested changes

2023-04-05 15:32 UTC, viroel commented
Also depends-on:
https://github.com/openstack-k8s-operators/ovs-operator/pull/92
and
https://github.com/openstack-k8s-operators/ovs-operator/pull/91

2023-04-06 06:06 UTC, marios reviewed
looks like needs some updates 

https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_release/36013/rehearse-36013-pull-ci-openstack-k8s-operators-ovs-operator-main-precommit-check/1643575331338063872

 /go/pkg/mod/sigs.k8s.io/json@v0.0.0-20220713155537-f223a00ba0e2/internal/golang/encoding/json/decode.go:1261:42: predeclared any requires go1.18 or later (-lang was set to go1.16; check go.mod)

2023-04-06 14:06 UTC, bshewale commented on ci-operator/config/openstack-k8s-operators/ovs-operator/openstack-k8s-operators-ovs-operator-main.yaml
> +    export GOFLAGS=" -mod=readonly"
Done

2023-04-06 14:59 UTC, viroel commented
/lgtm
/pj-rehearse ack

2023-04-06 15:25 UTC, merged