Added pre-commit job for maradb operator
openshift/release pull request #36011
Opened 2023-02-03 09:21 UTC by amolkahat

This patch adds pre-commit job for mariadb operator

Signed-off-by: Amol Kahat <amolkahat@gmail.com>

2023-02-06 03:42 UTC, amolkahat commented
/ok-to-test

2023-02-10 09:55 UTC, amolkahat commented
/pj-rehearse

2023-02-13 11:26 UTC, amolkahat commented
/pj-rehearse

2023-02-13 12:44 UTC, amolkahat commented
/retest-required

2023-02-14 13:39 UTC, amolkahat commented
/pj-rehearse

2023-02-20 11:09 UTC, amolkahat commented
/pj-rehearse

2023-02-27 12:51 UTC, amolkahat commented
/pj-rehearse

2023-03-13 11:22 UTC, amolkahat commented
/pj-rehearse pull-ci-openstack-k8s-operators-mariadb-operator-master-precommit-check

2023-03-14 21:22 UTC, viroel requested changes

2023-03-14 21:22 UTC, viroel commented on ci-operator/config/openstack-k8s-operators/mariadb-operator/openstack-k8s-operators-mariadb-operator-master.yaml
By adding pre-commit job, we should also remove duplicated jobs: govet, gofmt, golint will already be tested by pre-commit job.

2023-03-17 09:22 UTC, amolkahat commented on ci-operator/config/openstack-k8s-operators/mariadb-operator/openstack-k8s-operators-mariadb-operator-master.yaml
I agree with you. But we can't remove those until we are adding pre-commit jobs.

2023-03-20 17:31 UTC, amolkahat commented
/pj-rehearse pull-ci-openstack-k8s-operators-mariadb-operator-master-precommit-check

2023-03-28 07:10 UTC, amolkahat commented
/pj-rehearse pull-ci-openstack-k8s-operators-mariadb-operator-master-precommit-check

2023-03-28 10:13 UTC, marios requested changes
looks right but please update the commit message s/maradb/mariadb

2023-03-28 10:13 UTC, marios commented on ci-operator/config/openstack-k8s-operators/mariadb-operator/openstack-k8s-operators-mariadb-operator-master.yaml
> +    from: openstack-operator-ci-pre-commit
sanity check - looks like the repo already has the .pre-commit-config https://github.com/openstack-k8s-operators/mariadb-operator/blob/9b37cd889f189f86af017b8b0e51dd28bbcc7127/.pre-commit-config.yaml#L1

2023-03-29 06:28 UTC, marios approved these changes
lgtm 

no precommit job run on the latest updates but that should be OK since it was just a commit message update

run history there https://prow.ci.openshift.org/job-history/gs/origin-ci-test/pr-logs/directory/rehearse-36011-pull-ci-openstack-k8s-operators-mariadb-operator-master-precommit-check

last result from 28th @ https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_release/36011/rehearse-36011-pull-ci-openstack-k8s-operators-mariadb-operator-master-precommit-check/1640612596358844416/build-log.txt

2023-03-29 16:37 UTC, viroel commented
@amolkahat hi, can you remove jobs that are now duplicated, e.g. govet, gofmt, since they run in pre-commit.

2023-04-03 20:42 UTC, viroel commented
/pj-rehearse pull-ci-openstack-k8s-operators-mariadb-operator-master-precommit-check

2023-04-12 11:15 UTC, bshewale commented
Will need this PR first to merge : https://github.com/openstack-k8s-operators/mariadb-operator/pull/90

2023-04-13 14:42 UTC, viroel commented
/pj-rehearse pull-ci-openstack-k8s-operators-mariadb-operator-master-precommit-check

2023-04-13 15:11 UTC, viroel commented
/lgtm

2023-04-13 16:35 UTC, merged