enable p & z assisted installer builds
openshift/release pull request #36060
Opened 2023-02-06 05:04 UTC by jacobemery

Add Power (ppc64le) and Z (s390x) to enable the Assisted Installer to deploy OCP onto these architectures.

The following Assisted Installer components are required to run on the target architecture and are built using the scripts changed in this PR:
- assisted-installer
- assisted-installer-controller
- assisted-installer-agent

Strategy: [OCPPLAN-8327](https://issues.redhat.com/browse/OCPPLAN-8327)
Epic: [MULTIARCH-2889](https://issues.redhat.com/browse/MULTIARCH-2889)
Sub-task: [MGMT-13560](https://issues.redhat.com/browse/MGMT-13560)

2023-02-06 05:04 UTC, jacobemery commented
/pj-rehearse

2023-02-06 18:48 UTC, jacobemery commented
/pj-rehearse

2023-02-09 17:29 UTC, jacobemery commented
/pj-rehearse

2023-02-09 17:30 UTC, jacobemery commented
@droslean @smg247 I believe this is ready to test, could one of you confirm?

2023-02-12 07:21 UTC, osherdp commented
/ok-to-test

2023-02-12 07:41 UTC, osherdp commented
> @droslean @smg247 I believe this is ready to test, could one of you confirm?
> 
> Context: https://issues.redhat.com/browse/MGMT-13560

no, their not required for the review. prow sometimes assigns people from admins of the CI system
/uncc droslean smg247
/cc @osherdp @ori-amizur

2023-02-12 07:42 UTC, osherdp requested changes

2023-02-12 07:42 UTC, osherdp commented on ci-operator/config/openshift/assisted-installer-agent/openshift-assisted-installer-agent-master__edge.yaml
> +  postsubmit: false
be aware those are temporary changes just to enable testing in this PR. so it should not be merged

2023-02-12 07:42 UTC, osherdp commented on ci-operator/config/openshift/assisted-installer/openshift-assisted-installer-master__edge.yaml
> +  postsubmit: false
same as above

2023-02-12 07:43 UTC, osherdp commented
/hold (to make sure temporary changes don't get in by mistake)

2023-02-12 07:43 UTC, osherdp commented
/pj-rehearse

2023-02-12 07:46 UTC, osherdp commented
@jacobemery you may need to do ``make update`` and push the changes so it can auto-generate job definition changes

2023-02-27 18:37 UTC, jacobemery commented
> @jacobemery you may need to do `make update` and push the changes so it can auto-generate job definition changes

Done!

2023-02-27 19:35 UTC, osherdp commented
/pj-rehearse

2023-02-27 23:13 UTC, jacobemery commented
> it shouldn't really, and you can see the rehearses fail because `quay.io/centos/centos:stream8` doesn't support `s390x` now let's try to only add `ppc64le`

Ah, you're right... Done ^

2023-02-27 23:13 UTC, jacobemery commented
/pj-rehearse

2023-02-28 02:51 UTC, jacobemery commented
> make sure the rehearse jobs are passing. afterwards we can revert the jobs types back from presubmit to postsubmit (and regenerate the code using `make update`)

@osherdp Looks like rehearse tests passed, good to do the above now?

2023-02-28 07:16 UTC, osherdp commented
> > make sure the rehearse jobs are passing. afterwards we can revert the jobs types back from presubmit to postsubmit (and regenerate the code using `make update`)
> 
> @osherdp Looks like rehearse tests passed, good to do the above now?

Yes, good to go!

2023-02-28 07:58 UTC, jacobemery commented
> Yes, good to go!

Done!

2023-02-28 08:46 UTC, osherdp approved these changes

2023-02-28 08:46 UTC, osherdp commented
/unhold
/pj-rehearse ack

2023-02-28 08:50 UTC, merged