Add E2E job which build and deploy AnsibleEE
openshift/release pull request #36430
Opened 2023-02-15 17:01 UTC by fao89

2023-02-15 17:02 UTC, fao89 commented
/pj-rehearse

2023-02-15 17:50 UTC, fao89 commented
/pj-rehearse pull-ci-openstack-k8s-operators-openstack-ansibleee-operator-main-ansibleee-operator-build-deploy

2023-02-15 17:55 UTC, fao89 commented
/pj-rehearse

2023-02-15 21:13 UTC, fao89 commented
/assign @sandeepyadav93

2023-02-16 08:34 UTC, sandeepyadav93 requested changes

2023-02-16 08:34 UTC, sandeepyadav93 commented on ci-operator/config/openstack-k8s-operators/openstack-ansibleee-operator/openstack-k8s-operators-openstack-ansibleee-operator-main.yaml
> +  openstack-operator-ci-pre-commit:
We are moving to use the same build_root image for pre-commit job as well.

For some operators we have already done that, could you please follow the example from mariadb operator:

[1] https://github.com/openshift/release/blob/master/ci-operator/config/openstack-k8s-operators/openstack-operator/openstack-k8s-operators-openstack-operator-master.yaml#L33-L37
[2] https://github.com/openshift/release/blob/master/ci-operator/config/openstack-k8s-operators/openstack-operator/openstack-k8s-operators-openstack-operator-master.yaml#L93-L103


fyi.. there are open patches to do same for other operators:

https://github.com/openshift/release/pulls?q=is%3Apr+is%3Aopen+amol

2023-02-16 10:04 UTC, fao89 commented
/pj-rehearse

2023-02-16 10:34 UTC, fao89 commented
@sandeepyadav93 any clue why it is failing now?

2023-02-16 11:00 UTC, fao89 commented
/pj-rehearse

2023-02-16 13:12 UTC, fao89 commented
/pj-rehearse pull-ci-openstack-k8s-operators-openstack-ansibleee-operator-main-openstack-ansibleee-operator-build-deploy

2023-02-16 16:00 UTC, sandeepyadav93 commented
/lgtm

2023-02-16 16:00 UTC, sandeepyadav93 commented
/pj-rehearse ack

2023-02-16 16:14 UTC, merged