velero: initial setup
openshift/release pull request #36649
Opened 2023-02-22 15:44 UTC by hhpatel14

2023-02-22 16:31 UTC, hhpatel14 commented
/pj-rehearse

2023-02-23 19:40 UTC, kaovilai requested changes

2023-02-23 19:40 UTC, kaovilai commented on ci-operator/config/openshift/velero/openshift-velero-konveyor-dev.yaml
> +    tag: golang-1.17
```suggestion
    tag: golang-1.19
```

2023-02-27 16:35 UTC, hhpatel14 commented
/pj-rehearse

2023-02-27 16:55 UTC, kaovilai commented
/pj-rehearse ack

2023-02-27 16:55 UTC, kaovilai approved these changes

2023-02-27 16:56 UTC, kaovilai commented
/approve
/lgtm

2023-02-27 17:22 UTC, kaovilai commented
/assign smg247

2023-02-28 08:32 UTC, danilo-gemoli approved these changes

2023-02-28 09:03 UTC, merged