ROX-15287: enable ocp 4.6 testing
openshift/release pull request #36942
Opened 2023-03-03 18:38 UTC by BradLugo

/cc @gavin-stackrox

2023-03-03 18:47 UTC, BradLugo commented
/pj-rehearse refresh

2023-03-03 18:49 UTC, BradLugo commented
/pj-rehearse pull-ci-stackrox-stackrox-master-ocp-4-6-operator-e2e-tests pull-ci-stackrox-stackrox-master-ocp-4-6-qa-e2e-tests pull-ci-stackrox-stackrox-master-ocp-4-6-ui-e2e-tests

2023-03-03 23:33 UTC, gavin-stackrox requested changes

2023-03-03 23:33 UTC, gavin-stackrox commented on ci-operator/config/stackrox/stackrox/stackrox-stackrox-master__ocp-4-6.yaml
> +  as: qa-e2e-tests
Nice! gets rid of that echo :)

2023-03-03 23:33 UTC, gavin-stackrox commented on ci-operator/config/stackrox/stackrox/stackrox-stackrox-master__ocp-4-6.yaml
> +  run_if_changed: ^((generated|image|operator|pkg|make|deploy|scripts)/.*|Makefile|status\.sh|EXPECTED_GO_VERSION)
4.6 maser presubmit is ! run_if_changed per https://docs.engineering.redhat.com/display/StackRox/ACS+-+OpenShift+version+support
```suggestion
```

2023-03-03 23:33 UTC, gavin-stackrox commented on ci-operator/config/stackrox/stackrox/stackrox-stackrox-master__ocp-4-6.yaml
> +  run_if_changed: ^((generated|image|operator|pkg|make|deploy|scripts)/.*|Makefile|status\.sh|EXPECTED_GO_VERSION)
ditto
```suggestion
```

2023-03-03 23:33 UTC, gavin-stackrox commented on ci-operator/jobs/stackrox/stackrox/stackrox-stackrox-master-presubmits.yaml
> +    run_if_changed: ^((generated|image|operator|pkg|make|deploy|scripts)/.*|Makefile|status\.sh|EXPECTED_GO_VERSION)
you may need to manually delete this after removing in config and running `make update`.

2023-03-04 00:29 UTC, gavin-stackrox approved these changes
/lgtm

2023-03-04 00:30 UTC, gavin-stackrox commented
/cc @msugakov 
FYI

2023-03-04 00:40 UTC, BradLugo commented
/pj-rehearse ack

2023-03-04 00:43 UTC, merged