stackrox: fix nightly ocp 4.12 testing
openshift/release pull request #36992
Opened 2023-03-06 19:22 UTC by BradLugo

Splits nightly ocp 4.12 testing into its own variant and uses `cluster_profile` instead of `cluster_claim`. Prerequisite for https://github.com/openshift/release/pull/36771

/uncc
/hold

2023-03-06 19:23 UTC, BradLugo commented
/assign @BradLugo

2023-03-06 19:31 UTC, BradLugo commented
/pj-rehearse refresh

2023-03-06 19:36 UTC, BradLugo commented
I guess the postsubmit jobs aren't rehearsable. Is there a way to test these changes?

/cc @gavin-stackrox 
/unhold

2023-03-06 21:11 UTC, gavin-stackrox requested changes

2023-03-06 21:11 UTC, gavin-stackrox commented on ci-operator/config/stackrox/stackrox/stackrox-stackrox-nightlies__ocp-4-12.yaml
> +- as: ui-e2e-tests
UI e2e are not passing under OCP yet, so don't add these to nightlies (yet).

2023-03-06 21:13 UTC, gavin-stackrox commented
> I guess the postsubmit jobs aren't rehearsable. Is there a way to test these changes?

You _could_ remove the `postsubmit: true` to test but because these are a duplicate of what we know works for master, I don't think that is necessary.

2023-03-06 22:25 UTC, BradLugo commented
/pj-rehearse refresh

2023-03-09 22:26 UTC, gavin-stackrox commented on ci-operator/config/stackrox/stackrox/stackrox-stackrox-nightlies__ocp-4-12.yaml
> +      QA_TEST_TARGET: test
Only used by qa-e2e.
```suggestion
```

2023-03-09 22:50 UTC, gavin-stackrox approved these changes
/lgtm

2023-03-09 23:11 UTC, merged