WIP Run kuttl tests in e2e job for ironic-operator
openshift/release pull request #37103
Opened 2023-03-09 10:00 UTC by cescgina

Run the build-deploy-kuttl workflow instead of the build-deploy one.

2023-03-09 10:02 UTC, cescgina commented
/pj-rehearse pull-ci-openstack-k8s-operators-ironic-operator-master-keystone-operator-build-deploy-kuttl

2023-03-09 11:41 UTC, viroel requested changes

2023-03-09 11:41 UTC, viroel commented on ci-operator/config/openstack-k8s-operators/ironic-operator/openstack-k8s-operators-ironic-operator-master.yaml
> +- as: keystone-operator-build-deploy-kuttl
ironic

2023-03-09 11:46 UTC, cescgina commented on ci-operator/config/openstack-k8s-operators/ironic-operator/openstack-k8s-operators-ironic-operator-master.yaml
> +- as: keystone-operator-build-deploy-kuttl
Fixed, thanks!

2023-03-09 12:33 UTC, cescgina commented
/pj-rehearse pull-ci-openstack-k8s-operators-ironic-operator-master-ironic-operator-build-deploy-kuttl

2023-03-14 08:32 UTC, cescgina commented
/pj-rehearse pull-ci-openstack-k8s-operators-ironic-operator-master-ironic-operator-build-deploy-kuttl

2023-03-17 16:45 UTC, cescgina commented
/pj-rehearse pull-ci-openstack-k8s-operators-ironic-operator-master-ironic-operator-build-deploy-kuttl

2023-03-20 09:41 UTC, cescgina commented
/pj-rehearse pull-ci-openstack-k8s-operators-ironic-operator-master-ironic-operator-build-deploy-kuttl

2023-03-22 07:50 UTC, Sandeepyadav93 commented
/pj-rehearse ack

kuttl run looks good

https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_release/37103/rehearse-37103-pull-ci-openstack-k8s-operators-ironic-operator-master-ironic-operator-build-deploy-kuttl/1637751620852781056/artifacts/ironic-operator-build-deploy-kuttl/openstack-k8s-operators-kuttl/build-log.txt

2023-03-22 07:51 UTC, Sandeepyadav93 commented
/lgtm

2023-03-22 08:13 UTC, merged