stackrox: ocp 4.8 variant for master builds
openshift/release pull request #37181
Opened 2023-03-10 16:54 UTC by BradLugo

/hold
/uncc
/assign @BradLugo

2023-03-10 17:20 UTC, BradLugo commented
/pj-rehearse refresh

2023-03-10 17:31 UTC, BradLugo commented
/pj-rehearse

2023-03-10 18:13 UTC, BradLugo commented
/unhold
/cc @gavin-stackrox

2023-03-10 18:30 UTC, gavin-stackrox reviewed
WDYT about removing the `run_if_changed` lines and remove the `postsubmit: true` jobs? I _think_ based on conversations we no longer have to cover OCP pre 4.10 for ACS 4.xx (which is current master). cc @msugakov 
Though I think its wide to keep the option of running them on a PR.

2023-03-17 18:09 UTC, gavin-stackrox requested changes

2023-03-17 18:09 UTC, gavin-stackrox commented on ci-operator/config/stackrox/stackrox/stackrox-stackrox-master__ocp-4-8.yaml
> +  timeout: 5h0m0s
lets drop this
```suggestion
```

2023-03-17 18:20 UTC, gavin-stackrox commented
/lgtm

2023-04-20 15:37 UTC, BradLugo commented
Other PRs covered these changes

2023-04-20 15:37 UTC, closed without merging