ROX-15287: fix ocp 4.6 for release-3.74 branch
openshift/release pull request #37239
Opened 2023-03-13 21:45 UTC by BradLugo

/cc @gavin-stackrox 
/assign @BradLugo

2023-03-13 21:45 UTC, BradLugo commented on ci-operator/config/stackrox/stackrox/stackrox-stackrox-release-3.73__ocp-4-6.yaml
> +  timeout: 5h0m0s
not sure if we need this

2023-03-13 21:47 UTC, BradLugo commented
/pj-rehearse auto-ack

2023-03-13 21:47 UTC, gavin-stackrox commented
Changed files are for `3.73`?

2023-03-14 01:41 UTC, BradLugo commented
/pj-rehearse

2023-03-14 06:27 UTC, BradLugo commented
/retest

2023-03-14 06:50 UTC, BradLugo commented
/pj-rehearse

2023-03-14 15:47 UTC, BradLugo commented
/pj-rehearse ack

2023-03-14 18:12 UTC, gavin-stackrox requested changes

2023-03-14 19:22 UTC, BradLugo commented
/pj-rehearse auto-ack

2023-03-14 21:54 UTC, gavin-stackrox approved these changes
/lgtm

2023-03-14 22:14 UTC, BradLugo commented
/pj-rehearse auto-ack

2023-03-14 22:28 UTC, merged