sandboxed-containers-operator: add check job
openshift/release pull request #37771
Opened 2023-03-28 19:11 UTC by wainersm

Added the 'check' job that will run the `make test` in the repository for pull requests.

2023-03-28 19:26 UTC, wainersm commented
/pj-rehearse pull-ci-openshift-sandboxed-containers-operator-main-check

2023-03-28 20:01 UTC, wainersm commented
/pj-rehearse pull-ci-openshift-sandboxed-containers-operator-main-check

2023-03-28 21:53 UTC, wainersm commented
/pj-rehearse pull-ci-openshift-sandboxed-containers-operator-main-check

2023-03-28 22:16 UTC, wainersm commented
/pj-rehearse pull-ci-openshift-sandboxed-containers-operator-main-check

2023-03-29 00:09 UTC, wainersm commented
/pj-rehearse pull-ci-openshift-sandboxed-containers-operator-main-check

2023-03-29 00:12 UTC, wainersm commented
/retest

2023-03-29 12:43 UTC, wainersm commented
/pj-rehearse pull-ci-openshift-sandboxed-containers-operator-main-check

2023-03-30 16:38 UTC, bpradipt approved these changes
/lgtm

2023-03-30 17:16 UTC, wainersm commented
/pj-rehearse

2023-04-26 13:52 UTC, wainersm commented
/pj-rehearse

2023-04-26 15:17 UTC, cpmeadors requested changes
The check itself looks good.  Just a comment about the containers used.

2023-04-26 15:17 UTC, cpmeadors commented on ci-operator/config/openshift/sandboxed-containers-operator/openshift-sandboxed-containers-operator-main.yaml
> +  ocp_builder_rhel-8-golang-1.18-openshift-4.11:
OCP 1.4.0 will be build against rhel9, golang 1.19 and OCP 4.13.  Prow should be consistent with our builds.

2023-04-26 15:32 UTC, wainersm commented
/pj-rehearse pull-ci-openshift-sandboxed-containers-operator-main-check

2023-04-26 15:33 UTC, wainersm commented
Updated the PR to build the against rhel9, golang 1.19 and OCP 4.13.

The removal (or fixing) of the e2e test will be done in another PR.

2023-04-26 16:03 UTC, wainersm commented
@cpmeadors `ci/rehearse/openshift/sandboxed-containers-operator/main/check ` has passed with the new build root. But I still don't understand why tide did not merge it automatically

2023-04-26 17:36 UTC, wainersm commented
/pj-rehearse ack

2023-04-26 17:39 UTC, wainersm commented
/lgtm

2023-04-26 17:41 UTC, wainersm commented
Apparently it needs at least one lgtm label.

2023-04-26 18:40 UTC, cpmeadors approved these changes
/lgtm

2023-04-26 18:41 UTC, cpmeadors commented
/approve

2023-04-26 19:17 UTC, merged