Velero: add config for branch oadp-1.2
openshift/release pull request #38076
Opened 2023-04-05 14:57 UTC by hhpatel14

2023-04-05 15:27 UTC, kaovilai requested changes

2023-04-05 15:27 UTC, kaovilai commented on core-services/prow/02_config/openshift/velero/_prowconfig.yaml
>    queries:
```suggestion
tide:
  merge_method:
    openshift/velero: squash
  queries:
```
Similar to
https://github.com/openshift/release/pull/38010/files#diff-3662ab9ef29d6d8e8c3e3e2bbe09019fad92c59c3e5c3eb488f0984f917d1060R11-R12

2023-04-05 18:02 UTC, kaovilai commented
/pj-rehearse

2023-04-05 18:03 UTC, kaovilai commented
/retest

2023-04-05 18:57 UTC, kaovilai requested changes

2023-04-05 18:57 UTC, kaovilai commented on ci-operator/config/openshift/velero/openshift-velero-oadp-1.2.yaml
> +    tag: golang-1.18
Per https://github.com/vmware-tanzu/velero/blob/73f17404078f0247c5d27af3890d8f33b598ff6c/Dockerfile#L16
This needs to be 1.19

2023-04-05 18:59 UTC, kaovilai commented on ci-operator/config/openshift/velero/openshift-velero-oadp-1.2.yaml
> +    tag: golang-1.18
```suggestion
    tag: golang-1.19
```

2023-04-05 19:07 UTC, hhpatel14 commented
/pj-rehearse

2023-04-06 13:34 UTC, hhpatel14 commented
/pj-rehearse

2023-04-06 14:57 UTC, kaovilai commented
/retest

2023-04-06 15:14 UTC, kaovilai commented
/pj-rehearse

2023-04-06 15:52 UTC, sseago approved these changes

2023-04-06 15:56 UTC, kaovilai commented
/pj-rehearse ack

2023-04-06 16:35 UTC, hhpatel14 commented
/pj-rehearse

2023-04-06 16:56 UTC, hhpatel14 commented
/pj-rehearse

2023-04-06 17:09 UTC, hhpatel14 commented
/unhold

2023-04-06 17:41 UTC, kaovilai approved these changes
/lgtm

2023-04-06 18:02 UTC, merged