ODH workbench: Build the runtime images on post and pre submit jobs
openshift/release pull request #38165
Opened 2023-04-07 18:37 UTC by harshad16

Related-to: https://github.com/opendatahub-io/notebooks/issues/54
Depends-on: https://github.com/opendatahub-io/notebooks/pull/63

This would build the runtime image and push them to quay repo.

2023-04-11 10:07 UTC, atheo89 requested changes

2023-04-27 15:29 UTC, harshad16 commented on ci-operator/config/opendatahub-io/notebooks/opendatahub-io-notebooks-main.yaml
>  - as: notebooks-e2e-tests
Included tests for the runtimes as well :+1:

2023-05-02 14:14 UTC, atheo89 commented
/lgtm

2023-05-02 14:16 UTC, VaishnaviHire commented
/test all

2023-05-03 07:34 UTC, atheo89 commented
/lgtm
/pj-rehearse ack

2023-05-03 07:58 UTC, merged