Add CI tests for 4.13 IBMCloud
openshift/release pull request #38276
Opened 2023-04-12 21:28 UTC by cappetersson

2023-04-12 21:29 UTC, cappetersson commented
/pj-rehearse pull-ci-openshift-hypershift-release-4.13-e2e-ibmcloud-iks

2023-04-19 16:21 UTC, hasueki requested changes
Few tweaks required

2023-04-19 16:21 UTC, hasueki commented on ci-operator/config/openshift/hypershift/openshift-hypershift-release-4.13.yaml
>        MANAGEMENT_CLUSTER_KUBECONFIG: /etc/ibmcloud/secrets/iks.kubeconfig
```suggestion
      MANAGEMENT_CLUSTER_KUBECONFIG: /etc/ibmcloud/secrets/iks-release.kubeconfig
```

2023-04-19 16:21 UTC, hasueki commented on ci-operator/config/openshift/hypershift/openshift-hypershift-release-4.13.yaml
>    run_if_changed: ^api/
```suggestion
  skip_if_only_changed: (^(docs|examples|enhancements)/)|(^[A-Z]+\.md$)|((^|/)OWNERS$)
```

2023-04-19 16:21 UTC, hasueki commented on ci-operator/config/openshift/hypershift/openshift-hypershift-release-4.13.yaml
>      workflow: hypershift-ibmcloud-e2e
```suggestion
    workflow: hypershift-ibmcloud-e2e-release
```

2023-04-19 16:21 UTC, hasueki commented on ci-operator/config/openshift/hypershift/openshift-hypershift-release-4.13.yaml
>        MANAGEMENT_CLUSTER_KUBECONFIG: /etc/ibmcloud/secrets/roks.kubeconfig
```suggestion
      MANAGEMENT_CLUSTER_KUBECONFIG: /etc/ibmcloud/secrets/roks-release.kubeconfig
```

2023-04-19 16:21 UTC, hasueki commented on ci-operator/config/openshift/hypershift/openshift-hypershift-release-4.13.yaml
>    run_if_changed: ^api/
```suggestion
  skip_if_only_changed: (^(docs|examples|enhancements)/)|(^[A-Z]+\.md$)|((^|/)OWNERS$)
```

2023-04-21 01:43 UTC, hasueki commented
/pj-rehearse pull-ci-openshift-hypershift-release-4.13-e2e-ibmcloud-iks

2023-04-21 01:43 UTC, hasueki commented
/pj-rehearse pull-ci-openshift-hypershift-release-4.13-e2e-ibmcloud-roks

2023-04-21 02:03 UTC, hasueki commented on ci-operator/config/openshift/hypershift/openshift-hypershift-release-4.13.yaml
>      workflow: hypershift-ibmcloud-e2e
```suggestion
    workflow: hypershift-ibmcloud-e2e-release
```

2023-04-21 19:23 UTC, cappetersson commented
/pj-rehearse pull-ci-openshift-hypershift-release-4.13-e2e-ibmcloud-iks
/pj-rehearse pull-ci-openshift-hypershift-release-4.13-e2e-ibmcloud-roks

2023-04-21 19:29 UTC, cappetersson commented
/pj-rehearse pull-ci-openshift-hypershift-release-4.13-e2e-ibmcloud-iks

2023-04-21 20:05 UTC, cappetersson commented
/pj-rehearse pull-ci-openshift-hypershift-release-4.13-e2e-ibmcloud-roks

2023-04-21 22:01 UTC, hasueki commented
/lgtm
/approve

2023-04-24 20:12 UTC, a-dsouza commented
@csrwng @sjenning PTAL

2023-04-25 14:59 UTC, sjenning commented
/approve
/lgtm
/pj-rehearse ack

2023-04-25 15:26 UTC, merged