[azure] add workflow azure-ipi-minimal-permission
openshift/release pull request #38399
Opened 2023-04-17 11:44 UTC by jinyunma

Add workflow azure-ipi-minimal-permission

2023-04-17 12:20 UTC, jinyunma commented
/pj-rehearse periodic-ci-openshift-verification-tests-master-installer-rehearse-4.13-installer-rehearse-azure

2023-04-17 12:48 UTC, jinyunma commented
/pj-rehearse periodic-ci-openshift-verification-tests-master-installer-rehearse-4.13-installer-rehearse-azure

2023-04-17 13:09 UTC, jinyunma commented
/pj-rehearse periodic-ci-openshift-verification-tests-master-installer-rehearse-4.13-installer-rehearse-azure

2023-04-17 13:47 UTC, jinyunma commented
/pj-rehearse periodic-ci-openshift-verification-tests-master-installer-rehearse-4.13-installer-rehearse-azure

2023-04-17 14:15 UTC, jinyunma commented
/pj-rehearse periodic-ci-openshift-verification-tests-master-installer-rehearse-4.13-installer-rehearse-azure

2023-04-17 14:49 UTC, jinyunma commented
/pj-rehearse periodic-ci-openshift-verification-tests-master-installer-rehearse-4.13-installer-rehearse-azure

2023-04-18 01:03 UTC, jinyunma commented
/pj-rehearse periodic-ci-openshift-verification-tests-master-installer-rehearse-4.13-installer-rehearse-azure

2023-04-18 02:30 UTC, jinyunma commented
cc @jianlinliu @yunjiang29 @gpei @jianli-wei to review

After review, I will continue to add relevant CI jobs in this PR

2023-04-18 02:42 UTC, jianlinliu commented on ci-operator/step-registry/azure/provision/service-principal/minimal-permission/azure-provision-service-principal-minimal-permission-commands.sh
> +SP_OUTPUT=/tmp/azure_sp_output
suggest to use `mktemp` to instead of it.

2023-04-18 02:45 UTC, jianlinliu commented on ci-operator/step-registry/azure/deprovision/service-principal-and-custom-role/azure-deprovision-service-principal-and-custom-role-ref.metadata.json
> +	"path": "azure/deprovision/service-principal-and-custom-role/azure-deprovision-service-principal-and-custom-role-ref.yaml",
how about rename `service-principal-and-custom-role` to `sp-and-custom-role` for a shorter name.

2023-04-18 03:37 UTC, jianlinliu commented
looks good to me.

2023-04-18 04:42 UTC, jianlinliu commented
/lgtm

2023-04-18 05:34 UTC, jianlinliu commented
cc @liangxia to review

2023-04-18 05:34 UTC, jianlinliu commented
/pj-rehearse ack

2023-04-18 06:13 UTC, jianli-wei requested changes

2023-04-18 06:13 UTC, jianli-wei commented on ci-operator/step-registry/ipi/install/install/ipi-install-install-commands.sh
> +        export AZURE_AUTH_LOCATION=${SHARED_DIR}/azure_minimal_permission
How about showing a similar message as in ipi-deprovision-deprovision? Thanks!

2023-04-18 09:48 UTC, merged