OSSM-3666: migrate maistra test-infra containers jobs
openshift/release pull request #38574
Opened 2023-04-20 21:16 UTC by yxun

2023-04-20 21:23 UTC, yxun commented
/pj-rehearse

2023-04-20 21:30 UTC, yxun commented
It looks like the `make update` target willl automatically remove "postsubmit: true"  in the push-containers-x-x test job section.

2023-04-20 21:42 UTC, jwendell requested changes

2023-04-20 21:42 UTC, jwendell commented on ci-operator/config/maistra/test-infra/maistra-test-infra-main.yaml
> +    - as: push-containers-2-1
push jobs need to be on their own level. They will be postsubmit jobs

2023-04-20 21:50 UTC, yxun commented
/pj-rehearse

2023-04-25 11:57 UTC, yxun commented
/pj-rehearse pull-ci-maistra--test-infra-push-containers-2-3

2023-04-25 12:03 UTC, yxun commented
/pj-rehearse pull-ci-maistra-test-infra-main-test-infra-push-containers-2-3

2023-04-25 13:12 UTC, yxun commented
/pj-rehearse pull-ci-maistra-test-infra-main-test-infra-build-containers-2-3

2023-04-25 13:20 UTC, yxun commented
/pj-rehearse pull-ci-maistra-test-infra-main-test-infra-push-containers-2-3

2023-04-25 14:11 UTC, jwendell reviewed
LGTM, put the `postsubmit: true` back

2023-04-25 14:28 UTC, jwendell requested changes
Please use `run_if_changed` as we have today in test-infra jobs. Sorry for not having noticed it before.

2023-04-25 16:58 UTC, jwendell approved these changes

2023-04-25 17:00 UTC, jwendell commented
/pj-rehearse ack

2023-04-25 17:00 UTC, yxun commented
/pj-rehearse ack

2023-04-25 17:26 UTC, merged