stackrox: OCP 4.13 changes for master, nightlies & release template
openshift/release pull request #38578
Opened 2023-04-21 00:42 UTC by gavin-stackrox

- renames `-next` to `-4-13` for sanity.
- moves operator weekly to nightly.
- updates release template to match suite names and current master + nightly state

/hold
/uncc

2023-04-21 00:53 UTC, gavin-stackrox commented
/pj-rehearse
/cc @BradLugo @msugakov

2023-04-21 06:33 UTC, msugakov commented
`periodic-ci-stackrox-stackrox-master-ocp-4-13-weekly-ui-e2e-tests` failure -> created https://issues.redhat.com/browse/ROX-16641.

`pull-ci-stackrox-stackrox-master-ocp-4-13-operator-e2e-tests`: `kuttl` started after >5 hours since the test start and k8s api server was gone by then. Not sure what happened in the main log with
```
pod "operator-e2e-tests-stackrox-e2e" failed: pod pending for more than 30m0s: container "sidecar" has not started in 30m0.000874355s
```
OSCI flake?

`pull-ci-stackrox-stackrox-release-x.y-ocp-4-10-qa-e2e-tests`: `ERROR: There is no job script for ocp-qa-e2e-tests`. @gavin-stackrox please force-push `release-x.y` branch to the current head of `master`.

`pull-ci-stackrox-stackrox-release-x.y-ocp-4-12-operator-e2e-tests` - same.

`pull-ci-stackrox-stackrox-release-x.y-ocp-4-12-fips-qa-e2e-tests` - same.

`pull-ci-stackrox-stackrox-release-x.y-ocp-4-10-operator-e2e-test` - same.

`pull-ci-stackrox-stackrox-master-ocp-4-13-ui-e2e-tests` same ROX-16641 as `periodic-ci-stackrox-stackrox-master-ocp-4-13-weekly-ui-e2e-tests`.

`pull-ci-stackrox-stackrox-release-x.y-ocp-4-12-qa-e2e-tests` needs `release-x.y` branch force-push.

2023-04-21 15:14 UTC, gavin-stackrox commented
/pj-rehearse

2023-04-21 22:48 UTC, gavin-stackrox commented
/pj-rehearse

2023-04-24 17:29 UTC, BradLugo requested changes

2023-04-24 18:09 UTC, gavin-stackrox commented on ci-operator/jobs/stackrox/stackrox/stackrox-stackrox-release-x.y-presubmits.yaml
> +    always_run: false
I think we can leave it as optional for PRs against releases. We might want to add a `run_if_changed` set but my assumption is that the release engineer that is opening PRs will choose what to `/test`. These will always run for postsubmits.

2023-04-24 19:14 UTC, BradLugo commented on ci-operator/jobs/stackrox/stackrox/stackrox-stackrox-release-x.y-presubmits.yaml
> +    always_run: false
If that's the case, we should update https://docs.engineering.redhat.com/display/StackRox/ACS+-+OpenShift+version+support and https://docs.engineering.redhat.com/pages/viewpage.action?spaceKey=StackRox&title=Upstream+Release+Automation with this information

2023-04-25 16:40 UTC, gavin-stackrox commented on ci-operator/jobs/stackrox/stackrox/stackrox-stackrox-release-x.y-presubmits.yaml
> +    always_run: false
> If that's the case, we should update https://docs.engineering.redhat.com/display/StackRox/ACS+-+OpenShift+version+support and https://docs.engineering.redhat.com/pages/viewpage.action?spaceKey=StackRox&title=Upstream+Release+Automation with this information

Agreed. I will update the table(s) at the end of the version support doc and look over the release automation doc to see what needs to be added there.

2023-04-25 17:50 UTC, BradLugo approved these changes
/lgtm

2023-04-25 18:12 UTC, gavin-stackrox commented
/pj-rehearse ack

2023-04-25 21:08 UTC, BradLugo commented
/lgtm

2023-04-25 21:16 UTC, gavin-stackrox commented
/pj-rehearse ack

2023-04-25 21:16 UTC, BradLugo commented
/lgtm

2023-04-25 21:33 UTC, merged