OSSM-3731: Add api postsubmit jobs
openshift/release pull request #38733
Opened 2023-04-25 22:55 UTC by leoieggli

2023-04-26 02:55 UTC, leoieggli commented
/pj-rehearse

2023-04-26 18:43 UTC, leoieggli commented
/pj-rehearse

2023-05-03 15:06 UTC, yxun commented
/pj-rehearse pull-ci-maistra-api-maistra-2.2-api-update-istio-2-2

2023-05-03 15:38 UTC, yxun commented
/pj-rehearse pull-ci-maistra-api-maistra-2.2-api-update-istio-2-2

2023-05-03 19:45 UTC, yxun commented
I used a workaround to verify the job by copying the current latest api maistra-2.2 branch commit SHA and assigning it to the temporary var.
After review, I will remove the workaround in another commit for the PR.

2023-05-08 17:44 UTC, jwendell requested changes
LGTM.

Remove the workaround, add the postsubmit: true and remove an env variable from 2.4.

2023-05-08 17:44 UTC, jwendell commented on ci-operator/config/maistra/api/maistra-api-maistra-2.4.yaml
> +    export GOFLAGS="-mod=vendor"
remove this. 2.4 doesn't use vendor

2023-05-09 14:30 UTC, jwendell approved these changes

2023-05-09 14:58 UTC, merged