ROX-16723: add a job for operator tests on GKE
openshift/release pull request #38750
Opened 2023-04-26 08:48 UTC by porridge

I'm assuming this has no effect until invoked explicitly with `/test gke-operator-e2e-tests`, right?
And when invoked it will fail because there is no `stackrox/stackrox` counterpart for now? (This should be fine for the time being, while I work on that part.)

2023-04-26 08:50 UTC, porridge commented
/pj-rehearse skip

2023-04-26 09:35 UTC, porridge commented
So this part of the failure is expected...

```
ERROR: There is no job script for gke-operator-e2e-tests
INFO: Wed Apr 26 09:29:47 UTC 2023: Executing a general purpose exit trap for CI
Exit code is: 1
```
... because there is no script yet.

But I don't think this one is, any clues @gavin-stackrox ?
```
INFO: Wed Apr 26 09:29:47 UTC 2023: Finalizing a job record for this test run
/go/src/github.com/stackrox/stackrox/scripts/ci/metrics.sh: line 145: METRICS_JOB_ID: unbound variable
```

2023-04-27 04:57 UTC, porridge commented
So, can I please get and LGTM for this please? @gavin-stackrox

2023-04-27 16:37 UTC, gavin-stackrox requested changes
the job needs a manual change to not always run.

2023-04-27 16:37 UTC, gavin-stackrox commented on ci-operator/jobs/stackrox/stackrox/stackrox-stackrox-master-presubmits.yaml
> +    always_run: true
```suggestion
    always_run: false
```

2023-04-28 09:50 UTC, porridge commented
/pj-rehearse ack

2023-04-28 16:32 UTC, gavin-stackrox approved these changes
/lgtm

2023-04-28 16:56 UTC, merged