Onboard openstack-k8-operators/repo-setup repo
openshift/release pull request #39063
Opened 2023-05-05 14:36 UTC by son-vyas

2023-05-05 16:53 UTC, viroel requested changes

2023-05-05 16:53 UTC, viroel commented on ci-operator/config/openstack-k8s-operators/repo-setup/openstack-k8s-operators-repo-setup-master.yaml
> +tests:
We need to check which kind of jobs make sense to add here.
https://github.com/openstack-k8s-operators/repo-setup has no Makefile targets, and no golang code there.

2023-05-08 11:40 UTC, raukadah reviewed
Looks like a great start.

2023-05-08 11:40 UTC, raukadah commented on ci-operator/config/openstack-k8s-operators/repo-setup/openstack-k8s-operators-repo-setup-master.yaml
> +    from: src
We can drop this line.

2023-05-08 11:40 UTC, raukadah commented on ci-operator/config/openstack-k8s-operators/repo-setup/openstack-k8s-operators-repo-setup-master.yaml
> +  branch: master
branch: main

2023-05-08 11:40 UTC, raukadah commented on ci-operator/config/openstack-k8s-operators/repo-setup/OWNERS
> +- cedric
Based on https://github.com/openshift/release/pull/39063#issuecomment-1538184667, He needs to join openshift org. For timebeing , we can drop cedric from here.

2023-05-08 12:35 UTC, viroel commented on ci-operator/config/openstack-k8s-operators/repo-setup/openstack-k8s-operators-repo-setup-master.yaml
> +    pre-commit run --all-files --show-diff-on-failure
We first need to add a pre-commit configuration file to `repo-setup`  or it will be testing nothing.

2023-05-08 12:35 UTC, viroel commented on ci-operator/config/openstack-k8s-operators/repo-setup/openstack-k8s-operators-repo-setup-master.yaml
> +  branch: master
s/master/main

2023-05-08 14:34 UTC, viroel commented on ci-operator/config/openstack-k8s-operators/repo-setup/openstack-k8s-operators-repo-setup-master.yaml
this file needs to be renamed, fom ....repo-setup-master.yaml to ...repos-setup-main.yaml

2023-05-08 14:34 UTC, viroel commented on ci-operator/config/openstack-k8s-operators/repo-setup/openstack-k8s-operators-repo-setup-master.yaml
> +    pre-commit run --all-files --show-diff-on-failure
take a look on ci-framework one:
https://github.com/openstack-k8s-operators/ci-framework/blob/main/.pre-commit-config.yaml
we need to add in the repo-setup first

2023-05-08 14:34 UTC, viroel commented on ci-operator/jobs/openstack-k8s-operators/repo-setup/openstack-k8s-operators-repo-setup-master-presubmits.yaml
you will need to re-generate this file again, with make jobs
since you changed the branch to main, the file will need to be renamed also:
e.g: openstack-k8s-operators-repo-setup-main-presubmits.yaml

2023-05-09 11:16 UTC, viroel commented
/pj-rehearse pull-ci-openstack-k8s-operators-repo-setup-main-precommit-check

2023-05-10 10:18 UTC, son-vyas commented
/retest

2023-05-10 10:18 UTC, son-vyas commented
/pj-rehearse pull-ci-openstack-k8s-operators-repo-setup-main-precommit-check

2023-05-15 10:43 UTC, son-vyas commented
[soniya@myfedora repo-setup]$ git checkout -b fix_lint_issues
Switched to a new branch 'fix_lint_issues'
[soniya@myfedora repo-setup]$ pre-commit run --all-files
fix end of files.........................................................Passed
trim trailing whitespace.................................................Passed
mixed line ending........................................................Passed
check BOM - deprecated: use fix-byte-order-marker........................Passed
check that executables have shebangs.....................................Passed
check for merge conflicts................................................Passed
check for broken symlinks............................(no files to check)Skipped
debug statements (python)................................................Passed
check yaml...............................................................Passed
flake8...................................................................Passed
Ansible-lint.............................................................Passed
bashate..............................................(no files to check)Skipped


Locally tests are passing - https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_release/39063/rehearse-39063-pull-ci-openstack-k8s-operators-repo-setup-main-precommit-check/1656242686086090752

2023-05-15 10:44 UTC, son-vyas commented
/pj-rehearse pull-ci-openstack-k8s-operators-repo-setup-main-precommit-check

2023-05-15 13:05 UTC, viroel commented
/lgtm

2023-05-15 13:06 UTC, viroel commented
/pj-rehearse ack

Pre-commit job is passing now. Thanks Soniya.

2023-05-15 13:28 UTC, merged