Base for CSPI Jenkins Interop test job
openshift/release pull request #39216
Opened 2023-05-10 15:48 UTC by smatula

2023-05-26 15:59 UTC, smatula commented
/pj-rehearse

2023-06-07 15:32 UTC, smatula commented
/pj-rehearse

2023-06-28 14:00 UTC, calebevans requested changes
Just a couple of small things.

2023-06-28 14:00 UTC, calebevans commented on ci-operator/config/openshift/jenkins/openshift-jenkins-release-4.13__jenkins-hypershift4.13.yaml
> +           ]
Not sure if it will matter, but the indentation here doesn't match the opening bracket.

2023-06-28 14:00 UTC, calebevans commented on ci-operator/config/openshift/jenkins/openshift-jenkins-release-4.14__jenkins-ocp4.14-lp-interop.yaml
> +    RUN chgrp -R 0 /var && \
Looks like the permissions change on `/var` is missing in the Hypershift version of this image. Not sure if this is on purpose or if it needs to be put into the other image.

We may want to consider just writing a permanent Dockerfile for this so we don't have to maintain multiple files with `dockerfile_literal`.

2023-06-28 14:00 UTC, calebevans commented on ci-operator/config/openshift/jenkins/openshift-jenkins-release-4.13__jenkins-hypershift4.13.yaml
> +  cron: 0 6 * * 1
```suggestion
  cron: 0 10 * * 1
```
Per this message https://redhat-internal.slack.com/archives/C04PK4QPSR1/p1687889369616619

2023-06-28 20:48 UTC, Simranpal requested changes
Just comment about the operator step. You may need to remove the step.

2023-06-28 20:48 UTC, Simranpal commented on ci-operator/config/openshift/jenkins/openshift-jenkins-release-4.13__jenkins-hypershift4.13.yaml
> +          {"step": "install-operators", "failure_type": "all", "classification": "Infrastructure Provisioning - Operators", "jira_project": "LPTOCPCI"},
Is this step needed? As I don't see any `install-operators` step

I suppose there is no operator for this product,and you are just running the tests for hypershift.

2023-06-29 12:54 UTC, ascerra commented on ci-operator/config/openshift/jenkins/openshift-jenkins-release-4.13__jenkins-hypershift4.13.yaml
> +  remote_api: true
You can remove this line

2023-06-29 12:58 UTC, ascerra commented on ci-operator/config/openshift/jenkins/openshift-jenkins-release-4.14__jenkins-ocp4.14-lp-interop.yaml
> +  remote_api: true
You can remove this line

2023-06-29 17:28 UTC, ascerra commented
/lgtm

2023-06-29 17:28 UTC, ascerra commented
/pj-rehearse ack

2023-06-29 18:15 UTC, coreydaley commented
/approve

2023-06-29 18:34 UTC, merged