[stackrox] update builder/tester image to go1.19.9 for 3.73 + 3.74 release branches
openshift/release pull request #39423
Opened 2023-05-17 13:38 UTC by tommartensen

Combined PR for both 3.73 and 3.74 release branches.
To follow up with similar PRs with updates for 
* 4.0
* master, nightly, next release

2023-05-17 13:40 UTC, tommartensen commented
/pj-rehearse max

2023-05-17 15:59 UTC, tommartensen commented
/retest

2023-05-19 19:01 UTC, gavin-stackrox requested changes
The changes for *3.74* are good.

The changes for *3.73* however are not going to fly as the 0.3.50 -> 0.3.57 bumps Go from 1.18 to 1.19 which I don't expect is handled by the release branch. (Note: the fact that some OCP variants were already running 0.3.56 & 0.3.57 is a copy paste error that I'm trying to rectify here: https://github.com/openshift/release/pull/39523

2023-05-22 16:20 UTC, tommartensen commented
Split to https://github.com/openshift/release/pull/39547 and https://github.com/openshift/release/pull/39564

2023-05-22 16:20 UTC, closed without merging