ocm-terraform periodic defaluts to manged-oidc cluster
openshift/release pull request #39993
Opened 2023-06-05 08:49 UTC by AsherShoshan

2023-06-05 08:52 UTC, AsherShoshan commented
/pj-rehearse periodic-ci-terraform-redhat-terraform-provider-ocm-main-e2e-periodic

2023-06-05 09:12 UTC, AsherShoshan commented
/pj-rehearse periodic-ci-terraform-redhat-terraform-provider-ocm-main-e2e-periodic

2023-06-05 09:33 UTC, AsherShoshan commented
/pj-rehearse periodic-ci-terraform-redhat-terraform-provider-ocm-main-e2e-periodic

2023-06-05 10:44 UTC, AsherShoshan commented
/cc osherdp

2023-06-05 10:49 UTC, osherdp requested changes

2023-06-05 10:49 UTC, osherdp commented on ci-operator/config/terraform-redhat/terraform-provider-ocm/terraform-redhat-terraform-provider-ocm-main.yaml
> +      TF_FOLDER: ci/e2e/oidc_configuration/cluster_with_managed_oidc_config
I think we should rename the job name so it will be explicit and clear what flow it does. e.g.:
```
- as: managed-oidc-config-e2e-periodic
```

2023-06-05 11:53 UTC, osherdp requested changes

2023-06-05 11:53 UTC, osherdp commented on ci-operator/jobs/terraform-redhat/terraform-provider-ocm/terraform-redhat-terraform-provider-ocm-main-periodics.yaml
> -  reporter_config:
we need to preserve the slack notifications here

2023-06-05 11:53 UTC, osherdp commented
/retitle ocm-terraform periodic defaults to manged-oidc cluster

2023-06-05 12:08 UTC, osherdp approved these changes

2023-06-05 12:17 UTC, AsherShoshan commented
/pj-rehearse periodic-ci-terraform-redhat-terraform-provider-ocm-main-managed-oidc-config-e2e-periodic

2023-06-05 12:28 UTC, osherdp commented
/retitle ocm-terraform periodic defaults to managed-oidc cluster

2023-06-05 12:38 UTC, AsherShoshan commented
/pj-rehearse periodic-ci-terraform-redhat-terraform-provider-ocm-main-managed-oidc-config-e2e-periodic

2023-06-05 14:55 UTC, AsherShoshan commented
/pj-rehearse periodic-ci-terraform-redhat-terraform-provider-ocm-main-managed-oidc-config-e2e-periodic

2023-06-06 07:24 UTC, AsherShoshan commented
/pj-rehearse periodic-ci-terraform-redhat-terraform-provider-ocm-main-managed-oidc-config-e2e-periodic

2023-06-06 09:53 UTC, AsherShoshan commented
/pj-rehearse periodic-ci-terraform-redhat-terraform-provider-ocm-main-managed-oidc-config-e2e-periodic

2023-06-06 09:55 UTC, nirarg commented
@AsherShoshan its look good to me, please ping me when all verifications are passed to add the lgtm label

2023-06-06 12:07 UTC, AsherShoshan commented
/pj-rehearse periodic-ci-terraform-redhat-terraform-provider-ocm-main-managed-oidc-config-e2e-periodic

2023-06-06 15:41 UTC, AsherShoshan commented
/pj-rehearse periodic-ci-terraform-redhat-terraform-provider-ocm-main-managed-oidc-config-e2e-periodic

2023-06-06 20:26 UTC, osherdp approved these changes

2023-06-06 20:27 UTC, osherdp commented
/pj-rehearse ack

2023-06-06 20:46 UTC, merged