Add compliance CI to stackrox/stackrox repo
openshift/release pull request #41025
Opened 2023-07-06 15:40 UTC by rhmdnd

Add a job for running dedicated e2e compliance tests when compliance-related code is changed in stackrox/stackrox.

This change goes hand-in-hand with https://github.com/stackrox/stackrox/pull/6829

2023-07-07 16:03 UTC, gavin-stackrox commented
/uncc

2023-07-07 16:03 UTC, gavin-stackrox commented
/uncc @JoukoVirtanen @msugakov

2023-07-07 16:04 UTC, gavin-stackrox commented
/cc @gavin-stackrox

2023-07-07 16:05 UTC, rhmdnd commented
Once https://github.com/stackrox/stackrox/pull/6829 merges we can start to rehearse the job here (using `pj-rehearse`)

2023-07-07 20:28 UTC, rhmdnd commented
/retest

2023-07-07 22:11 UTC, rhmdnd commented
/pj-rehearse

2023-07-13 20:51 UTC, rhmdnd commented
/pj-rehearse

2023-07-14 03:07 UTC, rhmdnd commented
/pj-rehearse pull-ci-stackrox-stackrox-master-ocp-4-10-compliance-e2e-tests

2023-07-18 21:36 UTC, rhmdnd commented
/pj-rehearse pull-ci-stackrox-stackrox-master-ocp-4-10-compliance-e2e-tests

2023-07-18 21:38 UTC, rhmdnd commented
The rehearsal jobs are failing consistently with:

```
 INFO: Thu Jul 13 21:46:05 UTC 2023: ocp-compliance-e2e-tests will run because this is an openshift/release PR
ERROR: There is no job script for ocp-compliance-e2e-tests 
```

Which is interesting given we landed the script in stackrox with https://github.com/stackrox/stackrox/commit/f0a51597676fdde7e5bd638b215e154af16bb24c

2023-07-18 21:57 UTC, rhmdnd commented
> The rehearsal jobs are failing consistently with:
> 
> ```
> INFO: Thu Jul 13 21:46:05 UTC 2023: ocp-compliance-e2e-tests will run because this is an openshift/release PR
> ERROR: There is no job script for ocp-compliance-e2e-tests 
> ```
> 
> Which is interesting given we landed the script in stackrox with [stackrox/stackrox@f0a5159](https://github.com/stackrox/stackrox/commit/f0a51597676fdde7e5bd638b215e154af16bb24c)
> 
> Rebasing this PR to make sure we're really using the latest master branch of stackrox. Otherwise - this job should be getting invoked through https://github.com/stackrox/stackrox/blob/master/.openshift-ci/dispatch.sh#L56-L62.

Actually - the `release-x.y` CI is failing as expected since the script didn't exist there, yet.

@gavin-stackrox just rebased the `release-x.y` branch on master, so that will probably help.

https://github.com/stackrox/stackrox/blob/release-x.y/scripts/ci/jobs/ocp_compliance_e2e_tests.py

2023-07-18 21:57 UTC, rhmdnd commented
/pj-rehearse pull-ci-stackrox-stackrox-release-x.y-ocp-4-10-compliance-e2e-tests

2023-07-18 21:59 UTC, gavin-stackrox requested changes

2023-07-18 21:59 UTC, gavin-stackrox commented on ci-operator/jobs/stackrox/stackrox/stackrox-stackrox-master-postsubmits.yaml
> +    max_concurrency: 1
```suggestion
    max_concurrency: 6
```

2023-07-18 21:59 UTC, gavin-stackrox commented on ci-operator/jobs/stackrox/stackrox/stackrox-stackrox-master-postsubmits.yaml
> +    max_concurrency: 1
```suggestion
    max_concurrency: 6
```

2023-07-18 22:13 UTC, rhmdnd commented
/pj-rehearse pull-ci-stackrox-stackrox-master-ocp-4-10-compliance-e2e-tests
/pj-rehearse pull-ci-stackrox-stackrox-master-ocp-4-13-compliance-e2e-tests
/pj-rehearse pull-ci-stackrox-stackrox-release-x.y-ocp-4-10-compliance-e2e-tests
/pj-rehearse pull-ci-stackrox-stackrox-release-x.y-ocp-4-13-compliance-e2e-tests

2023-07-18 23:39 UTC, rhmdnd commented
/pj-rehearse pull-ci-stackrox-stackrox-release-x.y-ocp-4-13-compliance-e2e-tests
/pj-rehearse pull-ci-stackrox-stackrox-master-ocp-4-13-compliance-e2e-tests

2023-07-19 13:18 UTC, rhmdnd commented
/pj-rehearse pull-ci-stackrox-stackrox-master-ocp-4-13-compliance-e2e-tests

2023-07-19 13:45 UTC, rhmdnd commented
Running the last rehearsal job and this should be good to go.

2023-07-19 15:45 UTC, gavin-stackrox approved these changes
/lgtm
/honk

2023-07-19 16:13 UTC, merged