debuggin SOS reports from nodes
openshift/release pull request #41220
Opened 2023-07-13 07:48 UTC by eifrach

2023-07-13 07:50 UTC, eifrach commented
/pj-rehearse pull-ci-openshift-assisted-service-master-edge-e2e-ai-operator-ztp-compact-day2-masters

2023-07-13 14:55 UTC, eifrach commented
/retest

2023-07-13 14:59 UTC, eifrach commented
/pj-rehearse pull-ci-openshift-assisted-service-master-edge-e2e-ai-operator-ztp-compact-day2-masters

2023-07-13 15:09 UTC, eifrach commented
/retest

2023-07-14 11:33 UTC, eifrach commented
/retest

2023-07-16 06:35 UTC, eifrach commented
/retest

2023-07-16 06:49 UTC, eifrach commented
/pj-rehearse pull-ci-openshift-assisted-service-master-edge-e2e-ai-operator-ztp-compact-day2-masters

2023-07-16 11:58 UTC, eifrach commented
/pj-rehearse pull-ci-openshift-assisted-service-master-edge-e2e-ai-operator-ztp-compact-day2-masters

2023-07-17 06:10 UTC, eifrach commented
/pj-rehearse pull-ci-openshift-assisted-installer-master-edge-e2e-ai-operator-ztp

2023-07-17 06:31 UTC, eifrach commented
/pj-rehearse pull-ci-openshift-assisted-service-release-ocm-2.8-e2e-ai-operator-ztp-3masters

2023-07-17 09:29 UTC, eifrach commented
/pj-rehearse pull-ci-openshift-assisted-service-release-ocm-2.8-e2e-ai-operator-ztp-3masters

2023-07-17 09:39 UTC, eifrach commented
/pj-rehearse pull-ci-openshift-assisted-installer-master-edge-e2e-ai-operator-ztp

2023-07-17 13:33 UTC, eifrach commented
/pj-rehearse pull-ci-openshift-assisted-installer-master-edge-e2e-ai-operator-ztp

2023-07-18 06:21 UTC, eifrach commented
/pj-rehearse pull-ci-openshift-assisted-installer-master-edge-e2e-ai-operator-ztp

2023-07-18 09:04 UTC, eifrach commented
/pj-rehearse pull-ci-openshift-assisted-installer-master-edge-e2e-ai-operator-ztp

2023-07-18 09:46 UTC, eifrach commented
/pj-rehearse pull-ci-openshift-assisted-installer-master-edge-e2e-ai-operator-ztp

2023-07-18 12:33 UTC, eifrach commented
/pj-rehearse pull-ci-openshift-assisted-installer-master-edge-e2e-ai-operator-ztp

2023-07-19 06:45 UTC, eifrach commented
/pj-rehearse pull-ci-openshift-assisted-installer-master-edge-e2e-ai-operator-ztp

2023-07-19 11:59 UTC, eifrach commented
/pj-rehearse pull-ci-openshift-assisted-installer-master-edge-e2e-ai-operator-ztp

2023-07-20 07:00 UTC, eifrach commented
/pj-rehearse pull-ci-openshift-assisted-installer-master-edge-e2e-ai-operator-ztp

2023-07-20 13:24 UTC, eifrach commented
/pj-rehearse pull-ci-openshift-assisted-installer-master-edge-e2e-ai-operator-ztp

2023-07-20 16:28 UTC, eifrach commented
/retest

2023-07-20 16:34 UTC, eifrach commented
/pj-rehearse pull-ci-openshift-assisted-installer-master-edge-e2e-ai-operator-ztp

2023-07-23 06:46 UTC, eifrach commented
/pj-rehearse pull-ci-openshift-assisted-installer-master-edge-e2e-ai-operator-ztp

2023-07-23 09:48 UTC, eifrach commented
/pj-rehearse pull-ci-openshift-assisted-installer-master-edge-e2e-ai-operator-ztp

2023-07-26 10:51 UTC, eifrach commented
checking

2023-08-07 12:02 UTC, eifrach commented
/pj-rehearse auto-ack

2023-08-08 07:15 UTC, eifrach commented
/pj-rehearse pull-ci-openshift-assisted-installer-master-edge-e2e-ai-operator-ztp

2023-08-08 10:02 UTC, eifrach commented
/pj-rehearse auto-ack

2023-08-08 13:08 UTC, adriengentil requested changes
some nits, can you also add the jira ticket to the title of the PR?

2023-08-08 13:08 UTC, adriengentil commented on ci-operator/step-registry/assisted/baremetal/operator/gather/assisted-baremetal-operator-gather-commands.sh
> +          jq """. += [{ \"host\" : \"$_HOST\", \"address\" : \"$_IP\" }]""" < $TMP_HOSTFILE > $HOSTFILE
```suggestion
          jq """. += [{ \"host\" : \"${_HOST}\", \"address\" : \"${_IP}\" }]""" < ${TMP_HOSTFILE} > ${HOSTFILE}
```
nit: to be consistent with the rest of the file

2023-08-08 13:08 UTC, adriengentil commented on ci-operator/step-registry/assisted/baremetal/operator/gather/assisted-baremetal-operator-gather-commands.sh
> +      echo [] > ${TMP_HOSTFILE}
```suggestion
      echo "[]" > ${TMP_HOSTFILE}
```
I think it's clearer and not some shell shenanigans

2023-08-08 13:08 UTC, adriengentil commented on ci-operator/step-registry/assisted/baremetal/operator/gather/assisted-baremetal-operator-gather-commands.sh
> +          cat "$HOSTFILE" > "$TMP_HOSTFILE"
```suggestion
          cat "${HOSTFILE}" > "${TMP_HOSTFILE}"
```

2023-08-08 13:08 UTC, adriengentil commented on ci-operator/step-registry/assisted/baremetal/operator/gather/assisted-baremetal-operator-gather-commands.sh
> +        export REPORT_PATH="${SOS_BASEDIR}/$_HOST"
```suggestion
        _HOST=$(echo ${ITEM} | jq -r .host )
        _IP=$(echo ${ITEM} | jq -r .address )

        export REPORT_PATH="${SOS_BASEDIR}/${_HOST}"
```

2023-08-08 13:08 UTC, adriengentil commented on ci-operator/step-registry/assisted/baremetal/operator/gather/assisted-baremetal-operator-gather-commands.sh
> +        timeout -s 9 30m ssh -o StrictHostKeyChecking=off -l core $_IP REPORT_PATH="${SOS_BASEDIR}/$_HOST" bash - << "EOF"
```suggestion
        timeout -s 9 30m ssh -o StrictHostKeyChecking=off -l core $_IP REPORT_PATH="${SOS_BASEDIR}/${_HOST}" bash - << "EOF"
```

2023-08-08 13:13 UTC, eifrach commented
/cc @adriengentil 
/cc @osherdp

2023-08-08 14:20 UTC, eifrach commented
/pj-rehearse pull-ci-openshift-assisted-installer-master-edge-e2e-ai-operator-ztp

2023-08-08 14:28 UTC, eifrach commented
/pj-rehearse pull-ci-openshift-assisted-installer-master-edge-e2e-ai-operator-ztp

2023-08-09 07:48 UTC, adriengentil reviewed
LGTM, just a nit

2023-08-09 07:48 UTC, adriengentil commented on ci-operator/step-registry/assisted/baremetal/operator/gather/assisted-baremetal-operator-gather-commands.sh
> +            sudo chmod -R +r "${REPORT_PATH}"
```suggestion
           sudo chmod -R +r "${REPORT_PATH}"
```
nit, looks like it's not aligned

2023-08-09 07:50 UTC, adriengentil approved these changes

2023-08-09 09:17 UTC, eifrach commented
/rehearsals-ack

2023-08-09 12:46 UTC, eifrach commented
/cc @osherdp

2023-08-09 13:33 UTC, adriengentil commented
/pj-rehearse ack

2023-08-09 13:42 UTC, merged