Add KUTTL job trigger for Manila
openshift/release pull request #41363
Opened 2023-07-18 11:23 UTC by fmount

We have patches in manila-operator [1] and the openstack related tools [2] that are supposed to bring support to kuttl tests.
This change adds the missing bits to trigger kuttl tests via prow jobs.

[1] https://github.com/openstack-k8s-operators/manila-operator/pull/98
[2] https://github.com/openstack-k8s-operators/install_yamls/pull/216

2023-07-18 11:24 UTC, fmount commented
FYI @vhariria @gouthampacha we'll merge this once we have everything in place in the manila-operator repo.

2023-07-27 18:57 UTC, viroel requested changes
Thanks Francesco, see coments inline, since we recently migrate OCP cluster to 4.12.

2023-07-27 19:40 UTC, gouthampacha commented on ci-operator/config/openstack-k8s-operators/manila-operator/openstack-k8s-operators-manila-operator-main.yaml
> +    version: "4.10"
++

2023-07-27 19:41 UTC, gouthampacha commented on ci-operator/jobs/openstack-k8s-operators/manila-operator/openstack-k8s-operators-manila-operator-main-presubmits.yaml
> +    always_run: true
the tests have merged now: https://github.com/openstack-k8s-operators/manila-operator/pull/98

2023-07-27 19:50 UTC, gouthampacha commented
Duplicating this PR to rehearse the job with recent CI changes: https://github.com/openshift/release/pull/41744/

2023-07-31 13:36 UTC, closed without merging

2023-07-31 13:37 UTC, fmount commented
Closed in favor of: https://github.com/openshift/release/pull/41744