Adding network-perf step across our configs
openshift/release pull request #41453
Opened 2023-07-19 19:44 UTC by jtaleric

Adding network-perf

2023-07-19 19:47 UTC, jtaleric commented
/pj-rehearse pull-ci-openshift-qe-ocp-qe-perfscale-ci-main-rosa-4.12-stable-prod-perfscale-rosa-singleaz-network-perf-2nodes	periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-rosa-4.13-nightly-perfscale-rosa-singleaz-network-perf-2nodes	periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-rosa-4.12-nightly-perfscale-rosa-singleaz-network-perf-2nodes periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-ocp-qe-perfscale-ci-tests-net-perf

2023-07-19 20:05 UTC, svetsa-rh requested changes

2023-07-19 20:05 UTC, svetsa-rh commented on ci-operator/config/openshift-qe/ocp-qe-perfscale-ci/openshift-qe-ocp-qe-perfscale-ci-main__rosa-4.13-nightly.yaml
> +- as: perfscale-rosa-singleaz-network-perf-2nodes
Same here. "periodic" at end of test name.

2023-07-19 20:10 UTC, svetsa-rh commented
/pj-rehearse periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-rosa-4.13-nightly-perfscale-rosa-singleaz-network-perf-2nodes periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-rosa-4.12-nightly-perfscale-rosa-singleaz-network-perf-2nodes

2023-07-19 20:32 UTC, svetsa-rh commented
@jtaleric Can we add hcp tests too?

2023-07-19 20:54 UTC, jtaleric commented
/test ci-operator-config-metadata

2023-07-19 21:00 UTC, jtaleric commented
/pj-rehearse pull-ci-openshift-qe-ocp-qe-perfscale-ci-main-rosa-4.12-stable-prod-perfscale-rosa-singleaz-network-perf-2nodes periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-rosa-4.12-stable-prod-perfscale-rosa-hcp-1zone-network-perf-2nodes-periodic periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-rosa-4.12-nightly-perfscale-rosa-singleaz-network-perf-2nodes-periodic periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-ocp-qe-perfscale-ci-tests-net-perf periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-rosa-4.13-nightly-perfscale-rosa-singleaz-network-perf-2nodes-periodic periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-rosa-4.13-nightly-perfscale-rosa-hcp-1zone-network-perf-2nodes-periodic

2023-07-20 10:51 UTC, jtaleric commented
/pj-rehearse pull-ci-openshift-qe-ocp-qe-perfscale-ci-main-rosa-4.12-stable-prod-perfscale-rosa-singleaz-network-perf-2nodes periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-rosa-4.13-nightly-perfscale-rosa-hcp-1zone-network-perf-2nodes-periodic periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-rosa-4.12-nightly-perfscale-rosa-singleaz-network-perf-2nodes-periodic periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-rosa-4.12-stable-prod-perfscale-rosa-hcp-1zone-network-perf-2nodes-periodic

2023-07-20 16:32 UTC, jtaleric commented
/pj-rehearse periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-rosa-4.13-nightly-perfscale-rosa-hcp-1zone-network-perf-2nodes-periodic pull-ci-openshift-qe-ocp-qe-perfscale-ci-main-rosa-4.12-stable-prod-perfscale-rosa-singleaz-network-perf-2nodes

2023-07-20 20:33 UTC, svetsa-rh commented
@jtaleric I see that https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_release/41453/rehearse-41453-periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-rosa-4.13-nightly-perfscale-rosa-hcp-1zone-network-perf-2nodes-periodic/1682066376350502912 actually ran but failed at the end while deleting the stacks. So, we can ignore this failure for now.

Asking someone to help take a look here https://redhat-internal.slack.com/archives/CH76YSYSC/p1689885119584019?thread_ts=1670328469.221149&cid=CH76YSYSC

2023-07-20 21:18 UTC, svetsa-rh commented
/pj-rehearse pull-ci-openshift-qe-ocp-qe-perfscale-ci-main-rosa-4.12-stable-prod-perfscale-rosa-singleaz-network-perf-2nodes

2023-07-20 21:32 UTC, svetsa-rh commented on ci-operator/config/openshift-qe/ocp-qe-perfscale-ci/openshift-qe-ocp-qe-perfscale-ci-main__rosa-4.12-stable-prod.yaml
> +  cron: 0 7 * * 1
@jtaleric Do we want to run this in production on a cron basis for 4.12? Just want to make sure that it was not added here as periodic job accidentally.

2023-07-20 21:40 UTC, svetsa-rh reviewed
@jtaleric Pls see my comment regarding 4.12 prod network HCP test.

2023-07-31 11:07 UTC, jtaleric commented
/pj-rehearse pull-ci-openshift-qe-ocp-qe-perfscale-ci-main-rosa-4.12-stable-prod-perfscale-rosa-singleaz-network-perf-2nodes

2023-07-31 14:23 UTC, jtaleric commented
/pj-rehearse pull-ci-openshift-qe-ocp-qe-perfscale-ci-main-rosa-4.12-stable-prod-perfscale-rosa-singleaz-network-perf-2nodes

2023-08-09 13:15 UTC, closed without merging