vsphere-build02
openshift/release pull request #41604
Opened 2023-07-24 20:04 UTC by jcpowermac

2023-07-24 20:06 UTC, jcpowermac commented
```
cd to_directory_release
git pull --rebase upstream master
git checkout -b vsphere-build02
cd to_directory_ci_tools
git pull --rebase upstream master
go run ./cmd/cluster-init --create-pr=false --release-repo ../release --cluster-name vsphere-build02
go run ./cmd/cluster-init --create-pr=false --release-repo ../release --cluster-name vsphere-build02 --update
cd to_directory_release
make update
```

2023-08-25 19:01 UTC, bear-redhat requested changes

2023-08-25 19:01 UTC, bear-redhat commented on core-services/ci-secret-bootstrap/_config.yaml
> +    sa.pod-scaler.vsphere-build02.token.txt:
remove this

2023-08-25 19:01 UTC, bear-redhat commented on core-services/ci-secret-bootstrap/_config.yaml
> +  - vsphere-build02
remove this

2023-08-25 19:01 UTC, bear-redhat commented on ci-operator/jobs/openshift/release/openshift-release-master-periodics.yaml
> +- agent: kubernetes
remove this

2023-08-25 19:19 UTC, bear-redhat commented
/cc @hongkailiu 
The PR looks good to me now. Can you take another look?

2023-08-25 19:21 UTC, hongkailiu commented
Could we please name the cluster `vsphere02`? Simple and less-confusing with `build02`.

2023-08-25 19:33 UTC, jcpowermac commented
@hongkailiu renamed

2023-08-25 20:12 UTC, jcpowermac commented
/pj-rehearse pull-ci-openshift-release-master-vsphere02-dry

2023-08-25 20:26 UTC, jcpowermac commented
/pj-rehearse pull-ci-openshift-release-master-vsphere02-dry

2023-08-25 20:39 UTC, jcpowermac commented
@bear-redhat @hongkailiu anything else?

should `pull-ci-openshift-release-master-vsphere02-dry` do anything yet?

2023-08-26 13:09 UTC, jcpowermac commented
/pj-rehearse pull-ci-openshift-release-master-vsphere02-dry

2023-08-26 13:40 UTC, jcpowermac commented
@bear-redhat can you check the secret please. It still doesn't seem to be available.
```
The pod could not start because it could not mount the volume "build-farm-credentials": references non-existent secret key: sa.config-updater.vsphere02.config
```

2023-08-27 14:37 UTC, jcpowermac commented
/pj-rehearse pull-ci-openshift-release-master-vsphere02-dry

2023-08-28 12:13 UTC, jcpowermac commented
@hongkailiu @bear-redhat please review, see errors with secret.

2023-08-28 12:13 UTC, jcpowermac commented
/reopen

2023-08-29 14:27 UTC, bear-redhat commented
/pj-rehearse

2023-08-29 15:10 UTC, jcpowermac commented
/pj-rehearse ack

2023-08-29 15:10 UTC, bear-redhat commented
/approve

2023-08-29 15:12 UTC, bear-redhat commented
/approve

2023-08-29 15:56 UTC, jcpowermac commented
/retest-required

2023-08-29 16:27 UTC, jcpowermac commented
/retest-required

2023-08-29 17:01 UTC, bear-redhat commented
/retest

2023-08-29 18:17 UTC, bear-redhat commented
/retest

2023-08-29 18:30 UTC, merged

2023-08-30 10:17 UTC, jmguzik commented
@jcpowermac this PR is causing our dptp-controller-manager to fail. It also failed on postsubmits. I'll try to revert it.
cc @bear-redhat @hongkailiu