Jv rox 18537 switch e2e tests in stackrox to core bpf switch to core bpf
openshift/release pull request #41738
Opened 2023-07-27 17:34 UTC by JoukoVirtanen

## Description

Sets COLLECTION_METHOD to core_bpf for the CI jobs for which that is desired. A list is given below.

*PRs*
gke-qa-e2e-tests
gke-ui-e2e-tests
gke-nongroovy-e2e-tests
gke-sensor-integration-tests
gke-version-compatibility-tests
gke-race-condition-qa-e2e-tests
eks-qa-e2e-tests
osd-aws-qa-e2e-tests
osd-gcp-qa-e2e-tests
aro-qa-e2e-tests
rosa-qa-e2e-tests
aks-qa-e2e-tests
merge-gke-qa-e2e-tests
merge-gke-ui-e2e-tests
merge-gke-nongroovy-e2e-tests
merge-gke-sensor-integration-tests
powervs-qa-e2e-tests
nightly-powervs-qa-e2e-tests
ibmcloudz-qa-e2e-tests
nightly-ibmcloudz-qa-e2e-tests

ocp-4-10-qa-e2e-tests
ocp-4-10-sensor-integration-tests
ocp-4-10-ui-e2e-tests
ocp-4-10-compliance-e2e-tests
ocp-4-10-merge-qa-e2e-tests
ocp-4-10-merge-ui-e2e-tests
ocp-4-10-merge-compliance-e2e-tests

ocp-4-13-qa-e2e-tests
ocp-4-13-sensor-integration-tests
ocp-4-13-ui-e2e-tests
ocp-4-13-fips-qa-e2e-tests
ocp-4-13-pool-qa-e2e-tests
ocp-4-13-compliance-e2e-tests
ocp-4-13-merge-qa-e2e-tests
ocp-4-13-merge-compliance-e2e-tests

Nightly

The core_bpf collection method was recently released as a technical preview. In the next release it will be GA. In order to do that we need more confidence that it is working. E2e tests will be switched over to using core_bpf as the collection method. Some e2e tests will be kept as ebpf and the nightly CI runs will use both core_bpf and ebpf.

See the original issue in stackrox/collector

https://github.com/stackrox/collector/issues/1231

See the proposal for this work https://docs.google.com/document/d/1eS6W8yezfG0gf_o99XU7qTZ0iAWiGj54p8Y_uky9nFw/edit

## Related work

PR to set the default collection method to ebpf https://github.com/openshift/release/pull/41702

2023-07-27 18:42 UTC, JoukoVirtanen commented
/cc @BradLugo

2023-07-27 18:57 UTC, JoukoVirtanen commented
/hold

2023-07-27 23:06 UTC, JoukoVirtanen commented
/pj-rehearse max

2023-07-28 01:21 UTC, JoukoVirtanen commented
/pj-rehearse max

2023-07-28 17:38 UTC, BradLugo commented
/cc @BradLugo

2023-07-28 17:45 UTC, BradLugo requested changes
Same deal with the other PR; changing a couple `max_concurrency`s and we're good to go

2023-07-28 17:45 UTC, BradLugo commented on ci-operator/jobs/stackrox/stackrox/stackrox-stackrox-master-postsubmits.yaml
> +    max_concurrency: 1
```suggestion
    max_concurrency: 6
```

2023-07-28 17:51 UTC, BradLugo commented
To capture some context from our Slack discussion in case anyone comes across this PR:

---

**Brad:**
I could imagine myself being confused if if saw something like this:
```yaml
- as: gke-nongroovy-e2e-tests
  optional: true
  steps:
    env:
      COLLECTION_METHOD: core_bpf
    test:
    - ref: stackrox-e2e
- as: gke-operator-e2e-tests
  optional: true
  steps:
    test:
    - ref: stackrox-e2e
- as: ebpf-qa-e2e-tests
  optional: true
  steps:
    cluster_profile: aws
    env:
      TEST_SUITE: ocp-qa-e2e-tests
      COLLECTION_METHOD: ebpf
    test:
    - ref: stackrox-e2e
    workflow: ipi-aws
  timeout: 5h0m0s
```  
Unless there's a reason (which there totally could be that I'm not seeing), I think the jobs that use their names have the TEST_SUITE should all have the COLLECTION_METHOD the same, and anything that uses a different COLLECTION_METHOD should have that in the name

**Jouko**:
I made it so that all jobs that have ebpf in their names use the ebpf collection method. Otherwise they use the core_bpf collection method, or the collection method is not really something that applies to them.

---

Along with another discussion we had about not wanting to change the default `COLLECTION_METHOD` to `core_bpf` due to pre 4.0 release jobs, I agree with Jouko's response and implementation on this. In the future we can explore having `COLLECTION_METHOD: core_bpf` be the default but not at this time.

2023-07-28 17:51 UTC, BradLugo approved these changes
/lgtm

2023-07-28 18:41 UTC, JoukoVirtanen commented
/pj-rehearse max

2023-07-28 23:39 UTC, JoukoVirtanen commented
/pj-rehearse max

2023-07-31 18:45 UTC, gavin-stackrox commented
/lgtm

2023-07-31 21:22 UTC, BradLugo commented
/lgtm

2023-07-31 23:53 UTC, JoukoVirtanen commented
/test config

2023-08-01 00:02 UTC, JoukoVirtanen commented
/pj-rehearse max

2023-08-01 01:50 UTC, JoukoVirtanen commented
/pj-rehearse max

2023-08-01 21:21 UTC, JoukoVirtanen commented
/pj-rehearse max

2023-08-02 17:42 UTC, JoukoVirtanen commented
/pj-rehearse max

2023-08-02 18:21 UTC, gavin-stackrox approved these changes
/lgtm
/meow

2023-08-02 18:21 UTC, JoukoVirtanen commented
/unhold

2023-08-02 18:23 UTC, JoukoVirtanen commented
/pj-rehearse ack

2023-08-02 18:25 UTC, JoukoVirtanen commented
/hold

2023-08-02 21:51 UTC, BradLugo commented
/lgtm

2023-08-02 21:56 UTC, JoukoVirtanen commented
/unhold

2023-08-02 21:56 UTC, JoukoVirtanen commented
/pj-rehearse ack

2023-08-02 21:58 UTC, JoukoVirtanen commented
/hold

2023-08-02 21:59 UTC, merged