odf: remove the individual config files
openshift/release pull request #42155
Opened 2023-08-09 16:34 UTC by agarwal-mudit

Every repo should follow common set of rules.

2023-08-09 16:34 UTC, agarwal-mudit commented
/cc @nixpanic

2023-08-10 07:05 UTC, nixpanic commented
/lgtm

2023-08-10 07:17 UTC, nixpanic requested changes
Actually, this doesn't `/lgtm`. If the ``OWNERS` file is the only one remaining in the directory, remove the whole directory including the `OWNERS` file. The file is used form maintenance of that particular directory only, and hence is useless.

Don't confuse these `OWNERS` files in the openshift/release` repository with `OWNERS` files in the repository that contains the actual component/code.

2023-08-10 12:40 UTC, iamniting approved these changes

2023-08-10 12:57 UTC, merged