Add a step to prepare nodes for cert rotation
openshift/release pull request #42193
Opened 2023-08-10 10:20 UTC by vrutkovs

After installer is complete nodes are still using short lived certificates, which are rotated after 24 hours. This step rotates certificates on master so that nodes could be shut down immediately

2023-08-10 10:20 UTC, vrutkovs commented
/pj-rehearse

2023-08-10 11:53 UTC, vrutkovs commented
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.14-e2e-metal-ovn-ha-cert-rotation-shutdown-30d
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.14-e2e-metal-ovn-ha-cert-rotation-suspend-30d

2023-08-10 12:06 UTC, vrutkovs commented
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.14-e2e-metal-ovn-ha-cert-rotation-shutdown-30d
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.14-e2e-metal-ovn-ha-cert-rotation-suspend-30d
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.14-e2e-metal-ovn-ha-cert-rotation-shutdown-60d
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.14-e2e-metal-ovn-ha-cert-rotation-suspend-60d

2023-08-10 14:07 UTC, vrutkovs commented
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.14-e2e-metal-ovn-ha-cert-rotation-shutdown-30d
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.14-e2e-metal-ovn-ha-cert-rotation-suspend-30d

2023-08-10 15:38 UTC, vrutkovs commented
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.14-e2e-metal-ovn-ha-cert-rotation-shutdown-30d

2023-08-10 17:45 UTC, vrutkovs commented
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.14-e2e-metal-ovn-ha-cert-rotation-suspend-90d
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.14-e2e-metal-ovn-ha-cert-rotation-shutdown-30d

2023-08-10 18:46 UTC, vrutkovs commented
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.14-e2e-metal-ovn-ha-cert-rotation-shutdown-30d

2023-08-10 19:10 UTC, vrutkovs commented
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.14-e2e-metal-ovn-ha-cert-rotation-suspend-90d

2023-08-10 21:24 UTC, vrutkovs commented
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.14-e2e-metal-ovn-ha-cert-rotation-shutdown-30d
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.14-e2e-metal-ovn-ha-cert-rotation-suspend-90d

2023-08-11 05:41 UTC, vrutkovs commented
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.14-e2e-metal-ovn-ha-cert-rotation-shutdown-60d
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.14-e2e-metal-ovn-ha-cert-rotation-suspend-60d

2023-08-11 07:40 UTC, vrutkovs commented
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.14-e2e-metal-ovn-ha-cert-rotation-shutdown-30d
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.14-e2e-metal-ovn-ha-cert-rotation-suspend-30d

2023-08-11 09:45 UTC, vrutkovs commented
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.14-e2e-metal-ovn-ha-cert-rotation-shutdown-30d periodic-ci-openshift-release-master-nightly-4.14-e2e-metal-ovn-ha-cert-rotation-suspend-30d

2023-08-11 11:28 UTC, vrutkovs commented
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.14-e2e-metal-ovn-ha-cert-rotation-shutdown-30d periodic-ci-openshift-release-master-nightly-4.14-e2e-metal-ovn-ha-cert-rotation-suspend-30d

2023-08-11 13:11 UTC, vrutkovs commented
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.14-e2e-metal-ovn-ha-cert-rotation-shutdown-30d

2023-08-11 14:50 UTC, vrutkovs commented
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.14-e2e-metal-ovn-ha-cert-rotation-shutdown-30d periodic-ci-openshift-release-master-nightly-4.14-e2e-metal-ovn-ha-cert-rotation-suspend-30d

2023-08-11 14:58 UTC, vrutkovs commented
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.14-e2e-metal-ovn-ha-cert-rotation-shutdown-30d periodic-ci-openshift-release-master-nightly-4.14-e2e-metal-ovn-ha-cert-rotation-suspend-30d

2023-08-11 14:59 UTC, vrutkovs commented
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.14-e2e-metal-ovn-ha-cert-rotation-shutdown-60d /pj-rehearse periodic-ci-openshift-release-master-nightly-4.14-e2e-metal-ovn-ha-cert-rotation-suspend-60d

2023-08-11 14:59 UTC, vrutkovs commented
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.14-e2e-metal-ovn-ha-cert-rotation-shutdown-60d periodic-ci-openshift-release-master-nightly-4.14-e2e-metal-ovn-ha-cert-rotation-suspend-60d

2023-08-11 15:17 UTC, vrutkovs commented
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.14-e2e-metal-ovn-ha-cert-rotation-shutdown-30d periodic-ci-openshift-release-master-nightly-4.14-e2e-metal-ovn-ha-cert-rotation-suspend-30d periodic-ci-openshift-release-master-nightly-4.14-e2e-metal-ovn-ha-cert-rotation-shutdown-60d periodic-ci-openshift-release-master-nightly-4.14-e2e-metal-ovn-ha-cert-rotation-suspend-60d

2023-08-11 17:09 UTC, vrutkovs commented
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.14-e2e-metal-ovn-ha-cert-rotation-shutdown-30d periodic-ci-openshift-release-master-nightly-4.14-e2e-metal-ovn-ha-cert-rotation-suspend-30d

2023-08-11 18:57 UTC, vrutkovs commented
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.14-e2e-metal-ovn-ha-cert-rotation-shutdown-30d periodic-ci-openshift-release-master-nightly-4.14-e2e-metal-ovn-ha-cert-rotation-suspend-30d

2023-08-11 20:23 UTC, vrutkovs commented
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.14-e2e-metal-ovn-ha-cert-rotation-shutdown-30d periodic-ci-openshift-release-master-nightly-4.14-e2e-metal-ovn-ha-cert-rotation-suspend-30d

2023-08-11 21:56 UTC, vrutkovs commented
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.14-e2e-metal-ovn-ha-cert-rotation-shutdown-30d periodic-ci-openshift-release-master-nightly-4.14-e2e-metal-ovn-ha-cert-rotation-suspend-30d

2023-08-12 05:48 UTC, vrutkovs commented
/pj-rehearse

2023-08-12 08:34 UTC, vrutkovs commented
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.14-e2e-metal-ovn-ha-cert-rotation-suspend-30d

2023-08-12 11:11 UTC, vrutkovs commented
/pj-rehearse ack

2023-08-14 15:31 UTC, dinhxuanvu requested changes
Looking good. One nit.

2023-08-14 15:34 UTC, vrutkovs commented on ci-operator/step-registry/openshift/e2e/cert-rotation/prepare-for-shutdown/openshift-e2e-cert-rotation-prepare-for-shutdown-commands.sh
> +    k8s-app: kubelet-bootrap-cred-manager
Fixed

2023-08-14 16:41 UTC, dinhxuanvu approved these changes
/lgtm

2023-08-14 18:39 UTC, merged