HyperShift: add 'HCP' check
openshift/release pull request #42281
Opened 2023-08-14 10:24 UTC by LiangquanLi930

2023-08-14 10:27 UTC, LiangquanLi930 commented
/pj-rehearse pull-ci-openshift-cluster-storage-operator-release-4.13-e2e-hypershift-ovn-conformance

2023-08-14 11:45 UTC, bryan-cox approved these changes
/lgtm

2023-08-14 11:46 UTC, bryan-cox commented
/retitle HOSTEDCP-1120: HyperShift: add 'HCP' check

2023-08-14 13:26 UTC, LiangquanLi930 commented on ci-operator/step-registry/hypershift/azure/create/hypershift-azure-create-chain.yaml
> +      /usr/bin/hypershift create kubeconfig --namespace=clusters --name=${CLUSTER_NAME} >${SHARED_DIR}/nested_kubeconfig
Because for Azure, we currently do not have support, right? So, I just rolled back the code related to the Azure portion.

2023-08-14 14:52 UTC, csrwng commented
/approve

2023-08-14 15:08 UTC, bryan-cox approved these changes
/lgtm

2023-08-14 15:10 UTC, bryan-cox commented
/pj-rehearse pull-ci-openshift-cluster-storage-operator-release-4.13-e2e-hypershift-ovn-conformance

2023-08-14 15:28 UTC, LiangquanLi930 commented
/pj-rehearse pull-ci-openshift-cluster-storage-operator-release-4.13-e2e-hypershift-ovn-conformance

2023-08-14 16:20 UTC, bear-redhat requested changes

2023-08-14 16:20 UTC, bear-redhat commented on ci-operator/step-registry/hypershift/hostedcluster/create/hostedcluster/hypershift-hostedcluster-create-hostedcluster-commands.sh
> +  HCP_CLI="/usr/bin/hypershift"
please do not assume the path of the binary. It could change.

2023-08-14 16:25 UTC, sjenning commented
/hold
https://github.com/openshift/release/pull/42283 is reverted and we are waiting to convert any CI flows to `hcp`

2023-10-05 05:21 UTC, LiangquanLi930 commented
/close

2023-10-05 05:21 UTC, closed without merging