Jv rox 18829 switch gke ebpf race condition qa e2e tests to core bpf
openshift/release pull request #42327
Opened 2023-08-14 22:00 UTC by JoukoVirtanen

2023-08-14 22:01 UTC, JoukoVirtanen commented
/hold

2023-08-14 22:11 UTC, JoukoVirtanen commented
/pj-rehearse max

2023-08-15 03:03 UTC, JoukoVirtanen commented
/pj-rehearse max

2023-08-15 04:21 UTC, JoukoVirtanen commented
/pj-rehearse max

2023-08-15 15:07 UTC, JoukoVirtanen commented
/pj-rehearse pull-ci-stackrox-stackrox-release-x.y-gke-race-condition-qa-e2e-tests

2023-08-15 15:08 UTC, JoukoVirtanen commented
/retest

2023-08-15 16:23 UTC, gavin-stackrox requested changes

2023-08-15 16:23 UTC, gavin-stackrox commented on ci-operator/jobs/stackrox/stackrox/stackrox-stackrox-release-x.y-presubmits.yaml
> +    always_run: true
looks like this snuck in

2023-08-15 21:28 UTC, gavin-stackrox approved these changes
/lgtm

2023-08-15 21:36 UTC, JoukoVirtanen commented
/unhold

2023-08-15 21:37 UTC, JoukoVirtanen commented
/pj-rehearse ack

2023-08-15 22:26 UTC, merged