Added govulncheck to backplane CI
openshift/release pull request #42707
Opened 2023-08-26 06:45 UTC by Dee-6777

2023-08-26 06:45 UTC, Dee-6777 commented
/hold

2023-08-29 16:07 UTC, Dee-6777 commented
/unhold

2023-08-29 16:09 UTC, Dee-6777 commented
/retest

2023-08-31 05:53 UTC, samanthajayasinghe commented on ci-operator/jobs/openshift/backplane-cli/openshift-backplane-cli-main-presubmits.yaml
> +    rerun_command: /test govulncheck
Is it not `/test scan` ?

2023-08-31 09:57 UTC, Dee-6777 commented
/pj-rehearse pull-ci-openshift-backplane-cli-main-scan

2023-08-31 11:50 UTC, supreeth7 requested changes
This change is missing the job configuration.
You will need to run `make jobs` to generate Prow job configuration files out of ci-operator configuration files.

Suggestion: Try running `make jobs WHAT=openshift/backplane-cli` from the root of the repository to fix the issue.

2023-09-01 05:12 UTC, supreeth7 requested changes

2023-09-01 05:12 UTC, supreeth7 commented on ci-operator/config/openshift/backplane-cli/openshift-backplane-cli-main.yaml
> +    from: src
This should be an optional check

```suggestion
- as: scan
  commands: make scan
  container:
    from: src
  optional: true
```

2023-09-01 06:37 UTC, supreeth7 commented
/pj-rehearse
/hold

2023-09-01 06:43 UTC, supreeth7 requested changes

2023-09-01 06:43 UTC, supreeth7 commented on ci-operator/config/openshift/backplane-cli/openshift-backplane-cli-main.yaml
> +    from: src
This should be optional as stated earlier.

```suggestion
- as: scan
  commands: make scan
  container:
    from: src
  options: true
```

2023-09-01 07:19 UTC, supreeth7 requested changes
I've had a look at the Backplane CLI Makefile and I do not see govulncheck as a prerequisite. Please ensure you first install govulncheck before running `make scan` target. This change needs to happen in the Backplane CLI Makefile.

2023-09-01 11:07 UTC, supreeth7 commented
@Dee-6777 In the mentioned PR, you've added the make target which is correct. But the assumption here that `govulncheck` binary will already present isn't right, we have to first ensure that the binary is present, if not, we'll have to install (download) the binary and then run the `scan` make target.

For example. [here](https://github.com/openshift/backplane-cli/blob/main/Makefile#L77) we first ensure that `goreleaser` binary is present and then run the release target.

2023-09-03 15:05 UTC, Dee-6777 commented
@supreeth7 Thanks!
I carried out the changes in this [PR](https://github.com/openshift/backplane-cli/pull/198), it will first check if govulncheck binary present or not and then it will install

2023-09-04 05:09 UTC, supreeth7 commented
/pj-rehearse

2023-09-04 05:18 UTC, supreeth7 approved these changes
Rehearsals are ought to fail as they rehearse (force-test) the newly added CI step against the repository.

/pj-rehearse ack
/unhold
/lgtm

2023-09-04 10:48 UTC, supreeth7 commented
/pj-rehearse ack
/lgtm

2023-09-04 10:49 UTC, supreeth7 commented
/hold

2023-09-04 10:50 UTC, supreeth7 requested changes

2023-09-04 10:50 UTC, supreeth7 commented on ci-operator/config/openshift/backplane-cli/openshift-backplane-cli-main.yaml
> +    tag: golang-1.21
ubi-minimal/ubi base images don't have support for go1.21 yet, only till go1.20.
```suggestion
    tag: golang-1.20
```

2023-09-05 04:28 UTC, supreeth7 commented
/retest

2023-09-05 04:33 UTC, supreeth7 commented
/pj-rehearse auto-ack

2023-09-05 04:38 UTC, supreeth7 requested changes

2023-09-05 04:38 UTC, supreeth7 commented on ci-operator/config/openshift/backplane-cli/openshift-backplane-cli-main.yaml
> +    tag: golang-1.20
I reckon go1.20 tag isn't published yet as well, let's fallback to go1.19.
```suggestion
    tag: golang-1.19
```

2023-09-05 05:54 UTC, supreeth7 commented
/pj-rehearse auto-ack

2023-09-05 06:32 UTC, Dee-6777 commented
@supreeth7 I think the version of CI and the go version in bp-cli should be same to fix this error. Because go version in go.mod for bpcli is 1.21 and all test cases passed when I made CI version to 1.21

2023-09-05 07:30 UTC, supreeth7 commented
@Dee-6777 The rehearsals didn't pass back then as go1.21 image tag doesn't exist in the `release/openshift` registry.
The `make scan` is expected to fail as every release of go will have vulnerabilities that will be fixed in the next release, but we cannot keep bumping our base image to the latest go version and expect it to be a support base image in the OCP image registry.

I'd like to make the control over our CI easier, I'll address it in a couple of PRs soon.

2023-09-05 07:37 UTC, supreeth7 approved these changes
/lgtm
/pj-rehearse ack

2023-09-05 07:56 UTC, supreeth7 commented
/unhold
/retest

2023-09-05 10:08 UTC, supreeth7 commented
/retest

/pj-rehearse ack

2023-09-05 10:44 UTC, merged

2023-09-05 10:58 UTC, Dee-6777 commented
@supreeth7 for **ci/rehearse/openshift/backplane-cli/main/lint** to pass shall I created a new PR replacing all the ioutil to io