CI configured for 2023b branch
openshift/release pull request #42784
Opened 2023-08-29 12:50 UTC by dibryant

Fixes for #135 
https://github.com/opendatahub-io/notebooks/issues/135#issue-1782677134

Added Configuration for 2023b branch.

2023-08-29 13:37 UTC, atheo89 commented
/ok-to-test

2023-08-29 14:29 UTC, dibryant commented
make ci-operator-config

2023-08-30 01:17 UTC, harshad16 requested changes
lgtm
seems like some other parts were left out.

2023-08-30 01:17 UTC, harshad16 commented on ci-operator/config/opendatahub-io/notebooks/opendatahub-io-notebooks-2023b.yaml
> +\ No newline at end of file
```suggestion

```

This seems to be added by the editor, this shouldn't be here.

2023-08-30 14:00 UTC, atheo89 reviewed
Hi, I've noticed that the 2023b branch is currently out of sync with the latest commits. It seems that the build and test instructions for `runtimes/minimal/ubi8-python-3.8` and `runtimes/minimal/ubi9-python-3.9` are missing from the config file. To address this, could you perform a fetch and rebase? This would ensure that the branch incorporates the most recent changes.

2023-08-30 14:48 UTC, dibryant commented
pj-rehearse

2023-08-30 14:54 UTC, dibryant commented
/retest

2023-08-30 15:08 UTC, dibryant commented
/retest

2023-09-05 07:30 UTC, atheo89 commented
/retest-required

2023-09-12 12:58 UTC, harshad16 approved these changes
/lgtm
/approve
Thanks :100:

2023-09-12 12:59 UTC, harshad16 commented
/pj-rehearse

2023-09-12 13:52 UTC, harshad16 commented
/lgtm

2023-09-12 15:14 UTC, merged