[kubevirt-must-gather] Bump OCP version
openshift/release pull request #42972
Opened 2023-09-04 10:34 UTC by assafad

Bump OCP version used in kubevirt-must-gather CI to 4.13.

Signed-off-by: assafad <aadmi@redhat.com>

2023-09-04 10:35 UTC, assafad commented
@nunnatsa / @tiraboschi can you PTAL?

2023-09-04 11:04 UTC, machadovilaca commented
/ok-to-test

2023-09-04 11:52 UTC, assafad commented
/retest

2023-09-04 14:09 UTC, assafad commented
/pj-rehearse

2023-09-04 15:34 UTC, assafad commented
/pj-rehearse

2023-09-04 15:55 UTC, tiraboschi requested changes
Can you please also bump the golang builder image to rhel-9-golang-1.19-openshift-4.13 ?

2023-09-05 07:44 UTC, tiraboschi commented
/pj-rehearse max

2023-09-10 10:54 UTC, assafad commented
/pj-rehearse max

2023-09-12 13:38 UTC, assafad commented
/pj-rehearse pull-ci-kubevirt-must-gather-main-kubevirt-must-gather-e2e-azure

2023-09-13 07:26 UTC, assafad commented
/pj-rehearse

2023-09-13 08:24 UTC, assafad commented
/pj-rehearse pull-ci-kubevirt-must-gather-main-kubevirt-must-gather-e2e-gcp

2023-09-13 09:39 UTC, assafad commented
/pj-rehearse max

2023-09-13 12:22 UTC, tiraboschi commented
/approve

2023-09-13 12:22 UTC, tiraboschi approved these changes

2023-09-13 12:23 UTC, tiraboschi commented
/pj-rehearse ack

2023-09-13 13:08 UTC, assafad commented
/retest ci/prow/check-gh-automation

2023-09-13 13:12 UTC, assafad commented
/retest

2023-09-13 15:40 UTC, assafad commented
/test check-gh-automation

2023-09-13 16:01 UTC, merged