[PERFSCALE-2435] Add Control Plane Tests - HyperShift
openshift/release pull request #43004
Opened 2023-09-05 08:56 UTC by krishvoor

This PR adds control-plane tests for
medium & large scale tests in 4.13 & 4.14 HyperShift Versions

2023-09-05 08:56 UTC, krishvoor commented
/assign @jtaleric 
/assign @svetsa-rh 
/assign @paigerube14

2023-09-05 08:58 UTC, krishvoor commented
/pj-rehearse pull-ci-openshift-qe-ocp-qe-perfscale-ci-main-rosa-4.14-nightly-perfscale-rosa-hcp-multiaz-control-plane-120nodes

2023-09-05 16:57 UTC, jtaleric requested changes
compute type should be `m5.xlarge`

2023-09-05 16:57 UTC, jtaleric commented on ci-operator/config/openshift-qe/ocp-qe-perfscale-ci/openshift-qe-ocp-qe-perfscale-ci-main__rosa-4.13-nightly.yaml
> +      COMPUTE_MACHINE_TYPE: m5.2xlarge
m5.xlarge

2023-09-05 16:57 UTC, jtaleric commented on ci-operator/config/openshift-qe/ocp-qe-perfscale-ci/openshift-qe-ocp-qe-perfscale-ci-main__rosa-4.13-nightly.yaml
> +      COMPUTE_MACHINE_TYPE: m5.2xlarge
m5.xlarge

2023-09-05 16:57 UTC, jtaleric commented on ci-operator/config/openshift-qe/ocp-qe-perfscale-ci/openshift-qe-ocp-qe-perfscale-ci-main__rosa-4.14-nightly.yaml
> +      COMPUTE_MACHINE_TYPE: m5.2xlarge
m5.xlarge

2023-09-05 16:57 UTC, jtaleric commented on ci-operator/config/openshift-qe/ocp-qe-perfscale-ci/openshift-qe-ocp-qe-perfscale-ci-main__rosa-4.14-nightly.yaml
> +      COMPUTE_MACHINE_TYPE: m5.2xlarge
m5.xlarge

2023-09-11 19:51 UTC, krishvoor commented
> compute type should be `m5.xlarge`

updated- ptal!

2023-09-11 19:52 UTC, krishvoor commented
/pj-reherase ack

2023-09-11 19:53 UTC, krishvoor commented
/pj-rehearse ack

2023-09-11 19:54 UTC, krishvoor commented
/assign @dry923

2023-09-20 12:38 UTC, krishvoor commented
/pj-rehearse pull-ci-openshift-qe-ocp-qe-perfscale-ci-main-rosa-4.13-nightly-x86-perfscale-rosa-hcp-multiaz-control-plane-120nodes

2023-09-21 02:03 UTC, krishvoor commented
/pj-rehearse pull-ci-openshift-qe-ocp-qe-perfscale-ci-main-rosa-4.13-nightly-x86-perfscale-rosa-multiaz-cluster-density-v2-3nodes

2024-01-17 01:12 UTC, krishvoor commented
/reopen

2024-01-17 01:12 UTC, krishvoor commented
/remove-lifecycle rotten

2024-02-19 06:54 UTC, closed without merging