Update 4.14 ec tests to 4.15 ec
openshift/release pull request #44356
Opened 2023-10-13 17:04 UTC by svetsa-rh

Moving from 4.14 ec to 4.15 ec. Confirmed with Roshni.

2023-10-13 17:06 UTC, svetsa-rh commented
/assign @krishvoor

2023-10-13 17:18 UTC, krishvoor requested changes
Needs slack_reporter_config changes

2023-10-13 17:18 UTC, krishvoor commented on ci-operator/jobs/openshift-qe/ocp-qe-perfscale-ci/openshift-qe-ocp-qe-perfscale-ci-main-periodics.yaml
> +  name: periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-rosa-4.14-nightly-x86-perfscale-rosa-multiaz-node-density-cni-24nodes-periodic
Please slack's reporter config:
```
  reporter_config:
    slack:
      channel: '#ocp-qe-scale-ci-results'
      job_states_to_report:
      - success
      - failure
      - error
      report_template: '{{if eq .Status.State "success"}} :white_check_mark: Job *{{.Spec.Job}}*
        ended with *{{.Status.State}}*. <{{.Status.URL}}|View logs> :white_check_mark:
        {{else}} :warning:  Job *{{.Spec.Job}}* ended with *{{.Status.State}}*. <{{.Status.URL}}|View
        logs> :warning: {{end}}'
     
```

2023-10-13 17:18 UTC, krishvoor commented on ci-operator/jobs/openshift-qe/ocp-qe-perfscale-ci/openshift-qe-ocp-qe-perfscale-ci-main-periodics.yaml
> +  name: periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-rosa-4.15-ec-x86-perfscale-rosa-multiaz-control-plane-24nodes-periodic
Here as well, please add slack reporter_config

2023-10-13 17:18 UTC, krishvoor commented on ci-operator/jobs/openshift-qe/ocp-qe-perfscale-ci/openshift-qe-ocp-qe-perfscale-ci-main-periodics.yaml
> +  name: periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-rosa-4.15-ec-x86-perfscale-rosa-singleaz-data-path-2nodes-periodic
Here as well, please add slack reporter_config

2023-10-16 15:16 UTC, svetsa-rh commented
/pj-rehearse periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-rosa-4.15-ec-x86-perfscale-rosa-multiaz-node-density-heavy-24nodes-periodic periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-rosa-4.15-ec-x86-perfscale-rosa-singleaz-data-path-2nodes-periodic periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-rosa-4.15-ec-x86-perfscale-rosa-multiaz-control-plane-24nodes-periodic

2023-10-17 15:22 UTC, svetsa-rh commented
@krishvoor FYI, it turns out 4.15 ec is not available for Classic Rosa yet. Also, I am having rebase issues with this PR. Hence, I will close this PR and once we have support for 4.15 ec, will open a new PR.
For now, will continue to run the tests with 4.14 ec.

2023-10-17 15:22 UTC, closed without merging