wmco: remove ci-index-wmco-bundle job
openshift/release pull request #44558
Opened 2023-10-18 20:48 UTC by wgahnagl

stop building the ci-index for the wmco bundle as it's deprecated

2023-10-18 20:49 UTC, wgahnagl commented
/test pj-rehearse

2023-10-18 20:57 UTC, wgahnagl commented
/pj-rehearse

2023-10-18 21:25 UTC, aravindhp commented
/pj-rehearse abort

2023-10-18 21:26 UTC, aravindhp commented
/pj-rehearse ci/rehearse/openshift/windows-machine-config-operator/master/ci-bundle-wmco-bundle

2023-10-18 21:27 UTC, aravindhp commented
/pj-rehearse ci/rehearse/openshift/windows-machine-config-operator/master/images

2023-10-18 21:28 UTC, aravindhp commented
/pj-rehearse pull-ci-openshift-windows-machine-config-operator-master-ci-bundle-wmco-bundle pull-ci-openshift-windows-machine-config-operator-master-images

2023-10-19 14:48 UTC, sebsoto commented
/pj-rehearse pull-ci-openshift-windows-machine-config-operator-master-ci-bundle-wmco-bundle pull-ci-openshift-windows-machine-config-operator-master-images

2023-10-19 14:49 UTC, aravindhp requested changes

2023-10-19 14:49 UTC, aravindhp commented on ci-operator/config/openshift/windows-machine-config-operator/openshift-windows-machine-config-operator-release-4.15.yaml
> +    skip_building_index: true
This is not needed

2023-10-19 14:49 UTC, aravindhp commented on ci-operator/config/openshift/windows-machine-config-operator/openshift-windows-machine-config-operator-release-4.16.yaml
> +    skip_building_index: true
This is not needed

2023-10-20 14:44 UTC, wgahnagl commented
/test prow-config

2023-10-20 15:05 UTC, wgahnagl commented
/test config

2023-10-20 15:55 UTC, wgahnagl commented
/pj-rehearse pull-ci-openshift-windows-machine-config-operator-master-images

2023-10-20 17:24 UTC, wgahnagl commented
/pj-rehearse pull-ci-openshift-windows-machine-config-operator-release-4.11-images pull-ci-openshift-windows-machine-config-operator-release-4.12-images pull-ci-openshift-windows-machine-config-operator-release-4.13-images pull-ci-openshift-windows-machine-config-operator-release-4.14-images

2023-10-20 19:01 UTC, aravindhp approved these changes
/lgtm

2023-10-20 19:10 UTC, wgahnagl commented
/pj-rehearse auto-ack

2023-10-20 19:32 UTC, wgahnagl commented
/pj-rehearse abort

2023-10-20 19:33 UTC, wgahnagl commented
/pj-rehearse pull-ci-openshift-windows-machine-config-operator-master-ci-bundle-wmco-bundle pull-ci-openshift-windows-machine-config-operator-release-4.11-ci-bundle-wmco-bundle pull-ci-openshift-windows-machine-config-operator-release-4.12-ci-bundle-wmco-bundle pull-ci-openshift-windows-machine-config-operator-release-4.13-ci-bundle-wmco-bundle pull-ci-openshift-windows-machine-config-operator-release-4.15-ci-bundle-wmco-bundle

2023-10-20 19:45 UTC, wgahnagl commented
/pj-rehearse pull-ci-openshift-windows-machine-config-operator-release-4.14-ci-bundle-wmco-bundle

2023-10-21 15:54 UTC, aravindhp commented
/pj-rehearse pull-ci-openshift-windows-machine-config-operator-master-aws-e2e-upgrade

2023-10-21 15:57 UTC, aravindhp commented
/pj-rehearse pull-ci-openshift-windows-machine-config-operator-master-vsphere-e2e-upgrade

2023-10-21 22:53 UTC, aravindhp commented
/pj-rehearse pull-ci-openshift-windows-machine-config-operator-master-vsphere-e2e-upgrade

2023-10-22 01:08 UTC, aravindhp commented
/pj-rehearse ack

The vSphere upgrade job is failing in the expected manner in "run bundle". However I am seeing the issue this PR is attempting to fix with the `security` job now that it is marked as required. So I suspect this PR just transfers the issue to the `ci-bundle-wmco-bundle` job. But lets get this merged given we do need to skip building the index and then figure out how to move forward.

2023-10-22 01:36 UTC, merged