add ci-operator release file with fast tag and add periodical builds
openshift/release pull request #45265
Opened 2023-11-03 13:38 UTC by rpancham

Add ci-operator release file with fast tag and added the periodical builds
[246](https://github.com/opendatahub-io/modelmesh-serving/issues/246)

2023-11-03 14:50 UTC, Xaenalt commented
/ok-to-test

2023-11-03 16:02 UTC, Xaenalt requested changes

2023-11-03 16:02 UTC, Xaenalt commented on ci-operator/config/opendatahub-io/openvino_model_server/opendatahub-io-openvino_model_server-2023.1-main.yaml
> +  cron: 0 0 * * 0
It's looking like the cron job conflicts with the postsubmit job. Let's delete this cron line and add a third task of the form:

```
- as: nightly-image-mirror
  cron: 0 0 * * 0 ?
  steps:
    dependencies:
      SOURCE_IMAGE_REF: caikit-tgis-serving
    env:
      IMAGE_REPO: caikit-tgis-serving
      RELEASE_VERSION: rhods-1.31
    workflow: red-hat-data-services-ci-image-mirror
```

Likely needs an update to the same values here, etc. Would need for both release and main

2023-11-03 16:02 UTC, Xaenalt commented on ci-operator/config/opendatahub-io/openvino_model_server/opendatahub-io-openvino_model_server-2023.1-release.yaml
> +  cron: 0 0 * * 0
Same changes here

2023-11-06 17:47 UTC, Xaenalt commented
/pj-rehearse

2023-11-07 07:55 UTC, rpancham commented
/pj-rehearse

2023-11-07 09:06 UTC, rpancham commented
/pj-rehearse pull-ci-opendatahub-io-openvino_model_server-2023.1-main-pr-image-mirror
/pj-rehearse pull-ci-opendatahub-io-openvino_model_server-2023.1-release-images
/pj-rehearse pull-ci-opendatahub-io-openvino_model_server-2023.1-main-nightly-images
/pj-rehearse pull-ci-opendatahub-io-openvino_model_server-2023.1-release-nightly-images

2023-11-07 12:49 UTC, rpancham commented
/pj-rehearse
/pj-rehearse pull-ci-opendatahub-io-openvino_model_server-2023.1-main-pr-image-mirror
/pj-rehearse pull-ci-opendatahub-io-openvino_model_server-2023.1-release-images
/pj-rehearse pull-ci-opendatahub-io-openvino_model_server-2023.1-main-nightly-images
/pj-rehearse pull-ci-opendatahub-io-openvino_model_server-2023.1-release-nightly-images

2023-11-07 14:50 UTC, Xaenalt commented
/pj-rehearse

2023-11-09 14:36 UTC, rpancham commented
/pj-rehearse

2023-11-10 10:34 UTC, rpancham commented
/pj-rehearse pull-ci-opendatahub-io-openvino_model_server-main-images

2023-11-10 14:26 UTC, Xaenalt commented
/pj-rehearse ack

2023-11-10 14:26 UTC, Xaenalt approved these changes

2023-11-10 15:03 UTC, merged