Update GPU operator CI following 4.14 GA
openshift/release pull request #45316
Opened 2023-11-06 10:14 UTC by empovit

2023-11-06 11:08 UTC, empovit commented
/ok-to-test

2023-11-06 12:07 UTC, empovit commented
/rehearse

2023-11-06 13:51 UTC, empovit commented
/rehearsals

2023-11-07 08:30 UTC, mresvanis commented
/pj-rehearse

2023-11-07 08:31 UTC, mresvanis commented
/lgtm
/hold

2023-11-08 15:42 UTC, empovit commented
/rehearsals-ack

2023-11-08 15:50 UTC, empovit commented
/pj-rehearse ack

2023-11-09 08:36 UTC, sagidayan requested changes

2023-11-09 08:36 UTC, sagidayan commented on ci-operator/jobs/rh-ecosystem-edge/ci-tools-nvidia-gpu-operator/rh-ecosystem-edge-ci-tools-nvidia-gpu-operator-main-presubmits.yaml
> +    always_run: true
We dont want this to run always

2023-11-09 08:36 UTC, sagidayan commented on ci-operator/jobs/rh-ecosystem-edge/ci-tools-nvidia-gpu-operator/rh-ecosystem-edge-ci-tools-nvidia-gpu-operator-main-presubmits.yaml
> +    always_run: true
same here

2023-11-09 09:25 UTC, empovit commented
/pj-rehearse periodic-ci-rh-ecosystem-edge-ci-tools-nvidia-gpu-operator-main-4.15-nvidia-gpu-operator-e2e-23-6-x
/pj-rehearse periodic-ci-rh-ecosystem-edge-ci-tools-nvidia-gpu-operator-main-4.14-nvidia-gpu-operator-e2e-23-6-x
/pj-rehearse periodic-ci-rh-ecosystem-edge-ci-tools-nvidia-gpu-operator-main-4.14-nvidia-gpu-operator-e2e-23-9-x
/pj-rehearse periodic-ci-rh-ecosystem-edge-ci-tools-nvidia-gpu-operator-main-4.14-nvidia-gpu-operator-e2e-master
/pj-rehearse periodic-ci-rh-ecosystem-edge-ci-tools-nvidia-gpu-operator-main-4.15-nvidia-gpu-operator-e2e-23-9-x
/pj-rehearse periodic-ci-rh-ecosystem-edge-ci-tools-nvidia-gpu-operator-main-4.15-nvidia-gpu-operator-e2e-master

2023-11-09 11:16 UTC, empovit commented
/pj-rehearse ack

2023-11-09 11:16 UTC, empovit commented
/unhold

2023-11-09 13:50 UTC, sagidayan commented
/lgtm

2023-11-09 16:16 UTC, merged