Fix okd-scos image tags
openshift/release pull request #45322
Opened 2023-11-06 11:53 UTC by andfasano

Use the correct scos image tags

2023-11-06 11:53 UTC, andfasano commented
cc @LorbusChris

2023-11-06 12:08 UTC, LorbusChris requested changes

2023-11-06 12:08 UTC, LorbusChris commented on ci-operator/config/openshift/machine-os-images/openshift-machine-os-images-main__okd-scos.yaml
> +     okd_scos_4.15_installer:
```suggestion
    okd_scos_4.15_installer:
```

2023-11-07 16:33 UTC, elfosardo commented
/approve

2023-11-13 10:53 UTC, LorbusChris commented
/lgtm

2023-11-13 11:44 UTC, merged