Converge and stabilize hypershift kubevirt conformance periodics on baremetalds infra
openshift/release pull request #46172
Opened 2023-11-28 21:25 UTC by davidvossel

2023-11-28 21:43 UTC, davidvossel commented
/pj-rehearse periodic-ci-openshift-hypershift-release-4.15-periodics-e2e-kubevirt-baremetalds-conformance periodic-ci-openshift-hypershift-release-4.14-periodics-e2e-kubevirt-mce-baremetalds-conformance

2023-11-29 15:26 UTC, qinqon requested changes

2023-11-29 15:26 UTC, qinqon commented on ci-operator/step-registry/hypershift/mce/kubevirt/baremetalds/conformance/hypershift-mce-kubevirt-baremetalds-conformance-workflow.yaml
> +      TEST_SKIPS: etcd leader changes are not excessive \| StatefulSet Basic \| StatefulSet Non-retain
We need to add the following to use the 4.14 catalog source to install odf 
```
ODF_OPERATOR_SUB_SOURCE: redhat-operators-v4-14
```

2023-11-29 17:43 UTC, qinqon commented
/pj-rehearsal ack

2023-11-29 19:02 UTC, merged