Add 4.12 z-rollback test
openshift/release pull request #46465
Opened 2023-12-06 10:05 UTC by shellyyang1989

Refers [OTA-1084](https://issues.redhat.com/browse/OTA-1084)

2023-12-07 03:31 UTC, shellyyang1989 commented
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.12-aws-ipi-shared-vpc-phz-upgrade-rollback-oldest-supported

2023-12-07 06:42 UTC, shellyyang1989 commented
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.12-aws-ipi-shared-vpc-phz-upgrade-rollback-oldest-supported

2023-12-07 06:42 UTC, shellyyang1989 commented
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.12-azure-upi-f28-upgrade-rollback-oldest-supported

2023-12-07 06:43 UTC, shellyyang1989 commented
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.12-gcp-ipi-ovn-ipsec-upgrade-rollback-oldest-supported

2023-12-07 06:43 UTC, shellyyang1989 commented
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.12-ibmcloud-ipi-upgrade-rollback-oldest-supported

2023-12-07 06:44 UTC, shellyyang1989 commented
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.12-vsphere-upi-upgrade-rollback-oldest-supported

2023-12-07 14:30 UTC, shellyyang1989 commented
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.12-nutanix-ipi-upgrade-rollback-oldest-supported

2023-12-07 14:31 UTC, shellyyang1989 commented
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.12-gcp-ipi-ovn-ipsec-upgrade-rollback-oldest-supported

2023-12-08 02:20 UTC, shellyyang1989 commented
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.12-aws-ipi-byo-route53-upgrade-rollback-oldest-supported

2023-12-08 02:21 UTC, shellyyang1989 commented
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.12-azure-upi-f28-upgrade-rollback-oldest-supported

2023-12-08 02:21 UTC, shellyyang1989 commented
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.12-gcp-ipi-ovn-ipsec-upgrade-rollback-oldest-supported

2023-12-08 02:21 UTC, shellyyang1989 commented
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.12-ibmcloud-ipi-upgrade-rollback-oldest-supported

2023-12-08 02:21 UTC, shellyyang1989 commented
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.12-nutanix-ipi-upgrade-rollback-oldest-supported

2023-12-08 02:21 UTC, shellyyang1989 commented
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.12-vsphere-upi-upgrade-rollback-oldest-supported

2023-12-13 09:52 UTC, shellyyang1989 commented
All the rehearsals failed. I checked the [aws](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_release/46465/rehearse-46465-periodic-ci-openshift-release-master-nightly-4.12-aws-ipi-byo-route53-upgrade-rollback-oldest-supported/1732948738046955520) and [gcp](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_release/46465/rehearse-46465-periodic-ci-openshift-release-master-nightly-4.12-gcp-ipi-ovn-ipsec-upgrade-rollback-oldest-supported/1732948871534874624) runs, both failed with the error.
```
Dec 08 05:44:35.712853 ip-10-0-58-39 rpm-ostree[5775]: Failed to find image ostree-unverified-image:docker://quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:517eb21c6ba447a4e203b60578f3af1c11a1066863831d02d48dd1d34752f82b  
Dec 08 05:44:35.715874 ip-10-0-58-39 rpm-ostree[5775]: error: Couldn't start daemon: Error setting up sysroot: Reading deployment 1: Failed to find image ostree-unverified-image:docker://quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:517eb21c6ba447a4e203b60578f3af1c11a1066863831d02d48dd1d34752f82b
```

2023-12-14 05:11 UTC, shellyyang1989 commented
@LalatenduMohanty @wking @petr-muller  @jianlinliu @jiajliu @JianLi-RH Please help review when you have time. Thank you.

2023-12-14 15:04 UTC, petr-muller commented
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.12-gcp-ipi-ovn-ipsec-upgrade-rollback-oldest-supported
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.12-azure-upi-f28-upgrade-rollback-oldest-supported

Code looks good, let me see some rehearsals of the current revision

2023-12-14 15:04 UTC, petr-muller commented
/lgtm
/approve

2023-12-14 15:14 UTC, shellyyang1989 commented
Thank you Petr for review! I've run all of the rehearsals. But all failed. Looks like 4.12 rollback is blocked by https://issues.redhat.com/browse/OCPBUGS-25382.

2023-12-14 21:35 UTC, LalatenduMohanty requested changes

2023-12-14 21:35 UTC, LalatenduMohanty commented on ci-operator/jobs/openshift/release/openshift-release-master-periodics.yaml
> +      - --variant=nightly-4.12
@shellyyang1989 we do not need to test the z strema rollback for the nightly builds.

2023-12-14 21:36 UTC, LalatenduMohanty commented
/lgtm cancel As we do not need to test the rollback from nightly builds to 4.12.0.

2023-12-14 21:36 UTC, LalatenduMohanty commented on ci-operator/jobs/openshift/release/openshift-release-master-periodics.yaml
> +      - --variant=nightly-4.12
Please check my latest comment in the Jira https://issues.redhat.com/browse/OTA-1084

2023-12-15 12:40 UTC, shellyyang1989 commented
/close

2023-12-15 12:40 UTC, closed without merging