Mtsre 1662
openshift/release pull request #46612
Opened 2023-12-11 06:43 UTC by venkateshsredhat

change the e2e test config to point to the new dockerfile

2023-12-11 13:34 UTC, supreeth7 reviewed
Please change the title and add proper description for posterity

2023-12-13 04:34 UTC, supreeth7 requested changes
We'll need to change the webhook base image as well.

2023-12-13 04:34 UTC, supreeth7 commented on ci-operator/config/openshift/addon-operator/openshift-addon-operator-main.yaml
> +- dockerfile_path: bundle.Dockerfile
This should point to the operator image; `build/Dockerfile`.

2023-12-13 05:30 UTC, venkateshsredhat commented
/pj-rehearse

2023-12-13 06:25 UTC, venkateshsredhat commented
/retest

2023-12-13 06:28 UTC, venkateshsredhat commented
/pj-rehearse

2023-12-13 06:29 UTC, venkateshsredhat commented
/pj-rehearse pull-ci-openshift-addon-operator-main-operator-e2e

2023-12-14 07:08 UTC, venkateshsredhat commented
/pj-rehearse

2023-12-14 07:10 UTC, venkateshsredhat commented
/retest

2023-12-14 07:11 UTC, venkateshsredhat commented
/pj-rehearse pull-ci-openshift-addon-operator-main-operator-e2e

2023-12-14 07:21 UTC, supreeth7 commented
/pj-rehearse

2023-12-14 14:12 UTC, supreeth7 commented
/pj-rehearse

2023-12-14 14:56 UTC, supreeth7 commented
/pj-rehearse pull-ci-openshift-addon-operator-main-operator-e2e

2023-12-15 03:06 UTC, supreeth7 approved these changes
/lgtm

2023-12-15 03:10 UTC, supreeth7 commented
/label tide/merge-method-squash

2023-12-15 03:33 UTC, supreeth7 commented
/pj-rehearse ack

2023-12-15 03:42 UTC, merged