Add config for stackrox ui component test job
openshift/release pull request #46991
Opened 2023-12-20 16:05 UTC by dvail

Step 1 from [Middle change: Adding a new job to OpenShift CI for stackrox/stackrox](https://docs.engineering.redhat.com/pages/viewpage.action?spaceKey=StackRox&title=Making+changes+to+OpenShift+CI). 

Adds a new job that runs UI component tests. These tests will run in Cypress, like the ui-e2e tests, but are entirely self-contained and do not require an openshift cluster.

The purpose of this job is to allow a level of test abstraction for UI code between low-level unit tests and high level e2e tests.

This job:
- is currently optional
- does not automatically run
- will upload screenshots and videos to GCS, like the e2e job

Step 2 to add a supporting job in stackrox/stackrox is in progress.

2023-12-20 16:07 UTC, dvail commented
/uncc
/cc @vjwilson @gavin-stackrox

2023-12-20 16:08 UTC, dvail commented
/uncc

2023-12-20 17:30 UTC, gavin-stackrox commented
/uncc @vi-patel @msugakov

2023-12-20 17:33 UTC, gavin-stackrox requested changes

2023-12-20 17:33 UTC, gavin-stackrox commented on ci-operator/config/stackrox/stackrox/stackrox-stackrox-master.yaml
> +  run_if_changed: ^ui/
Can you remove this 'for now'. IIUC `always_run: false` has precedence, so this job should not run on any PRs unless explicitly requested but I'm never 100% sure what prow will do.
```suggestion
```

2023-12-20 23:29 UTC, gavin-stackrox approved these changes

2023-12-20 23:30 UTC, gavin-stackrox commented
@dvail see https://github.com/openshift/release/pull/46991#issuecomment-1865016590 for the last step to merge this PR.

2023-12-21 13:05 UTC, dvail commented
/pj-rehearse pull-ci-stackrox-stackrox-master-ui-component-tests

2024-01-03 13:56 UTC, dvail commented
/pj-rehearse ack

2024-01-03 14:17 UTC, merged