use env vars for reserved and isolated cpus in NTO and cnf-features-deploy
openshift/release pull request #47439
Opened 2024-01-09 13:10 UTC by shajmakh

Following https://github.com/openshift/cluster-node-tuning-operator/pull/909, we now can provide the CPU
specifications for the performance profile that will be used as a base
for the functional tests. Given that the NTO and cnf-features-deploy u/s CI is using vm-node clusters and that the deployment settings are constant, according to the PPC CPU calculation using must-gather data, we export the result in environment variables indicating reserved and isolated CPUs.

Note: this will need to be maintained should node cpu settings change.
in gcp.

2024-01-09 13:12 UTC, shajmakh commented
/hold
let's wait to see how the CI accepts this. 

/cc @ffromani @sshnaidm

2024-01-09 15:52 UTC, shajmakh commented
we need to wait for https://github.com/openshift/cluster-node-tuning-operator/pull/909 to be merged, otherwise this will be pointless and testing it is with no value

2024-01-09 18:46 UTC, sshnaidm requested changes

2024-01-09 18:46 UTC, sshnaidm commented on ci-operator/config/openshift/cluster-node-tuning-operator/openshift-cluster-node-tuning-operator-master.yaml
> +      commands: |
Let's do this in different patches, step registry in one patch and these jobs in a separate.
It's different areas with different jobs and permissions, better to keep them separated.

2024-02-06 18:18 UTC, shajmakh commented
https://github.com/openshift/cluster-node-tuning-operator/pull/909 was merged. This PR addressed 4.16 branch. we also need similar one for each other supported version following merging the cherry-picks of 909. 

/pj-rehearse periodic-ci-openshift-release-master-nightly-4.14-e2e-telco5g-cnftests periodic-ci-openshift-release-master-nightly-4.15-e2e-telco5g-cnftests periodic-ci-openshift-release-master-nightly-4.16-e2e-telco5g-cnftests periodic-ci-openshift-release-master-nightly-4.13-e2e-telco5g-sno-cnftests periodic-ci-openshift-release-master-nightly-4.14-e2e-telco5g-sno-cnftests

/hold cancel

2024-02-12 13:09 UTC, shajmakh commented
/pj-rehearse pull-ci-openshift-cluster-node-tuning-operator-master-e2e-aws-ovn-techpreview	pull-ci-openshift-cluster-node-tuning-operator-master-e2e-gcp-pao pull-ci-openshift-cluster-node-tuning-operator-master-e2e-gcp-pao-updating-profile pull-ci-openshift-cluster-node-tuning-operator-master-e2e-gcp-pao-workloadhints

2024-02-12 13:12 UTC, shajmakh commented
/pj-rehearse max

2024-02-12 13:30 UTC, shajmakh commented
same failure for all failed lanes:

`ERRO[2024-02-12T13:26:28Z] 
  * could not run steps: step [release:latest] failed: release "release-latest" failed: could not watch pod: the pod ci-op-1njngbf1/release-latest failed after 27s (failed containers: release): ContainerFailed one or more containers exited`
  * 
/retest

2024-02-14 08:29 UTC, sshnaidm commented
/pj-rehearse max

2024-02-14 13:28 UTC, sshnaidm commented
techpreview job seems broken:
```
 /bin/bash: line 6: pao-functests-mixedcpus: command not found 
```
in the other only one test failed.

2024-02-29 16:02 UTC, shajmakh commented
/pj-rehearse max

2024-02-29 16:22 UTC, shajmakh commented
/pj-rehearse max

2024-02-29 16:28 UTC, shajmakh commented
/pj-rehearse max

2024-03-01 09:03 UTC, shajmakh commented
/pj-rehearse max

2024-03-01 12:42 UTC, shajmakh commented
the failure in gcp-pao lane doesn't tell much about whether it is a legit or a flake, thus:
https://github.com/openshift/cluster-node-tuning-operator/pull/974 
and rerun to verify again:
/pj-rehearse pull-ci-openshift-cluster-node-tuning-operator-master-e2e-gcp-pao
apart from that, the changes look like they were applied successfully without issues.

2024-04-04 11:07 UTC, shajmakh commented
/pj-rehearse pull-ci-openshift-cluster-node-tuning-operator-master-e2e-telco5g-cnftests

2024-04-04 13:55 UTC, shajmakh commented
/pj-rehearse max

2024-05-13 19:33 UTC, closed without merging