Merge ci-tools-build-root and managed-clonerefs jobs
openshift/release pull request #47491
Opened 2024-01-10 17:23 UTC by Toma5OD

# PR: Merge Periodic Jobs into Single Job

/cc @danilo-gemoli 

## Description
Merged `periodic-trigger-ci-tools-build-root-mabc` and `periodic-trigger-managed-clonerefs-mabc` into one job, `periodic-trigger-images-mabc`, simplifying the CI pipeline.

## Changes
- Combined two periodic jobs into a single job.
- Unified script handling for both tasks.
- Improved maintainability and resource efficiency.

## Impact
Simplifies job management and potentially improves resource utilization in the CI/CD pipeline.

2024-01-11 09:46 UTC, droslean commented
Since you are doing that, it would be better to have a script in the https://github.com/openshift/release/tree/master/hack folder and use that instead to run the job. It would be easier to maintain and we can incrementally add more mabc build in the future without touching the job.

2024-01-12 09:08 UTC, danilo-gemoli commented
It would be better to remove the comments you added as they don't add so much. Each of them is just a description of what the next command does without adding any context and, since each command is quite self explanatory, it's better to get rid of them.

2024-01-12 13:08 UTC, droslean commented
/hold

@Toma5OD 
The changes LGTM but there is a problem with your commits. Please try to rebase the PR

2024-01-12 13:22 UTC, danilo-gemoli requested changes

2024-01-12 13:22 UTC, danilo-gemoli commented on ci-operator/jobs/infra-periodics.yaml
> +      - /release/hack/manage_mabc_builds.sh
The job current working dir is already the `openshift/release` repo, replace with `hack/manage_mabc_builds.sh`

2024-01-12 13:22 UTC, danilo-gemoli commented on hack/manage_mabc_builds.sh
> +#!/bin/bash
```
set -o errexit
set -o nounset
set -o pipefail
```
These bash options are missing.

2024-01-12 13:22 UTC, danilo-gemoli commented on hack/manage_mabc_builds.sh
> +mabcs["managed_clonerefs"]="clusters/build-clusters/multi01/supplemental-ci-images/001_managed-clonerefs_mabc.yaml"
Correct name is `managed-clonerefs`

2024-01-12 13:22 UTC, danilo-gemoli commented on ci-operator/jobs/infra-periodics.yaml
> +  name: periodic-trigger-images-mabc
Definitely you'll prove me wrong here but `periodic-trigger-mabc-images` sounds more correct in English.

2024-01-12 14:40 UTC, droslean commented
/label tide/merge-method-squash

2024-01-12 14:51 UTC, danilo-gemoli commented on ci-operator/jobs/infra-periodics.yaml
>        - /bin/bash
Yet another thing:
```yaml
containers:
- args:
  - hack/manage_mabc_builds.sh
  command:
  - /bin/bash
```
won't work.
Run `hack/manage_mabc_builds.sh` directly instead.

2024-01-12 15:20 UTC, danilo-gemoli commented
It looks fine, we are going to unhold it on Monday morning

2024-01-15 09:19 UTC, danilo-gemoli commented
/lgtm
/unhold

2024-01-15 09:40 UTC, merged