WIP:LP Interop configs update ocp ver to 4.16
openshift/release pull request #48757
Opened 2024-02-13 18:45 UTC by smatula

2024-02-14 12:02 UTC, smatula commented
/pj-rehearse periodic-ci-openshift-grafana-tempo-operator-main-tempo-product-ocp-4.16-lp-interop-tempo-interop-aws periodic-ci-mtc-qe-mtc-e2e-qev2-master-mtc1.8-ocp4.16-lp-interop-mtc-interop-aws periodic-ci-rh-openjdk-jdkContainerOcpTests-main-openjdk-ocp4.16-lp-interop-openjdk-interop-aws periodic-ci-redhat-developer-service-binding-operator-release-v1.4.x-4.16-acceptance-lp-interop periodic-ci-openshift-jenkins-release-4.16-jenkins-ocp4.16-lp-interop-jenkins-interop-aws

2024-02-14 13:58 UTC, calebevans requested changes
Just that MTC change, otherwise lgtm

2024-02-14 13:58 UTC, calebevans commented on ci-operator/config/mtc-qe/mtc-e2e-qev2/mtc-qe-mtc-e2e-qev2-master__mtc1.8-ocp4.16-lp-interop.yaml
> +      CLUSTER1_CONFIG: name=mtc-aws-ipi-source;base-domain=cspilp.interop.ccitredhat.com;platform=aws;region=us-east-2;version=4.14;stream=stable;worker-flavor=m5.xlarge;timeout=2h
```suggestion
      CLUSTER1_CONFIG: name=mtc-aws-ipi-source;base-domain=cspilp.interop.ccitredhat.com;platform=aws;region=us-east-2;version=4.15;stream=stable;worker-flavor=m5.xlarge;timeout=2h
```

Like you said in your Slack message, this should be 4.15 now

2024-02-14 15:23 UTC, smatula commented
/pj-rehearse periodic-ci-openshift-knative-serverless-operator-main-ocp4.16-lp-interop-operator-e2e-interop-aws-ocp416 periodic-ci-openshift-jenkins-release-4.16-jenkins-ocp4.16-lp-interop-jenkins-interop-aws periodic-ci-quay-quay-tests-master-ocp-416-quay-quay-e2e-tests-quay310-ocp416-lp-interop periodic-ci-sclorg-ansible-tests-master-dotnet-ocp4.16-lp-interop-dotnet-interop-aws periodic-ci-redhat-developer-odo-main-odo-ocp4.16-lp-interop-odo-scenario-aws

2024-02-15 02:58 UTC, calebevans approved these changes
/lgtm

2024-02-15 20:51 UTC, calebevans commented on ci-operator/jobs/windup/windup-ui-tests/windup-windup-ui-tests-v1.2-periodics.yaml
> +  name: periodic-ci-windup-windup-ui-tests-v1.2-mtr-ocp4.16-lp-interop-mtr-interop-aws
Just need a slack config

2024-02-15 21:08 UTC, calebevans approved these changes
/lgtm

2024-02-16 11:27 UTC, smatula commented
/pj-rehearse ack

2024-02-16 13:13 UTC, IshwarKanse approved these changes

2024-02-16 13:47 UTC, merged