Use builder root from repo operator-framework-rukpak
openshift/release pull request #48766
Opened 2024-02-13 22:13 UTC by kevinrizza

Update rukpak 4.12 and 4.13 to match config for rest of builds Don't pull releease tag from image stream

2024-02-13 22:16 UTC, ankitathomas approved these changes
/lgtm

2024-02-13 22:25 UTC, kevinrizza commented
/pj-rehearse more

2024-02-14 13:35 UTC, kevinrizza commented
The one test failure is because we're already pointing to a go 1.19 image in the repo and that is failing our linter, which is expected. We can fix that up when we bump the rest of the repo to use 1.19 to build

/pj-rehearse ack

2024-02-14 13:48 UTC, joelanford commented
/lgtm

2024-02-14 13:52 UTC, grokspawn requested changes
If lint is never going to succeed until/unless we correct code in the rukpak repo, then shouldn't you remove these lines to (temporarily) disable the linter?

2024-02-14 14:11 UTC, grokspawn commented
/lgtm

2024-02-14 14:15 UTC, grokspawn approved these changes

2024-02-14 14:48 UTC, merged