[INTEROP-7281] Expand OpenShift Pipelines to v1.13 for OCP 4.15 and 4.16.
openshift/release pull request #48976
Opened 2024-02-19 20:34 UTC by dfrazzette

Per [SRVKP-3694](https://issues.redhat.com/browse/SRVKP-3694), Pipelines 1.11 is not supported on OCP 4.15. Expanding the scenario to test Pipelines 1.13 on OCP 4.15.

2024-02-19 20:58 UTC, dfrazzette commented
/pj-rehearse periodic-ci-openshift-pipelines-release-tests-release-v1.13-openshift-pipelines-ocp4.15-lp-interop-openshift-pipelines-interop-aws

2024-02-19 23:26 UTC, dfrazzette commented
/pj-rehearse ack

2024-02-20 00:09 UTC, calebevans requested changes
One small thing

2024-02-20 00:09 UTC, calebevans commented on ci-operator/jobs/openshift-pipelines/release-tests/openshift-pipelines-release-tests-release-v1.13-periodics.yaml
> +  name: periodic-ci-openshift-pipelines-release-tests-release-v1.13-openshift-pipelines-ocp4.16-lp-interop-openshift-pipelines-interop-aws
Can you add the `reporter_config` section here? Should look like [this](https://github.com/openshift/release/blob/2984f584c8c5c6d340a2f6aa4c74e4a8311e13fd/ci-operator/jobs/openshift-pipelines/release-tests/openshift-pipelines-release-tests-release-v1.11-periodics.yaml#L20-L30).

2024-02-20 00:40 UTC, closed without merging