MGMT-16880: assisted-service config for ocm 2.10
openshift/release pull request #49112
Opened 2024-02-22 10:25 UTC by adriengentil

2024-02-22 10:26 UTC, adriengentil commented
/cc @danmanor @osherdp
/hold

2024-02-26 09:00 UTC, osherdp requested changes

2024-02-26 09:00 UTC, osherdp commented on ci-operator/config/openshift/assisted-service/openshift-assisted-service-release-ocm-2.10.yaml
> +- as: push-pr-image
you know what? let's remove it from everywhere, it's not worth the future risk

2024-02-26 09:01 UTC, adriengentil commented on ci-operator/config/openshift/assisted-service/openshift-assisted-service-master__edge.yaml
> +- always_run: false
oh right, I did it mechanically

2024-02-26 09:24 UTC, adriengentil commented on ci-operator/config/openshift/assisted-service/openshift-assisted-service-release-ocm-2.10.yaml
> +- as: push-pr-image
done!

2024-02-26 09:24 UTC, adriengentil commented on ci-operator/config/openshift/assisted-service/openshift-assisted-service-master__edge.yaml
> +- always_run: false
done!

2024-02-26 09:26 UTC, osherdp requested changes

2024-02-26 09:26 UTC, osherdp commented on ci-operator/config/openshift/assisted-service/openshift-assisted-service-release-ocm-2.8.yaml
> +- as: oserator-publish
typo

2024-02-26 10:04 UTC, osherdp approved these changes

2024-02-26 14:51 UTC, adriengentil commented
/pj-rehearse ack

2024-02-26 16:47 UTC, danmanor approved these changes

2024-02-26 16:47 UTC, danmanor commented
/lgtm

2024-02-26 16:58 UTC, adriengentil commented
/pj-rehearse ack

2024-02-26 17:57 UTC, merged