Init Openshift Kapp Controller
openshift/release pull request #49737
Opened 2024-03-11 21:10 UTC by theishshah

Add initial yaml to enable prow for openshift operator framework kapp controller

2024-03-14 15:04 UTC, m1kola commented
/cc

2024-03-14 15:59 UTC, grokspawn commented
Looks like you're missing the `make jobs` step from https://docs.ci.openshift.org/docs/how-tos/onboarding-a-new-component/#generating-prow-jobs-from-ci-operator-configuration-files
You will likely also have to run `make openshift-image-mirror-mappings` because you're adding a new image [here](https://github.com/openshift/release/pull/49737/files#diff-566f9e1b5a8bdc12eafd924c457b793b718aad51f07db047ece7f1a9d69efa02R25)

2024-03-14 16:34 UTC, m1kola reviewed
We use develop as a default branch in this repo. So need to keep an eye on places where we need to update these settings.

2024-03-14 16:34 UTC, m1kola commented on ci-operator/config/openshift/operator-framework-kapp-controller/openshift-operator-framework-kapp-controller-main.yml
> +  commands: commitchecker --start ${PULL_BASE_SHA:-main}
```suggestion
  commands: commitchecker --start ${PULL_BASE_SHA:-develop}
```

2024-03-14 16:34 UTC, m1kola commented on ci-operator/config/openshift/operator-framework-kapp-controller/openshift-operator-framework-kapp-controller-main.yml
> +  branch: main
```suggestion
  branch: develop
```

2024-04-08 14:17 UTC, m1kola requested changes
@theishshah we decided to change the direction and this is no longer needed. Let's close this PR please.

2024-04-22 14:25 UTC, m1kola commented
/unassign

2024-04-29 13:02 UTC, grokspawn commented
@theishshah close this since we are going a diff way?

2024-06-28 20:52 UTC, closed without merging