[winc] Remove unsupported version 6.0.4
openshift/release pull request #49834
Opened 2024-03-13 19:18 UTC by saifshaikh48

[OCP 4.11 maintenance support ended](https://access.redhat.com/support/policy/updates/openshift/ ) on February 10, 2024 so [WMCO 6 is end-of-life](https://access.redhat.com/support/policy/updates/openshift_operators) as well.

2024-03-13 19:32 UTC, sebsoto requested changes

2024-03-13 19:32 UTC, sebsoto commented on ci-operator/config/openshift/windows-machine-config-bootstrapper/openshift-windows-machine-config-bootstrapper-community-4.11__okd.yaml
> -base_images:
Its a bit confusing that this is being done for 4.11 when there are 4.10, etc being left.
Can we remove the entire WMCB repo and WMCO 4.11,4.10, etc?

If so please reframe this as `Remove unsupported versions`

2024-03-13 20:18 UTC, mansikulkarni96 commented
/lgtm

2024-03-13 23:28 UTC, sebsoto commented
/approve

2024-03-14 17:51 UTC, saifshaikh48 commented
had to push an update to resolve a merge conflict that arose overnight

2024-03-14 17:58 UTC, saifshaikh48 commented
/lgtm

2024-03-14 18:03 UTC, alinaryan commented
/lgtm

2024-03-14 18:10 UTC, merged

2024-03-14 18:21 UTC, saifshaikh48 commented
@alinaryan thank you for helping get this in before another merge conflict arose :rocket: