Adds build and tests for OpenDataHub Intel Machine Learning Jupyter Notebooks Container
openshift/release pull request #49889
Opened 2024-03-14 21:31 UTC by sharvil10

2024-03-14 23:38 UTC, harshad16 requested changes
Hello @sharvil10 
Thank you for the PR
can you address these changes

2024-03-14 23:38 UTC, harshad16 commented on ci-operator/config/opendatahub-io/notebooks/opendatahub-io-notebooks-main.yaml
> +    tag: rhel-8-release-golang-1.17-openshift-4.10
can you please revert this change?

2024-03-14 23:38 UTC, harshad16 commented on ci-operator/config/opendatahub-io/notebooks/opendatahub-io-notebooks-main.yaml
> -  to: jupyter-datascience-anaconda-python-3.8
can you please revert this change?

2024-03-14 23:38 UTC, harshad16 commented on ci-operator/config/opendatahub-io/notebooks/opendatahub-io-notebooks-main.yaml
> -    workflow: opendatahub-io-ci-image-mirror
can you please revert this change?

2024-03-15 16:11 UTC, harshad16 commented
@sharvil10 please make these changes.

2024-03-15 16:40 UTC, sharvil10 commented on ci-operator/config/opendatahub-io/notebooks/opendatahub-io-notebooks-main.yaml
> +    tag: rhel-8-release-golang-1.17-openshift-4.10
Updated

2024-03-15 16:40 UTC, sharvil10 commented on ci-operator/config/opendatahub-io/notebooks/opendatahub-io-notebooks-main.yaml
> -  to: jupyter-datascience-anaconda-python-3.8
Updated

2024-03-15 16:40 UTC, sharvil10 commented on ci-operator/config/opendatahub-io/notebooks/opendatahub-io-notebooks-main.yaml
> -    workflow: opendatahub-io-ci-image-mirror
Updated

2024-03-15 17:00 UTC, harshad16 commented
@sharvil10 , i dont think you pushed your changes
there are no new changes, please take a look.

2024-03-15 17:42 UTC, sharvil10 commented
> @sharvil10 , i dont think you pushed your changes there are no new changes, please take a look.

https://github.com/openshift/release/pull/49889/commits/722510660fb0cc8d04172ff108bf7daa14a96751 is the commit with the change.

2024-03-15 18:52 UTC, harshad16 reviewed
/lgtm
/approve
:+1:

2024-03-15 18:52 UTC, harshad16 commented
/ok-to-test

2024-03-15 20:06 UTC, harshad16 commented
/pj-rehearse ack

2024-03-15 20:34 UTC, merged