Add rook operator install command in ocs-operator
openshift/release pull request #49896
Opened 2024-03-15 06:50 UTC by Nikhil-Ladha

Add `make install-rook` command to ocs-operator e2e test

2024-03-15 06:51 UTC, Nikhil-Ladha commented
cc @iamniting @malayparida2000

2024-03-15 06:57 UTC, iamniting requested changes

2024-03-15 06:57 UTC, iamniting commented on ci-operator/config/red-hat-storage/ocs-operator/red-hat-storage-ocs-operator-main.yaml
> +        export BUNDLE_FULL_IMAGE_NAME="$OO_BUNDLE"; make install-ocs; make install-noobaa; make install-rook
Lets keep it in b/w

2024-03-15 09:56 UTC, Nikhil-Ladha commented on ci-operator/config/red-hat-storage/ocs-operator/red-hat-storage-ocs-operator-main.yaml
> +        export BUNDLE_FULL_IMAGE_NAME="$OO_BUNDLE"; make install-ocs; make install-noobaa; make install-rook
Done

2024-03-15 13:53 UTC, Nikhil-Ladha commented
/pj-rehearse

2024-03-15 14:36 UTC, iamniting commented
/ok-to-test

2024-03-19 10:38 UTC, iamniting approved these changes

2024-03-19 10:39 UTC, iamniting commented
/approve
/lgtm

2024-03-19 10:42 UTC, iamniting commented
/pj-rehearse ack

2024-03-19 10:43 UTC, iamniting commented
/approve

2024-03-19 10:56 UTC, merged