This commit will
openshift/release pull request #49999
Opened 2024-03-19 14:27 UTC by tonyxrmdavidson

target the openshift-ci/script/oci-model-registry-deploy.sh script change the openshift-ci deployment to include a cron job running at 1am add the option to call the script on a PR by adding the label /test e2e-odh-cfo-optional adds configuration to output results into our team slack channel

2024-03-19 15:12 UTC, tonyxrmdavidson commented
/pj-rehearse

2024-03-21 17:05 UTC, tonyxrmdavidson commented
/pj-rehearse pull-ci-opendatahub-io-model-registry-main-e2e-odh-cfo-optional

2024-03-27 14:09 UTC, tonyxrmdavidson commented
/pj-rehearse pull-ci-opendatahub-io-model-registry-main-e2e-odh-cfo-optional

2024-03-28 10:46 UTC, tonyxrmdavidson commented
/retest

2024-03-28 10:53 UTC, tonyxrmdavidson commented
/pj-rehearse pull-ci-opendatahub-io-model-registry-main-e2e-odh-cfo-optional

2024-03-28 17:01 UTC, tonyxrmdavidson commented
/pj-rehearse pull-ci-opendatahub-io-model-registry-main-e2e-odh-cfo-optional

2024-03-28 19:30 UTC, tonyxrmdavidson commented
/pj-rehearse more

2024-03-28 21:57 UTC, tonyxrmdavidson commented
/pj-rehearse

2024-03-29 09:53 UTC, tonyxrmdavidson commented
/pj-rehearse pull-ci-opendatahub-io-model-registry-main-e2e-odh-cfo-optional

2024-03-29 15:39 UTC, tonyxrmdavidson commented
/pj-rehearse pull-ci-opendatahub-io-model-registry-main-e2e-odh-cfo-optional

2024-03-29 19:37 UTC, tonyxrmdavidson commented
/pj-rehearse pull-ci-opendatahub-io-model-registry-main-e2e-odh-cfo-optional

2024-04-01 12:28 UTC, tonyxrmdavidson commented
/pj-rehearse pull-ci-opendatahub-io-model-registry-main-e2e-odh-cfo-optional

2024-04-08 13:03 UTC, tonyxrmdavidson commented
/pj-rehearse periodic-ci-opendatahub-io-model-registry-main-e2e-odh-cfo-cron

2024-04-08 14:25 UTC, tonyxrmdavidson commented
https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_release/49999/rehearse-49999-pull-ci-opendatahub-io-model-registry-main-e2e-odh-cfo-optional/1774776454932860928

https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_release/49999/rehearse-49999-periodic-ci-opendatahub-io-model-registry-main-e2e-odh-cfo-cron/1777322112441126912

2024-04-09 12:40 UTC, rkubis requested changes
Please just change `cfo` to `mro` everywhere to properly recognize product/component :) Thanks!

2024-04-09 12:40 UTC, rkubis commented on ci-operator/config/opendatahub-io/model-registry/opendatahub-io-model-registry-main.yaml
> +- as: e2e-odh-cfo-cron
I think that `cfo` means Cloudflare Operator here :) We should use `mro` for Model Registry Operator.

2024-04-09 12:40 UTC, rkubis commented on ci-operator/config/opendatahub-io/model-registry/opendatahub-io-model-registry-main.yaml
> +- as: e2e-odh-cfo-optional
The same as above :) Change `cfo` to `mro`.

2024-04-10 18:16 UTC, tonyxrmdavidson commented
/wip

2024-04-10 18:17 UTC, tonyxrmdavidson commented
This PR was pulled, updated and pushed as part of another PR

2024-04-11 08:57 UTC, tonyxrmdavidson commented
/pj-rehearse pull-ci-opendatahub-io-model-registry-main-e2e-odh-mro-optional

2024-04-12 09:10 UTC, rkubis commented
/test clusterimageset-validate

2024-04-12 09:14 UTC, rkubis commented
/test hosted-mgmt-dry

2024-04-12 09:17 UTC, rkubis commented
/pj-rehearse pull-ci-opendatahub-io-model-registry-main-images pull-ci-opendatahub-io-model-registry-main-e2e-odh-mro-optional

2024-04-12 09:35 UTC, tonyxrmdavidson commented
/pj-rehearse pull-ci-opendatahub-io-model-registry-main-e2e-odh-mro-optional

2024-04-15 09:40 UTC, tonyxrmdavidson commented
/pj-rehearse pull-ci-opendatahub-io-model-registry-main-e2e-odh-mro-optional

2024-04-16 08:50 UTC, tonyxrmdavidson commented
/pj-rehearse pull-ci-opendatahub-io-model-registry-main-e2e-odh-mro-optional

2024-04-16 13:08 UTC, tonyxrmdavidson commented
/pj-rehearse pull-ci-opendatahub-io-model-registry-main-images pull-ci-opendatahub-io-model-registry-main-e2e-odh-mro-optional

2024-04-16 14:15 UTC, tonyxrmdavidson commented
forum-ocp-testplatform team notified of catalogsource failure. Jira [here](https://issues.redhat.com/browse/DPTP-3956)

2024-04-17 11:52 UTC, bear-redhat commented
/pj-rehearse pull-ci-opendatahub-io-model-registry-main-e2e-odh-mro-optional

2024-04-18 15:08 UTC, tonyxrmdavidson commented
/pj-rehearse pull-ci-opendatahub-io-model-registry-main-e2e-odh-mro-optional

2024-04-19 08:06 UTC, tonyxrmdavidson commented
/pj-rehearse pull-ci-opendatahub-io-model-registry-main-e2e-odh-mro-optional

2024-04-19 14:22 UTC, tonyxrmdavidson commented
/pj-rehearse pull-ci-opendatahub-io-model-registry-main-e2e-odh-mro-optional

2024-04-22 11:52 UTC, tonyxrmdavidson commented
/pj-rehearse pull-ci-opendatahub-io-model-registry-main-e2e-odh-mro-optional

2024-04-22 13:14 UTC, tonyxrmdavidson commented
/pj-rehearse pull-ci-opendatahub-io-model-registry-main-e2e-odh-mro-optional

2024-04-22 13:34 UTC, tonyxrmdavidson commented
/pj-rehearse pull-ci-opendatahub-io-model-registry-main-images

2024-04-22 13:35 UTC, tonyxrmdavidson commented
/pj-rehearse pull-ci-opendatahub-io-model-registry-main-e2e-odh-mro-optional

2024-04-22 15:48 UTC, tonyxrmdavidson commented
/pj-rehearse pull-ci-opendatahub-io-model-registry-main-images

2024-04-22 15:49 UTC, tonyxrmdavidson commented
/pj-rehearse pull-ci-opendatahub-io-model-registry-main-e2e-odh-mro-optional

2024-04-22 19:01 UTC, rkubis commented
/pj-rehearse pull-ci-opendatahub-io-model-registry-main-e2e-odh-mro-optional

2024-04-22 20:04 UTC, rkubis commented
/lgtm

2024-04-22 20:05 UTC, rkubis commented
/rehearse ack

2024-04-22 20:07 UTC, rkubis commented
/pj-rehearse ack

2024-04-22 20:43 UTC, merged