bump origin to go 1.21
openshift/release pull request #50075
Opened 2024-03-20 23:07 UTC by sanchezl

2024-03-21 05:34 UTC, sanchezl commented
/pj-rehearse auto-ack

2024-03-21 13:43 UTC, sanchezl commented
/pj-rehearse pull-ci-openshift-origin-master-e2e-aws-disruptive
/pj-rehearse pull-ci-openshift-origin-master-4.12-upgrade-from-stable-4.11-e2e-aws-ovn-upgrade-rollback
/pj-rehearse pull-ci-openshift-origin-master-e2e-aws-csi

2024-03-25 12:40 UTC, stlaz commented
/lgtm
/hold
to see whether the tests go green

2024-03-25 16:11 UTC, sanchezl commented
/pj-rehearse pull-ci-openshift-origin-master-e2e-aws-disruptive pull-ci-openshift-origin-master-4.12-upgrade-from-stable-4.11-e2e-aws-ovn-upgrade-rollback pull-ci-openshift-origin-master-e2e-aws-csi

2024-03-25 19:54 UTC, sanchezl commented
/pj-rehearse ack

2024-03-25 19:55 UTC, sanchezl commented
/hold cancel

2024-03-26 09:47 UTC, soltysh requested changes
/hold
I've already tried that and run into issues, more details in https://issues.redhat.com//browse/TRT-1515

2024-03-28 05:00 UTC, sanchezl commented
/retest

2024-04-23 14:00 UTC, closed without merging