WIP: Add Install-operators-verify ref
openshift/release pull request #50255
Opened 2024-03-26 16:47 UTC by oharan2

2024-03-26 16:49 UTC, oharan2 commented
/pj-rehearse periodic-ci-stolostron-acmqe-autotest-main-acm-ocp4.16-lp-interop-acm-interop-aws

2024-03-26 17:37 UTC, oharan2 commented
/pj-rehearse periodic-ci-mtc-qe-mtc-e2e-qev2-master-mtc1.8-ocp4.16-lp-interop-mtc-interop-aws

2024-03-27 17:04 UTC, oharan2 commented
/pj-rehearse periodic-ci-mtc-qe-mtc-e2e-qev2-master-mtc1.8-ocp4.16-lp-interop-mtc-interop-aws

2024-03-27 17:24 UTC, oharan2 commented
/pj-rehearse periodic-ci-mtc-qe-mtc-e2e-qev2-master-mtc1.8-ocp4.16-lp-interop-mtc-interop-aws

2024-03-27 17:55 UTC, oharan2 commented
/pj-rehearse periodic-ci-mtc-qe-mtc-e2e-qev2-master-mtc1.8-ocp4.16-lp-interop-mtc-interop-aws

2024-03-27 18:24 UTC, calebevans requested changes

2024-03-27 18:24 UTC, calebevans commented on ci-operator/step-registry/firewatch/ipi/aws/firewatch-ipi-aws-workflow.yaml
> +      - ref: install-operators-verify
My only issue with this is there are some scenarios that use the `firewatch-ipi-aws` workflow that do not use `install-operators` so the `OPERATORS` variable will not be present in the config. For example, [serverless](https://github.com/openshift/release/blob/master/ci-operator/config/openshift-knative/serverless-operator/openshift-knative-serverless-operator-main__ocp4.16-lp-interop.yaml#L217) does not use the ref (plus there are a couple of scenarios that use this that are not operators).

We may just need to add this to the scenarios where it applies? The grate thing about this being a ref is that we will be able to add a firewatch rule specifically for failures where the operator is not in the catalog for a pre-release OCP build. 😄

2024-03-27 19:23 UTC, dfrazzette commented on ci-operator/step-registry/firewatch/ipi/aws/firewatch-ipi-aws-workflow.yaml
> +      - ref: install-operators-verify
Can we define which scenarios will default to using the `firewatch-ipi-aws` workflow and apply this ref to them? Additionally, can we define which scenarios are exceptions (do not include `install-operators` ref; do not use operators, or use operators that may be in a different catalog)?

2024-03-28 17:03 UTC, oharan2 commented
/pj-rehearse periodic-ci-openshift-pipelines-release-tests-release-v1.13-openshift-pipelines-ocp4.16-lp-interop-openshift-pipelines-interop-aws

2024-03-28 17:04 UTC, oharan2 commented
/pj-rehearse periodic-ci-skupperproject-skupper-openshift-smoke-test-image-main-service-interconnect-ocp4.16-lp-interop-rhsi-interop-aws

2024-03-28 17:18 UTC, oharan2 commented
/pj-rehearse abort

2024-03-31 04:26 UTC, oharan2 commented
/pj-rehearse periodic-ci-skupperproject-skupper-openshift-smoke-test-image-main-service-interconnect-ocp4.16-lp-interop-rhsi-interop-aws

2024-03-31 04:38 UTC, oharan2 commented
/pj-rehearse periodic-ci-openshift-pipelines-release-tests-release-v1.13-openshift-pipelines-ocp4.16-lp-interop-openshift-pipelines-interop-aws

2024-04-01 18:15 UTC, oharan2 commented
/pj-rehearse periodic-ci-skupperproject-skupper-openshift-smoke-test-image-main-service-interconnect-ocp4.16-lp-interop-rhsi-interop-aws

2024-04-02 08:09 UTC, oharan2 commented
/pj-rehearse periodic-ci-openshift-pipelines-release-tests-release-v1.13-openshift-pipelines-ocp4.16-lp-interop-openshift-pipelines-interop-aws

2024-04-02 10:06 UTC, oharan2 commented
/pj-rehearse periodic-ci-stolostron-acmqe-autotest-main-acm-ocp4.16-lp-interop-acm-interop-aws

2024-04-02 13:15 UTC, oharan2 commented
/pj-rehearse periodic-ci-quarkus-qe-quarkus-openshift-interop-main-quarkus-ocp4.16-lp-interop-quarkus-interop-aws

2024-04-02 16:20 UTC, calebevans approved these changes
/lgtm

2024-04-04 09:24 UTC, oharan2 commented
/pj-rehearse ack

2024-04-04 09:37 UTC, merged

2024-04-04 10:27 UTC, oharan2 commented on ci-operator/step-registry/firewatch/ipi/aws/firewatch-ipi-aws-workflow.yaml
> +      - ref: install-operators-verify
Providing info for future interest:

Within our internal discussions, we verified that using the `OPERATORS` env var is 100% optional, therefore scenarios that uses the `firewatch-ipi-aws` workflow and apply this ref doesn't get effected

See POC:
Job [periodic-ci-quarkus-qe-quarkus-openshift-interop-main-quarkus-ocp4.16-lp-interop-quarkus-interop-aws](https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_release/50255/rehearse-50255-periodic-ci-quarkus-qe-quarkus-openshift-interop-main-quarkus-ocp4.16-lp-interop-quarkus-interop-aws/1775150998822588416#1:build-log.txt%3A34)
- Uses the workflow
- Doesn't use `install-operators` ref for installing the Operator
- Passed this step with:
`Step quarkus-interop-aws-install-operators-verify succeeded after 8s.`
(Job aborted manually before executing cluster provision)