Test upgrade FAR v0.3.0 from to latest
openshift/release pull request #50559
Opened 2024-04-03 15:14 UTC by razo7

2024-04-03 15:14 UTC, razo7 commented
/pj-rehearse max

2024-04-08 06:12 UTC, razo7 commented
/pj-rehearse pull-ci-medik8s-fence-agents-remediation-main-4.16-far-upgarde-latest

2024-04-08 07:31 UTC, razo7 commented
FAR doesn't have the [`bundle-run-update` target](https://github.com/medik8s/node-maintenance-operator/pull/120), so switching the change and testing for NMO ATM

2024-04-08 07:36 UTC, razo7 commented
/pj-rehearse pull-ci-medik8s-node-maintenance-operator-main-4.16-openshift-e2e

2024-04-08 08:57 UTC, razo7 commented
> * why spinning up a new cluster for this test instead of using the one we have alrady?
> * what about doing what the docs suggest, using 3 steps: install, upgrade, e2e test? ([docs.ci.openshift.org/docs/how-tos/testing-operator-sdk-operators/#operator-upgrade-testing](https://docs.ci.openshift.org/docs/how-tos/testing-operator-sdk-operators/#operator-upgrade-testing))
> 
> /hold

Good input, I have followed your suggestions, applied them for NMO, and I will now add the upgrade utility in FAR

2024-04-08 11:23 UTC, razo7 commented
/pj-rehearse pull-ci-medik8s-node-maintenance-operator-main-4.16-openshift-e2e

2024-04-08 13:43 UTC, razo7 commented
/pj-rehearse pull-ci-medik8s-node-maintenance-operator-main-4.16-openshift-e2e

2024-04-08 13:54 UTC, razo7 commented
/pj-rehearse pull-ci-medik8s-node-maintenance-operator-main-4.16-openshift-e2e

2024-04-08 14:58 UTC, razo7 commented
/pj-rehearse pull-ci-medik8s-node-maintenance-operator-main-4.16-openshift-e2e

2024-04-09 05:28 UTC, razo7 commented
/pj-rehearse ack

2024-04-09 05:37 UTC, razo7 commented
/pj-rehearse auto-ack

2024-04-14 04:35 UTC, razo7 commented
/pj-rehearse auto-ack

2024-04-14 04:44 UTC, razo7 commented
/retest

2024-04-15 07:28 UTC, clobrano requested changes

2024-04-15 08:05 UTC, razo7 commented on ci-operator/config/medik8s/node-maintenance-operator/medik8s-node-maintenance-operator-main__4.16.yaml
> +      commands: BUNDLE_IMG="$OO_BUNDLE" make bundle-run-update
It [does](https://github.com/medik8s/node-maintenance-operator/blob/main/Makefile#L202), but OPERATOR_NAMESPACE is [defined already as an environment variable ](https://github.com/openshift/release/pull/50559/files#diff-7d3049ecc7981664e5c32a8c217f3ceb2c413bc9fd4f61bb6b5c07f81ff36dd6R44)for the main test (`openshift-e2e`)

2024-04-15 08:12 UTC, clobrano approved these changes

2024-04-15 08:45 UTC, merged