OLS-426: Add step to run lint check
openshift/release pull request #50561
Opened 2024-04-03 15:22 UTC by sauagarwa

2024-04-03 16:16 UTC, bparees requested changes
you also need to run "make update" to generate the job from the config

2024-04-03 16:16 UTC, bparees commented on ci-operator/config/openshift/lightspeed-console/openshift-lightspeed-console-main.yaml
> +- as: lint-aws-plugin-template
```suggestion
- as: lint
```

unless you expect to have multiple lint jobs

2024-04-04 01:15 UTC, sauagarwa commented
/pj-rehearse

2024-04-04 01:18 UTC, sauagarwa commented
/pj-rehearse pull-ci-openshift-lightspeed-console-main-lint

2024-04-04 02:52 UTC, sauagarwa commented
/pj-rehearse pull-ci-openshift-lightspeed-console-main-lint

2024-04-04 03:04 UTC, sauagarwa commented
/pj-rehearse pull-ci-openshift-lightspeed-console-main-lint

2024-04-04 16:28 UTC, sauagarwa commented
/pj-rehearse pull-ci-openshift-lightspeed-console-main-images

2024-04-04 16:28 UTC, sauagarwa commented
/pj-rehearse pull-ci-openshift-lightspeed-console-main-lint

2024-04-04 17:02 UTC, sauagarwa commented
/pj-rehearse pull-ci-openshift-lightspeed-console-main-images

2024-04-04 17:02 UTC, sauagarwa commented
/pj-rehearse pull-ci-openshift-lightspeed-console-main-lint

2024-04-04 17:28 UTC, sauagarwa commented
/pj-rehearse pull-ci-openshift-lightspeed-console-main-lint

2024-04-04 18:22 UTC, sauagarwa commented
/pj-rehearse

2024-04-05 02:41 UTC, sauagarwa commented
/pj-rehearse pull-ci-openshift-lightspeed-console-main-lint

2024-04-05 02:57 UTC, sauagarwa commented
/pj-rehearse pull-ci-openshift-lightspeed-console-main-lint

2024-04-05 15:14 UTC, sauagarwa commented
/pj-rehearse pull-ci-openshift-lightspeed-console-main-lint

2024-04-05 15:30 UTC, sauagarwa commented
/pj-rehearse pull-ci-openshift-lightspeed-console-main-lint

2024-04-05 15:37 UTC, sauagarwa commented
/pj-rehearse pull-ci-openshift-lightspeed-console-main-lint

2024-04-05 15:49 UTC, sauagarwa commented
/pj-rehearse pull-ci-openshift-lightspeed-console-main-lint

2024-04-05 16:12 UTC, sauagarwa commented
/pj-rehearse pull-ci-openshift-lightspeed-console-main-lint

2024-04-05 16:36 UTC, sauagarwa commented
/pj-rehearse pull-ci-openshift-lightspeed-console-main-lint

2024-04-05 17:04 UTC, sauagarwa commented
/pj-rehearse pull-ci-openshift-lightspeed-console-main-lint

2024-04-05 17:08 UTC, sauagarwa commented
/pj-rehearse ci/rehearse/openshift/lightspeed-console/main/images

2024-04-05 17:34 UTC, sauagarwa commented
/pj-rehearse pull-ci-openshift-lightspeed-console-main-lint

2024-04-05 17:44 UTC, sauagarwa commented
/pj-rehearse pull-ci-openshift-lightspeed-console-main-images

2024-04-05 18:21 UTC, sauagarwa commented
/pj-rehearse pull-ci-openshift-lightspeed-console-main-images

2024-04-05 18:26 UTC, sauagarwa commented
/pj-rehearse pull-ci-openshift-lightspeed-console-main-images

2024-04-05 19:16 UTC, sauagarwa commented
/pj-rehearse pull-ci-openshift-lightspeed-console-main-lint

2024-04-05 19:20 UTC, sauagarwa commented
/pj-rehearse pull-ci-openshift-lightspeed-console-main-images

2024-04-05 19:34 UTC, sauagarwa commented
/pj-rehearse pull-ci-openshift-lightspeed-console-main-lint

2024-04-05 20:02 UTC, sauagarwa commented
/pj-rehearse pull-ci-openshift-lightspeed-console-main-lint

2024-04-05 20:13 UTC, sauagarwa commented
/pj-rehearse pull-ci-openshift-lightspeed-console-main-images

2024-04-08 15:32 UTC, sauagarwa commented
/pj-rehearse pull-ci-openshift-lightspeed-console-main-lint

2024-04-08 16:31 UTC, sauagarwa commented
/pj-rehearse pull-ci-openshift-lightspeed-console-main-lint

2024-04-08 16:43 UTC, sauagarwa commented
/pj-rehearse pull-ci-openshift-lightspeed-console-main-lint

2024-04-09 12:23 UTC, sauagarwa commented
/pj-rehearse pull-ci-openshift-lightspeed-console-main-lint

2024-04-09 13:30 UTC, bparees commented
/lgtm
/approve

2024-04-09 13:31 UTC, bparees commented
/pj-rehearse ack

@sauagarwa for future reference don't forget you need to ack that the rehearsals have been run and passed (to ensure we don't merge a CI change that breaks the CI jobs and prevents PRs from merging)

2024-04-09 14:28 UTC, merged