Test SSO on ibmcloud
openshift/release pull request #50641
Opened 2024-04-05 15:11 UTC by Simranpal

2024-04-05 15:15 UTC, calebevans commented
/pj-rehearse periodic-ci-rhbk-interop-ocp-ci-main-rhsso-product-ocp4.15-lp-interop-rhsso-interop-ibmcloud

2024-04-05 15:18 UTC, calebevans commented
/pj-rehearse periodic-ci-rhbk-interop-ocp-ci-main-rhsso-product-ocp4.15-lp-interop-rhsso-interop-ibmcloud

2024-04-05 15:22 UTC, calebevans commented
/pj-rehearse periodic-ci-rhbk-interop-ocp-ci-main-rhsso-product-ocp4.15-lp-interop-rhsso-interop-ibmcloud

2024-04-09 00:31 UTC, Simranpal commented
/pj-rehearse

2024-04-09 04:15 UTC, Simranpal commented
/pj-rehearse periodic-ci-rhbk-interop-ocp-ci-main-rhsso-product-ocp4.14-lp-interop-rhsso-interop-ibmcloud

2024-04-09 13:28 UTC, calebevans requested changes

2024-04-09 13:28 UTC, calebevans commented on ci-operator/config/rhbk/interop-ocp-ci/rhbk-interop-ocp-ci-main__rhsso-product-ocp4.14-lp-interop.yaml
> +              {"step": "gather-*", "failure_type": "pod_failure", "classification": "Other",  ee"group": {"name": "cluster", "priority": 2}, "jira_additional_labels": ["!default"]},
```suggestion
              {"step": "gather-*", "failure_type": "pod_failure", "classification": "Other",  "group": {"name": "cluster", "priority": 2}, "jira_additional_labels": ["!default"]},
```

2024-04-09 13:28 UTC, calebevans commented on ci-operator/jobs/rhbk/interop-ocp-ci/rhbk-interop-ocp-ci-main-periodics.yaml
> +  name: periodic-ci-rhbk-interop-ocp-ci-main-rhsso-product-ocp4.14-lp-interop-rhsso-interop-ibmcloud
Do you need a slack config here?

2024-04-09 14:08 UTC, Simranpal commented on ci-operator/jobs/rhbk/interop-ocp-ci/rhbk-interop-ocp-ci-main-periodics.yaml
> +  name: periodic-ci-rhbk-interop-ocp-ci-main-rhsso-product-ocp4.14-lp-interop-rhsso-interop-ibmcloud
yeah, I will add it here. Thanks!

2024-04-09 14:19 UTC, calebevans approved these changes
/lgtm

2024-04-09 15:01 UTC, calebevans commented
/pj-rehearse periodic-ci-rhbk-interop-ocp-ci-main-rhsso-product-ocp4.14-lp-interop-rhsso-interop-ibmcloud

2024-04-09 15:01 UTC, Simranpal commented
/pj-rehearse periodic-ci-rhbk-interop-ocp-ci-main-rhsso-product-ocp4.14-lp-interop-rhsso-interop-ibmcloud

2024-04-09 20:15 UTC, Simranpal commented
/pj-rehearse ack

2024-04-09 20:39 UTC, merged