[ART-9247] Create release-fips config
openshift/release pull request #50712
Opened 2024-04-08 16:12 UTC by ashwindasr

2024-04-08 16:13 UTC, ashwindasr commented
/test all

2024-04-08 16:15 UTC, ashwindasr commented
/pj-rehearse pull-ci-openshift-release-master-nightly-4.16-fips-payload-scan

2024-04-08 19:53 UTC, ashwindasr commented
/pj-rehearse pull-ci-openshift-release-master-nightly-4.16-fips-payload-scan

2024-04-08 20:43 UTC, ashwindasr commented
/pj-rehearse pull-ci-openshift-release-master-nightly-4.16-fips-payload-scan

2024-04-08 21:45 UTC, ashwindasr commented
/pj-rehearse pull-ci-openshift-release-master-nightly-4.16-fips-payload-scan

2024-04-08 21:48 UTC, ashwindasr commented
/pj-rehearse pull-ci-openshift-release-master-nightly-4.16-fips-payload-scan

2024-05-14 21:12 UTC, ashwindasr commented
/test all

2024-05-14 21:17 UTC, ashwindasr commented
/pj-rehearse pull-ci-openshift-release-master-nightly-4.16-fips-payload-scan

2024-05-14 22:17 UTC, ashwindasr commented
/pj-rehearse pull-ci-openshift-release-master-nightly-4.16-fips-payload-scan

2024-05-17 13:52 UTC, ashwindasr commented
/pj-rehearse pull-ci-openshift-release-master-nightly-4.16-fips-payload-scan

2024-05-17 17:04 UTC, ashwindasr commented
/pj-rehearse pull-ci-openshift-release-master-nightly-4.16-fips-payload-scan

2024-05-17 18:46 UTC, ashwindasr commented
/pj-rehearse pull-ci-openshift-release-master-nightly-4.16-fips-payload-scan

2024-05-20 14:09 UTC, ashwindasr commented
/uncc @deepsm007
/uncc @DennisPeriquet

2024-05-20 14:09 UTC, ashwindasr commented
/pj-rehearse pull-ci-openshift-release-master-nightly-4.16-fips-payload-scan

2024-05-20 15:27 UTC, ashwindasr commented
/pj-rehearse pull-ci-openshift-release-master-nightly-4.16-fips-payload-scan

2024-05-20 18:55 UTC, ashwindasr commented
/pj-rehearse pull-ci-openshift-release-master-nightly-4.16-fips-payload-scan

2024-05-20 20:25 UTC, bradmwilliams requested changes

2024-05-20 20:25 UTC, bradmwilliams commented on ci-operator/step-registry/openshift/release/fips/openshift-release-fips-commands.sh
> +
Is any of this is necessary?

2024-05-20 20:25 UTC, bradmwilliams commented on ci-operator/config/openshift/release/openshift-release-master__nightly-4.16.yaml
> +  steps:
I think you want this to be a `periodic` job...
You can add the following to enable a periodic:
```
interval: 168h
```

2024-05-20 20:25 UTC, bradmwilliams commented on ci-operator/config/openshift/release/openshift-release-master__nightly-4.16.yaml
> +    workflow: ipi-aws
I would go ahead and add this configuration to all the versions where the job will be ran from.
After this PR merges, you can chase it with the necessary update to add informing jobs to the respective releases.

2024-05-20 20:43 UTC, ashwindasr commented
/label tide/merge-method-squash

2024-05-20 20:44 UTC, ashwindasr commented on ci-operator/step-registry/openshift/release/fips/openshift-release-fips-commands.sh
> +
Apologies, cleaned

2024-05-20 20:46 UTC, ashwindasr commented
/test

2024-05-20 20:46 UTC, ashwindasr commented
/test v

2024-05-20 20:46 UTC, ashwindasr commented
/test core-valid

2024-05-20 20:52 UTC, bradmwilliams commented
/remove-lifecycle stale
/approve

2024-05-20 20:54 UTC, bradmwilliams commented
/pj-rehearse

2024-05-20 21:05 UTC, ashwindasr commented
/pj-rehearse

2024-05-21 01:27 UTC, ashwindasr commented
/pj-rehearse ack

The errors are not an issue. I'll update the excludes with check-payload

2024-05-21 13:54 UTC, bradmwilliams commented
/lgtm

2024-05-21 18:39 UTC, ashwindasr commented
/approve

2024-05-21 18:50 UTC, ashwindasr commented
/assign @vrutkovs

2024-05-21 20:03 UTC, neisw commented
/lgtm

2024-05-21 20:34 UTC, merged

2024-05-22 14:04 UTC, stbenjam commented on ci-operator/step-registry/openshift/release/fips/openshift-release-fips-commands.sh
> +payload_pullspec=$(oc get clusterversion version -o json | jq -r .status.desired.image)
I think this ends up just checking the payload image on the build cluster? You probably really do want to check `${RELEASE_IMAGE_LATEST}` so you're checking the payload under test

2024-05-22 14:19 UTC, stbenjam commented on ci-operator/step-registry/openshift/release/fips/openshift-release-fips-commands.sh
> +payload_pullspec=$(oc get clusterversion version -o json | jq -r .status.desired.image)
Disregard, we cleared this up on Slack