Add new `troubleshooting-panel-console-plugin` repo
openshift/release pull request #51065
Opened 2024-04-17 19:52 UTC by zhuje

The PR was created by

1. Running `make new-repo`
2. Editing `ci-operator/config/openshift/openshift-troubleshooting-panel-console-plugin/openshift-troubleshooting-panel-console-plugin-main.yaml` to add `openshift-troubleshooting-panel-console-plugin-test` similar to `monitoring-plugin`'s `monitoring-plugin-test`
3.  Running `make jobs`

2024-04-17 21:33 UTC, zhuje commented
/assign @jgbernalp

2024-04-18 07:01 UTC, jgbernalp requested changes

2024-04-18 14:40 UTC, zhuje commented on ci-operator/config/openshift/troubleshooting-panel-console-plugin/openshift-troubleshooting-panel-console-plugin-main.yaml
> +      name: "4.16"
Will update to: 
```
name: "0.1"
namespace: "observability-ui"
```

2024-04-18 14:43 UTC, zhuje commented on ci-operator/config/openshift/troubleshooting-panel-console-plugin/openshift-troubleshooting-panel-console-plugin-main.yaml
> +      name: "4.16"
Doublecheck if we can use the format above for `releases` as well.

2024-04-18 15:08 UTC, zhuje commented on ci-operator/jobs/openshift/troubleshooting-panel-console-plugin/openshift-troubleshooting-panel-console-plugin-main-presubmits.yaml
> +    - ^main$
We agreed for now we will leave this as main until we add the image mirror. We will then add the release as 0.1 
```
    branches:
    - ^release-0\.1$
 ```

2024-04-18 18:22 UTC, zhuje commented on ci-operator/jobs/openshift/troubleshooting-panel-console-plugin/openshift-troubleshooting-panel-console-plugin-main-presubmits.yaml
> +    - ^main$
As discussed, we will update this in a separate PR.

2024-04-18 19:12 UTC, zhuje commented on ci-operator/config/openshift/troubleshooting-panel-console-plugin/openshift-troubleshooting-panel-console-plugin-main.yaml
> +      name: "4.16"
"Most commonly, the same integration ImageStream is specified for ephemeral release snapshots as is for promotion" [1]

[1] https://docs.ci.openshift.org/docs/architecture/ci-operator/#testing-with-an-ephemeral-openshift-release

2024-04-18 20:21 UTC, zhuje commented
/pj-rehearse

2024-04-19 16:46 UTC, zhuje commented
/pj-rehearse

2024-04-26 14:03 UTC, zhuje commented on ci-operator/config/openshift/troubleshooting-panel-console-plugin/openshift-troubleshooting-panel-console-plugin-main.yaml
> +      name: "4.16"
The namespace `observability-ui` in the app.ci cluster was approved on April 24, 2024 in this PR: [https://github.com/openshift/release/pull/51216](https://github.com/openshift/release/pull/51216). 

I believe the rights to this namespace are managed by the [Rover group](https://rover.redhat.com/groups/), `observability-ui-admin` assigned within this file: https://github.com/openshift/release/tree/master/clusters/app.ci/registry-access/observability-ui](https://github.com/openshift/release/tree/master/clusters/app.ci/registry-access/observability-ui). 

To verify if you have rights to this namespace visit the [app.ci cluster ](https://console-openshift-console.apps.ci.l2s4.p1.openshiftapps.com/k8s/cluster/projects). `observability-ui` should be listed in the Projects page.

2024-04-26 16:02 UTC, zhuje commented
/pj-rehearse

2024-05-03 14:35 UTC, zhuje commented
/pj-rehearse

2024-05-03 14:56 UTC, zhuje commented
/pj-rehearse

2024-05-06 16:28 UTC, zhuje commented
/pj-reherase

2024-05-06 16:28 UTC, zhuje commented
/pj-rehearse

2024-05-07 11:48 UTC, zhuje commented
/pj-rehearse

2024-05-07 15:06 UTC, zhuje commented
/pj-rehearse

2024-05-08 14:05 UTC, zhuje commented
/pj-rehearse

2024-05-08 14:28 UTC, zhuje commented
/pj-rehearse ack

(/pj-rehearse tests passed, so adding rehearsals-ack label)

2024-05-08 14:56 UTC, zhuje commented
/pj-rehearse

2024-05-08 14:58 UTC, danilo-gemoli commented
/lgtm

2024-05-08 15:27 UTC, zhuje commented
/pj-rehearse ack

(/pj-rehearse tests passed, so adding rehearsals-ack label)

2024-05-08 15:44 UTC, merged