STONEBLD-2371 Tests for multi platform controller
openshift/release pull request #51236
Opened 2024-04-23 08:55 UTC by stuartwdouglas

2024-04-30 09:44 UTC, psturc commented
/ok-to-test

2024-04-30 13:35 UTC, psturc reviewed
@stuartwdouglas wondering, would it make sense to temporarily update [this script](https://github.com/openshift/release/blob/85869b3dc438e8465f082dd7dc39bc009e129a14/ci-operator/step-registry/redhat-appstudio/e2e/redhat-appstudio-e2e-commands.sh#L109) in this PR so it points to [your e2e-tests PR](https://github.com/redhat-appstudio/e2e-tests/pull/1134/files) and run rehearsal job to validate it works as expected?

2024-05-02 13:42 UTC, psturc commented
/pj-rehearse pull-ci-redhat-appstudio-multi-platform-controller-main-multi-platform-controller-e2e

2024-05-08 02:59 UTC, stuartwdouglas commented
@psturc any idea what those failures mean?

2024-05-13 18:26 UTC, psturc commented
/pj-rehearse pull-ci-redhat-appstudio-multi-platform-controller-main-multi-platform-controller-e2e

2024-05-13 18:27 UTC, psturc commented
/pj-rehearse abort

2024-05-13 18:32 UTC, psturc commented
/pj-rehearse abort

2024-05-13 18:35 UTC, psturc commented
> @psturc any idea what those failures mean?

run `make ci-operator-config` to address the error in [ci-operator-config job](https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_release/51236/pull-ci-openshift-release-master-ci-operator-config-metadata/1788030557486059520)

regarding the error in check-gh-automation job - it complains about 'openshift-cherrypick-robot' not having access to the repo. afaik we don't use that bot in our org so I think we can ignore this error

2024-05-13 18:36 UTC, psturc commented
@stuartwdouglas otherwise the rehearsal job needs at least [these changes](https://github.com/redhat-appstudio/e2e-tests/pull/1134#pullrequestreview-2036115374) to be addressed in order to be successful

2024-05-13 18:59 UTC, psturc commented
/test check-gh-automation

2024-05-13 19:00 UTC, psturc commented
/verify-owners

2024-05-13 19:09 UTC, psturc commented
@stuartwdouglas  looks like the label with invalid owners file won't disappear until you become a member of openshift org :/
could you request access to the org? guide for how to do that is [here](https://source.redhat.com/groups/public/openshift/openshift_wiki/openshift_onboarding_checklist_for_github)

2024-05-14 10:11 UTC, psturc commented
/pj-rehearse pull-ci-redhat-appstudio-multi-platform-controller-main-multi-platform-controller-e2e

2024-05-23 10:40 UTC, psturc commented
/pj-rehearse pull-ci-redhat-appstudio-multi-platform-controller-main-multi-platform-controller-e2e

2024-06-27 12:58 UTC, psturc commented
/pj-rehearse pull-ci-redhat-appstudio-multi-platform-controller-main-multi-platform-controller-e2e

2024-06-27 12:59 UTC, psturc requested changes

2024-06-27 12:59 UTC, psturc commented on ci-operator/config/redhat-appstudio/multi-platform-controller/redhat-appstudio-multi-platform-controller-main.yaml
> +    version: "4.13"
we've updated all jobs to use 4.14

```suggestion
    version: "4.14"
```

2024-07-27 21:47 UTC, closed without merging