[DRAFT] [DNM] adds aws-disconnected
openshift/release pull request #51814
Opened 2024-05-08 17:50 UTC by wgahnagl

open to have another alternative e2e test if wmco vsphere disconnected doesn't work

2024-05-08 18:09 UTC, wgahnagl commented
/pj-rehearse pull-ci-openshift-windows-machine-config-operator-master-aws-disconnected-e2e-operator

2024-05-08 19:00 UTC, wgahnagl commented
/pj-rehearse pull-ci-openshift-windows-machine-config-operator-master-aws-disconnected-e2e-operator

2024-05-08 20:17 UTC, wgahnagl commented
/pj-rehearse pull-ci-openshift-windows-machine-config-operator-master-aws-disconnected-e2e-operator

2024-05-09 13:44 UTC, sebsoto requested changes
the mirror images step is failing

2024-05-09 13:44 UTC, sebsoto commented on ci-operator/step-registry/windows/e2e/operator/test/aws-disconnected/post/windows-e2e-operator-test-aws-disconnected-post-chain.yaml
> +    - chain: upi-vsphere-windows-post
this shouldnt be vsphere

2024-05-09 13:44 UTC, sebsoto commented on ci-operator/step-registry/windows/e2e/operator/test/aws-disconnected/pre/windows-e2e-operator-test-aws-disconnected-pre-chain.yaml
> +    and a Windows instance in vSphere.
vSphere -> aws

2024-05-09 17:03 UTC, wgahnagl commented
/pj-rehearse pull-ci-openshift-windows-machine-config-operator-master-aws-disconnected-e2e-operator

2024-05-09 17:07 UTC, wgahnagl commented
/pj-rehearse pull-ci-openshift-windows-machine-config-operator-master-aws-disconnected-e2e-operator

2024-05-09 18:23 UTC, wgahnagl commented
/pj-rehearse pull-ci-openshift-windows-machine-config-operator-master-aws-disconnected-e2e-operator

2024-05-09 20:22 UTC, wgahnagl commented
oh my god the cluster failed to launch with a timeout 

/pj-rehearse pull-ci-openshift-windows-machine-config-operator-master-aws-disconnected-e2e-operator

2024-05-10 12:59 UTC, wgahnagl commented
/pj-rehearse pull-ci-openshift-windows-machine-config-operator-master-aws-disconnected-e2e-operator

2024-05-10 16:08 UTC, wgahnagl commented
/pj-rehearse pull-ci-openshift-windows-machine-config-operator-master-aws-disconnected-e2e-operator

getting some legitimately bizarre failures 
invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference) in the console operator, and Unable to connect to the server: dial tcp: lookup api.ci-op-v4gllnj4-66620.origin-ci-int-aws.dev.rhcloud.com on 172.30.0.10:53: no such host right after

2024-05-13 13:03 UTC, wgahnagl commented
/pj-rehearse pull-ci-openshift-windows-machine-config-operator-master-aws-disconnected-e2e-operator

the last failure was a documented bug, let's see if it's fixed this morning

2024-05-14 13:26 UTC, wgahnagl commented
/pj-rehearse pull-ci-openshift-windows-machine-config-operator-master-aws-disconnected-e2e-operator

it wasn't fixed! Maybe now?

2024-05-14 14:36 UTC, wgahnagl commented
/pj-rehearse pull-ci-openshift-windows-machine-config-operator-master-aws-disconnected-e2e-operator

why is this test so unstable, this is also a flake 
this is somehow more unstable than vsphere, which isn't even supposed to run as a CI job 

```
Created stack

Waiter StackCreateComplete failed: Waiter encountered a terminal failure state: For expression "Stacks[].StackStatus" we matched expected path: "ROLLBACK_COMPLETE" at least once
{"component":"entrypoint","error":"wrapped process failed: exit status 255","file":"sigs.k8s.io/prow/pkg/entrypoint/run.go:84","func":"sigs.k8s.io/prow/pkg/entrypoint.Options.internalRun","level":"error","msg":"Error executing test process","severity":"error","time":"2024-05-14T14:33:56Z"}
error: failed to execute wrapped command: exit status 255
```

2024-05-14 17:42 UTC, wgahnagl commented
/pj-rehearse pull-ci-openshift-windows-machine-config-operator-master-aws-disconnected-e2e-operator

test didn't flake the last time! 
Testing with a much cleaner version

2024-05-14 17:44 UTC, wgahnagl commented
/pj-rehearse pull-ci-openshift-windows-machine-config-operator-master-aws-disconnected-e2e-operator

2024-05-14 17:55 UTC, wgahnagl commented
/pj-rehearse pull-ci-openshift-windows-machine-config-operator-master-aws-disconnected-e2e-operator

didn't trigger argh

2024-05-14 18:31 UTC, wgahnagl commented
/pj-rehearse pull-ci-openshift-windows-machine-config-operator-master-aws-disconnected-e2e-operator

2024-05-14 18:47 UTC, wgahnagl commented
/pj-rehearse pull-ci-openshift-windows-machine-config-operator-master-aws-disconnected-e2e-operator

2024-05-14 18:55 UTC, wgahnagl commented
/pj-rehearse pull-ci-openshift-windows-machine-config-operator-master-aws-disconnected-e2e-operator

2024-05-14 19:28 UTC, wgahnagl commented
/pj-rehearse pull-ci-openshift-windows-machine-config-operator-master-aws-disconnected-e2e-operator

2024-05-15 14:20 UTC, wgahnagl commented
/pj-rehearse pull-ci-openshift-windows-machine-config-operator-master-aws-disconnected-e2e-operator

2024-05-15 18:32 UTC, wgahnagl commented
/pj-rehearse pull-ci-openshift-windows-machine-config-operator-master-aws-disconnected-e2e-operator

2024-05-15 20:19 UTC, wgahnagl commented
/pj-rehearse pull-ci-openshift-windows-machine-config-operator-master-aws-disconnected-e2e-operator

2024-05-16 13:04 UTC, wgahnagl commented
/pj-rehearse pull-ci-openshift-windows-machine-config-operator-master-aws-disconnected-e2e-operator

2024-05-16 13:59 UTC, wgahnagl commented
/pj-rehearse pull-ci-openshift-windows-machine-config-operator-master-aws-disconnected-e2e-operator 

another flake :(

2024-05-16 17:32 UTC, wgahnagl commented
/pj-rehearse pull-ci-openshift-windows-machine-config-operator-master-aws-disconnected-e2e-operator

2024-07-16 03:21 UTC, closed without merging