bumps to 4.17
openshift/release pull request #52175
Opened 2024-05-17 18:15 UTC by rauhersu

ci configuration to test the new 4.16 branch.

Changes target 'ztp'. 'cnf-tests' and 'dpdk' config still needs to be configured.

2024-05-17 21:19 UTC, nishant-parekh requested changes

2024-05-17 21:19 UTC, nishant-parekh commented on core-services/image-mirroring/openshift-kni/mapping_openshift-kni_quay
> +registry.ci.openshift.org/ocp-kni/4.16:ztp-site-generator quay.io/openshift-kni/ztp-site-generator:4.17 quay.io/openshift-kni/ztp-site-generator:4.17.0 quay.io/openshift-kni/ztp-site-generator:latest
ocp-kni/4.17

2024-05-17 21:20 UTC, nishant-parekh commented
/ok-to-test

2024-05-21 10:59 UTC, rauhersu commented on core-services/image-mirroring/openshift-kni/mapping_openshift-kni_quay
> +registry.ci.openshift.org/ocp-kni/4.16:ztp-site-generator quay.io/openshift-kni/ztp-site-generator:4.17 quay.io/openshift-kni/ztp-site-generator:4.17.0 quay.io/openshift-kni/ztp-site-generator:latest
good catch, fixed !

2024-05-21 12:25 UTC, nishant-parekh commented
/pj-rehearse auto-ack

2024-05-21 12:25 UTC, nishant-parekh approved these changes
/approve
/lgtm

2024-05-27 16:11 UTC, rauhersu commented
/pj-rehearse auto-ack

2024-05-27 16:33 UTC, nishant-parekh approved these changes
/lgtm
/approve

2024-05-28 11:33 UTC, rauhersu commented
/retest

2024-05-29 16:58 UTC, rauhersu commented
/retest 

dependant MR merged already: https://github.com/openshift-kni/cnf-features-deploy/pull/1915

2024-05-29 17:02 UTC, rauhersu commented
/retest

2024-05-29 17:04 UTC, rauhersu commented
/pj-rehearse auto-ack

2024-06-03 16:50 UTC, rauhersu commented
/pj-rehearse auto-ack

2024-06-07 09:45 UTC, rauhersu commented
/pj-rehearse auto-ack

2024-06-12 11:19 UTC, rauhersu commented
/retest

2024-06-12 11:27 UTC, rauhersu commented
/pj-rehearse auto-ack

2024-06-12 17:45 UTC, rauhersu commented
/pj-rehearse auto-ack

2024-06-17 11:16 UTC, rauhersu commented
/pj-rehearse auto-ack

2024-06-21 16:39 UTC, SchSeba commented
/pj-rehearse ack
/lgtm
/approve

2024-06-21 16:40 UTC, SchSeba commented
/pj-rehearse ack

2024-06-21 17:06 UTC, merged