Adding loaded upgrade for ibmcloud on prow
openshift/release pull request #52637
Opened 2024-05-30 19:33 UTC by shahsahil264

2024-05-30 19:36 UTC, shahsahil264 commented
/pj-rehearse periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-ibmcloud-4.16-nightly-x86-loaded-upgrade-from-4.15-loaded-upgrade-415to416-24nodes

2024-05-30 20:29 UTC, shahsahil264 commented
/pj-rehearse periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-ibmcloud-4.16-nightly-x86-loaded-upgrade-from-4.15-loaded-upgrade-415to416-24nodes

2024-05-31 16:40 UTC, shahsahil264 commented
/pj-rehearse periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-ibmcloud-4.16-nightly-x86-loaded-upgrade-from-4.15-loaded-upgrade-415to416-24nodes

2024-06-03 20:36 UTC, shahsahil264 commented
/pj-rehearse periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-ibmcloud-4.16-nightly-x86-loaded-upgrade-from-4.15-loaded-upgrade-415to416-24nodes

2024-06-03 21:37 UTC, shahsahil264 commented
/pj-rehearse periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-ibmcloud-4.16-nightly-x86-loaded-upgrade-from-4.15-loaded-upgrade-415to416-24nodes

2024-06-04 16:16 UTC, shahsahil264 commented
@paigerube14 can you PTAL and approve?

2024-06-07 03:44 UTC, qiliRedHat requested changes
We use 'always_run: false' for the jobs that we don't want to run in cron.

2024-06-07 03:44 UTC, qiliRedHat commented on ci-operator/config/openshift-qe/ocp-qe-perfscale-ci/openshift-qe-ocp-qe-perfscale-ci-main__ibmcloud-4.16-nightly-x86-loaded-upgrade-from-4.15.yaml
> +- as: loaded-upgrade-415to416-24nodes
```suggestion
- always_run: false
  as: loaded-upgrade-415to416-24nodes
```

2024-06-11 08:11 UTC, qiliRedHat commented
/lgtm

2024-06-11 08:11 UTC, qiliRedHat commented
/approve

2024-06-14 14:38 UTC, shahsahil264 commented
LGTM

2024-06-20 19:51 UTC, shahsahil264 commented
@qiliRedHat Can you PTAL and add the lgtm tag?

2024-06-21 01:52 UTC, qiliRedHat commented
@shahsahil264 I've added /lgtm and /approve, you can see them in the right top corner 'Labels'. What is needed in this pr may be /pj-rehearse ack. Let me try.

2024-06-21 01:52 UTC, qiliRedHat commented
/pj-rehearse ack

2024-06-24 02:50 UTC, qiliRedHat commented
/lgtm

2024-06-24 02:50 UTC, qiliRedHat commented
/unhold

2024-06-24 06:14 UTC, qiliRedHat commented
/pj-rehearse ack

2024-06-24 06:32 UTC, merged