Amd
openshift/release pull request #53309
Opened 2024-06-17 18:44 UTC by dibryant

Adding CI builds for AMD Pytorch and Tensorflow.

2024-06-20 19:30 UTC, harshad16 commented
/ok-to-test

2024-06-21 08:36 UTC, atheo89 requested changes
Added some review commends. Once you pass this PR from a second iteration of fixes you will need to run on your PC `make job` this will auto generate some files that will fix the complaining jobs

2024-06-25 16:57 UTC, harshad16 requested changes
Thank you for the awesome work
some comments.

2024-06-25 16:57 UTC, harshad16 commented on ci-operator/config/opendatahub-io/notebooks/opendatahub-io-notebooks-main.yaml
> +- context_dir: jupyter/tensorflow/ubi9-python-3.9
```suggestion
- context_dir: jupyter/amd/tensorflow/ubi9-python-3.9
```

2024-06-25 16:57 UTC, harshad16 commented on ci-operator/config/opendatahub-io/notebooks/opendatahub-io-notebooks-main.yaml
> +- context_dir: jupyter/pytorch/ubi9-python-3.9
```suggestion
- context_dir: jupyter/amd/pytorch/ubi9-python-3.9
```

2024-06-25 16:57 UTC, harshad16 commented on ci-operator/config/opendatahub-io/notebooks/opendatahub-io-notebooks-main.yaml
> +    workflow: opendatahub-io-ci-image-mirror
For now, we can drop the AMD data-science and minimal, as we are not gonna provide them in.
leaving this for future.

Remove these lines, and the minimal as well, as we don't really provide them to the user.

2024-06-25 16:57 UTC, harshad16 commented on ci-operator/config/opendatahub-io/notebooks/opendatahub-io-notebooks-main.yaml
> +  to: amd-jupyter-minimal-ubi9-python-3.9
```suggestion
  to: amd-jupyter-minimal-c9s-python-3.9
```


Even though we use the directory, ubi9-python-3.9
we are still basing these on centos , so we should use the centos in naming them
can you do this for the below ones as well.

2024-06-27 08:36 UTC, atheo89 commented on ci-operator/config/opendatahub-io/notebooks/opendatahub-io-notebooks-main.yaml
> +  from: amd-jupyter-datascience-ubi9-python-3.9
This `amd-jupyter-datascience-ubi9-python-3.9` is not build (amd specific), I think you need here `jupyter-datascience-ubi9-python-3.9`

And again, once you apply the changes please run from your pc `make jobs` this command will fix some of the tests and also will autogenerate the post-submit jobs

2024-06-27 13:56 UTC, dibryant commented
/ok-to-test

2024-06-28 07:41 UTC, atheo89 commented
https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_release/53309/pull-ci-openshift-release-master-generated-config/1806328621720145920

```
ERROR: Run the following command to re-generate the Prow jobs:
ERROR: $ make jobs
```

2024-06-28 08:00 UTC, atheo89 requested changes
New iteration of comments

2024-06-28 08:00 UTC, atheo89 commented on ci-operator/config/opendatahub-io/notebooks/opendatahub-io-notebooks-main.yaml
> +  run_if_changed: (amd\/ubi9-python-3.9\/*)|(base\/ubi9-python-3.9\/*)|(jupyter\/minimal\/ubi9-python-3.9\/*)|(jupyter\/datascience\/ubi9-python-3.9\/*)|(jupyter\/amd\/tensorflow\/ubi9-python-3.9\/*)
```suggestion
  run_if_changed: (amd\/c9s-python-3.9\/*)|(jupyter\/datascience\/ubi9-python-3.9\/*)|(jupyter\/amd\/tensorflow\/ubi9-python-3.9\/*)
```

2024-06-28 08:00 UTC, atheo89 commented on ci-operator/config/opendatahub-io/notebooks/opendatahub-io-notebooks-main.yaml
> +  run_if_changed: (amd\/ubi9-python-3.9\/*)|(base\/ubi9-python-3.9\/*)|(jupyter\/minimal\/ubi9-python-3.9\/*)|(jupyter\/datascience\/ubi9-python-3.9\/*)|(jupyter\/amd\/pytorch\/ubi9-python-3.9\/*)
```suggestion
  run_if_changed: (amd\/c9s-python-3.9\/*)|(jupyter\/datascience\/ubi9-python-3.9\/*)|(jupyter\/amd\/pytorch\/ubi9-python-3.9\/*)
```

2024-06-28 08:00 UTC, atheo89 commented on ci-operator/config/opendatahub-io/notebooks/opendatahub-io-notebooks-main.yaml
> +  run_if_changed: (base\/ubi9-python-3.9\/*)|(jupyter\/minimal\/ubi9-python-3.9\/*)|(jupyter\/datascience\/ubi9-python-3.9\/*)|(amd\/*)
```suggestion
  run_if_changed: (amd\/c9s-python-3.9\/*)||(jupyter\/datascience\/ubi9-python-3.9\/*)|(jupyter\/amd\/pytorch\/ubi9-python-3.9\/*)||(jupyter\/amd\/tensorflow\/ubi9-python-3.9\/*)
```

2024-06-28 08:00 UTC, atheo89 commented on ci-operator/config/opendatahub-io/notebooks/opendatahub-io-notebooks-main.yaml
> +    - as: amd-jupyter-ubi9-python-3.9-test-e2e
```suggestion
    - as: amd-jupyter-tensorflow-python-3.9-test-e2e
```

2024-06-28 08:00 UTC, atheo89 commented on ci-operator/config/opendatahub-io/notebooks/opendatahub-io-notebooks-main.yaml
> +        oc new-project amd-jupyter-ubi9-python-3-9
```suggestion
        oc new-project amd-jupyter-tensorflow-python-3-9
```

2024-06-28 08:00 UTC, atheo89 commented on ci-operator/config/opendatahub-io/notebooks/opendatahub-io-notebooks-main.yaml
> +        IFS=':' read -r -a NOTEBOOK_IMAGE <<< "${JUPYTER_AMD_IMAGE}"
```suggestion
        IFS=':' read -r -a NOTEBOOK_IMAGE <<< "${JUPYTER_AMD__TENSORFLOW_IMAGE}"
```

2024-06-28 08:00 UTC, atheo89 commented on ci-operator/config/opendatahub-io/notebooks/opendatahub-io-notebooks-main.yaml
> +        make deploy8-amd-ubi9-python-3.9 \
```suggestion
        make deploy9-amd-ubi9-python-3.9 \
```
Not tested, but to be sure please check it localy with the makefile

2024-06-28 08:00 UTC, atheo89 commented on ci-operator/config/opendatahub-io/notebooks/opendatahub-io-notebooks-main.yaml
> +        make undeploy8-amd-ubi9-python-3.9
```suggestion
        make undeploy9-amd-ubi9-python-3.9
```

2024-06-28 08:00 UTC, atheo89 commented on ci-operator/config/opendatahub-io/notebooks/opendatahub-io-notebooks-main.yaml
> +      - env: JUPYTER_AMD_IMAGE
```suggestion
      - env: JUPYTER_AMD__TENSORFLOW_IMAGE
```

2024-06-28 08:00 UTC, atheo89 commented on ci-operator/config/opendatahub-io/notebooks/opendatahub-io-notebooks-main.yaml
> +        name: amd-jupyter-ubi9-python-3.9
```suggestion
        name: amd-jupyter-tensorflow-python-3.9
```

2024-06-28 08:00 UTC, atheo89 commented on ci-operator/config/opendatahub-io/notebooks/opendatahub-io-notebooks-main.yaml
> +- as: amd-notebooks-e2e-tests
Right now, we have test only for tensorflow, you will need to do the same for pytorch .
Hint: copy the lines from 1530-1546 and replace it accordingly

2024-06-28 13:23 UTC, dibryant commented
/ok-to-test

2024-06-28 14:04 UTC, dibryant commented
/ok-to-test

2024-07-01 12:52 UTC, atheo89 commented
/lgtm

2024-07-01 19:39 UTC, harshad16 commented
/hold
reviewing

2024-07-01 19:49 UTC, harshad16 requested changes
Require following changes for the build of AMD based TF and PyTorch

2024-07-01 19:49 UTC, harshad16 commented on ci-operator/config/opendatahub-io/notebooks/opendatahub-io-notebooks-main.yaml
> +- context_dir: jupyter/amd/pytorch/ubi9-python-3.9
We need to build minimal,datascience with AMD
however we don't push them to quay.io, they would only be used for building 
pytorch and tensorflow.

```suggestion
- context_dir: jupyter/minimal/ubi9-python-3.9
  dockerfile_path: Dockerfile
  from: amd-c9s-python-3.9
  to: amd-jupyter-minimal-c9s-python-3.9
- context_dir: jupyter/data-science/ubi9-python-3.9
  dockerfile_path: Dockerfile
  from: amd-jupyter-minimal-c9s-python-3.9
  to: amd-jupyter-datascience-c9s-python-3.9
- context_dir: jupyter/amd/tensorflow/ubi9-python-3.9
  dockerfile_path: Dockerfile
  from: amd-jupyter-datascience-c9s-python-3.9
  to: amd-jupyter-tensorflow-c9s-python-3.9
- context_dir: jupyter/amd/pytorch/ubi9-python-3.9
```



Even though we are using c9s base image, we use the structure of ubi9-python3.9 in others
as there is no OS based information.

2024-07-04 09:53 UTC, atheo89 commented
/pj-rehearse pull-ci-opendatahub-io-notebooks-main-notebook-rocm-c9s-python-3-9-pr-image-mirror pull-ci-opendatahub-io-notebooks-main-notebook-rocm-jupyter-pyt-c9s-python-3-9-pr-image-mirror pull-ci-opendatahub-io-notebooks-main-notebook-rocm-jupyter-tf-c9s-python-3-9-pr-image-mirror pull-ci-opendatahub-io-notebooks-main-rocm-notebooks-e2e-tests

2024-07-05 13:19 UTC, dibryant commented
/retest

2024-07-08 12:23 UTC, atheo89 commented
@dibryant PTAL, Once this pull request https://github.com/opendatahub-io/notebooks/pull/609 is merged, it will fix the failed test for the TensorFlow image build.

2024-07-08 12:30 UTC, atheo89 commented
/retest

2024-07-08 12:32 UTC, atheo89 commented
/retest-required ci/rehearse/opendatahub-io/notebooks/main/notebook-rocm-jupyter-tf-c9s-python-3-9-pr-image-mirror

2024-07-09 11:50 UTC, jiridanek commented
The right command should actually be
/pj-rehearse pull-ci-opendatahub-io-notebooks-main-notebook-rocm-jupyter-tf-c9s-python-3-9-pr-image-mirror

2024-07-09 11:52 UTC, jiridanek commented
ah, ok, so rebase needs to be done first, then we can rehearse, and then hopefully this will work

2024-07-19 12:31 UTC, harshad16 approved these changes
/lgtm
/approve
/unhold
/pj-rehearse ack
thanks :+1:

2024-07-19 15:20 UTC, harshad16 commented
/lgtm
/approve
/pj-rehearse ack
thanks 👍

2024-07-19 15:25 UTC, merged