chore: upgrade registry-operator tests to ocp 4.15
openshift/release pull request #53498
Opened 2024-06-20 18:45 UTC by thepetk

Upgrades the registry operator ci-operator-config and jobs to use ocp 4.15

Related to https://github.com/devfile/registry-operator/pull/91

2024-06-20 21:17 UTC, michael-valdron commented
/pj-rehearse auto-ack

2024-06-20 21:20 UTC, michael-valdron requested changes

2024-06-20 21:20 UTC, michael-valdron commented on ci-operator/config/devfile/registry-operator/devfile-registry-operator-main__v4.15.yaml
`tag` should be `golang-1.21`

2024-06-20 21:20 UTC, michael-valdron commented on ci-operator/config/devfile/registry-operator/devfile-registry-operator-release-v0__v4.15.yaml
`tag` should be `golang-1.21`

2024-06-21 12:10 UTC, thepetk commented on ci-operator/config/devfile/registry-operator/devfile-registry-operator-release-v0__v4.15.yaml
I think something got messed up. I've updated it again.

2024-06-21 14:20 UTC, michael-valdron commented
/pj-rehearse auto-ack

2024-06-21 14:24 UTC, michael-valdron approved these changes
/lgtm

Once the rehearsal passes the PR can be put into the merge pool.

2024-06-21 16:49 UTC, merged