WIP:jws onboarding on ibmcloud
openshift/release pull request #53635
Opened 2024-06-25 16:51 UTC by smatula

2024-06-25 17:17 UTC, smatula commented
/pj-rehearse periodic-ci-jws-qe-interop-ocp-ci-main-ocp-4.14-lp-interop-jws-interop-ibmcloud periodic-ci-jws-qe-interop-ocp-ci-main-ocp-4.15-lp-interop-jws-interop-ibmcloud

2024-06-25 19:04 UTC, smatula commented
/pj-rehearse periodic-ci-jws-qe-interop-ocp-ci-main-ocp-4.14-lp-interop-jws-interop-ibmcloud periodic-ci-jws-qe-interop-ocp-ci-main-ocp-4.15-lp-interop-jws-interop-ibmcloud

2024-06-26 11:21 UTC, smatula commented
/pj-rehearse periodic-ci-jws-qe-interop-ocp-ci-main-ocp-4.14-lp-interop-jws-interop-ibmcloud

2024-06-26 13:07 UTC, smatula commented
/pj-rehearse periodic-ci-jws-qe-interop-ocp-ci-main-ocp-4.15-lp-interop-jws-interop-ibmcloud

2024-06-26 17:15 UTC, smatula commented
/pj-rehearse periodic-ci-jws-qe-interop-ocp-ci-main-ocp-4.14-lp-interop-jws-interop-ibmcloud

2024-06-26 19:07 UTC, smatula commented
/pj-rehearse periodic-ci-jws-qe-interop-ocp-ci-main-ocp-4.15-lp-interop-jws-interop-ibmcloud

2024-06-27 10:39 UTC, smatula commented
/pj-rehearse periodic-ci-jws-qe-interop-ocp-ci-main-ocp-4.14-lp-interop-jws-interop-ibmcloud periodic-ci-jws-qe-interop-ocp-ci-main-ocp-4.15-lp-interop-jws-interop-ibmcloud

2024-06-27 12:34 UTC, smatula commented
/pj-rehearse periodic-ci-jws-qe-interop-ocp-ci-main-ocp-4.15-lp-interop-jws-interop-ibmcloud

2024-07-01 10:59 UTC, smatula commented
/pj-rehearse periodic-ci-jws-qe-interop-ocp-ci-main-ocp-4.14-lp-interop-jws-interop-ibmcloud periodic-ci-jws-qe-interop-ocp-ci-main-ocp-4.15-lp-interop-jws-interop-ibmcloud

2024-07-01 12:27 UTC, smatula commented
/pj-rehearse periodic-ci-jws-qe-interop-ocp-ci-main-ocp-4.14-lp-interop-jws-interop-aws periodic-ci-jws-qe-interop-ocp-ci-main-ocp-4.15-lp-interop-jws-interop-aws

2024-07-03 10:52 UTC, smatula commented
/pj-rehearse periodic-ci-jws-qe-interop-ocp-ci-main-ocp-4.14-lp-interop-jws-interop-ibmcloud periodic-ci-jws-qe-interop-ocp-ci-main-ocp-4.15-lp-interop-jws-interop-ibmcloud

2024-07-03 12:21 UTC, smatula commented
/pj-rehearse periodic-ci-jws-qe-interop-ocp-ci-main-ocp-4.14-lp-interop-jws-interop-ibmcloud periodic-ci-jws-qe-interop-ocp-ci-main-ocp-4.15-lp-interop-jws-interop-ibmcloud

2024-07-03 15:04 UTC, smatula commented
/pj-rehearse periodic-ci-jws-qe-interop-ocp-ci-main-ocp-4.14-lp-interop-jws-interop-ibmcloud periodic-ci-jws-qe-interop-ocp-ci-main-ocp-4.15-lp-interop-jws-interop-ibmcloud

2024-07-08 11:08 UTC, smatula commented
/pj-rehearse periodic-ci-jws-qe-interop-ocp-ci-main-ocp-4.14-lp-interop-jws-interop-ibmcloud periodic-ci-jws-qe-interop-ocp-ci-main-ocp-4.15-lp-interop-jws-interop-ibmcloud

2024-07-08 12:16 UTC, smatula commented
/pj-rehearse periodic-ci-jws-qe-interop-ocp-ci-main-ocp-4.15-lp-interop-jws-interop-ibmcloud periodic-ci-jws-qe-interop-ocp-ci-main-ocp-4.16-lp-interop-jws-interop-ibmcloud

2024-07-10 11:56 UTC, smatula commented
/pj-rehearse periodic-ci-jws-qe-interop-ocp-ci-main-ocp-4.15-lp-interop-jws-interop-ibmcloud periodic-ci-jws-qe-interop-ocp-ci-main-ocp-4.16-lp-interop-jws-interop-ibmcloud

2024-07-11 16:36 UTC, smatula commented
/pj-rehearse periodic-ci-jws-qe-interop-ocp-ci-main-ocp-4.15-lp-interop-jws-interop-ibmcloud periodic-ci-jws-qe-interop-ocp-ci-main-ocp-4.16-lp-interop-jws-interop-ibmcloud

2024-07-12 10:34 UTC, smatula commented
/pj-rehearse periodic-ci-jws-qe-interop-ocp-ci-main-ocp-4.16-lp-interop-jws-interop-ibmcloud

2024-07-15 16:46 UTC, smatula commented
/pj-rehearse periodic-ci-jws-qe-interop-ocp-ci-main-ocp-4.15-lp-interop-jws-interop-ibmcloud periodic-ci-jws-qe-interop-ocp-ci-main-ocp-4.16-lp-interop-jws-interop-ibmcloud

2024-07-16 12:45 UTC, smatula commented
/pj-rehearse ack

2024-07-16 13:12 UTC, calebevans requested changes

2024-07-16 13:12 UTC, calebevans commented on ci-operator/config/jws-qe/interop-ocp-ci/jws-qe-interop-ocp-ci-main__ocp-4.14-lp-interop.yaml
>                {"jira_project": "CSPIT", "jira_additional_labels": ["!default"]}
We can remove the success rules as it is already defined in https://raw.githubusercontent.com/CSPI-QE/cspi-utils/main/firewatch-base-configs/aws-ipi/lp-interop.json 

Should be able to remove it from all the configs in this PR

2024-07-16 13:13 UTC, Simranpal approved these changes
/lgtm

2024-07-16 13:58 UTC, smatula commented
/pj-rehearse ack

2024-07-16 14:12 UTC, calebevans approved these changes
/lgtm

2024-07-16 14:29 UTC, merged