WIP: Onboard SSO On HyperShift
openshift/release pull request #53872
Opened 2024-07-01 19:51 UTC by liswang89

2024-07-02 16:23 UTC, liswang89 commented
/test check-gh-automation

2024-07-10 13:14 UTC, liswang89 commented
/test check-gh-automation

2024-07-11 11:13 UTC, liswang89 commented
/pj-rehearse periodic-ci-rhbk-interop-ocp-ci-main-rhsso-product-ocp4.14-lp-rosa-hypershift-rhsso-interop-aws

2024-07-11 14:40 UTC, liswang89 commented
/pj-rehearse periodic-ci-rhbk-interop-ocp-ci-main-rhsso-product-ocp4.14-lp-rosa-hypershift-rhsso-interop-aws

2024-07-11 14:40 UTC, liswang89 commented
/pj-rehearse periodic-ci-rhbk-interop-ocp-ci-main-rhsso-product-ocp4.15-lp-rosa-hypershift-rhsso-interop-aws

2024-07-11 16:13 UTC, liswang89 commented
/pj-rehearse periodic-ci-rhbk-interop-ocp-ci-main-rhsso-product-ocp4.15-lp-rosa-hypershift-rhsso-interop-aws

2024-07-11 18:56 UTC, calebevans requested changes

2024-07-11 18:56 UTC, calebevans commented on ci-operator/jobs/rhbk/interop-ocp-ci/rhbk-interop-ocp-ci-main-periodics.yaml
>    name: periodic-ci-rhbk-interop-ocp-ci-main-rhsso-product-ocp4.14-lp-interop-rhsso-interop-ibmcloud
Need a slack config here

2024-07-11 18:56 UTC, calebevans commented on ci-operator/jobs/rhbk/interop-ocp-ci/rhbk-interop-ocp-ci-main-periodics.yaml
>    name: periodic-ci-rhbk-interop-ocp-ci-main-rhsso-product-ocp4.15-lp-interop-rhsso-interop-ibmcloud
Slack config was removed by `make update` here

2024-07-11 18:56 UTC, calebevans commented on ci-operator/config/rhbk/interop-ocp-ci/rhbk-interop-ocp-ci-main__rhsso-product-ocp4.15-lp-rosa-hypershift.yaml
> +          "success_rules":
You can remove the "success_rules" here. They are in https://raw.githubusercontent.com/CSPI-QE/cspi-utils/main/firewatch-base-configs/aws-ipi/lp-interop.json already.

2024-07-11 18:56 UTC, calebevans commented on ci-operator/config/rhbk/interop-ocp-ci/rhbk-interop-ocp-ci-main__rhsso-product-ocp4.14-lp-rosa-hypershift.yaml
> +          "success_rules":
We can remove success rules

2024-07-12 13:35 UTC, calebevans approved these changes

2024-07-12 13:36 UTC, calebevans commented
/lgtm

2024-07-12 13:38 UTC, liswang89 commented on ci-operator/jobs/rhbk/interop-ocp-ci/rhbk-interop-ocp-ci-main-periodics.yaml
>    name: periodic-ci-rhbk-interop-ocp-ci-main-rhsso-product-ocp4.14-lp-interop-rhsso-interop-ibmcloud
updated.

2024-07-12 13:38 UTC, liswang89 commented on ci-operator/jobs/rhbk/interop-ocp-ci/rhbk-interop-ocp-ci-main-periodics.yaml
>    name: periodic-ci-rhbk-interop-ocp-ci-main-rhsso-product-ocp4.15-lp-interop-rhsso-interop-ibmcloud
updated.

2024-07-12 13:38 UTC, liswang89 commented on ci-operator/config/rhbk/interop-ocp-ci/rhbk-interop-ocp-ci-main__rhsso-product-ocp4.14-lp-rosa-hypershift.yaml
> +          "success_rules":
updated.

2024-07-12 13:39 UTC, liswang89 commented
/pj-rehearse ack

2024-07-12 14:04 UTC, merged