Add 4.17 Rosa tests and adjust crons for all versions for Classic Rosa and HCP
openshift/release pull request #54275
Opened 2024-07-11 19:36 UTC by svetsa-rh

I am adding 4.17 tests for Classic Rosa and HCP. 
No tests will be executed when merging tests this time, if any failures as part of Jedi, we will start looking. 
I am thinking of taking this approach so that we don't miss adding tests to the repo unlike 4.16 release where we realized missing tests on the day of release.

Need to adjust cron. Seeking @afcollins help.
4.17 to be weekly,
4.16 and 4.15 - bi-weekly and
4.14 and below, once a month

2024-07-11 21:25 UTC, afcollins commented on ci-operator/config/openshift-qe/ocp-qe-perfscale-ci/openshift-qe-ocp-qe-perfscale-ci-main__rosa_hcp-4.17-nightly-x86.yaml
> +  cron: 0 1 9,23 * *
suggest: `0 2 9,23 * *`

2024-07-11 21:26 UTC, afcollins commented on ci-operator/config/openshift-qe/ocp-qe-perfscale-ci/openshift-qe-ocp-qe-perfscale-ci-main__rosa-4.17-nightly-x86.yaml
> +  cron: 0 4 9,23 * *
suggest: `0 11 9,23 * *`

2024-07-11 21:36 UTC, svetsa-rh commented
/pj-rehearse 
periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-rosa_hcp-4.17-nightly-x86-node-density-heavy-24nodes
periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-rosa_hcp-4.17-nightly-x86-control-plane-24nodes
periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-rosa_hcp-4.17-nightly-x86-data-path-9nodes
periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-rosa-4.17-nightly-x86-control-plane-24nodes
periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-rosa-4.17-nightly-x86-data-path-9nodes
periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-rosa-4.17-nightly-x86-node-density-heavy-24nodes
periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-rosa-4.17-nightly-x86-control-plane-120nodes

2024-07-11 21:49 UTC, svetsa-rh commented on ci-operator/config/openshift-qe/ocp-qe-perfscale-ci/openshift-qe-ocp-qe-perfscale-ci-main__rosa_hcp-4.17-nightly-x86.yaml
> +  cron: 0 1 9,23 * *
@afcollins we need this weekly for 4.17

2024-07-11 21:49 UTC, svetsa-rh commented on ci-operator/config/openshift-qe/ocp-qe-perfscale-ci/openshift-qe-ocp-qe-perfscale-ci-main__rosa-4.17-nightly-x86.yaml
> +  cron: 0 4 9,23 * *
@afcollins we need this weekly for 4.17

2024-07-11 21:50 UTC, svetsa-rh commented on ci-operator/config/openshift-qe/ocp-qe-perfscale-ci/openshift-qe-ocp-qe-perfscale-ci-main__rosa_hcp-4.17-nightly-x86.yaml
> +  cron: 0 1 9,23 * *
Same for all new 4.17 tests

2024-07-11 21:50 UTC, svetsa-rh commented on ci-operator/config/openshift-qe/ocp-qe-perfscale-ci/openshift-qe-ocp-qe-perfscale-ci-main__rosa-4.17-nightly-x86.yaml
> +  cron: 0 4 9,23 * *
Same for all new 4.17 tests

2024-07-11 22:00 UTC, afcollins commented on ci-operator/config/openshift-qe/ocp-qe-perfscale-ci/openshift-qe-ocp-qe-perfscale-ci-main__rosa-4.17-nightly-x86.yaml
> +  cron: 0 4 9,23 * *
:(

2024-07-11 22:14 UTC, afcollins commented on ci-operator/config/openshift-qe/ocp-qe-perfscale-ci/openshift-qe-ocp-qe-perfscale-ci-main__rosa_hcp-4.17-nightly-x86.yaml
> +  cron: 0 1 9,23 * *
same as above: `"0 9 2,9,16,23 * *"`

2024-07-11 22:16 UTC, afcollins commented on ci-operator/config/openshift-qe/ocp-qe-perfscale-ci/openshift-qe-ocp-qe-perfscale-ci-main__rosa_hcp-4.17-nightly-x86.yaml
> +  cron: 0 1 12,26 * *
suggest: `0 5 5,12,19,26 * *`

2024-07-11 22:16 UTC, afcollins commented on ci-operator/config/openshift-qe/ocp-qe-perfscale-ci/openshift-qe-ocp-qe-perfscale-ci-main__rosa-4.17-nightly-x86.yaml
> +  cron: 0 2 5,19 * *
suggest: `0 7 5,12,19,26 * *`

2024-07-12 01:09 UTC, svetsa-rh commented
/pj-rehearse
periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-rosa_hcp-4.17-nightly-x86-node-density-heavy-24nodes
periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-rosa_hcp-4.17-nightly-x86-control-plane-24nodes
periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-rosa_hcp-4.17-nightly-x86-data-path-9nodes
periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-rosa-4.17-nightly-x86-control-plane-24nodes
periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-rosa-4.17-nightly-x86-data-path-9nodes
periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-rosa-4.17-nightly-x86-node-density-heavy-24nodes
periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-rosa-4.17-nightly-x86-control-plane-120nodes

2024-07-12 03:36 UTC, svetsa-rh commented
/pj-rehearse periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-rosa-4.17-nightly-x86-node-density-heavy-24nodes

2024-07-12 03:40 UTC, svetsa-rh commented
/pj-rehearse periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-rosa_hcp-4.17-nightly-x86-data-path-9nodes

2024-07-12 03:44 UTC, svetsa-rh commented
/pj-rehearse periodic-ci-openshift-qe-ocp-qe-perfscale-ci-main-rosa_hcp-4.17-nightly-x86-control-plane-24nodes

2024-07-12 19:48 UTC, afcollins commented on ci-operator/config/openshift-qe/ocp-qe-perfscale-ci/openshift-qe-ocp-qe-perfscale-ci-main__rosa-4.17-nightly-x86.yaml
> +  cron: 0 20 4,11,18,25 * *
conflicts with 4.13 . Suggest: `"0 6 4,11,18,25 * *"`

2024-07-12 19:49 UTC, afcollins commented on ci-operator/config/openshift-qe/ocp-qe-perfscale-ci/openshift-qe-ocp-qe-perfscale-ci-main__rosa_hcp-4.17-nightly-x86.yaml
> +  cron: 0 9 2,9,16,23 * *
Good!

2024-07-12 19:50 UTC, afcollins commented on ci-operator/config/openshift-qe/ocp-qe-perfscale-ci/openshift-qe-ocp-qe-perfscale-ci-main__rosa-4.17-nightly-x86.yaml
> +  cron: 0 11 2,9,16,23 * *
good!

2024-07-12 19:50 UTC, afcollins commented on ci-operator/config/openshift-qe/ocp-qe-perfscale-ci/openshift-qe-ocp-qe-perfscale-ci-main__rosa-4.17-nightly-x86.yaml
> +  cron: 0 11 1,8,15,22 * *
good

2024-07-12 19:51 UTC, afcollins commented on ci-operator/config/openshift-qe/ocp-qe-perfscale-ci/openshift-qe-ocp-qe-perfscale-ci-main__rosa_hcp-4.17-nightly-x86.yaml
> +  cron: 0 1 1,8,15,22 * *
same hour as 4.16 hcp .

Spreading is less important with data-path jobs. So, this could be fine unchanged.

2024-07-12 19:52 UTC, afcollins commented on ci-operator/config/openshift-qe/ocp-qe-perfscale-ci/openshift-qe-ocp-qe-perfscale-ci-main__rosa_hcp-4.17-nightly-x86.yaml
> +  cron: 0 5 5,12,19,26 * *
good

2024-07-12 19:52 UTC, afcollins commented on ci-operator/config/openshift-qe/ocp-qe-perfscale-ci/openshift-qe-ocp-qe-perfscale-ci-main__rosa-4.17-nightly-x86.yaml
> +  cron: 0 7 5,12,19,26 * *
good

2024-07-12 19:53 UTC, afcollins requested changes
The 120 nodes is the only one I want to see changed. Everything else is fine.

2024-07-12 19:57 UTC, afcollins approved these changes
lgtm

Thank you!

2024-07-12 20:12 UTC, svetsa-rh commented
/pj-rehearse ack

2024-07-12 20:18 UTC, svetsa-rh commented
/pj-rehearse ack

2024-07-12 20:51 UTC, svetsa-rh commented
@paigerube14 @vishnuchalla Can I get a lgtm here? 
I got an [lgtm](https://github.com/openshift/release/pull/54275#pullrequestreview-2175631962) from Andrew before, but it got [removed](https://github.com/openshift/release/pull/54275#issuecomment-2226291283) since I had to rebase.

2024-07-12 21:03 UTC, mukrishn commented
/lgtm

2024-07-12 21:03 UTC, mukrishn approved these changes

2024-07-12 21:36 UTC, merged