add kserve release-v0.12.1
openshift/release pull request #54301
Opened 2024-07-12 08:40 UTC by Jooho

2024-07-13 00:17 UTC, israel-hdez requested changes

2024-07-13 00:17 UTC, israel-hdez commented on ci-operator/config/opendatahub-io/kserve/opendatahub-io-kserve-release-v0.12.1.yaml
> +    tag: latest
```suggestion
    tag: release-v0.12.1
```

2024-07-15 03:04 UTC, Jooho commented
/pj-rehearse auto-ack

2024-07-15 07:43 UTC, Jooho commented
/pj-rehearse pull-ci-opendatahub-io-kserve-release-v0.12.1-e2e-raw

2024-07-15 07:43 UTC, Jooho commented
/pj-rehearse pull-ci-opendatahub-io-kserve-release-v0.12.1-e2e-fast

2024-07-26 04:48 UTC, Jooho commented
E2E test need to be fixed first so I will close this ticket for now.

2024-07-26 04:48 UTC, closed without merging