Create a CI build for ROCM Images for base, pytorch and tensorflow
openshift/release pull request #54486
Opened 2024-07-17 17:25 UTC by dibryant

Fixes for https://issues.redhat.com/browse/RHOAIENG-6371
Adding CI builds for AMD Base Pytorch and Tensorflow.

2024-07-18 13:30 UTC, dibryant commented
/ok-to-test

2024-07-19 10:10 UTC, atheo89 commented
/ok-to-test

2024-07-22 09:31 UTC, atheo89 commented on ci-operator/config/red-hat-data-services/notebooks/red-hat-data-services-notebooks-main.yaml
> +- context_dir: jupyter/amd/tensorflow/ubi9-python-3.9
```suggestion
- context_dir: jupyter/rocm/tensorflow/ubi9-python-3.9
```

2024-07-22 09:35 UTC, atheo89 commented
Thanks Diamond for opening this PR to change the AMD directory name to ROCM.
In order to be 100% functional these change keep in mind that you will need to update the dir name on the notebooks repo as well:
- https://github.com/opendatahub-io/notebooks/tree/main/amd
- https://github.com/opendatahub-io/notebooks/tree/main/jupyter/amd 

And also take a look on the dockerfile `label` to change any naming inconcistensy ex: https://github.com/opendatahub-io/notebooks/blob/main/jupyter/amd/pytorch/ubi9-python-3.9/Dockerfile#L5

2024-07-24 06:38 UTC, atheo89 commented
These changes are going to be introduced on downstream, could you refine a bit the title?
like: [RHOAI] Create a CI build for ROCM Images for base, pytorch and tensorflow

2024-08-07 17:51 UTC, harshad16 requested changes
Great work,
can we use `rocm-notebooks` for the IMAGE_REPO everywhere
and also can we push rocm-minimal, instead of only rocm

2024-08-07 17:51 UTC, harshad16 commented on ci-operator/config/red-hat-data-services/notebooks/red-hat-data-services-notebooks-main.yaml
> +      IMAGE_REPO: workbench-images
```suggestion
      IMAGE_REPO: rocm-notebooks
```

2024-08-07 17:51 UTC, harshad16 commented on ci-operator/config/red-hat-data-services/notebooks/red-hat-data-services-notebooks-main.yaml
> +      IMAGE_REPO: workbench-images
```suggestion
      IMAGE_REPO: rocm-notebooks
```

2024-08-07 17:51 UTC, harshad16 commented on ci-operator/config/red-hat-data-services/notebooks/red-hat-data-services-notebooks-main.yaml
> +      IMAGE_REPO: workbench-images
```suggestion
      IMAGE_REPO: rocm-notebooks
```

2024-08-07 17:51 UTC, harshad16 commented on ci-operator/config/red-hat-data-services/notebooks/red-hat-data-services-notebooks-main.yaml
> +      IMAGE_REPO: workbench-images
```suggestion
      IMAGE_REPO: rocm-notebooks
```

2024-08-08 13:47 UTC, dibryant commented
/pj-rehearse ack

2024-08-09 13:50 UTC, jiridanek commented
/pj-rehearse list

2024-08-09 13:51 UTC, jiridanek commented
/pj-rehearse notebook-rocm-jupyter-tf-ubi9-python-3-9-image-mirror

2024-08-09 13:52 UTC, jiridanek commented
/pj-rehearse max

2024-08-09 14:17 UTC, jiridanek commented
aah, got it, the names of the jobs are like this! anyways, there's not too many of them created/touched, so running it all is perfectly fine

2024-08-12 19:06 UTC, harshad16 reviewed
All good, 
just missing some pr mirror and run-if-changed needs to be removed from postsubmit jobs.

2024-08-13 15:50 UTC, dibryant commented
/retest

2024-08-13 15:53 UTC, dibryant commented
/pj-rehearse ack

2024-08-14 12:27 UTC, harshad16 requested changes
some additional changes needed

2024-08-14 12:27 UTC, harshad16 commented on ci-operator/config/red-hat-data-services/notebooks/red-hat-data-services-notebooks-release-2024a.yaml
> +      RELEASE_VERSION: rocm-jupyter-minimal-ubi9-python-3.9
```suggestion
      RELEASE_VERSION: rocm-jupyter-minimal-ubi9-python-3.9-2024a
```

2024-08-14 12:27 UTC, harshad16 commented on ci-operator/config/red-hat-data-services/notebooks/red-hat-data-services-notebooks-release-2024a.yaml
> +      RELEASE_VERSION: rocm-jupyter-tensorflow-ubi9-python-3.9
```suggestion
      RELEASE_VERSION: rocm-jupyter-tensorflow-ubi9-python-3.9-2024a
```

2024-08-14 12:27 UTC, harshad16 commented on ci-operator/config/red-hat-data-services/notebooks/red-hat-data-services-notebooks-release-2024a.yaml
> +      RELEASE_VERSION: rocm-jupyter-pytorch-ubi9-python-3.9
```suggestion
      RELEASE_VERSION: rocm-jupyter-pytorch-ubi9-python-3.9-2024a
```

2024-08-14 12:27 UTC, harshad16 commented on ci-operator/config/red-hat-data-services/notebooks/red-hat-data-services-notebooks-release-2024a.yaml
> +      RELEASE_VERSION: runtime-rocm-pytorch-ubi9-python-3.9
```suggestion
      RELEASE_VERSION: runtime-rocm-pytorch-ubi9-python-3.9-2024a
```

2024-08-15 12:53 UTC, dibryant commented
/pj-rehearse ack

2024-08-18 00:44 UTC, harshad16 requested changes
final change, this are required.

2024-08-18 00:44 UTC, harshad16 commented on ci-operator/config/red-hat-data-services/notebooks/red-hat-data-services-notebooks-main.yaml
> +- context_dir: jupyter/data-science/ubi9-python-3.9
```suggestion
- context_dir: jupyter/datascience/ubi9-python-3.9
```

2024-08-18 00:44 UTC, harshad16 commented on ci-operator/config/red-hat-data-services/notebooks/red-hat-data-services-notebooks-release-2024a.yaml
> +- context_dir: jupyter/data-science/ubi9-python-3.9
```suggestion
- context_dir: jupyter/datascience/ubi9-python-3.9
```

2024-08-18 00:44 UTC, harshad16 commented on ci-operator/config/red-hat-data-services/notebooks/red-hat-data-services-notebooks-main.yaml
> +  from: jupyter-datascience-ubi9-python-3.9
```suggestion
  from: rocm-jupyter-datascience-ubi9-python-3.9
```

2024-08-18 00:44 UTC, harshad16 commented on ci-operator/config/red-hat-data-services/notebooks/red-hat-data-services-notebooks-main.yaml
> +  from: jupyter-datascience-ubi9-python-3.9
```suggestion
  from: rocm-jupyter-datascience-ubi9-python-3.9
```

2024-08-19 14:05 UTC, dibryant commented
/pj-rehearse ack

2024-08-19 14:22 UTC, dibryant commented
/pj-rehearse ack

2024-08-20 19:52 UTC, harshad16 approved these changes
/lgtm
/approve

thanks :100:

2024-08-20 20:12 UTC, merged