Added PowerVS QE reps permission to do cherry-pick-approval for Power VS repos.
openshift/release pull request #55257
Opened 2024-08-06 19:00 UTC by jaypoulz

Currently the power QE team is unabled to `cherry-pick-approve` PRs for PowerVS repos. This update adds a few members of the partner team to help prevent PRs from getting stuck in the backport process.

2024-08-06 19:14 UTC, mjturek commented
/lgtm

2024-08-06 19:20 UTC, mffiedler approved these changes
/LGTM  
@jupierce Can you help this one along?

2024-08-06 19:22 UTC, jaypoulz commented
/hold Until @juliemathew can ensure her team has sufficient coverage.

2024-08-06 21:03 UTC, dobsonj commented
@jaypoulz If this is for PowerVS, you should update these two ibm-powervs manifests instead of the ibm-vpc ones (they're two different CSI drivers):
https://github.com/openshift/release/blob/master/core-services/prow/02_config/openshift/ibm-powervs-block-csi-driver-operator/_pluginconfig.yaml
https://github.com/openshift/release/blob/master/core-services/prow/02_config/openshift/ibm-powervs-block-csi-driver/_pluginconfig.yaml

Also, make sure someone on the team can add `backport-risk-assessed` like this:
```
    - allowed_teams:
      - openshift-staff-engineers
      allowed_users:
      - mkumatag
      - yussufsh
      label: backport-risk-assessed
```
Typically the dev team adds `backport-risk-assessed` and then QE adds `cherry-pick-approved`. Both labels are required by prow to merge bug fixes into release branches.

2024-08-07 07:29 UTC, juliemathew commented
> /hold Until @juliemathew can ensure her team has sufficient coverage.

fyi: @jaypoulz 
Yes, our team (OCP QE on Power) is responsible for verifying the fixes for PowerVS bugs.
So you can add our names as QE approvers.

Github IDs: 
sajauddin
juliemathew

2024-08-07 14:15 UTC, jaypoulz commented
@dobsonj Thanks for the heads up! I intended to get the PowerVS CSI drivers, but looks like I mixed up the files. I'll make sure we have a clean listing for both backport-risk-assessed and the corresponding cherry-pick-approved.

@juliemathew @sajauddin I'm going to start by added just you two to the cherry-pick-approved list. I'll also add staff-es and myself as the backport-risk-assessed list for now.

2024-08-08 14:11 UTC, mjturek commented
/lgtm

2024-08-08 14:20 UTC, mkumatag requested changes

2024-08-08 15:19 UTC, jaypoulz commented
/unhold

2024-08-09 04:02 UTC, mkumatag approved these changes
/lgtm
/approve

2024-08-12 16:19 UTC, patrickdillon reviewed
/approve

2024-08-12 16:19 UTC, patrickdillon commented on core-services/prow/02_config/openshift/cloud-provider-powervs/_pluginconfig.yaml
> +      - openshift-staff-engineers
do we need to add openshift-staff-engineers? I thought they already had the powers, perhaps by different means.

2024-08-12 16:44 UTC, merged