Adding FIPS job to MTC test run
openshift/release pull request #55472
Opened 2024-08-12 15:32 UTC by aviavraham

Implement rollout of FIPS-enabled OCP 4.17 testing for MTC test run

2024-08-12 21:11 UTC, calebevans requested changes
I believe the variables for this workflow are just `fips` rather than `fips_enabled`. Also, please run a rehearsal on this one to verify it works.

2024-08-12 21:11 UTC, calebevans commented on ci-operator/config/mtc-qe/mtc-e2e-qev2/mtc-qe-mtc-e2e-qev2-master__mtc1.8-ocp4.17-lp-interop.yaml
> +      CLUSTER1_CONFIG: name-prefix=mtc-source;base-domain=cspilp.interop.ccitredhat.com;platform=aws;region=us-east-2;version=4.17;stream=stable;worker-flavor=m5.xlarge;timeout=2h;fips_enabled=true
```suggestion
      CLUSTER1_CONFIG: name-prefix=mtc-source;base-domain=cspilp.interop.ccitredhat.com;platform=aws;region=us-east-2;version=4.17;stream=stable;worker-flavor=m5.xlarge;timeout=2h;fips=true
```

2024-08-12 21:11 UTC, calebevans commented on ci-operator/config/mtc-qe/mtc-e2e-qev2/mtc-qe-mtc-e2e-qev2-master__mtc1.8-ocp4.17-lp-interop.yaml
> +      CLUSTER2_CONFIG: name-prefix=mtc-target;base-domain=cspilp.interop.ccitredhat.com;platform=aws;region=us-east-2;version=4.17;stream=nightly;worker-flavor=m5.xlarge;timeout=2h;fips_enabled=true
```suggestion
      CLUSTER2_CONFIG: name-prefix=mtc-target;base-domain=cspilp.interop.ccitredhat.com;platform=aws;region=us-east-2;version=4.17;stream=nightly;worker-flavor=m5.xlarge;timeout=2h;fips=true
```

2024-08-13 10:39 UTC, aviavraham commented
Hi @calebevans 
As you suggested, I made the change to the YAML file. Could you please review the code again?

2024-08-13 13:09 UTC, calebevans commented
/pj-rehearse periodic-ci-mtc-qe-mtc-e2e-qev2-master-mtc1.8-ocp4.17-lp-interop-mtc-interop-aws-fips

2024-08-13 13:10 UTC, calebevans commented
@aviavraham if this rehearsal works, we can merge. I just want to make sure that works.

2024-08-13 13:40 UTC, calebevans commented
/pj-rehearse periodic-ci-mtc-qe-mtc-e2e-qev2-master-mtc1.8-ocp4.17-lp-interop-mtc-interop-aws-fips

2024-08-14 17:04 UTC, calebevans commented
Waiting on https://github.com/RedHatQE/openshift-cli-installer/pull/677 to be merged to fix IPI FIPS installs

2024-08-15 19:47 UTC, calebevans commented
/pj-rehearse periodic-ci-mtc-qe-mtc-e2e-qev2-master-mtc1.8-ocp4.17-lp-interop-mtc-interop-aws-fips

2024-08-16 18:47 UTC, calebevans commented
/pj-rehearse periodic-ci-mtc-qe-mtc-e2e-qev2-master-mtc1.8-ocp4.17-lp-interop-mtc-interop-aws-fips

2024-08-16 18:56 UTC, calebevans commented
/retest ci/build-farm/build11-dry

2024-08-16 18:57 UTC, calebevans commented
/retest-required

2024-08-16 20:32 UTC, dfrazzette commented
Rehearsal run is successfully creating/installing the FIPS cluster; now failing with the same blocking errors seen in [weekly periodic jobs](https://prow.ci.openshift.org/view/gs/test-platform-results/logs/periodic-ci-mtc-qe-mtc-e2e-qev2-master-mtc1.8-ocp4.17-lp-interop-mtc-interop-aws/1815269464950706176). Ready to merge.

2024-08-16 20:33 UTC, dfrazzette commented
/pj-rehearse ack

2024-08-16 20:34 UTC, dfrazzette commented
/lgtm

2024-08-16 21:09 UTC, merged