Add build11 config-updater
openshift/release pull request #55588
Opened 2024-08-14 19:06 UTC by deepsm007

Add `sa.config-updater.build11.config` to `secret-bootstrap`

/cc @bear-redhat @openshift/test-platform

2024-08-14 19:12 UTC, deepsm007 commented
/hold for other steps

2024-08-15 15:43 UTC, bear-redhat requested changes

2024-08-15 15:43 UTC, bear-redhat commented on clusters/build-clusters/build11/ci-scheduling-webhook/ci-longtests-worker-aarch64.yaml
> +      taints:
Add `NoExecution` as well

2024-08-15 15:43 UTC, bear-redhat commented on clusters/build-clusters/build11/machineset/infra-aarch64.yaml
> +      taints:
Add `NoExecution` as well

2024-08-15 15:43 UTC, bear-redhat commented on clusters/build-clusters/build11/multiarch-manager-operator/admin_01-operator.yaml
> +apiVersion: v1
remove the `multiarch-manager-operator`, since we already added proper `nodeSelectors`

2024-08-16 14:10 UTC, bear-redhat commented
/lgtm

2024-08-16 14:21 UTC, deepsm007 commented
/unhold

2024-08-16 14:25 UTC, deepsm007 commented
/pj-rehearse ack

2024-08-16 15:13 UTC, deepsm007 commented
/pj-rehearse pull-ci-openshift-release-master-build11-dry

2024-08-16 15:18 UTC, deepsm007 commented
/retest-required

2024-08-16 15:35 UTC, deepsm007 commented
/pj-rehearse abort

Rehearsal is meant to fail as the sa.config for the cluster is not merged

2024-08-16 15:41 UTC, merged