OSASINFRA-3574Update worker nodes in OVN PerfScale ingress-perf job
openshift/release pull request #55928
Opened 2024-08-26 11:26 UTC by MiguelCarpio

Updating worker and infra nodes:

OpenStack Nodes Config (proposal)

Node Types:
- Master: m1.xlarge 
- Worker: m1.large 
- Workload: ingress-perf
- Infra: m1.xlarge 

Node Counts:
- Master: 3
- Worker: 4
- Infra: 2

2024-08-26 11:40 UTC, MiguelCarpio commented
/pj-rehearse periodic-ci-shiftstack-ci-release-4.16-e2e-openstack-ingress-perf

2024-08-26 13:06 UTC, MiguelCarpio commented
/pj-rehearse periodic-ci-shiftstack-ci-release-4.16-e2e-openstack-ingress-perf

2024-08-26 15:16 UTC, MiguelCarpio commented
/pj-rehearse periodic-ci-shiftstack-ci-release-4.16-e2e-openstack-ingress-perf

2024-08-26 16:51 UTC, MiguelCarpio commented
/pj-rehearse periodic-ci-shiftstack-ci-release-4.16-e2e-openstack-ingress-perf

2024-08-26 20:48 UTC, MiguelCarpio commented
/pj-rehearse periodic-ci-shiftstack-ci-release-4.16-e2e-openstack-ingress-perf

2024-08-26 22:58 UTC, MiguelCarpio commented
/test build-clusters

2024-08-26 22:58 UTC, MiguelCarpio commented
/pj-rehearse periodic-ci-shiftstack-ci-release-4.16-e2e-openstack-ingress-perf

2024-08-27 09:19 UTC, MiguelCarpio commented
/pj-rehearse periodic-ci-shiftstack-ci-release-4.16-e2e-openstack-ingress-perf

2024-08-27 11:14 UTC, MiguelCarpio commented
/pj-rehearse periodic-ci-shiftstack-ci-release-4.16-e2e-openstack-ingress-perf

2024-08-27 14:11 UTC, MiguelCarpio commented
/pj-rehearse periodic-ci-shiftstack-ci-release-4.16-e2e-openstack-ingress-perf

2024-08-27 18:26 UTC, MiguelCarpio commented
/pj-rehearse periodic-ci-shiftstack-ci-release-4.16-e2e-openstack-ingress-perf

2024-08-27 22:08 UTC, MiguelCarpio commented
/pj-rehearse periodic-ci-shiftstack-ci-release-4.16-e2e-openstack-ingress-perf

2024-08-27 23:40 UTC, MiguelCarpio commented
/pj-rehearse periodic-ci-shiftstack-ci-release-4.16-e2e-openstack-ingress-perf

2024-08-28 08:36 UTC, MiguelCarpio commented
/pj-rehearse periodic-ci-shiftstack-ci-release-4.16-e2e-openstack-ingress-perf

2024-08-28 10:05 UTC, MiguelCarpio commented
/pj-rehearse periodic-ci-shiftstack-ci-release-4.16-e2e-openstack-ingress-perf

2024-08-28 12:07 UTC, MiguelCarpio commented
/pj-rehearse ack

2024-08-28 13:46 UTC, mandre commented on ci-operator/config/shiftstack/ci/shiftstack-ci-release-4.16.yaml
> +      INFRA_NODES_TO_TAG: "3"
Why do we need to differ from the default of `2` infra nodes to tag?

2024-08-29 10:03 UTC, MiguelCarpio commented
/pj-rehearse ack

2024-09-04 07:18 UTC, mandre requested changes
Can you squash the commits?

Then I think this is good to go.

2024-09-04 09:27 UTC, MiguelCarpio commented
/reopen

2024-09-04 13:32 UTC, MiguelCarpio commented
/reopen

2024-09-04 13:42 UTC, MiguelCarpio commented
/pj-rehearse periodic-ci-shiftstack-ci-release-4.16-e2e-openstack-ingress-perf

2024-09-04 19:54 UTC, MiguelCarpio commented
/pj-rehearse ack

2024-09-04 19:54 UTC, MiguelCarpio commented
/pj-rehearse periodic-ci-shiftstack-ci-release-4.16-e2e-openstack-ingress-perf

2024-09-04 20:11 UTC, MiguelCarpio commented
/test prow-config-semantics

2024-09-04 20:13 UTC, MiguelCarpio commented
/test config

2024-09-04 20:15 UTC, MiguelCarpio commented
/test stackrox-stackrox-stackrox-stackrox-check

2024-09-05 07:04 UTC, MiguelCarpio commented
/pj-rehearse ack

2024-09-05 07:39 UTC, mandre reviewed
/lgtm
/approve

2024-09-05 07:57 UTC, merged