OCPEDGE-1198: feat: adding timing information to the ibu and ibi steps
openshift/release pull request #56516
Opened 2024-09-10 17:27 UTC by jeff-roche

2024-09-10 17:31 UTC, jeff-roche commented
/pj-rehearse periodic-ci-openshift-kni-lifecycle-agent-main-nightly-4.18-image-based-install pull-ci-openshift-kni-lifecycle-agent-release-4.17-ibu-e2e-flow

2024-09-10 21:03 UTC, jeff-roche commented
/pj-rehearse periodic-ci-openshift-kni-lifecycle-agent-main-nightly-4.18-image-based-install pull-ci-openshift-kni-lifecycle-agent-release-4.17-ibu-e2e-flow

2024-09-11 13:36 UTC, jeff-roche commented
/pj-rehearse ack

2024-09-12 07:14 UTC, suleymanakbas91 requested changes

2024-09-12 07:14 UTC, suleymanakbas91 commented on ci-operator/step-registry/openshift/image-based/install/openshift-image-based-install-commands.sh
> +echo "IBI Times:"
Could you also add the time unit to the output?

2024-09-13 14:14 UTC, jeff-roche commented
/pj-rehearse periodic-ci-openshift-kni-lifecycle-agent-main-nightly-4.18-image-based-install pull-ci-openshift-kni-lifecycle-agent-release-4.17-ibu-e2e-flow

2024-09-13 14:54 UTC, jeff-roche commented
/pj-rehearse periodic-ci-openshift-kni-lifecycle-agent-main-nightly-4.18-image-based-install pull-ci-openshift-kni-lifecycle-agent-release-4.17-ibu-e2e-flow

2024-09-13 16:43 UTC, suleymanakbas91 commented
/lgtm

2024-09-16 12:42 UTC, merged