[Test Automation] Automate E2E scenario with use of Operator for installation
openshift/release pull request #56663
Opened 2024-09-12 21:29 UTC by Omar-AlJaljuli

Adding a periodic nightly job that runs the e2e tests on an Operator instance of RHDH.
https://issues.redhat.com/browse/RHIDP-2919
rh-pre-commit.version: 2.3.1
rh-pre-commit.check-secrets: ENABLED

2024-09-13 20:34 UTC, Omar-AlJaljuli commented
@josephca can I get an ok-to-test?

2024-09-18 15:19 UTC, josephca commented
/ok-to-test

2024-11-07 19:43 UTC, Omar-AlJaljuli commented
/remove-lifecycle stale

2024-12-13 21:31 UTC, Omar-AlJaljuli commented
/remove-lifecycle stale

2024-12-17 08:03 UTC, subhashkhileri commented on ci-operator/config/janus-idp/backstage-showcase/janus-idp-backstage-showcase-main.yaml
> +  cron: 0 8 * * *
```suggestion
  cluster_claim:
    architecture: amd64
    cloud: aws
    labels:
      region: us-east-2
    owner: rhdh
    product: ocp
    timeout: 1h0m0s
    version: "4.17"
  cron: 0 8 * * *
```

2024-12-17 08:05 UTC, subhashkhileri commented on ci-operator/config/janus-idp/backstage-showcase/janus-idp-backstage-showcase-main.yaml
> +    - ref: janus-idp-backstage-showcase-operator-nightly
```suggestion
    - ref: janus-idp-backstage-showcase-operator-nightly
    workflow: generic-claim
```

2024-12-20 10:45 UTC, subhashkhileri requested changes

2024-12-20 10:45 UTC, subhashkhileri commented on ci-operator/jobs/janus-idp/backstage-showcase/janus-idp-backstage-showcase-main-periodics.yaml
> +  name: periodic-ci-janus-idp-backstage-showcase-main-e2e-tests-operator-nightly
```suggestion
  name: periodic-ci-janus-idp-backstage-showcase-main-e2e-tests-operator-nightly
  reporter_config:
    slack:
      channel: '#rhdh-e2e-test-alerts'
      job_states_to_report:
      - success
      - failure
      - error
      report_template: '{{if eq .Status.State "success"}} :done-circle-check: {{else}}<!subteam^S07BMJ56R8S>
        :failed: {{end}} Job *`{{.Spec.Job}}`* ended with *{{.Status.State}}*. Open
        Report: <https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/test-platform-results/logs/periodic-ci-janus-idp-backstage-showcase-main-e2e-tests-nightly-aks/{{.Status.BuildID}}/artifacts/e2e-tests-nightly-aks/janus-idp-backstage-showcase-helm-aks-nightly/artifacts/showcase-k8s-ci-nightly/index.html|nightly>
        | <https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/test-platform-results/logs/periodic-ci-janus-idp-backstage-showcase-main-e2e-tests-nightly-aks/{{.Status.BuildID}}/artifacts/e2e-tests-nightly-aks/janus-idp-backstage-showcase-helm-aks-nightly/artifacts/showcase-rbac-k8s-ci-nightly/index.html|rbac-nightly>
        | <https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/test-platform-results/logs/periodic-ci-janus-idp-backstage-showcase-main-e2e-tests-nightly-aks/{{.Status.BuildID}}/artifacts/e2e-tests-nightly-aks/janus-idp-backstage-showcase-helm-aks-nightly/artifacts/|Open
        artifacts> | <{{.Status.URL}}|View logs>'
```

Manually add this slack configuration for this periodic job alerts. make sure to update the links as per you job names.

2024-12-20 10:46 UTC, subhashkhileri commented
/pj-rehearse auto-ack

2024-12-20 15:02 UTC, Omar-AlJaljuli commented
/retest

2024-12-20 15:26 UTC, Omar-AlJaljuli commented
/pj-rehearse auto-ack

2024-12-21 03:43 UTC, Omar-AlJaljuli commented
/retest

2025-01-06 11:55 UTC, Omar-AlJaljuli commented
/pj-rehearse auto-ack

2025-01-06 15:03 UTC, Omar-AlJaljuli commented
/pj-rehearse auto-ack

2025-01-06 16:08 UTC, Omar-AlJaljuli commented
/pj-rehearse auto-ack

2025-01-06 16:19 UTC, subhashkhileri commented
/ltgm

2025-01-06 16:20 UTC, subhashkhileri commented
/approve

2025-01-06 16:22 UTC, subhashkhileri commented
/lgtm

2025-01-06 16:23 UTC, subhashkhileri commented
/pj-rehearse ack

2025-01-06 17:00 UTC, merged