telco5g: commatrix workflow and step
openshift/release pull request #56792
Opened 2024-09-17 07:01 UTC by danimjaffe

Add relevant files and directories for commatrix workflow and step, that are required for the periodic job.

2024-09-17 07:02 UTC, danimjaffe commented
/uncc dgoodwin stbenjam

2024-09-17 10:10 UTC, danimjaffe commented
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.18-e2e-telco5g-commatrix

2024-09-17 12:38 UTC, danimjaffe commented
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.16-network-flow-matrix

2024-09-17 16:03 UTC, danimjaffe commented
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.16-network-flow-matrix

2024-09-18 07:26 UTC, danimjaffe commented
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.16-network-flow-matrix

2024-09-18 10:27 UTC, danimjaffe commented
/cc sshnaidm

2024-09-18 10:28 UTC, danimjaffe commented
/cc saledort

2024-09-18 12:16 UTC, danimjaffe commented
/cc aabughosh

2024-09-18 12:20 UTC, danimjaffe commented
/cc sabinaaledort

2024-09-18 13:06 UTC, sshnaidm requested changes

2024-09-18 13:06 UTC, sshnaidm commented on ci-operator/step-registry/telco5g/commatrix/tests/telco5g-commatrix-tests-ref.yaml
> +  - name: TEST_RUN_FEATURES
please remove TEST_RUN_FEATURES and E2E_TESTS_CONFIG

2024-09-19 09:36 UTC, danimjaffe commented
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.16-network-flow-matrix-bm periodic-ci-openshift-release-master-nightly-4.16-network-flow-matrix-single-node-bm

2024-09-19 11:52 UTC, sshnaidm commented
/lgtm

2024-09-19 12:56 UTC, danimjaffe commented
/pj-rehearse ack

2024-09-19 14:09 UTC, stbenjam commented on ci-operator/config/openshift/release/openshift-release-master__nightly-4.16.yaml
> +- as: network-flow-matrix-bm
These should follow our naming scheme for CI jobs

https://docs.ci.openshift.org/docs/how-tos/naming-your-ci-jobs/

Mostly I think you're missing platform and CNI provider.

2024-09-19 15:10 UTC, danimjaffe commented
/pj-rehearse periodic-ci-openshift-release-master-nightly-4.16-metal-ovn-network-flow-matrix-single-node-bm periodic-ci-openshift-release-master-nightly-4.16-metal-ovn-network-flow-matrix-bm

2024-09-19 15:32 UTC, stbenjam commented
Thank you, names look better 👍🏻 

/approve

2024-09-19 18:08 UTC, sshnaidm commented
/lgtm

2024-09-22 05:56 UTC, danimjaffe commented
/pj-rehearse ack

2024-09-22 06:37 UTC, merged