[winc] Fix naming of EUS upgrade test job
openshift/release pull request #57325
Opened 2024-09-30 19:45 UTC by saifshaikh48

Remove any dots from the step name as the step name is used to create k8s resources, which caused them to fail spec validation before test even ran.

2024-09-30 19:50 UTC, saifshaikh48 commented
/pj-rehearse auto-ack

2024-09-30 21:16 UTC, jrvaldes requested changes
@saifshaikh48  thanks for catching this. PTAL at my comment.

2024-09-30 21:16 UTC, jrvaldes commented on ci-operator/config/openshift/windows-machine-config-operator/openshift-windows-machine-config-operator-master.yaml
> +- as: azure-e2e-upgrade-from-previous-eus
I see, the `.` is the beauty here. 

What about using `azure-e2e-upgrade-from-eus-4-16`



@saifshaikh48   4.16 is not technically the prev, given the job is targeting 4.18.

The path must be is strict 4.16 -> master (4.18), after the 4.19 branching day this job cannot go into master, it must stay in 4.18 branch 


this

2024-10-01 15:19 UTC, jrvaldes commented on ci-operator/config/openshift/windows-machine-config-operator/openshift-windows-machine-config-operator-master.yaml
> +- as: azure-e2e-upgrade-from-previous-eus
correct

2024-10-02 14:40 UTC, saifshaikh48 commented
/pj-rehearse auto-ack

2024-10-02 14:44 UTC, saifshaikh48 commented
/pj-rehearse periodic-ci-openshift-windows-machine-config-operator-release-4.18-azure-e2e-upgrade-from-previous-eus

2024-10-02 17:29 UTC, jrvaldes approved these changes
/lgtm

2024-10-02 20:28 UTC, saifshaikh48 commented
/pj-rehearse ack

2024-10-03 13:15 UTC, jrvaldes commented
/pj-rehearse periodic-ci-openshift-windows-machine-config-operator-release-4.18-azure-e2e-upgrade-from-previous-eus

2024-10-03 13:33 UTC, jrvaldes commented
/lgtm

2024-10-07 13:07 UTC, jrvaldes commented
/pj-rehearse periodic-ci-openshift-windows-machine-config-operator-release-4.18-azure-e2e-upgrade-from-previous-eus

2024-10-07 16:39 UTC, saifshaikh48 commented
/pj-rehearse periodic-ci-openshift-windows-machine-config-operator-release-4.18-azure-e2e-upgrade-from-previous-eus

2024-10-07 21:21 UTC, jrvaldes commented
/pj-rehearse periodic-ci-openshift-windows-machine-config-operator-release-4.18-azure-e2e-upgrade-from-previous-eus

2024-10-08 14:49 UTC, jrvaldes commented
upgrade-from-previous-eus  job is [failing](https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/test-platform-results/pr-logs/pull/openshift_release/57325/rehearse-57325-periodic-ci-openshift-windows-machine-config-operator-release-4.18-azure-e2e-upgrade-from-previous-eus/1843401963702587392/artifacts/azure-e2e-upgrade-from-previous-eus/gather-extra/artifacts/pods/openshift-windows-machine-config-operator_windows-machine-config-operator-6fcf8465f5-h97hs_manager.log) with 

```
error validating k8s version: unsupported server version: v1.31.1-dirty. Supported versions are v1.29.x to v1.30.x
```

depends on:

- https://github.com/openshift/windows-machine-config-operator/pull/2448

2024-10-08 15:09 UTC, saifshaikh48 commented
@jrvaldes that is expected until https://github.com/openshift/windows-machine-config-operator/pull/2448 goes in

2024-10-08 17:55 UTC, jrvaldes commented
/lgtm

2024-10-08 18:02 UTC, saifshaikh48 commented
/pj-rehearse ack

2024-10-08 18:12 UTC, mansikulkarni96 approved these changes

2024-10-08 18:44 UTC, merged