[PERFSCALE-3509] BM CPT deployment pre-reqs
openshift/release pull request #57927
Opened 2024-10-17 10:46 UTC by josecastillolema

Making sure the cluster is in the proper state before starting the OCP deployment.

2024-10-17 11:01 UTC, josecastillolema commented
/hold

2024-10-17 11:02 UTC, josecastillolema commented
/assign @rsevilla87

2024-10-23 11:45 UTC, josecastillolema commented
/pj-rehearse pull-ci-openshift-qe-ocp-qe-perfscale-ci-main-metal-4.17-latest-x86-deploy-sno

2024-10-23 12:01 UTC, rsevilla87 commented on ci-operator/step-registry/openshift-qe/installer/bm/deploy/openshift-qe-installer-bm-deploy-commands.sh
> +    badfish -v -H $i -u $USER -p $PWD --racreset
where can we get the badfish RPM?

2024-10-23 12:04 UTC, rsevilla87 commented on ci-operator/step-registry/openshift-qe/installer/bm/deploy/openshift-qe-installer-bm-deploy-commands.sh
> +    badfish -v -H $i -u $USER -p $PWD --racreset
I think is better to use the badfish container instead. i.e:, as jetlag installs podman

```shell
$ podman run --pull always --rm quay.io/quads/badfish:latest -v -H $i -u $USER -p $PWD --racreset
``

2024-10-23 12:11 UTC, josecastillolema commented
/pj-rehearse abort

2024-10-23 13:26 UTC, jtaleric commented on ci-operator/step-registry/openshift-qe/installer/bm/deploy/openshift-qe-installer-bm-deploy-commands.sh
> +    badfish -v -H $i -u $USER -p $PWD --racreset
yeah, this is how I  have ran badfish in the past... I made this suggestion based on the PR here... but +1 to podman

2024-10-23 14:06 UTC, josecastillolema commented
/pj-rehearse pull-ci-openshift-qe-ocp-qe-perfscale-ci-main-metal-4.17-latest-x86-deploy-sno

2024-10-24 08:59 UTC, rsevilla87 commented on ci-operator/step-registry/openshift-qe/installer/bm/deploy/openshift-qe-installer-bm-deploy-commands.sh
> +    badfish -v -H \$i -u $USER -p $PWD --racreset
why are you resetting the iDRAC?

2024-10-24 09:02 UTC, rsevilla87 requested changes
During my recent experiments I faced an issue b/c the servers of my allocation were in BIOS boot mode, I wonder if we can add the step the update them to Uefi, that can be done passing the following flags to badfish

```
--set-bios-attribute --attribute BootMode --value Uefi
``

2024-11-22 15:20 UTC, josecastillolema commented
/pj-rehearse pull-ci-openshift-qe-ocp-qe-perfscale-ci-main-metal-4.17-latest-x86-deploy-sno

2024-11-22 16:14 UTC, josecastillolema commented
/pj-rehearse pull-ci-openshift-qe-ocp-qe-perfscale-ci-main-metal-4.17-latest-x86-deploy-sno

2024-11-22 16:42 UTC, josecastillolema commented
/pj-rehearse pull-ci-openshift-qe-ocp-qe-perfscale-ci-main-metal-4.17-latest-x86-deploy-sno

2024-11-22 20:02 UTC, josecastillolema commented
/pj-rehearse pull-ci-openshift-qe-ocp-qe-perfscale-ci-main-metal-4.17-latest-x86-deploy-sno

2024-11-26 12:17 UTC, josecastillolema commented
/pj-rehearse pull-ci-openshift-qe-ocp-qe-perfscale-ci-main-metal-4.17-latest-x86-deploy-sno

2024-11-26 16:14 UTC, rsevilla87 commented
/pj-rehearse network-access-allowed

2024-11-26 16:17 UTC, josecastillolema commented
/pj-rehearse pull-ci-openshift-qe-ocp-qe-perfscale-ci-main-metal-4.17-latest-x86-deploy-sno

2024-11-26 16:44 UTC, rsevilla87 commented
/pj-rehearse network-access-allowed

2024-11-26 16:44 UTC, josecastillolema commented
/pj-rehearse pull-ci-openshift-qe-ocp-qe-perfscale-ci-main-metal-4.17-latest-x86-deploy-sno

2024-11-26 16:46 UTC, rsevilla87 commented on ci-operator/step-registry/openshift-qe/installer/bm/deploy/openshift-qe-installer-bm-deploy-ref.yaml
> +      default: "http://quads.rdu3.labs.perfscale.redhat.com"
It can be calculated with using the variable LAB

2024-11-27 11:47 UTC, rsevilla87 commented
/pj-rehearse network-access-allowed

2024-11-27 11:54 UTC, josecastillolema commented
/pj-rehearse pull-ci-openshift-qe-ocp-qe-perfscale-ci-main-metal-4.17-latest-x86-deploy-sno

2024-11-27 14:08 UTC, deepsm007 commented
/pj-rehearse pull-ci-openshift-qe-ocp-qe-perfscale-ci-main-metal-4.17-latest-x86-deploy-sno

2024-11-27 14:09 UTC, josecastillolema commented
/pj-rehearse network-access-allowed

2024-11-27 14:10 UTC, deepsm007 commented
/pj-rehearse network-access-allowed

2024-11-27 14:35 UTC, deepsm007 commented
/pj-rehearse pull-ci-openshift-qe-ocp-qe-perfscale-ci-main-metal-4.17-latest-x86-deploy-sno

2024-11-27 15:51 UTC, josecastillolema commented
/pj-rehearse pull-ci-openshift-qe-ocp-qe-perfscale-ci-main-metal-4.17-latest-x86-deploy-sno

2024-11-27 18:53 UTC, deepsm007 commented
/pj-rehearse pull-ci-openshift-qe-ocp-qe-perfscale-ci-main-metal-4.17-latest-x86-deploy-sno

2024-11-28 10:55 UTC, josecastillolema commented
/pj-rehearse pull-ci-openshift-qe-ocp-qe-perfscale-ci-main-metal-4.17-latest-x86-deploy-sno

2024-11-28 12:31 UTC, josecastillolema commented
/pj-rehearse pull-ci-openshift-qe-ocp-qe-perfscale-ci-main-metal-4.17-latest-x86-deploy-6nodes

2024-11-29 09:43 UTC, josecastillolema commented
/pj-rehearse pull-ci-openshift-qe-ocp-qe-perfscale-ci-main-metal-4.17-latest-x86-deploy-6nodes

2024-11-29 11:46 UTC, josecastillolema commented
/pj-rehearse pull-ci-openshift-qe-ocp-qe-perfscale-ci-main-metal-4.17-latest-x86-deploy-6nodes

2024-11-29 12:29 UTC, josecastillolema commented
/pj-rehearse pull-ci-openshift-qe-ocp-qe-perfscale-ci-main-metal-4.17-latest-x86-deploy-6nodes

2024-11-29 14:28 UTC, josecastillolema commented
/pj-rehearse pull-ci-openshift-qe-ocp-qe-perfscale-ci-main-metal-dev-latest-x86-deploy-6nodes

2024-11-29 16:28 UTC, josecastillolema commented
/pj-rehearse pull-ci-openshift-qe-ocp-qe-perfscale-ci-main-metal-4.17-latest-x86-deploy-6nodes

2024-11-30 09:15 UTC, josecastillolema commented
/pj-rehearse ack

2024-11-30 09:18 UTC, josecastillolema commented
Ignore the `ci/rehearse/openshift-qe/ocp-qe-perfscale-ci/main/metal-dev-latest-x86-deploy-6nodes` fail, that is unrelated, in latest 4.18 (4.18 EC.4), there is an issue with tls certificates https://redhat-internal.slack.com/archives/CUPJTHQ5P/p1732628339517549

2024-12-02 07:52 UTC, josecastillolema commented
/pj-rehearse pull-ci-redhat-performance-jetlag-main-deploy-sno

2024-12-02 09:04 UTC, josecastillolema commented
/pj-rehearse ack

2024-12-02 19:01 UTC, jtaleric commented on ci-operator/step-registry/openshift-qe/installer/bm/deploy/openshift-qe-installer-bm-deploy-commands.sh
> +if [[ "$PRE_CLEAR_JOB_QUEUE" == "true" ]]; then
A racreset should clear the jobqueue so I don't think we need both.

2024-12-02 19:02 UTC, jtaleric commented on ci-operator/step-registry/openshift-qe/installer/bm/deploy/openshift-qe-installer-bm-deploy-commands.sh
> +  export QUADS_INSTANCE="http://quads.rdu3.labs.perfscale.redhat.com"
should we have this in the ref file? that way the config sets the `LAB` var?

2024-12-03 10:52 UTC, josecastillolema commented
/pj-rehearse ack

2024-12-03 11:59 UTC, rsevilla87 commented on ci-operator/step-registry/openshift-qe/installer/bm/deploy/openshift-qe-installer-bm-deploy-commands.sh
> +  sleep 300
I wonder if there's another way to check the iDRAC is up & running rather than an arbitrary sleep

2024-12-03 13:50 UTC, jtaleric commented on ci-operator/step-registry/openshift-qe/installer/bm/deploy/openshift-qe-installer-bm-deploy-commands.sh
> +    podman run quay.io/quads/badfish:latest -v -H $i -u $USER -p $PWD --racreset
I wonder if we want the latest?  We should understand what are the differences here - https://quay.io/repository/quads/badfish?tab=tags

2024-12-04 13:20 UTC, josecastillolema commented
/unhold

2024-12-04 13:21 UTC, josecastillolema commented
/pj-rehearse ack

2024-12-04 13:43 UTC, merged