feat: do not run konflux image-controller and build-service checks in PR
openshift/release pull request #57956
Opened 2024-10-17 22:11 UTC by flacatus

2024-10-17 22:38 UTC, flacatus commented
@psturc could you take a look

2024-10-18 07:52 UTC, psturc requested changes

2024-10-18 07:52 UTC, psturc commented on ci-operator/config/konflux-ci/build-service/konflux-ci-build-service-main.yaml
>    skip_if_only_changed: ^docs/|^\.github/|^\.tekton/|\.md$|^(?:.*/)?(?:\.gitignore|OWNERS|PROJECT|LICENSE)$
I think this needs to be removed as well

2024-10-18 07:52 UTC, psturc commented on ci-operator/config/konflux-ci/image-controller/konflux-ci-image-controller-main.yaml
>    skip_if_only_changed: ^docs/|^\.github/|^\.tekton/|\.md$|^(?:.*/)?(?:\.gitignore|OWNERS|PROJECT|LICENSE)$
same as above

2024-10-18 11:10 UTC, psturc approved these changes
/lgtm

2024-10-18 11:39 UTC, psturc commented
/pj-rehearse ack

2024-10-25 11:33 UTC, flacatus commented
/retest

2024-10-25 11:38 UTC, closed without merging