chore(rhdh): add branch protection rules for...
openshift/release pull request #58191
Opened 2024-10-25 15:32 UTC by nickboldt

chore(rhdh): add branch protection rules for rhd/red-hat-developer-hub repo

Signed-off-by: Nick Boldt <nboldt@redhat.com>

2024-10-25 15:37 UTC, schultzp2020 requested changes

2024-10-25 15:37 UTC, schultzp2020 commented on core-services/prow/02_config/redhat-developer/red-hat-developer-hub/_prowconfig.yaml
> +                - Main Job
The action names need to be updated.

2024-10-25 15:37 UTC, schultzp2020 commented on core-services/prow/02_config/redhat-developer/red-hat-developer-hub/_prowconfig.yaml
> +  - excludedBranches:
We don't have any excluded branches.

2024-10-29 13:57 UTC, schultzp2020 commented
@nickboldt we'll need to copy [these changes](https://github.com/openshift/release/pull/58276).

2024-11-07 02:41 UTC, nickboldt commented
/test config

2024-11-08 18:38 UTC, schultzp2020 commented
/lgtm

2024-11-08 19:43 UTC, nickboldt commented
/lgtm

2024-11-08 19:44 UTC, nickboldt commented on core-services/prow/02_config/redhat-developer/red-hat-developer-hub/OWNERS
> +- rm3l
```suggestion
- rm3l
- schultz2020
```

2024-11-08 19:53 UTC, kim-tsao commented
/lgtm

2024-11-08 20:21 UTC, nickboldt commented
/test ci/prow/check-gh-automation-tide

2024-11-08 20:23 UTC, nickboldt commented on core-services/prow/02_config/redhat-developer/red-hat-developer-hub/OWNERS
> +- christoph-jerolimov
```suggestion
- 04kash
- christoph-jerolimov
```

2024-11-08 20:24 UTC, nickboldt commented on core-services/prow/02_config/redhat-developer/red-hat-developer-hub/OWNERS
> +- josephca
```suggestion
- JessicaJHee
- josephca
```

2024-11-08 20:24 UTC, nickboldt commented on core-services/prow/02_config/redhat-developer/red-hat-developer-hub/OWNERS
> +- rm3l
```suggestion
- PatAKnight
- rm3l
```

2024-11-08 20:24 UTC, nickboldt commented on core-services/prow/02_config/redhat-developer/red-hat-developer-hub/OWNERS
> +- fortune-ndlovu
```suggestion
- Fortune-Ndlovu
- its-mitesh-kumar
```

2024-11-08 20:36 UTC, kim-tsao commented
/lgtm

2024-11-08 23:01 UTC, merged