Add registry pods config to CLusterLogForwarder
openshift/release pull request #58800
Opened 2024-11-13 21:17 UTC by deepsm007

/cc @jupierce

2024-11-14 13:44 UTC, jupierce requested changes

2024-11-14 15:51 UTC, deepsm007 commented
/test sync-rover-groups

pod timeout

2024-11-14 16:25 UTC, deepsm007 commented
Failure is related to the ci-tools postsubmit affecting the sync-rover-groups image

2024-11-14 18:37 UTC, jupierce requested changes

2024-11-14 18:37 UTC, jupierce commented on clusters/build-clusters/common_managed/rh-logging.yaml
> +    parse: json
The registry does not log in structured JSON.

2024-11-14 18:39 UTC, deepsm007 commented
/test sync-rover-groups

2024-11-15 18:05 UTC, jupierce commented
/hold

2024-11-18 20:23 UTC, deepsm007 commented
/unhold

2024-11-18 20:39 UTC, merged