MCO run OCL compatible test cases in a cluster with OCL
openshift/release pull request #58868
Opened 2024-11-15 11:00 UTC by sergiordlr

Run OCL compatible test cases in a cluster where OCL is enabled in master and worker pools.

2024-11-15 11:00 UTC, sergiordlr commented
WIP
/hold

2024-11-15 11:03 UTC, sergiordlr commented
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.18-amd64-nightly-aws-ipi-longrun-mco-tp-ocl-p3-f7 periodic-ci-openshift-openshift-tests-private-release-4.18-amd64-nightly-aws-ipi-tp-ocl-f7 periodic-ci-openshift-openshift-tests-private-release-4.18-amd64-nightly-aws-ipi-longrun-mco-tp-ocl-p1-f7 periodic-ci-openshift-openshift-tests-private-release-4.18-amd64-nightly-aws-ipi-longrun-mco-tp-ocl-p2-f7

2024-12-02 10:00 UTC, sergiordlr commented
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.18-amd64-nightly-aws-ipi-longrun-mco-tp-ocl-p3-f7 periodic-ci-openshift-openshift-tests-private-release-4.18-amd64-nightly-aws-ipi-tp-ocl-f7 periodic-ci-openshift-openshift-tests-private-release-4.18-amd64-nightly-aws-ipi-longrun-mco-tp-ocl-p1-f7 periodic-ci-openshift-openshift-tests-private-release-4.18-amd64-nightly-aws-ipi-longrun-mco-tp-ocl-p2-f7

2024-12-03 08:41 UTC, sergiordlr commented
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.18-amd64-nightly-aws-ipi-longrun-mco-tp-ocl-p3-f7 periodic-ci-openshift-openshift-tests-private-release-4.18-amd64-nightly-aws-ipi-tp-ocl-f7 periodic-ci-openshift-openshift-tests-private-release-4.18-amd64-nightly-aws-ipi-longrun-mco-tp-ocl-p1-f7 periodic-ci-openshift-openshift-tests-private-release-4.18-amd64-nightly-aws-ipi-longrun-mco-tp-ocl-p2-f7

2024-12-04 18:13 UTC, sergiordlr commented
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.18-amd64-nightly-aws-ipi-longrun-mco-tp-ocl-p3-f7 periodic-ci-openshift-openshift-tests-private-release-4.18-amd64-nightly-aws-ipi-tp-ocl-f7 periodic-ci-openshift-openshift-tests-private-release-4.18-amd64-nightly-aws-ipi-longrun-mco-tp-ocl-p1-f7 periodic-ci-openshift-openshift-tests-private-release-4.18-amd64-nightly-aws-ipi-longrun-mco-tp-ocl-p2-f7

2024-12-12 15:29 UTC, sergiordlr commented
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.18-amd64-nightly-4.18-upgrade-from-stable-4.18-aws-ipi-ocl-fips-f60

2024-12-13 09:43 UTC, sergiordlr commented
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.18-amd64-nightly-4.18-upgrade-from-stable-4.18-aws-ipi-ocl-fips-f60

2024-12-13 14:50 UTC, sergiordlr commented
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.18-amd64-nightly-4.18-upgrade-from-stable-4.18-aws-ipi-ocl-fips-f60

2024-12-16 10:49 UTC, sergiordlr commented
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.18-amd64-nightly-4.18-upgrade-from-stable-4.18-aws-ipi-ocl-fips-f60

2025-01-14 14:53 UTC, sergiordlr commented
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.18-amd64-nightly-aws-ipi-longrun-mco-tp-ocl-p3-f7 periodic-ci-openshift-openshift-tests-private-release-4.18-amd64-nightly-aws-ipi-tp-ocl-f7 periodic-ci-openshift-openshift-tests-private-release-4.18-amd64-nightly-aws-ipi-longrun-mco-tp-ocl-p1-f7 periodic-ci-openshift-openshift-tests-private-release-4.18-amd64-nightly-aws-ipi-longrun-mco-tp-ocl-p2-f7

2025-01-15 09:19 UTC, sergiordlr commented
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.18-amd64-nightly-aws-ipi-longrun-mco-tp-ocl-p3-f7 periodic-ci-openshift-openshift-tests-private-release-4.18-amd64-nightly-aws-ipi-tp-ocl-f7 periodic-ci-openshift-openshift-tests-private-release-4.18-amd64-nightly-aws-ipi-longrun-mco-tp-ocl-p1-f7 periodic-ci-openshift-openshift-tests-private-release-4.18-amd64-nightly-aws-ipi-longrun-mco-tp-ocl-p2-f7

2025-01-16 14:04 UTC, sergiordlr commented
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.18-amd64-nightly-4.18-upgrade-from-stable-4.18-aws-ipi-ocl-fips-f60

2025-01-23 09:44 UTC, sergiordlr commented
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.18-amd64-nightly-aws-ipi-tp-ocl-f7

2025-01-23 11:19 UTC, sergiordlr commented
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.18-amd64-nightly-4.18-upgrade-from-stable-4.18-aws-ipi-ocl-fips-f60

2025-01-23 12:48 UTC, sergiordlr commented
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.18-amd64-nightly-4.18-upgrade-from-stable-4.18-aws-ipi-ocl-fips-f60

2025-01-23 14:20 UTC, sergiordlr commented
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.18-amd64-nightly-4.18-upgrade-from-stable-4.18-aws-ipi-ocl-fips-f60

2025-01-23 18:43 UTC, sergiordlr commented
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.18-amd64-nightly-4.18-upgrade-from-stable-4.18-aws-ipi-ocl-fips-f60

2025-01-24 07:25 UTC, ptalgulk01 requested changes

2025-01-24 08:18 UTC, ptalgulk01 commented
/lgtm
/pj-rehearse ack

2025-01-24 10:19 UTC, ptalgulk01 commented
/lgtm
/pj-rehearse ack

2025-01-24 10:42 UTC, merged