Update image tag to console-plugin-test-cypress
openshift/release pull request #58913
Opened 2024-11-18 08:09 UTC by sanketpathak

2024-11-18 09:10 UTC, sanketpathak commented
/pj-rehearse

2024-11-21 07:46 UTC, sanketpathak commented
/cc @vikram-raj

2024-11-21 07:47 UTC, sanketpathak commented
/cc @jhadvig

2024-12-06 13:15 UTC, sanketpathak commented
/pj-rehearse

2024-12-10 06:00 UTC, yapei commented
/pj-rehearse pull-ci-openshift-pipelines-console-plugin-release-4.19-build

2025-02-11 13:26 UTC, sanketpathak commented
/reopen

2025-03-17 09:04 UTC, sanketpathak commented
/reopen

2025-03-18 15:59 UTC, vikram-raj commented
/pj-rehearse

2025-03-19 06:10 UTC, vikram-raj commented
/pj-rehearse

2025-03-19 06:11 UTC, vikram-raj commented
/remove-lifecycle rotten

2025-03-19 06:32 UTC, vikram-raj requested changes
@sanketpathak, the config file for release-4.20 has also been added; please make sure to update it as well.

2025-03-20 06:46 UTC, vikram-raj commented
/retest-required

2025-03-21 12:05 UTC, vikram-raj commented
/pj-rehearse

2025-03-21 12:45 UTC, vikram-raj commented
/pj-rehearse ack

2025-03-21 12:50 UTC, vikram-raj reviewed
/lgtm

2025-03-21 13:10 UTC, merged