OpenStack: Add Validate conditions at openstack-provision-etcd-disk-speed step
openshift/release pull request #59057
Opened 2024-11-21 11:10 UTC by MiguelCarpio

Validate the controlPlaneHardwareSpeed value and Etcd Available and Degraded state after the slow profile patch

2024-11-21 11:16 UTC, MiguelCarpio commented
/pj-rehearse periodic-ci-shiftstack-ci-release-4.16-e2e-openstack-ovn-serial

2024-11-21 12:46 UTC, MiguelCarpio commented
/hold

2024-11-21 12:50 UTC, mandre commented on ci-operator/step-registry/openstack/provision/etcd-disk-speed/openstack-provision-etcd-disk-speed-commands.sh
> +  info 'INFO: Waiting for patch etcd cluster...'
Nit: Please remove the INFO prefix, it's already in the output of the info() function (on [line 8](https://github.com/openshift/release/pull/59057/files#diff-61a78a69fc41150f08b8b255492a18d34f09d942945bd0bc0f94ae9656d3bec3R8)).

2024-11-21 12:50 UTC, mandre commented on ci-operator/step-registry/openstack/provision/etcd-disk-speed/openstack-provision-etcd-disk-speed-commands.sh
> +  info 'INFO: Etcd Patched successfully!'
ditto

2024-11-21 13:02 UTC, mandre commented
We should try to update the [check in openstack-rotate-cloud-credentials-commands.sh](https://github.com/openshift/release/blob/master/ci-operator/step-registry/openstack/rotate/cloud-credentials/openstack-rotate-cloud-credentials-commands.sh#L61) from:
```
oc wait --timeout=5m --for=condition=Progressing=false $(oc get clusteroperator -o NAME) -o template='{{.metadata.name}} is ready
```

to:
```
oc wait clusteroperators --all --for=condition=Progressing=false --timeout=30m
```

2024-11-21 13:03 UTC, MiguelCarpio commented
/pj-rehearse periodic-ci-shiftstack-ci-release-4.16-e2e-openstack-ovn-serial

2024-11-21 19:45 UTC, MiguelCarpio commented
/hold remove

2024-11-21 19:48 UTC, MiguelCarpio commented
/hold cancel

2024-11-21 20:09 UTC, MiguelCarpio commented
/pj-rehearse ack

2024-11-22 08:29 UTC, mandre requested changes
Let's rework the commit message to match the conventions and limit the title to 50 chars if possible.

https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project for reference.

Also, we should run the CI on the most recent commit before approving.

2024-11-22 08:49 UTC, MiguelCarpio commented
/pj-rehearse periodic-ci-shiftstack-ci-release-4.18-techpreview-e2e-openstack-ovn-serial-techpreview

2024-11-25 08:33 UTC, mandre reviewed
/lgtm
/approve

2024-11-25 09:27 UTC, merged