feat(config): Enable slack notify to #pr-review-ai-ide-team for faile…
openshift/release pull request #59197
Opened 2024-11-25 18:12 UTC by andyatmiami

…d image builds

To improve efficiency, we want to be able to be proactively notified in slack if any of our `ci-operator` jobs that build images result in failure.

This PR adds slack notifications to Prow to post to `#pr-review-ai-ide-team` in the event the job state ended in `error` or `failure`.
- The `:failed:` slack emoji is included on the posted message in the event the job ended in a `failure` state
- The `:bangbang:` slack emoji is included on the posted message in the event the job ended in a `error` state

The alert message also includes the relevant config directory in the message ( `opendatahub-io/notebooks` or `red-hat-data-services/notebooks` )
- I was unable to find documentation that lists all the available _built-ins_ that are able to be referenced in the Prow  `report_template` field - so for now these directories are hard-coded in their respective configs.

As the `job_names` field acts as an explicit allow-list - I opted for the following methodology in determining which job names to include:
- `opendatahub-io/notebooks`
    - `yq e -N '.tests[].as' opendatahub-io-notebooks-*.yaml | grep "\-image-mirror$" | sort | uniq`
- `red-hat-data-services/notebooks`
    - `yq e -N '.tests[].as' red-hat-data-services-notebooks-*.yaml | grep "\-image-mirror$" | sort | uniq`

In both cases, all `*yaml` files matching an appropriate prefix are parsed by `yq`.  Any `as:` field that ends with `-image-mirror` is then aggregated, sorted, and has duplicates removed.  That resultant list is then what I have included in the `.config.prowgen` file.
- Certainly possible in the future to potentially automate this as part of a GHA.  Given this "explicit allowlist" paradigm - its unfortunate that adding **NEW** "image mirrors" steps would as of now require some manual toil to them also update to `.config.prowgen` file to ensure alerts are published to slack.

A `make update` was ran against the changes to ensure all files appropriately configured.

Related-to: https://issues.redhat.com/browse/RHOAIENG-15586

2024-11-26 09:11 UTC, atheo89 commented
/test check-gh-automation

2024-11-26 09:16 UTC, atheo89 commented
So it goes and apply the alert whenever find the same name that the `-as` has. So, our current naming setup has a drawback, if we want to apply alerts. we will get spammed all the time from the main. So, I would suggest to rename the `-as`  jobs on the current release branches to have an extra identifier for example for  `- as: notebook-jupyter-minimal-ubi9-python-3-11-image-mirror` on the 24b config to rename it to `- as: notebook-jupyter-minimal-ubi9-python-3-11-image-mirror-2024b` this way we will avoid notifications from the main. wdyt?

2024-11-27 08:11 UTC, atheo89 requested changes
Thank you Andy for this enhancement! :100: 

I have only a question in regards the filtering, apart of this we will need to trim the list. 
- Need to exclude job names that ending `*-pr-image-mirror`
- Exclude all the base and Intel builds
- Keep only related images that we need to monitor while the release, (see the list bellow):

```
(notebooks-2024b)
- jupyter-minimal-ubi9-python-3.11
- jupyter-datascience-ubi9-python-3.11
- cuda-jupyter-minimal-ubi9-python-3.11
- cuda-jupyter-datascience-ubi9-python-3.11
- cuda-jupyter-tensorflow-ubi9-python-3.11
- jupyter-pytorch-ubi9-python-3.11
- jupyter-trustyai-ubi9-python-3.11
- rstudio-c9s-python-3.11
- cuda-rstudio-c9s-python-3.11
- codeserver-ubi9-python-3.11
- rocm-jupyter-minimal-ubi9-python-3.11
- rocm-jupyter-tensorflow-ubi9-python-3.11
- rocm-jupyter-pytorch-ubi9-python-3.11
- runtime-minimal-ubi9-python-3.11
- runtime-datascience-ubi9-python-3.11
- runtime-pytorch-ubi9-python-3.11
- runtime-cuda-tensorflow-ubi9-python-3.11
- runtime-rocm-tensorflow-ubi9-python-3.11
- runtime-rocm-pytorch-ubi9-python-3.11

(notebooks-2024a)
- jupyter-minimal-ubi9-python-3.9
- jupyter-datascience-ubi9-python-3.9
- cuda-jupyter-minimal-ubi9-python-3.9
- cuda-jupyter-datascience-ubi9-python-3.9
- cuda-jupyter-tensorflow-ubi9-python-3.9
- jupyter-pytorch-ubi9-python-3.9
- jupyter-trustyai-ubi9-python-3.9
- rstudio-c9s-python-3.9
- cuda-rstudio-c9s-python-3.9
- codeserver-ubi9-python-3.9
- runtime-minimal-ubi9-python-3.9
- runtime-datascience-ubi9-python-3.9
- runtime-pytorch-ubi9-python-3.9
- runtime-cuda-tensorflow-ubi9-python-3.9
```

The same trimming applies for the downstream configuration.

2024-11-27 13:45 UTC, andyatmiami commented on ci-operator/config/opendatahub-io/notebooks/.config.prowgen
> +      {{- $active_release := "2024b" -}}
do you mean you want `2024a` to also tag the group?

2024-11-27 21:04 UTC, andyatmiami commented
While I [confirmed it is not possible to test alert notifications **prior** to merging the configs](https://redhat-internal.slack.com/archives/CBN38N3MW/p1732637496007519), I did verify the validity of the template using the following script:
- https://github.com/openshift/release/blob/master/hack/validate_slack_report_template.go

Even then... Slack's `postMessage` API expects `mrkdwn` syntax.. which is, while phonetically similar, **NOT** the Markdown we all know... 

As such, once I verified the template via `validate_slack_report_template.go` - I think simply "manually" represented the desired message to myself in a DM for visualization purposes.  See below for some examples (that hopefully match what happens when the code is ran _for realz_ 🤞 )

![Screenshot 2024-11-26 at 4 12 37 PM](https://github.com/user-attachments/assets/99c44fa2-c72c-494d-9b18-2dd1ee3382dc)

![Screenshot 2024-11-26 at 4 13 05 PM](https://github.com/user-attachments/assets/194375e6-11cb-4d50-91b7-9652c23b8854)

2024-11-28 11:36 UTC, atheo89 approved these changes
Thank you Andy! 

/lgtm

2024-11-28 11:39 UTC, atheo89 commented
/approve

2024-11-28 12:01 UTC, merged