[WIP]Add filestore-csi for gcp workload identity test
openshift/release pull request #59939
Opened 2024-12-17 03:33 UTC by chao007

2024-12-17 06:55 UTC, chao007 commented
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.18-multi-nightly-gcp-ipi-proxy-oidc-filestore-csi-arm-f28

2024-12-18 04:39 UTC, chao007 commented
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.18-multi-nightly-gcp-ipi-proxy-oidc-filestore-csi-arm-f28

2024-12-18 06:40 UTC, chao007 commented
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.18-multi-nightly-gcp-ipi-proxy-oidc-filestore-csi-arm-f28

2024-12-23 01:53 UTC, chao007 commented
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.18-multi-nightly-gcp-ipi-proxy-oidc-filestore-csi-arm-f28

2024-12-23 02:49 UTC, chao007 commented
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.18-multi-nightly-gcp-ipi-proxy-oidc-filestore-csi-arm-f28

2025-01-09 06:44 UTC, jianli-wei commented
@chao007 Is it possible to also update the steps `ipi-conf-gcp-filestore-workload-identity-federation` & `ipi-conf-gcp-filestore-workload-identity-federation-cleanup`? 

`ipi-conf-gcp-filestore-workload-identity-federation`:
Append ` 1>/dev/null` to the commands `gcloud projects add-iam-policy-binding...` ([lines](https://github.com/openshift/release/blob/master/ci-operator/step-registry/ipi/conf/gcp/filestore-workload-identity-federation/ipi-conf-gcp-filestore-workload-identity-federation-commands.sh#L82-L85)) so as to avoid long outputs? 

`ipi-conf-gcp-filestore-workload-identity-federation-cleanup`:
Firstly `remove-iam-policy-binding` and then delete the service account.

2025-01-10 05:43 UTC, chao007 commented
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.18-multi-nightly-gcp-ipi-proxy-oidc-filestore-csi-arm-f28

2025-01-14 10:18 UTC, chao007 commented
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.18-multi-nightly-gcp-ipi-proxy-oidc-filestore-csi-arm-f28

2025-01-15 02:45 UTC, chao007 commented
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.18-multi-nightly-gcp-ipi-proxy-oidc-filestore-csi-arm-f28

2025-01-17 01:54 UTC, chao007 commented
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.18-multi-nightly-gcp-ipi-proxy-oidc-filestore-csi-arm-f28

2025-01-20 03:07 UTC, chao007 commented
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.18-multi-nightly-gcp-ipi-proxy-oidc-filestore-csi-arm-f28

2025-01-21 02:11 UTC, chao007 commented
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.18-multi-nightly-gcp-ipi-proxy-oidc-filestore-csi-arm-f28

2025-01-21 13:17 UTC, chao007 commented
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.18-multi-nightly-gcp-ipi-proxy-oidc-filestore-csi-arm-f28

2025-01-22 06:40 UTC, jianli-wei requested changes

2025-01-22 06:40 UTC, jianli-wei commented on ci-operator/step-registry/ipi/conf/gcp/filestore-workload-identity-federation/ipi-conf-gcp-filestore-workload-identity-federation-commands.sh
> +run_command "${CMD}" 1>/dev/null
How about below instead? 
```
CMD="gcloud iam service-accounts add-iam-policy-binding...  1>/dev/null"
run_command "${CMD}"

2025-01-22 06:40 UTC, jianli-wei commented on ci-operator/step-registry/ipi/conf/gcp/filestore-workload-identity-federation-cleanup/ipi-conf-gcp-filestore-workload-identity-federation-cleanup-commands.sh
> +CMD="gcloud iam service-accounts remove-iam-policy-binding \"$SERVICE_ACCOUNT_EMAIL\" --member=\"principal://iam.googleapis.com/projects/$PROJECT_NUMBER/locations/global/workloadIdentityPools/$POOL_I
CMD="gcloud iam service-accounts remove-iam-policy-binding... 1>/dev/null"

2025-01-22 11:56 UTC, chao007 commented
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.18-multi-nightly-gcp-ipi-proxy-oidc-filestore-csi-arm-f28

2025-01-23 01:32 UTC, jianli-wei commented
/lgtm

2025-01-23 02:54 UTC, chao007 commented
Hello, I add `remove-iam-policy-binding` when try to clean up the filestore csi operator and driver. Please help review.
/assign @RomanBednar

2025-02-07 06:02 UTC, chao007 commented on ci-operator/step-registry/ipi/conf/gcp/filestore-workload-identity-federation/ipi-conf-gcp-filestore-workload-identity-federation-commands.sh
> +CMD="gcloud iam service-accounts add-iam-policy-binding \"$SERVICE_ACCOUNT_EMAIL\" --member=\"principal://iam.googleapis.com/projects/$PROJECT_NUMBER/locations/global/workloadIdentityPools/$POOL_ID/s
Adding this due to there are some outputs. I can remove the redirect if we would like to debug.

2025-02-07 13:22 UTC, RomanBednar commented on ci-operator/step-registry/ipi/conf/gcp/filestore-workload-identity-federation-cleanup/ipi-conf-gcp-filestore-workload-identity-federation-cleanup-commands.sh
> +    echo "Running Command: ${CMD}" >&2
What error is it? I have some doubts silencing any error is a good choice. If there actually is a reason we should explain it in the comment. Maybe we just need to attempt to run the command and don't care if it failed (then `your_command || true` with a comment is a viable choice)

2025-02-07 13:25 UTC, RomanBednar commented on ci-operator/step-registry/ipi/conf/gcp/filestore-workload-identity-federation/ipi-conf-gcp-filestore-workload-identity-federation-commands.sh
> +CMD="gcloud iam service-accounts add-iam-policy-binding \"$SERVICE_ACCOUNT_EMAIL\" --member=\"principal://iam.googleapis.com/projects/$PROJECT_NUMBER/locations/global/workloadIdentityPools/$POOL_ID/s
I think seeing the output is better, imagine someone debugging this job in a year or more - they will have to remove all the redirects, rerun, then inspect what went wrong...

2025-02-11 12:02 UTC, chao007 commented on ci-operator/step-registry/ipi/conf/gcp/filestore-workload-identity-federation-cleanup/ipi-conf-gcp-filestore-workload-identity-federation-cleanup-commands.sh
> +# Remove the iam policy binding
No error with the code. Adding this step just to double check the clean up section is ok.

2025-02-12 02:50 UTC, chao007 commented
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.18-multi-nightly-gcp-ipi-proxy-oidc-filestore-csi-arm-f28

2025-02-12 08:47 UTC, RomanBednar commented on ci-operator/step-registry/ipi/conf/gcp/filestore-workload-identity-federation-cleanup/ipi-conf-gcp-filestore-workload-identity-federation-cleanup-commands.sh
> +    echo "Running Command: ${CMD}" >&2
@chao007 I meant to use this form selectively on some commands where we expect the command to fail, not all of them. For example we can attempt a cleanup that you added, and we're ok with failures there.

But since you mentioned the cleanup is there just as a double check, the best way would be to first find out if there is some leftover to be removed and branch based on the result. That way we could also verify that the cleanup did not fail if it should have been done. But I don't think we need to be this thorough - so this method is fine for this purpose, just make sure to comment it to indicate it's something optional and serves as a fail safe.

2025-02-12 08:49 UTC, RomanBednar commented on ci-operator/step-registry/ipi/conf/gcp/filestore-workload-identity-federation-cleanup/ipi-conf-gcp-filestore-workload-identity-federation-cleanup-commands.sh
> +# Remove the iam policy binding
What about the resource leak? Were you able to observe any leftover policy bindings from this job in the cloud without this cleanup? If not we could as well remove this block.

2025-03-04 02:31 UTC, chao007 commented
/pj-rehearse periodic-ci-openshift-openshift-tests-private-release-4.18-multi-nightly-gcp-ipi-proxy-oidc-filestore-csi-arm-f28

2025-03-18 09:09 UTC, jianli-wei requested changes

2025-03-18 09:09 UTC, jianli-wei commented on ci-operator/step-registry/ipi/conf/gcp/filestore-workload-identity-federation-cleanup/ipi-conf-gcp-filestore-workload-identity-federation-cleanup-commands.sh
> +    echo "Running Command: ${CMD}" || true
Suggest to follow similar as https://github.com/openshift/release/blob/master/ci-operator/step-registry/ipi/conf/gcp/filestore-workload-identity-federation/ipi-conf-gcp-filestore-workload-identity-federation-commands.sh#L23

2025-03-18 09:09 UTC, jianli-wei commented on ci-operator/config/openshift/openshift-tests-private/openshift-openshift-tests-private-release-4.18__multi-nightly.yaml
> +- as: gcp-ipi-proxy-oidc-filestore-csi-arm-f28
FYI we had updated `gcp-ipi-proxy-oidc-arm-f28` into `gcp-ipi-proxy-oidc-mini-perm-arm-f28`, in https://github.com/openshift/release/pull/62332.

2025-03-25 02:01 UTC, closed without merging